GeoNode/geonode

- Dockerfile
- README
- fig.yml
- pavement.py
This PR adds a Dockerfile and fig file for easier development with the help of Docker. 
It is open for discussion and any comments are appreciated.
If someone is unfamiliar with: [fig](http://fig.sh/) or [docker](https://www.docker.com).
Using fig is much easier than using docker directly but might be replaced with a direct way in docker soon. 
The pavement script could be replaced with additions into the docker file and another container running GeoServer. 
I did not tackle this just yet because I wanted to make sure you guys would like to have a dockerized way.
Option for start action of pavement script to run django in foreground. This is needed for Docker to detect something is running and does not quit. 
Dockerfile added to install all dependencies into the docker container.
Fig file …
> Dockerizing

- geonode/layers/templates/layers/layer_list.html
- geonode/templates/_permissions.html
> add perm choice for #1922

- geonode/geoserver/helpers.py
- geonode/tests/integration.py
Now updatelayers keeps the attributes field values
> This fixes #1908

- geonode/geoserver/tests.py
- geonode/geoserver/views.py
If the number of layers increases the view layer_acls becomes very slow. 
This patch significantly reduces the number of SQL queries using the polymorphic selectors/functions.
This partialy fixes the #1873 issue.
> improved layer_acls performaces

- geonode/groups/models.py
- geonode/groups/templates/groups/group_members.html
- geonode/groups/views.py
- geonode/static/geonode/less/base.less
- geonode/templates/avatar/change.html
Layout Changes for groups members and avatar change pages.  Added tabs to filter by role and some styling to members list (see image below).  Minor style fixes to avatar change.
> Layout Changes / Group Members, Avatar Change

- geonode/base/templates/base/resourcebase_info_panel.html
This PR hyperlinks the category on the ResourceBase Info Panel to the search page pre-filtered by the same category.  Also added more info button, like for licenses.
> Category Link

- geonode/utils.py
handles unicode properly and fixes #1966
> Fixes #1966

- geonode/services/views.py
Maybe there is a better way, could not figure out
> Hack to fix #1932

- geonode/base/models.py
Removing stale links when updating layers. Fixes #1090
> Removing stile links (#1090)

- geonode/people/templates/people/profile_detail.html
This PR fixes #1803. Adds a message button to profile page.
> fixed #1803

- geonode/layers/views.py
Flake8 Error:
```
./layers/views.py:432:40: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
```
> quick pep8 fix

- geonode/templates/about.html
> modified about page

- geonode/groups/templates/groups/_group_list_item.html
- geonode/layers/templates/layers/layer_detail.html
- geonode/layers/templates/upload/layer_upload.html
- geonode/people/templates/people/_profile_list_item.html
- geonode/people/templates/people/profile_edit.html
- geonode/people/templates/people/profile_list.html
> Some minor layout fixes

- geonode/people/views.py
This applies the same fix in https://github.com/GeoNode/geonode/pull/1907 to current `master`.
See: https://github.com/GeoNode/geonode/issues/1982
> Users should not be able to edit other users profile

- geonode/layers/utils.py
- geonode/tests/integration.py
> Clean upload errors

- docs/organizational/contribute/contribute_to_documentation.txt
- docs/organizational/contribute/contribute_to_translation.txt
- docs/tutorials/users/intro/tour.txt
- adding a link in introduction for user workshop
- updated procedure for contributing to translation
- small addin to procedure for contributing to the documentation
> some simple documentation changes

- docs/tutorials/admin/install/quick_install.txt
Added some notes about GEOS and GDAL for Windows install.
> Windows quick install docs update

- geonode/groups/models.py
No changes in database applied.
> moving the logo from file field to image field

- geonode/templates/geonode/geo_header.html
This pr resolve #2011 by not showing the button if not logged
> styler does not show up when not logged #2011

- pavement.py
pypi is now using compiled wheels which has better support for pip than the previously used .exe files, which required easy_install.  As packages like pycsw are brought around to use wheel supported packages, win_deps_install will no longer be required per the comments in code.
Also a note in code that 64bit python users are on their own to install everything.
> removed some required win_install_dep packages since compiled wheels are now used

- geonode/layers/templates/layers/layer_detail.html
just an new "edit data" entry in the existing menu :
for #1890
> Adding link to edit data into the layer edit menu

- package/support/geonode.updateip
https://github.com/GeoNode/geonode/issues/1199 is accomplished with this PR.
> refactored 'geonode.updateip' script to accomplish #1199 github issue

- docs/tutorials/admin/data/osm.txt
@state-hiu @garnertb can you guys take a quick review of this before merging.
Related to #1931
> Initial work on describing GeoGig OSM functionality

- docs/organizational/contribute/review_criteria.txt
> replaced numbered list with bullet points

- geonode/proxy/views.py
> Correct proxy fail for specifics characters

- geonode/base/models.py
- geonode/maps/tests.py
Assuming a map size of 1000 * 700 px. Fixes #2024
> Calculate map extent based on save

- geonode/context_processors.py
- geonode/documents/templates/documents/document_upload_base.html
- geonode/documents/views.py
dynamic list of allowed document types. resolves issue #1792
> allowed document types list

- geonode/geoserver/signals.py
- geonode/layers/models.py
- geonode/layers/views.py
- geonode/static/geonode/js/upload/LayerInfo.js
- geonode/utils.py
- setup.py
Commit in reference to issue #2060
Columns names from layer upload are checked before the upload and are replaced if they included error.
The rule on the regex are verified and if they are incorrect the columns name are modified to match it.
The new parameter who was transmitted is a dictionary for inform the user of the modification of the columns names.
And you can see the modification on the layer page:
If the upload fail, a new message are shown to user, asking him to check if the file was correct and check the charset encoding of it.
For the rename of column we use [awesome-slugify](https://pypi.python.org/pypi/awesome-slugify) who was added on the setup.py
> Geode issue 2060

- geonode/layers/forms.py
- geonode/layers/tests.py
One shapefile per zip, fixes #1319
> Add support for zip upload

- geonode/base/templatetags/base_tags.py
Added group to homepage facets.  Useful for downstream GeoNode projects that would like to display the number of groups on the homepage.
> Added group to homepage facets

- geonode/layers/forms.py
- geonode/layers/utils.py
The importlayers command currently doesn't handle zip files, these modifications should fix that.
> Fix importlayers command for zip files

- geonode/geoserver/helpers.py
In ref to #2093 the xml returned by IE11 was malformed.
(found some NSx attributes into xml)
> Resolve malformed XMLHttpRequest from in IE11

- geonode/static/geonode/js/upload/upload.js
> fix for case-sensitive extension comparison

- docs/tutorials/admin/commands.txt
- geonode/layers/management/commands/importlayers.py
- geonode/layers/utils.py
Added command line options for specifying category, title, and 'private' (making layer viewable only to owner).
> Additional options for importlayers command

- geonode/templates/announcements/announcement_confirm_delete.html
in ref to #2083 
This commit add and modify the delete page for announcement.
> add and custome announcement_confirm_delete.html

- geonode/base/templates/base/resourcebase_info_panel.html
Now the keywords and regions in resource info panel are linkified with the api search string
> Linkify keywords and regions

- scripts/misc/create_full_geonode_db.py
This is useful to check the performances of count dehidrate, guardian permissions and geoserver
> Added a script to generate a full GeoNode instance to test performance

- geonode/templates/base.html
> add missing libraries for DEBUG_STATIC mode

- geonode/api/resourcebase_api.py
- geonode/base/models.py
- geonode/layers/search_indexes.py
- geonode/static/geonode/js/search/search.js
These modifications should allow search to work properly with Haystack enabled.
> Fix issues with Haystack search (date, regions)

- geonode/api/resourcebase_api.py
Fix issue with permissions filter when HAYSTACK_SEARCH = True and SKIP_PERMS_FILTER = False
> Fix issue with permissions filter when HAYSTACK_SEARCH = True

- geonode/base/templates/base/resourcebase_info_panel.html
Reversing some url that were hard coded
> Reversing some url that were hard coded

- geonode/api/resourcebase_api.py
otherwise all layers show up under a user's profile page.
> Add owner filter to haystack search function

- geonode/api/resourcebase_api.py
- geonode/documents/search_indexes.py
- geonode/layers/search_indexes.py
- geonode/maps/search_indexes.py
Also added back some deleted fields (popular count, share count, rating)
> Make Haystack search indexes more consistent across layers, maps, documents

- geonode/static/geonode/less/base.less
> Fix for autocomplete for Search UI Issue #2152

- geonode/base/models.py
- geonode/base/templates/base/resourcebase_info_panel.html
- geonode/documents/templates/documents/document_detail.html
- geonode/documents/views.py
- geonode/groups/models.py
- geonode/layers/templates/layers/layer_detail.html
- geonode/maps/templates/maps/map_detail.html
- geonode/templates/base.html
- geonode/templates/social_links.html
This PR includes a lot of minor translation fixes, including adding `{% trans XXX %}` to templates and adding `verbose_name=_("XXX")` to model fields, which isn't a model change right?
> Translation fixes

- geonode/documents/models.py
This fixes fails from Wand (for some pdf it is happening in our instance)
> Handling Wand fails. Refs #2194

- geonode/base/models.py
without this the admin must type a value in the admin form.
> agon rating must be blank in admin

- Dockerfile
- README
I was just messing around with docker.  Thought it might be useful to expose the geoserver port as well even if the link is incorrect in the UI.
> expose geoserver port in docker

- docs/tutorials/devel/projects/projectsintro.txt
added downstream projects and hyperlinks as commented in issue #1939
> added hyperlinks to downstream projects

- geonode/services/templates/services/service_register.html
This is in reference to #2248.
> Validate remote service name to comply with GeoServer workspace name restrictions.

- geonode/services/views.py
> Remote services fixes

- geonode/settings.py
> Change language name

- geonode/settings.py
Fix #2277 Moved middleware class addition after local_settings.py import.
> Fix LOCKDOWN_GEONODE not working

- geonode/geoserver/helpers.py
- geonode/static/geonode/js/upload/LayerInfo.js
- geonode/static/geonode/js/upload/upload.js
- geonode/tasks/deletion.py
- geonode/upload/tests/integration.py
- geonode/upload/upload.py
- geonode/upload/views.py
- Improvements for the management of the Importer Session next ID
- Fix for Issue #2273
- Integration upload test
>  - Improvements for the management of the Importer Session next ID

- geonode/layers/templates/upload/layer_upload.html
In PR #2290 cookie.js was not being included.  This PR explicitly loads cookie.js.   #2290 could be improved by submitting the CategoryForm instead of using cookies.
> Added explicit import of cookie.js

- geonode/utils.py
This fix an issue of strftime when the year of the resource data is before 1900.
> fixed issue with date before 1900

- geonode/layers/views.py
remove obsolete references to category form in labels/views.py
> remove obsolete references to category form in labels/views.py

- geonode/layers/views.py
- geonode/static/geonode/js/upload/LayerInfo.js
Restoring master after something stupid I did earlier today.
> Restore master

- geonode/settings.py
- geonode/templates/base.html
- geonode/templates/geonode/app_header.html
- geonode/templates/geonode/ext_header.html
- geonode/templates/geonode/geo_header.html
- geonode/templates/geonode/sdk_header.html
- geonode/templates/search/search_scripts.html
Adding geonode version number to static files in order to force reload in browser every time there is a new geonode version
> Adding geonode version number to static files

- geonode/documents/templates/documents/document_remove.html
- geonode/maps/templates/maps/map_remove.html
- geonode/templates/account/password_change.html
> Fixes layout for some pages

- geonode/templates/account/admin_approval_sent.html
- geonode/templates/account/email_confirmation_sent.html
- geonode/templates/account/invite_user.html
- geonode/templates/account/signup.html
Fixes html layout in some account pages
> Fixes html layout in some account pages

- geonode/catalogue/tests.py
- geonode/catalogue/views.py
- geonode/templates/developer.html
- geonode/urls.py
> add support for data.json output (#1022)

- docs/reference/developers/settings.txt
- geonode/settings.py
Refs #2314
thanks @garnertb for suggested changes
> Now bingmaps base layer will be enabled if a BING_API_KEY is defined

- geonode/static/geonode/js/upload/LayerInfo.js
- geonode/static/geonode/js/upload/path.js
problem was in files containing dots.
> Fixes #2301

- geonode/static/geonode/js/upload/path.js
> support XML metadata uploads with filenames like xyz.shp.xml (#2351)

- geonode/static/geonode/js/search/search.js
- geonode/templates/search/_extent_filter.html
Fix for Mobile Design / Extent Search #2171
> Extent Search closed by default

- geonode/urls.py
- geonode/views.py
> implement ident/status JSON (#2100)

- docs/tutorials/install_and_admin/geonode_install/setup_configure_httpd.txt
- docs/tutorials/install_and_admin/setup_on_centos/install_base_httpd.txt
> Add SSL configuration to docs

- geonode/maps/models.py
the condition must check if geonode.geoserver is in the installed apps
> updating the condition in line 321 in geonode.maps.models

- docs/tutorials/install_and_admin/setup_on_centos/devmode_install_centos.txt
- docs/tutorials/install_and_admin/setup_on_centos/index.txt
I have been struggling a bit to figure out how to do this, with the help of Paolo Corti, so we thought to contribute to the docs.
Thanks
> Tutorial for installing GeoNode on CentOS 7 (devmode)

- docs/tutorials/devel/install_devmode/index.txt
> added devinstall centos to the index

- docs/tutorials/install_and_admin/setup_on_centos/devmode_install_centos.txt
Hopefully this version should render better. Thank you
> modified in order to render correctly in the html page

- geonode/geoserver/helpers.py
Affects new layers created via `gs_slurp`.
> Allow permissions to be set in gs_slurp.

- geonode/contrib/geosites/views.py
- geonode/documents/views.py
- geonode/geoserver/views.py
- geonode/layers/views.py
- geonode/maps/models.py
- geonode/maps/views.py
- geonode/security/views.py
- geonode/services/views.py
- geonode/upload/views.py
- geonode/views.py
This PR replaces the deprecated `HttpResponse` `mimetype` argument with `content_type`.
> update deprecated Django argument

- pavement.py
Give the developer the ability to set a different port for Geoserver, in case port:8080 is taken by other applications such as required enterprise applications (e.g. CISCO apps).
> flexible port for development geoserver

- geonode/contrib/metadataxsl/README.md
Adding a README file as per comment https://github.com/GeoNode/geonode/issues/2453#issuecomment-220310474
> #2453: Add README file to metadataxsl contrib app.

- README
Ref: https://github.com/GeoNode/geonode/issues/2473
Quick & tiny fix, since I ran into this issue myself recently
> Update dev install instructions link

- geonode/layers/utils.py
Improvement upon [PR#2492](https://github.com/GeoNode/geonode/pull/2492)
> Check for existing thumbs before overwriting

- geonode/static/geonode/js/upload/LayerInfo.js
> removed mosaic entry in basename variable of doGeoGigToggle

- README
- docs/tutorials/devel/devel_env/index.txt
Ref this thread: http://lists.osgeo.org/pipermail/geonode-devel/2016-June/000988.html
> Update docs with database initialization step

- docs/reference/developers/settings.txt
> Update documentation for the MAPBOX_ACCESS_TOKEN setting

- geonode/static/geonode/less/base.less
These few lines enable the vertical scroll in the search bar
> added fields to enable vertical scroll in search bar

- docs/tutorials/devel/devel_env/gdal_install.txt
> Fix issue #2526

- setup.py
AttributeError: 'NoneType' object has no attribute 'name'
https://github.com/django-polymorphic/django-polymorphic/issues/201
> Fixes admin interface for layers

- geonode/geoserver/helpers.py
See https://github.com/GeoNode/geonode/pull/2539
> addition to previous patch: format port as str

- README
Heading "Docker Usage" was not rendered correctly.
> README: fix syntax error

- docs/tutorials/install_and_admin/geonode_install/all_together.txt
- docs/tutorials/install_and_admin/geonode_install/install_geonode_application.txt
- docs/tutorials/install_and_admin/geonode_install/setup_configure_httpd.txt
I tested the installation successfully on Debian 8.5 and found some details I'd like to share.
> Changes in manual installation docs

- geonode/static/geonode/js/upload/LayerInfo.js
- geonode/static/geonode/js/upload/common.js
- geonode/static/geonode/js/upload/csv.js
- geonode/static/geonode/js/upload/time.js
- geonode/upload/views.py
This PR prevent auto redirect when additional information is required to complete the import. For the case when a user selects multiple files to upload/import, the application will prompt the user with a friendly message stating that more information is required to complete the upload thus requiring the user to click the continue link.
> Prevent auto redirect when additional information is required.

- geonode/geoserver/helpers.py
- geonode/geoserver/views.py
- geonode/layers/migrations/0002_initial_step2.py
- geonode/layers/models.py
This pull request changes all instances of the layer style field's related name value (`LayerStyles`) to `layer_styles` to conform with convention.
> Change related name "LayerStyles" to snake_case.

- CONTRIBUTING.
> Create new CONTRIBUTING file

- geonode/api/api.py
- geonode/base/templatetags/base_tags.py
- geonode/groups/autocomplete_light_registry.py
- geonode/templates/search/search_scripts.html
This is the first step in resolving https://github.com/GeoNode/geonode/issues/2555; note that search itself is not fixed with this patch, only autocomplete. PR to fix search coming soon.
> Fix autocomplete for profiles and groups

- README
> url fix in README

- docker-compose.yml
It is possible to override configuration for development using docker-compose.override.yml
> Using docker images from hub

- requirements.txt
- setup.py
Pinning should be done in requirements.txt
Reasoning is explained in https://packaging.python.org/requirements/
> Don't pin versions in setup.py use >= or <=

- MANIFEST.in
- setup.py
In the latest release, we were missing the fixtures.
> Use a pattern for adding package data, fixes missing fixtures on packages

- geonode/layers/templates/layers/layer_detail.html
> Make download links open in new tab

- geonode/geoserver/context_processors.py
MAPFISH_PRINT_ENABLED, PRINT_NG_ENABLED, GEONODE_SECURITY_ENABLED, GEOGIG_ENABLED
> Provide defaults for optional ogc_server_settings

- geonode/base/models.py
should fix #2659, thanks @gdreich
> use names instead of slugs for keywords

- geonode/people/templates/people/profile_detail.html
Template update to include the view from #2673 
<sub><sup>My bad</sup></sub>
> Use new UserActivity view

- geonode/base/models.py
- geonode/tests/csw.py
> Revert "Fix for (Issue 2720) - Incomplete OGC:WMS Download Link for Catalog"

- docs/tutorials/install_and_admin/vm_setup_virtualbox.txt
Add instructions on how to download Ubuntu ISO image
> Fix for VM Setup with Virtualbox Doc #2577

- .travis.yml
- README
- pavement.py
See: https://github.com/GeoNode/geonode/issues/2729
Wait to merge until Travis finishes & Coveralls.io confirmed working...
> Add optional coverage generation & integrate CI with Coveralls.io

- geonode/api/resourcebase_api.py
fix potential use before assignment issue
> initialise variable before assignment

- geonode/catalogue/backends/pycsw_local.py
- geonode/catalogue/models.py
> Use isPublished field to control whether a Resource is exposed in pycsw

- docs/tutorials/devel/devel_core/coremodules.txt
wrong link to layers app under geonode.maps section
> Fixed a wrong link in the documentation

- geonode/catalogue/backends/pycsw_local.py
Inspired by the Tom Kradalis code seen here:
- https://github.com/GeoNode/geonode/pull/2763
> Fix for PostgreSQL/SQLite boolean type differences

- README
- docs/tutorials/install_and_admin/quick_install.txt
Adds Ubuntu development installation instructions in readme and quick_install documentation
Not applicatble.
Apparently not issues are open about this.
> Added Ubuntu development installation instructions

- geonode/templates/index.html
L169 limited featured dataset title to 20 characters so the the name doesnt overlap the next dataset.
> Fix for index.html for dataset name length <h4>

- geonode/api/api.py
- geonode/api/resourcebase_api.py
- geonode/api/urls.py
- geonode/base/autocomplete_light_registry.py
- geonode/base/management/commands/load_thesaurus.py
- geonode/base/migrations/0008_add_thesaurus_keywords.py
- geonode/base/migrations/0009_resourcebase_tkeywords.py
- geonode/base/models.py
- geonode/context_processors.py
- geonode/settings.py
- geonode/static/geonode/js/search/search.js
- geonode/templates/search/_search_content.html
- geonode/templates/search/_t_keywords_filter.html
- geonode/templates/search/search_scripts.html
This is the back-end part of this improvement 
https://github.com/GeoNode/geonode/issues/2670
> PR for Issue #2670: handling keywords thesauri

- docs/tutorials/admin/admin_mgmt_commands/index.txt
- geonode/documents/management/commands/delete_orphaned_files.py
- geonode/documents/utils.py
- geonode/tasks/deletion.py
Adds a management command and a celery task to delete orphaned files of removed documents. Fixes #2291
> Fixes #2291

- docs/tutorials/admin/admin_mgmt_commands/index.txt
- geonode/base/management/commands/delete_orphaned_thumbs.py
- geonode/base/utils.py
- geonode/tasks/deletion.py
Adds a management command and a celery task to delete orpahed thumbs. Fixes #2535
> Fixes #2535

- README
thanks to @kalxas for all his help getting it set up, this is the notes I took
> Updates to README for Ubuntu 16.04

- geonode/geoserver/helpers.py
- geonode/geoserver/signals.py
- geonode/geoserver/views.py
Update layer thumbnail when layer style is changed.
> Fixes #2652

- geonode/catalogue/templates/catalogue/feature_catalogue.xml
- geonode/catalogue/templates/catalogue/full_metadata.xml
- geonode/layers/templates/layers/layer_detail.html
- geonode/layers/tests.py
- geonode/layers/urls.py
- geonode/layers/views.py
> implement ISO 19110 support for vector layers (#2810)

- geonode/geoserver/helpers.py
- geonode/geoserver/signals.py
Refactor create_gs_thumbnail. Now we have same method for both layers and maps thumb generation
> Refactor create_gs_thumbnail for maps and layers

- docs/tutorials/devel/devel_core/index.txt
> Fixed typo in title

- geonode/base/migrations/24_initial.py
- geonode/base/migrations/24_to_26.py
> move metadata_uploaded_preserve to the right migration

- geonode/base/management/commands/backup.py
- geonode/base/management/commands/restore.py
- geonode/utils.py
Code contributed by
Matteo Nastasi <matteo.nastasi@globalquakemodel.org>
> PR for Issue #2885 - Manage signals when performing BR

- geonode/base/templates/base/_resourcebase_info_panel.html
- geonode/documents/templates/documents/document_detail.html
- geonode/layers/templates/layers/layer_detail.html
- geonode/maps/templates/maps/map_detail.html
- geonode/people/templates/people/_profile_list_item.html
- geonode/templates/base.html
- geonode/templates/index.html
Fix togglable tabs in detail pages (fix #2881), remove truncatechars in Resource Base Info Panel Abstract. Fix meta-category links in home page to include all ISOs. Fix issue #2783
> Minor template fixes on Detail pages and Index

- geonode/templates/geonode/geo_header.html
- geonode/utils.py
Disable 3D viewer #2921
Change Geoexplorer aboutUrl #2892
> Multiple changes in Geoexplorer

- geonode/contrib/favorite/templates/favorite/favorite_list.html
- geonode/documents/templates/documents/document_detail.html
- geonode/documents/templates/documents/document_list.html
- geonode/documents/templates/documents/document_metadata.html
- geonode/documents/templates/documents/document_upload.html
- geonode/groups/templates/groups/group_detail.html
- geonode/groups/templates/groups/group_list.html
- geonode/groups/templates/groups/group_members.html
- geonode/layers/templates/layers/layer_detail.html
- geonode/layers/templates/layers/layer_list.html
- geonode/layers/templates/layers/layer_metadata.html
- geonode/layers/templates/layers/layer_replace.html
- geonode/layers/templates/layers/layer_style_manage.html
- geonode/layers/templates/upload/layer_upload.html
- geonode/layers/templates/upload/layer_upload_csv.html
- geonode/layers/templates/upload/layer_upload_time.html
- geonode/maps/templates/maps/map_detail.html
- geonode/maps/templates/maps/map_download.html
- geonode/maps/templates/maps/map_list.html
- geonode/maps/templates/maps/map_metadata.html
- geonode/people/templates/people/profile_detail.html
- geonode/people/templates/people/profile_list.html
- geonode/services/templates/services/service_register.html
- geonode/templates/account/signup.html
- geonode/templates/index.html
- geonode/templates/search/search.html
As these templates extended from base if you want to add anaylics the script was not
included in all the site
Solves: https://github.com/GeoNode/geonode/issues/2937
> Added `{{ block.super}}` to all `{% block extra_script %}`

- geonode/contrib/favorite/templates/favorite/favorite_list.html
- geonode/documents/templates/documents/document_detail.html
- geonode/documents/templates/documents/document_list.html
- geonode/documents/templates/documents/document_metadata.html
- geonode/documents/templates/documents/document_upload.html
- geonode/groups/templates/groups/group_detail.html
- geonode/groups/templates/groups/group_list.html
- geonode/groups/templates/groups/group_members.html
- geonode/layers/templates/layers/layer_detail.html
- geonode/layers/templates/layers/layer_list.html
- geonode/layers/templates/layers/layer_metadata.html
- geonode/layers/templates/layers/layer_replace.html
- geonode/layers/templates/layers/layer_style_manage.html
- geonode/layers/templates/upload/layer_upload.html
- geonode/layers/templates/upload/layer_upload_csv.html
- geonode/layers/templates/upload/layer_upload_time.html
- geonode/maps/templates/leaflet_maps/map_list.html
- geonode/maps/templates/leaflet_maps/map_view.html
- geonode/maps/templates/maps/map_detail.html
- geonode/maps/templates/maps/map_download.html
- geonode/maps/templates/maps/map_list.html
- geonode/maps/templates/maps/map_metadata.html
- geonode/people/templates/people/profile_detail.html
- geonode/people/templates/people/profile_list.html
- geonode/services/templates/services/service_register.html
- geonode/templates/account/signup.html
- geonode/templates/avatar/change.html
- geonode/templates/index.html
- geonode/templates/search/search.html
- geonode/templates/user_messages/inbox.html
As these templates extended from base if you want to add anaylics the script was not
included in all the site
Solves: #2937
Also replaced repeated code for facebook buttons with an include to facebook_sdk
> Added {{block.super}} to all {% block extra_script %}

- geonode/layers/templates/layers/layer_geoext_map.html
> Change legend in layer detail page when the style is changed by the user

- geonode/layers/templates/layers/layer_geoext_map.html
- geonode/layers/views.py
Fixes #2942 also in 2.6.x
Fixes #2946
> Fixes some style stuff

- geonode/local_settings.py.geoserver.sample
- geonode/local_settings.py.qgis.sample
- geonode/settings.py
> minor settings refractor

- docs/reference/developers/settings.txt
- geonode/geoserver/helpers.py
- geonode/geoserver/signals.py
- geonode/layers/utils.py
- geonode/layers/views.py
- geonode/settings.py
- geonode/tests/integration.py
- pavement.py
Make the PUBSUB work opt in instead of opt out by creating a new setting.
> GEONODE_PUBSUB as an optional setting

- geonode/base/models.py
- geonode/documents/tests.py
- geonode/documents/views.py
- geonode/layers/tests.py
- geonode/layers/views.py
- geonode/maps/admin.py
- geonode/maps/tests.py
- geonode/maps/views.py
- geonode/people/utils.py
- geonode/settings.py
uploads moderation tests #3061
> mark uploads as unpublished if moderaiton flag is set #3061

- geonode/context_processors.py
- geonode/settings.py
- geonode/templates/user_messages/inbox.html
- geonode/templates/user_messages/message_create.html
> setting for multiple recipients 

- README
and setup instructions on other systems, see :
https://github.com/GeoNode/geonode/blob/master/.gitignore#L98
> Rename virtual env folder to match .gitignore

- geonode/context_processors.py
- geonode/settings.py
- geonode/templates/account/signup.html
> use ACCOUNT_OPEN_SIGNUP instead of REGISTRATION_OPEN

- geonode/groups/fixtures/group_test_data.json
- geonode/groups/migrations/26_to_27.py
- geonode/groups/models.py
- geonode/templates/search/_group_snippet.html
- geonode/templates/search/_search_user_content.html
> Fix for ISSUE #3097: Display date of group creating

- geonode/people/models.py
> do not create email twice when user signs up 

- geonode/base/management/commands/settings.ini
Ticket: https://github.com/GeoNode/geonode/issues/2989
> Fix for ISSUE #2989: backup/restore: order of fixtures

- geonode/base/management/commands/restore.py
Ticket: https://github.com/GeoNode/geonode/issues/2988
> For for ISSUE #2988: restore command: allow work with unpacked data

- geonode/base/management/commands/backup.py
- geonode/base/management/commands/restore.py
Ticket: https://github.com/GeoNode/geonode/issues/2983
> Fix for ISSUE #2983: backup/restore gracefully handle non-json responses from geoserver backup api

- geonode/base/management/commands/backup.py
- geonode/base/management/commands/restore.py
Ticket: https://github.com/GeoNode/geonode/issues/2985
> Fix for ISSUE #2985: Backup/Restore skip geoserver operations switch in cli 

- geonode/base/management/commands/backup.py
- geonode/base/management/commands/helpers.py
- geonode/base/management/commands/migrate_layers.py
- geonode/base/management/commands/restore.py
Ticket: https://github.com/GeoNode/geonode/issues/2984
> Fix for ISSSUE #2984: backup/restore allow customized settings.ini path

- geonode/base/management/commands/backup.py
- geonode/base/management/commands/helpers.py
- geonode/base/management/commands/restore.py
Ticket: https://github.com/GeoNode/geonode/issues/3118
> Fix for ISSUES #3118: Allow to override geoserver settings.ini from cli

- geonode/base/migrations/26_to_27.py
- geonode/base/models.py
- geonode/documents/templates/layouts/doc_panels.html
- geonode/documents/views.py
- geonode/groups/views.py
- geonode/layers/templates/layouts/panels.html
- geonode/layers/views.py
- geonode/maps/templates/layouts/map_panels.html
- geonode/maps/views.py
- geonode/templates/metadata_form_js.html
> Fix for ISSUE #3124: Fix display of group activity

- docs/tutorials/admin/backup_restore/index.txt
Ticket: https://github.com/GeoNode/geonode/issues/3119
> Fix for ISSUE #3119: Add to documentation new options and instructions implemented

- geonode/templates/base.html
Close a Tag for help menu item
> Close a tag

- geonode/documents/forms.py
- geonode/documents/migrations/25_add_documentresourcelink_table.py
- geonode/documents/migrations/26_move_data_to_documentresourcelink_table.py
- geonode/documents/migrations/27_drop_resource_columns_from_document_table.py
- geonode/documents/models.py
- geonode/documents/templates/documents/document_detail.html
- geonode/documents/templates/documents/document_upload.html
- geonode/documents/templates/layouts/doc_panels.html
- geonode/documents/tests.py
- geonode/documents/views.py
Add many-to-many relation for documents and resources
> Fix for ISSUE #3133: Change document-[layer|map] relation (many-to-many)

- geonode/base/management/commands/backup.py
- geonode/base/management/commands/helpers.py
- geonode/base/management/commands/restore.py
Ticket: https://github.com/GeoNode/geonode/issues/2986
Please do not merge, work in progress.
> Fix for ISSUE #2986: backup/restore handling geoserver data outside GS data dir.

- geonode/base/utils.py
> Fix for ISSUE #3147: Display form errors

- geonode/base/forms.py
- geonode/base/utils.py
- geonode/base/views.py
- geonode/documents/tests.py
- geonode/documents/views.py
- geonode/layers/tests.py
- geonode/layers/views.py
- geonode/maps/tests.py
- geonode/maps/views.py
> Fix for ISSUE #3149: trying to change the Language

- geonode/base/forms.py
- geonode/base/views.py
- geonode/documents/tests.py
- geonode/layers/tests.py
- geonode/maps/tests.py
> Fix for ISSUE #3150: more fields to batch update

- geonode/notifications_helper.py
> notifications #3170 do not fail during notifications init

- geonode/utils.py
> bbox_to_wkt: remove EPSG: prefix in srid if present

- geonode/services/views.py
> Fix remote service importation error

- geonode/geoserver/helpers.py
- geonode/services/views.py
>  - fixes #3225: Create Thumbnail should not rely on GeoServer reflector

- requirements.txt
This works just for dev setup.
> Fixes #3235 for dev installation

- geonode/static/geonode/js/search/search.js
This fixes the h_keywords search in configurations where Elasticsearch and Haystack is enabled.
> Use href instead of text for keywords_slugs.

- geonode/contrib/ows_api/tests.py
- geonode/contrib/ows_api/urls.py
- geonode/contrib/ows_api/views.py
- geonode/urls.py
> expose list of ows services #3250

- geonode/contrib/ows_api/views.py
> improved ows links app: csw and homepage

- setup.py
> Backport fix for the six dependency to 2.6.x branch

- geonode/geoserver/management/commands/updatelayers.py
> Port #3309

- docs/tutorials/advanced/geonode_production/production.txt
Added that local_settings.py should be updated with the new password from default geoserver admin.
> Added additional instructions

- geonode/templates/_messages.html
Fixes user messages so they are displayed correctly depending on the type of message. (Yellow for warning, green for success, etc.)
> Message colors fix.

- geonode/templates/_messages.html
Messages now display with the correct color for the message type.
> Fixes messages colors.

- geonode/layers/templates/layers/layer_detail.html
- geonode/layers/views.py
- geonode/maps/tests.py
- geonode/maps/urls.py
- geonode/maps/views.py
As in the following screenshot
> Add the "Add the layer to an existing map" feature in layer detail page

- geonode/layers/templates/layers/layer_detail.html
Fixes the JS error message when the "+" sign is clicked without selecting any values from the dropdown menus.
> fix js error

- geonode/static/geonode/js/utils/thumbnail.js
- geonode/templates/base.html
- geonode/templates/metadata_base.html
>  - Improved Thumbnail Feedbacks

- geonode/base/enumerations.py
Following the #3350 pull request, I applied the changes on master.
> master:Adding Greek code 'gre' into Language field in admin layer's form

- .gitignore
- .travis.yml
- geonode/decorators.py
- geonode/utils.py
- pavement.py
Related with stage 1 for Issue #3362 : Merging QGIS Server Backend.
Include changes to improve unittests and CI:
- Parallel job for GeoServer and QGIS Server backend
- Switch from coveralls to codecov for code coverage
- Add methods and decorators to check active backend
> QGIS Server Related PR to upstream.

- geonode/layers/management/commands/importlayers.py
- geonode/layers/utils.py
@simod I fixed the conflicts in utils.py. Because I had problems to update my last pull request #3360, I created a new.
> Adding charset as option in importlayers command

- docs/tutorials/admin/loading_data_into_geonode/importlayers.txt
I made an update of importlayers command's docs in order to include the new options that have been added.
> Update the importlayers command's docs

- docs/tutorials/admin/admin_mgmt_commands/index.txt
- geonode/geoserver/management/commands/sync_geofence.py
Add sync_geofence command, which syncronize permissions from GeoNodedatabase to GeoServer/GeoFence
> Adding the sync_geofence command

- geonode/geoserver/helpers.py
updatelayers will now synchronize django-guardian permissions with GeoFence
> Fixes #3376

- setup.py
error with registration 
- geonode version:  ```2.6.3```
- ```geonode-user-accounts``` version : ```1.0.15```
- log: 
```
return EmailAddress.objects.add_email(self.created_user, self.created_user.email, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/account/managers.py", line 10, in add_email
email_address = self.create(user=user, email=email, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 348, in create
obj.save(force_insert=True, using=self.db)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 734, in save
force_update=force_update, …
```
> fix registration bug

- geonode/documents/admin.py
- geonode/layers/admin.py
- geonode/maps/admin.py
> [ISSUE 3445] Admin forms for Base Resources improvements

- requirements.txt
> Closes #3462

- requirements.txt
> [Fixes #3473] - Legend Panel pop-ups on GeoExplorer client

- requirements.txt
- setup.py
> [Closes #3480] - Support for GeoServer Importer on 'master' branch

- geonode/static/geonode/js/utils/thumbnail.js
> [Fixes #3478] - Typo on thumbnail.js error handling

- geonode/api/resourcebase_api.py
- geonode/contrib/createlayer/templates/createlayer/layer_create.html
- geonode/documents/templates/documents/document_metadata_advanced.html
- geonode/documents/templates/documents/document_upload_base.html
- geonode/layers/templates/layers/layer_granule_remove.html
- geonode/layers/templates/layers/layer_metadata_advanced.html
- geonode/layers/templates/layers/layer_metadata_upload.html
- geonode/layers/templates/layers/layer_remove.html
- geonode/layers/templates/layers/layer_style_upload.html
- geonode/layers/templates/upload/layer_upload.html
- geonode/layers/templates/upload/layer_upload_base.html
- geonode/layers/templates/upload/layer_upload_metadata_base.html
- geonode/maps/templates/maps/map_metadata_advanced.html
- geonode/people/templates/people/profile_detail.html
- geonode/services/templates/services/services_base.html
- geonode/settings.py
- geonode/templates/500.html
- geonode/templates/base.html
> [Fixes #3476] - API_LIMIT_PER_PAGE affecting Tastypye resource limits also

- geonode/layers/templates/layers/layer_detail.html
- geonode/maps/qgis_server_views.py
- geonode/maps/templates/leaflet_maps/map_edit.html
- geonode/maps/templates/leaflet_maps/map_embed.html
- geonode/qgis_server/tasks/update.py
- Fix Layer Detail View for QGIS Server
- Fix issues with thumbnail generations
Sometimes the execution is too fast, the database
were not in sync on different thread of celery
- Refactor and fix maps functionality
> Cumulative fixes for QGIS Server Map view

- geonode/layers/views.py
> [Fixes #3496][Monitoring] - saved_layer referenced before assignment

- geonode/base/models.py
- geonode/utils.py
> [Fixes #3504] - Keywords and encoding parsing issues on metadata upload

- geonode/contrib/monitoring/collector.py
- geonode/contrib/monitoring/management/commands/collect_metrics.py
- geonode/contrib/monitoring/middleware.py
- geonode/contrib/monitoring/models.py
- geonode/contrib/monitoring/service_handlers.py
- geonode/contrib/monitoring/tests.py
- geonode/contrib/monitoring/utils.py
- geonode/contrib/monitoring/views.py
- geonode/settings.py
> [Fixes #3518] [Monitoring plugin] - Collection of statistics should take into account TimeZones

- geonode/layers/templates/layers/layer_metadata_upload.html
- geonode/layers/templates/layers/layer_style_upload.html
> [Fixes #3506] - SLD and Metadata Upload Pages should maintain the Layer Permissions

- geonode/geoserver/helpers.py
- geonode/geoserver/views.py
> [Fixes #3533] - GeoServer Proxy creates a wrong URL when dealing with 'workspaces' bounded SLDs

- geonode/people/templates/people/profile_detail.html
- geonode/settings.py
- geonode/templates/500.html
- geonode/templates/pinax/notifications/account_approve/full.txt
- geonode/templates/pinax/notifications/email_body.txt
- requirements.txt
- setup.py
> [Fixes #3598] [Pinax Notifications] Upgrade to version 4.1.0

- geonode/geoserver/views.py
- geonode/layers/views.py
- geonode/local_settings.py.geoserver.sample
- requirements.txt
- setup.py
> [Fixes #3596] [OWS] GetCapabilities local cache on DJango

- geonode/layers/templates/layers/layer_geoext_map.html
- geonode/maps/templates/maps/map_geoexplorer.js
- geonode/maps/templates/maps/map_include.html
- geonode/static/geonode/js/extjs/GeoNode-GeoExplorer.js
- geonode/templates/geonode/geo_header.html
- geonode/templates/geonode/geo_header_debug.html
> [Fixes #3591] [Map Client - GeoExplorer] Zoom level seems not to be respected the first time

- geonode/layers/templates/layers/layer_detail.html
- geonode/layers/views.py
> [Fixes #3609] Download filter not working

- docs/tutorials/users/edit_style/index.txt
This page is difficult to read. Added extra punctuation, formatting, and changed some sentences.
> Fix readability

- geonode/base/models.py
- geonode/geoserver/helpers.py
- geonode/geoserver/signals.py
- geonode/settings.py
This is a backport of https://github.com/GeoNode/geonode/pull/3617
> Add ability to control thumbnail generation implementation (backport)

- geonode/base/models.py
- geonode/geoserver/helpers.py
- geonode/geoserver/signals.py
- geonode/settings.py
> Add ability to control thumbnail generation implementation

- geonode/contrib/monitoring/management/commands/collect_metrics.py
- geonode/contrib/monitoring/management/commands/render_metrics.py
- geonode/contrib/monitoring/service_handlers.py
- geonode/contrib/monitoring/utils.py
- geonode/utils.py
> [Fixes #3588] [Monitoring] Protect GeoServer REST endpoint and make requests pass through GeoNode Proxy

- geonode/people/adapters.py
> [Fixes #3619] Password reset error with 'people' adapter

- geonode/geoserver/helpers.py
> [Fixes #3593] Thumbnail generation issue for layer in non EPSG:4326 projection

- geonode/geoserver/helpers.py
- geonode/geoserver/signals.py
- geonode/geoserver/upload.py
- geonode/geoserver/urls.py
- geonode/geoserver/views.py
- geonode/layers/forms.py
- geonode/layers/templates/layers/layer_metadata_upload.html
- geonode/layers/tests.py
- geonode/layers/utils.py
- geonode/layers/views.py
- geonode/local_settings.py.geoserver.sample
- geonode/qgis_server/signals.py
- geonode/security/utils.py
- geonode/services/serviceprocessors/wms.py
- geonode/settings.py
- geonode/static/geonode/js/upload/LayerInfo.js
- geonode/tests/integration.py
- geonode/tests/smoke.py
- geonode/upload/files.py
- geonode/upload/tests/integration.py
- geonode/upload/tests/test_settings.py
- geonode/upload/upload.py
- geonode/upload/utils.py
- geonode/utils.py
> [Fixes #3636][Fixes #3639] - Replaces PRs for #3636 and #3639 along with test fixes

- README
I added the docker install document link in the readme file.
> add doc link for install and running docker

- geonode/maps/views.py
> [Fixes #3665] http request bad keyword argument layers=

- geonode/templates/metadata_form_js.html
> [Fixes #3668] Metadata Advanced and Wizard return links broken

- tasks.py
> Fix nginx service as allowed host

- docs/tutorials/advanced/geonode_production/production.txt
Closes https://github.com/GeoNode/geonode/issues/3613
> Documentation on Google & Bing basemaps

- geonode/api/fixtures/group_test_data.json
- geonode/groups/fixtures/group_test_data.json
- geonode/groups/fixtures/test_data.json
- geonode/people/fixtures/people_data.json
- geonode/people/fixtures/sample_admin.json
- geonode/security/fixtures/security_data.json
- geonode/settings.py
- package/support/geonode.admin
> [Closes #3713] Update settings password hashers

- geonode/decorators.py
- geonode/groups/tests.py
- geonode/groups/views.py
- geonode/invitations/views.py
- geonode/people/templates/people/profile_detail.html
- geonode/templates/500.html
- geonode/templates/base.html
- geonode/templates/user_messages/_message_snippet.html
> [Fixes #3704] Protect and hide views and pages accessible to superuser only

- geonode/client/templates/geoext/maps/map_include.html
> [Fixes #3700] Map detail page wrong zoom

- geonode/contrib/createlayer/utils.py
- geonode/contrib/datastore_shards/models.py
- geonode/contrib/datastore_shards/tests.py
- geonode/contrib/datastore_shards/utils.py
- geonode/contrib/exif/utils.py
- geonode/contrib/monitoring/collector.py
- geonode/contrib/mp/signals.py
> [Closes #3721] Align contrib apps with Django improvements and remove print statements

- dev_config.yml
- docs/tutorials/install_and_admin/geonode_update/26_to_27/index.txt
- geonode/base/populate_test_data.py
- geonode/layers/views.py
- geonode/local_settings.py.geoserver.sample
- geonode/maps/models.py
- geonode/maps/views.py
- geonode/messaging/__init__.py
- geonode/messaging/management/commands/runmessaging.py
- geonode/messaging/producer.py
- geonode/settings.py
- geonode/tests/integration.py
- geonode/upload/tests/test_settings.py
- geonode/upload/utils.py
- geonode/utils.py
- package/install.sh
- package/support/geonode.local_settings
- pavement.py
- requirements.txt
- setup.py
> [Fixes #3702] Improve settings and documentation accordingly for CELERY and MAP DEFAULT CRS

- geonode/layers/views.py
> [Fixes #3712] Fix Layer getFeatureInfo Property Labels

- geonode/base/forms.py
> [Closes #3720] Improve Base Regions Form Widget: remove deprecated stuff and use region IDs consistently

- geonode/base/management/commands/backup.py
- geonode/base/management/commands/fixoauthuri.py
- geonode/base/management/commands/helpers.py
- geonode/base/management/commands/load_thesaurus.py
- geonode/base/management/commands/migrate_baseurl.py
- geonode/base/management/commands/migrate_layers.py
- geonode/base/management/commands/restore.py
- geonode/base/management/commands/settings.ini
- geonode/layers/management/commands/importlayers.py
- scripts/backup-restore/backup.py
- scripts/backup-restore/helpers.py
- scripts/backup-restore/restore.py
- scripts/backup-restore/settings.ini
> [Closes #3715] Remove deprecated BaseCommand.option_list from management commands

- .travis.yml
- geonode/catalogue/backends/pycsw_local.py
- geonode/catalogue/backends/pycsw_plugin.py
- geonode/settings.py
- requirements.txt
- setup.py
> [Fixes #3703] Upgrade pycsw to the new version 2.2.0

- geonode/contrib/metadataxsl/views.py
- geonode/geoserver/helpers.py
- geonode/geoserver/signals.py
- geonode/geoserver/views.py
- geonode/layers/views.py
- geonode/maps/models.py
- geonode/maps/views.py
- geonode/people/templates/people/profile_detail.html
- geonode/services/admin.py
- geonode/services/apps.py
- geonode/services/management/commands/importservice.py
- geonode/services/serviceprocessors/arcgis.py
- geonode/services/serviceprocessors/handler.py
- geonode/services/serviceprocessors/wms.py
- geonode/services/signals.py
- geonode/services/templates/services/service_list.html
- geonode/services/templates/services/service_resources_harvest.html
- geonode/services/tests.py
- geonode/services/utils.py
- geonode/services/views.py
- geonode/settings.py
- geonode/templates/500.html
- geonode/templates/base.html
- geonode/tests/integration.py
- geonode/utils.py
- requirements.txt
> [Fixes #3705] Add GeoNode (OWS) and ArcGIS Endpoints to Remote Services

- geonode/urls.py
> [Rebased] Changed pattern for user name in capabilities url (added +@)

- docs/tutorials/install_and_admin/geonode_install/install_geonode_application.txt
Because nice and readable documentation matters ;)
> aligned lines in code block

- setup.py
The dedicated requirements_docs.txt is enough now
> remove fix for readthedocs

- geonode/templates/index.html
> [FIX #3643] fix/better display for discover section on homepage

- geonode/__init__.py
- geonode/apps.py
- geonode/geoserver/upload.py
- geonode/layers/tasks.py
- geonode/qgis_server/tasks/update.py
- geonode/settings.py
- geonode/tests/bdd/conftest.py
- requirements.txt
- setup.py
> [Fixes #3769] - Pip install geonode complains about Celery

- geonode/geoserver/helpers.py
> Fixes #3789

- requirements.txt
>  - Fixes issue #3843 - Fix vulnerability with Pillow dependency

- docs/tutorials/install_and_admin/running_docker/setup_docker_compose.txt
A note about the solutions given in #3709
> note on docker-compose up for Windows users (see #3709)

- package/support/geonode.updateip
> [Fixes #3874] sudo geonode-updateip fails on fresh Ubuntu 16.04 install

- docs/tutorials/install_and_admin/geonode_install/install_geoserver_application.txt
the folder /data/geoserver-data/geonodeAuthProvider is not more present
> removed step in geonode authentication

- docs/tutorials/install_and_admin/geonode_install/install_geonode_application.txt
fixes the missing -get at GeoNode Setup
> fix missing '-get' in apt-get

- geonode/utils.py
issue https://github.com/GeoNode/geonode/issues/3921
> return layer styles in map json as a list

- geonode/contrib/worldmap/wm_extra/views.py
- geonode/maps/admin.py
- geonode/utils.py
@afabiani this is fixing a problem with snapshots I am experiencing.
I am not sure why you need to save the map from layer_from_viewer_config (I think you added that), but just in case I added an optional save_map parameter which defaults to True.
Saving the map from there is causing snapshots to add duplicate layers.
> Fixes issue 4046

- geonode/client/templates/worldmap/maps/map_worldmap.html
- geonode/context_processors.py
- geonode/contrib/worldmap/gazetteer/utils.py
- geonode/contrib/worldmap/gazetteer/views.py
- geonode/settings.py
- requirements.txt
* Improvements on the gazetteer tool: external services can be set from the template
* Enable the enter key in the search text field
* Fixes a problem with icons path
> [worldmap-client] Improvements and fixes on the Gazetteer. Fixes #4072.

- geonode/client/templates/worldmap/maps/map_worldmap.html
- geonode/context_processors.py
- geonode/contrib/worldmap/wm_extra/views.py
- geonode/settings.py
- requirements.txt
Makes Google StreetView optional. Bump django-geoex plorer-worldmap 4.0.61. Remove some unused code
> [worldmap-client] Makes Google StreetView optional. Bump django-geoex plorer-worldmap 4.0.61. Remove some unused code

- geonode/base/models.py
- geonode/settings.py
>  - Making OAUTH2 Access Token expiration seconds configurable by settings/env

- geonode/base/enumerations.py
Otherwise language_title method in geonode/base fails (the list comprehension would be empty)
> Added chinese to ALL_LANGUAGES enumeration

- scripts/docker/env/production/celery.env
- scripts/docker/env/production/django.env
- scripts/spcgeonode/django/docker-entrypoint.sh
- scripts/spcgeonode/django/initialize.py
- scripts/spcgeonode/docker-compose.yml
> Use gs instead of geoserver for URLs in Docker

- docker-compose.override.localhost.yml
- docker-compose.override.yml
- docs/reference/worldmap.txt
- docs/tutorials/install_and_admin/geonode_install/create_geonode_db.txt
- docs/tutorials/install_and_admin/geonode_install/setup_configure_httpd.txt
- docs/tutorials/install_and_admin/geonode_update/26_to_27/index.txt
- docs/tutorials/install_and_admin/running_docker/resources/docker-compose.yml
- docs/tutorials/install_and_admin/setup_on_centos/install_geonode.txt
- geonode/local_settings.py.psql_test
- package/support/geonode.local_settings
- tasks.py
> Fix missing replacement of geoserver public location

- geonode/layers/search_indexes.py
> Revert " Includes additional layer fields in the search index"

- geonode/geoserver/tasks.py
set task queue for  the thumbnail_task to 'update' queue instead of using the default
> use 'update' queue instead of using the default

- scripts/spcgeonode/geoserver/Dockerfile
- scripts/spcgeonode/geoserver/docker-entrypoint.sh
Pull request for SPC Geonode. No regression detected with `geonode-selenium`. Using `ARG` to parametrize the Dockerfile.
> Update GeoServer to 2.14.2

- AUTHORS
> Add frafra to AUTHORS

- scripts/spcgeonode/geoserver/docker-entrypoint.sh
Longer wait and set the parameter correctly.
> Fix GeoServer wait for Postgres

- geonode/geoserver/signals.py
- geonode/geoserver/tasks.py
- geonode/geoserver/utils.py
This fixes #4317 and https://github.com/GeoNode/geonode-project/issues/67.
When this pull request will be merged into master, I will push the test I have made for geonode-selenium, so the old pull request could be modified and checked automatically to avoid the regression.
> Revert "add async_thumbnail to improve upload time"

- geonode/static/geonode/css/base.css
added .profile-details small with word-wrap break words as suggested by @t-book
> fixes profile text overflow UI glitch #4376

- docs/tutorials/install_and_admin/running_docker/setup_docker_compose.txt
> Documentation: Spelling Fix

- .travis.yml
- geonode/geoserver/helpers.py
- geonode/geoserver/tests.py
- geonode/layers/utils.py
- geonode/settings.py
- geonode/utils.py
> [Fixes #4447] Database locked when using sqlite/spatialite databases

- docs/install/core/index.rst
- package/support/geonode.binary
- publish.sh
- scripts/misc/apache2/geonode.conf.sample
> address WORKON_HOME variable abuse and unneeded .bashrc tweak

- README.rst
After the new docs are finished the Reamde needs to be reviewed. Until now let's have it good looking.
> Fixed OpenSource Image on Readme

- docs/install/core/index.rst
> more proper pygdal version filtering

- docs/install/core/docker/ubuntu.rst
- docs/install/core/index.rst
> [New docs] docker part improvements 

- geonode/upload/files.py
See / Fixes: #4478
```
ARNING:geonode.upload.utils:Traceback (most recent call last):
File "./geonode/upload/views.py", line 649, in view
resp = _steps[step](req, upload_session)
File "./geonode/upload/views.py", line 175, in save_step_view
charset=form.cleaned_data["charset"]
File "./geonode/upload/files.py", line 262, in scan_file
raise Exception(_("Could not access to uploaded data."))
Exception: Zugriff auf hochgeladene Daten nicht m\xf6glich.
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 38: ordinal not in range(128)
ERROR:django.request:Internal Server Error: /upload/
File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
response = get_response(request)
File …
```
> Upload Exception cannot handle special character  (Fixes: #4478)

- README.md
- geonode/local_settings.py.geoserver.sample
- geonode/settings.py
- requirements.txt
- setup.py
- [requirements] django-mapstore-adapter==1.0.1
- [requirements] django-geonode-mapstore-client==1.1
>  - Minor Adjustments to README and settings

- docs/usage/managing_layers/using_remote_services.rst
- docs/usage/managing_maps/creating_maps.rst
- docs/usage/managing_maps/index.rst
Added more explanations in user guide about the available types of remote services.
> Add more explanations about remote services types

- docs/install/core/index.rst
This shortens the installation for pygdal by use of range *
> Docs: Simplify pygdal installation step

- Dockerfile
- docker-compose.async.yml
- docker-compose.yml
The dockerimage tags were wrong. They were updated by @francbartoli to follow GN-major.minor naming convention. This PR does change the dockerfiles to align with the new convention.
- [ x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING) 
I can not sign this CLA for my company without discussing it within the corporation (research institute - www.thuenen.de). I am contributing as single person currently.
I will not target master …
> [Fixes #4636 ] Docker install - build

- dev_config.yml
- docker-compose-geoserver-server.yml
- docker-compose.async.yml
- docker-compose.yml
- docs/install/core/index.rst
- docs/install/project/index.rst
- scripts/spcgeonode/geoserver/Dockerfile
> [Fixes #4653] Use GeoServer 2.15.2

- geonode/base/templates/base/_resourcebase_opengraph.html
- geonode/groups/templates/groups/_group_opengraph.html
- geonode/people/templates/people/_profile_opengraph.html
- geonode/proxy/tests.py
- geonode/proxy/views.py
- geonode/settings.py
> [Fixes #4656] When DEBUG=False configured remote services should be PROXY ALLOWED

- AUTHORS
> added gannebamm to authors

- geonode/upload/tests/integration.py
- pavement.py
- requirements.txt
> Bump owslib from 0.17.1 to 0.18.0

- Dockerfile
- docker-compose.async.yml
- docker-compose.yml
> Revert "[Fixes #4636 ] Docker install - build"

- geonode/maps/templates/layouts/map_panels.html
small typo in map_panels.html creates broken link, fixed
> typo in map_panels.html, broken link

- Dockerfile
- docker-compose.async.yml
- docker-compose.yml
> [Backport 2.10.x] Revert "[Fixes #4636 ] Docker install - build" (#4678)

- Dockerfile
- docker-compose.async.yml
- docker-compose.yml
Fix inconsistencies with GeoNode version for images from Docker Hub which basically has to follow simply this rule:
- docker-compose scripts on master branch have to stick with the newest branch version (Es. `geonode/geonode:2.10.x` now)
- docker-compose scripts on specific branch have to be aligned with that branch version (Es. `geonode/geonode:2.10.x`)
Proposal for tag release:
- docker-compose scripts on tag release have to be changed with the tag number of the release. Also, a GitHub tag has to be created for each `<component>-docker` repository on GitHub and consequently a tagged image has to be triggered on Docker Hub from the GitHub tag already generated. (Es. `geonode/geonode:2.10`)
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep …
> Fix geonode docker image version

- geonode/base/management/commands/load_thesaurus.py
- geonode/catalogue/backends/generic.py
- geonode/catalogue/backends/pycsw_local.py
- geonode/catalogue/metadataxsl/views.py
- geonode/catalogue/models.py
- geonode/catalogue/views.py
- geonode/geoserver/helpers.py
- geonode/geoserver/views.py
- geonode/layers/metadata.py
- geonode/layers/views.py
- geonode/maps/tests.py
- geonode/maps/views.py
- geonode/monitoring/tests.py
- geonode/monitoring/utils.py
- geonode/qgis_server/gis_tools.py
- geonode/qgis_server/helpers.py
- geonode/qgis_server/models.py
- geonode/qgis_server/tests/test_helpers.py
- geonode/qgis_server/tests/test_views.py
- geonode/security/tests.py
- geonode/tests/csw.py
- geonode/tests/integration.py
- geonode/upload/utils.py
- requirements.txt
> [Backport 4729 to 2.10.x] Use defusedxml instead of xml 

- geonode/settings.py
- pavement.py
- requirements.txt
Bump geonode-oauth-toolkit from 1.1.3 to 1.1.4.1rc0
> Bump geonode-oauth-toolkit from 1.3.1 to 1.1.4.1rc0

- geonode/geoserver/helpers.py
- geonode/proxy/views.py
- geonode/security/tests.py
- geonode/settings.py
- geonode/upload/tests/integration.py
- geonode/utils.py
> [Fixes #4713] Attributes are not added in layers_attributes table when a layer is uploaded

- requirements.txt
> Backporting dependabot requirements updates from master branch

- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/gnip.md
- .github/ISSUE_TEMPLATE/report_issue.md
> Update Issues Templates

- geonode/monitoring/frontend/index.html
- geonode/templates/500.html
- geonode/templates/base.html
FIxes: #4774 4771
_I've recreated the PR as I messed up GPG keys._
When password auto-complete is enabled, the browser will remember the password entered into the login form, such that it will automatically fill it next time the user tries to login.
However, if an attacker gains physical access to the victim's computer, he can retrieve the saved password from the browser's memory and use it to gain access to the victim's account in the application.
Furthermore, if the application is also vulnerable to Cross-Site Scripting, the attacker could steal the saved password remotely.
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free …
> [Fixes: #4774][Fixes: #4771] Removed autocomplete from password fields

- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/gnip.md
- .github/ISSUE_TEMPLATE/report_issue.md
- requirements.txt
> [Backport 2.10.x] Backporting dependabot requirements to 2.10.x

- geonode/documents/tasks.py
- geonode/geoserver/tasks.py
- geonode/layers/tasks.py
- geonode/maps/tasks.py
- geonode/qgis_server/tasks/update.py
- geonode/services/tasks.py
- geonode/settings.py
- geonode/tasks/tasks.py
> [Fixes #4813] Removing a layer is broken - Celery error

- geonode/settings.py
Fixes #4844 
- [] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [] The issue connected to the PR must have Labels and Milestone assigned
> Fixes #4844

- docs/intermediate/monitoring/user_analytics/index.rst
- geonode/monitoring/collector.py
- geonode/monitoring/tests/integration.py
- geonode/monitoring/utils.py
- geonode/monitoring/views.py
This PR fixes #4842 .
It makes the monitoring frontend able to retrieve:
- the number of unique visitors (users) in a time interval (fixes #4841 )
- the number of anonymous users sessions count (fixes #4840 )
- the unique visitors list with sessions count for each visitor (fixes #4822 )
The `monitoring/collector.py` module contains the changes to the `get_metrics_data` method which build the query.
In the `monitoring/views.py` module, the [`MetricsFilters` form](https://github.com/GeoNode/geonode/blob/6cd3ec5b06bbd578694b5298e38138e6150dc194/geonode/monitoring/views.py#L157) has been improved to allow the following "group_by" conditions:
- `GROUP_BY_USER = 'user'`
- `GROUP_BY_USER_ON_LABEL = 'user_on_label'`
A new `user` CharField has been also introduced with related validation method:
- …
> [Fixes #4842] Monitoring APIs improvements

- geonode/monitoring/collector.py
- geonode/monitoring/fixtures/metric_data.json
- geonode/monitoring/tests/integration.py
This PR fixes #4849 .
Metric data about `cpu.usage.percent`, `mem.usage.percent` and `uptime` metrics are now available for the monitoring frontend.
> [Fixes #4849] retrieve cpu and mem usage metric data

- geonode/geoserver/signals.py
- geonode/monitoring/collector.py
- geonode/monitoring/management/commands/collect_metrics.py
- geonode/monitoring/tests/integration.py
- geonode/security/tests.py
- geonode/settings.py
- geonode/tests/utils.py
- geonode/upload/tests/integration.py
- geonode/upload/tests/test_settings.py
- geonode/upload/utils.py
- geonode/upload/views.py
> [Fixes  #4855] Download links always return whole world bbox

- geonode/static/geonode/js/upload/LayerInfo.js
- geonode/templates/_permissions.html
- geonode/templates/_permissions_form_js.html
> [Fixes #4863] Trying to assign permission to more than one users, fails

- geonode/geoserver/helpers.py
- geonode/tests/integration.py
> [Fixes #4827] Line layer uploaded to GeoNode is rendered as point layer

- geonode/monitoring/collector.py
- geonode/monitoring/tests/integration.py
This PR fixes #4903 .
Wrong repeated "for loop" has been removed in the `process_requests_batch`method (called by `collec_metrics` command).
When grouping by `event_type` the requests (hits) count is now returned.
**Submitting the PR does not require you to check all items, but by the time it gets …
> [Fixes #4903] fixing wrong hits count

- geonode/templates/index.html
Fixes https://github.com/GeoNode/geonode/issues/4916
Angular problem not showing featured items
> [Fixes #4916] – show featured items on startpage

- geonode/groups/forms.py
- geonode/groups/templates/groups/group_members.html
- geonode/groups/views.py
> [Fixes #4924] Add member to Group is broken

- geonode/templates/base.html
Fixes #4933
Include the link to the password reset inside the login modal form
- [] New unit tests have been added covering the changes, unless there are explanation on why the tests are not necessary/implemented
> [Fixes: #4933] forgot password in modal

- geonode/templates/account/verification_sent.html
[Fixes: #4963] 
Correct template include
> [Fixes: #4963] Fix wrong template include for all_auth

- geonode/upload/models.py
- geonode/upload/tests/integration.py
[Fixes #4949] UnicodeEncodeError in upload.models.update_from_session
> [Fixes #4949] UnicodeEncodeError in upload.models.update_from_session

- geonode/static/geonode/js/search/search.js
- geonode/templates/base.html
> [Fixes #4964] Date widget has gone

- geonode/layers/management/commands/set_layers_permissions.py
- geonode/layers/tests.py
- geonode/layers/utils.py
> [Fixes #4990] fix set_layers_permissions managament command

- docs/advanced/contrib/index.rst
- docs/advanced/index.rst
- docs/advanced/ldap/index.rst
Adding LDAP configuration docs with few advanced configuration hints.
> [Documentation] LDAP Contrib Module Documentation

- geonode/documents/templates/documents/document_detail.html
- geonode/layers/templates/layers/layer_detail.html
- geonode/maps/templates/maps/map_detail.html
- geonode/settings.py
> [Fixes: #4929] Remove Google+ from share options

- geonode/settings.py
This PR fixes #5031 .
Monitoring disabled by default.
Ref. #4986 
> [Fixes #5031] Disable monitoring by default

- geonode/layers/templates/layers/layer_detail.html
- geonode/proxy/templatetags/__init__.py
- geonode/proxy/templatetags/proxy_lib_tags.py
- geonode/proxy/views.py
- geonode/templates/401.html
- geonode/templates/base.html
- Fixes #4956 : "Original Dataset" Link behavior improvements
> [Fixes #4956] "Original Dataset" Link behavior improvements

- docs/basic/settings/index.rst
- geonode/settings.py
- requirements.txt
- Fixes #5070 : Add Bing background layer config to MapStore2 adapter if apiKey is provided
> [Fixes #5070] Add Bing background layer config to MapStore2 adapter if apiKey is provided

- docs/install/core/index.rst
- Correct Tomcat Version
- Fix gzip compression for js
Fixes #5073
Closes #5073
> [Fixes #5073] Update install docs

- geonode/layers/tests.py
- geonode/layers/utils.py
- geonode/locale/ar/LC_MESSAGES/django.po
This PR mitigates possibilities for error #2932 - which I am experiencing when uploading a layer with a same name of a recently removed layer in installations with a large number of layers.
> [Fixes  #2932] Unable to update a layer (replace action) nor create a new layer with the same name of a already deleted layer

- requirements.txt
> Revert "Bump amqp from 2.5.1 to 2.5.2"

- geonode/templates/about.html
deleted about GeoNode duplicate in template
> [Fixes #5258] Duplicate Headline in /about

- dev_config.yml
- docker-compose-geoserver-server.yml
- docker-compose.async.yml
- docker-compose.yml
- docs/install/core/index.rst
- docs/install/project/index.rst
- scripts/spcgeonode/geoserver/Dockerfile
- Fixes #5264 : Use GeoServer 2.15.3
> [Fixes #5264] Use GeoServer 2.15.3

- geonode/geoserver/helpers.py
- geonode/groups/models.py
- geonode/monitoring/models.py
- requirements.txt
- Fixes #5283 : UnicodeEncodeError when trying to delete a Layer on a GeoNode instance with action streams containing exotic characters.
> [Fixes #5283] UnicodeEncodeError when trying to delete a Layer on a GeoNode instance with action streams containing exotic characters.

- .clabot
@afabiani cannot push directly here. let me know if we need an issue here and I will open one and add checklist ...
> Added kikislater to contributors

- .clabot
This Pr is for maintenance github no milestones assigned.
> Fixes: #5306 Add new contributors to cla

- geonode/static/geonode/css/base.css
- geonode/static/geonode/less/base.less
added `visibility: hidden;` to keyframe for msgDisappear. Now the div #user_message is hidden and does not overlay the site anymore.
> Fixes #5311 user_messages div does not completely disappear

- geonode/people/test_adapters.py
- geonode/proxy/tests.py
- geonode/services/tests.py
- geonode/upload/tests/test_upload_preprocessing.py
PR to switch to the built-in mock library as outlined in https://github.com/GeoNode/geonode/issues/4276
The mock package is now included in the Python 3 standard library. Changes have been made to allow for easy transition to Python 3 and the unittest.mock library. …
> [Issue #4276] Updated to import unittest.mock over legacy mock package

- geonode/layers/views.py
- Fixes #5339 : [Performance] Vectorial Layers are quite slow while trying to fetch the details page
> [Fixes #5339][Performance] Vectorial Layers are quite slow while trying to fetch the details page

- geonode/catalogue/__init__.py
- geonode/catalogue/backends/generic.py
- geonode/catalogue/backends/pycsw_local.py
- geonode/catalogue/backends/pycsw_plugin.py
- geonode/catalogue/metadataxsl/management/commands/addmissinglinks.py
- geonode/catalogue/metadataxsl/models.py
- geonode/catalogue/tests.py
- geonode/catalogue/views.py
PR to update `catalogue` app to be Python 2.7/3 cross-compatible as part of https://github.com/GeoNode/geonode/issues/4276.
> [Issue #4276] Upgrade catalogue for Python 2.7/3 compatibility

- pavement.py
- tasks.py
PR to update the base directory *.py scripts to be Python 2.7/3 cross-compatible as part of #4276.
> [Issue #4276] Upgrade base dir for Python 2.7/3 compatibility

- scripts/backup-restore/backup.py
- scripts/backup-restore/helpers.py
- scripts/backup-restore/migrate_layers.py
- scripts/backup-restore/restore.py
- scripts/cloud/demo_site.py
- scripts/cloud/ec2.py
- scripts/cloud/fabfile.py
- scripts/misc/create_full_geonode_db.py
- scripts/misc/upload.py
PR to update the scripts/ directory to be Python 2.7/3 cross-compatible as part of #4276.
> [Issue #4276] Running 2to3 on scripts module

- .travis.yml
This merge request avoid running setup steps that have been included in the geonode-selenium new container.
> [Fixes #5365] Setup code moved to geonode-selenium container

- geonode/base/management/commands/updategeoip.py
> [Fixes #5463] Change geolite2-city endpoint

- geonode/templates/500.html
> [Fixes #5467] Gender neutral terminology

- .clabot
- [] The issue connected to the PR must have Labels and Milestone assigned
> Add lucernae to CLA

- docs/install/core/index.rst
[Fixes #5464] Update docs for Tomcat download
Updated version .47 to .50
> [Fixes #5464] Update docs for Tomcat download

- geonode/geoserver/tests/test_helpers.py
- geonode/geoserver/views.py
[Fixes #5497] W*S on QGis not authenticating
> [Fixes #5497] W*S on QGis not authenticating

- geonode/layers/utils.py
- geonode/local_settings.py.geoserver.sample
- geonode/maps/tests.py
- geonode/security/utils.py
- geonode/settings.py
- geonode/utils.py
- package/support/geonode.local_settings
- requirements.txt
- [Fixes #5504] Map Thumbnails Broken
> [Fixes #5504] Map Thumbnails Broken

- dev_config.yml
- docker-compose-geoserver-server.yml
- docker-compose.async.yml
- docker-compose.yml
- docs/install/core/index.rst
- docs/install/project/index.rst
- geonode/local_settings.py.geoserver.sample
- geonode/settings.py
- scripts/spcgeonode/geoserver/Dockerfile
>  - Bump to GeoServer 2.15.4

- dev_config.yml
- docker-compose-geoserver-server.yml
- docker-compose.async.yml
- docker-compose.yml
- docs/install/core/index.rst
- docs/install/project/index.rst
- geonode/local_settings.py.geoserver.sample
- geonode/settings.py
- scripts/spcgeonode/geoserver/Dockerfile
(cherry picked from commit 944e543bab6071ca2bb95280c58c290a7a356a41)
> [Backport 5507 to 2.10.x] - Bump to GeoServer 2.15.4

- dev_config.yml
PR to update JETTY_RUNNER_URL in `dev_config.yml` to the new HTTPS equivalent of the old URL. The old URL now displays this error:
```
501 HTTPS Required. 
Use https://repo1.maven.org/maven2/
More information at https://links.sonatype.com/central/501-https-required
```
This PR simply amends the URL in accordance with the [page](https://links.sonatype.com/central/501-https-required) specified above. …
> Update JETTY_RUNNER_URL to secure HTTPS equivalent

- geonode/base/forms.py
- geonode/base/management/commands/backup.py
- geonode/base/management/commands/helpers.py
- geonode/base/management/commands/migrate_notifications.py
- geonode/base/populate_test_data.py
- geonode/base/templatetags/base_tags.py
- geonode/documents/tests.py
- geonode/documents/views.py
- geonode/geoserver/tests/test_server.py
- geonode/geoserver/views.py
- geonode/layers/tests.py
- geonode/layers/utils.py
- geonode/layers/views.py
- geonode/maps/models.py
- geonode/security/models.py
- geonode/security/tests.py
- geonode/services/serviceprocessors/arcgis.py
- geonode/services/tests.py
- geonode/utils.py
Co-authored-by: Dingding Fan <dingdingfan@catalyst.net.nz>
Co-authored-by: Dana Lambert <danalambert@catalyst.net.nz>
**PR to the GeoNode:bump_to_python3 branch** to merge our (NZ contributors) work on core modules in GeoNode for the upgrade to Python 3. These are primarily amendments that remove redundant code and fixes to minor bugs encountered when testing locally (`paver run_tests`) under Python 3.6.9. …
> [Issue #4276] Fixes to core modules for Python 3

- docs/devel/index.rst
- docs/devel/installation/index.rst
- docs/devel/installation/install_gdal_for_development.rst
- docs/devel/running/index.rst
- docs/devel/workshops/index.rst
**This PR resolves adding documentation for Develop section to be added here:** http://docs.geonode.org/en/stable/devel/index.html
**The changes include:**
- Adding documentation for installing GeoNode Core and Project for development purposes
- Adding documentation for installing GDAL for development 
- Adding documentation for running/starting GeoNode Core and Project for development
- Adding documentation for the developers workshops 
The following are required only for core and extension …
> Adding documentation for Develop section

- docs/devel/installation/index.rst
typo in l30 `service apahe2 stop`
> fix typo in docs/devel/installation/index.rst

- docker-compose.async.yml
- requirements.txt
PR to amend elasticsearch versions. At the present, when `HAYSTACK_SEARCH` is enabled, GeoNode fails to start as there is a version mismatch between the Python package (7.5) the elasticsearch server (2.4.1). The fix is to revert the elasticsearch Python package to version 2.4.x. The elasticsearch backend can also be upgraded to version 2.4.6.
elasticsearch could not be upgraded to version 5 or later due to the dependency on django-haystack, the latest version of which (2.8.1), does not officially support versions >2. Additionally, django-haystack lacks official support for Python versions >3.6 or Django versions >=2.1 (see Travis logs of https://github.com/django-haystack/django-haystack/tree/v2.8.1).
However, version 2 appears to retain searching capabilities with the Python 3 upgrade so …
> Fix elasticsearch versions

- geonode/layers/metadata.py
- geonode/layers/views.py
> [Fixes #5560] Cannot upload XML layer metadata

- geonode/templates/announcements/announcement_confirm_delete.html
PR to fix #5554 . Previously, this page was blank due to a reference to an old template that no longer exists. Amended this to extend `geonode_base.html` to remain consistent with other forms.
> [Fixes #5554] Fixed blank page when deleting announcements

- .clabot
Going without a ticket. If needed I will open it.
> Add travislbrundage to clabot

- docs/devel/workshops/index.rst
This PR fixed formatting issues, updated links and structure at workshop documentation page
> [Fixes #5562] Formatting issues at Develop documentation

- docs/basic/settings/index.rst
- geonode/api/api.py
- geonode/api/authorization.py
- geonode/api/tests.py
- geonode/groups/tests.py
- geonode/settings.py
[Fixes #5437] API endpoints reveal too much information - 2.10.x
(cherry picked from commit bdf13968a660d846dc70eb279f57a6777c2be2b9)
#	geonode/api/api.py
#	geonode/groups/tests.py …
> [Fixes #5437] API endpoints reveal too much information

- requirements.txt
Security patch for Django 2.2.9: upgrading to 2.2.10 to fix CVE-2020-7471, see #5615
> Upgrade to Django 2.2.10

- requirements.txt
Security patch for Django 1.11.27: upgrading to 1.11.28 to fix CVE-2020-7471, see #5615
> Upgrade to Django 1.11.28

- dev_config.yml
- docker-compose-geoserver-server.yml
- docker-compose.async.yml
- docker-compose.yml
- docs/install/core/index.rst
- docs/install/project/index.rst
- geonode/geoserver/helpers.py
- geonode/monitoring/service_handlers.py
- geonode/security/tests.py
- package/geoserver/rpm/SPECS/geoserver.spec
- requirements.txt
- scripts/docker/env/development/geoserver.env
- scripts/docker/env/production/geoserver.env
- scripts/spcgeonode/geoserver/Dockerfile
>  - Bump to GeoServer 2.16.2

- geonode/groups/models.py
> [Fixes #5656] Typo in on_delete at groups

- .pre-commit-config.yaml
- pyproject.toml
- requirements_dev.txt
> Add pre-commit and black

- .travis.yml
> [Fixes #5743] Add codecov to Selenium tests

- geonode/api/tests.py
- geonode/base/forms.py
- geonode/base/management/commands/fixoauthuri.py
- geonode/base/populate_test_data.py
- geonode/catalogue/views.py
- geonode/geoserver/createlayer/utils.py
- geonode/geoserver/management/commands/find_geoserver_broken_layers.py
- geonode/geoserver/signals.py
- geonode/monitoring/tests/integration.py
- geonode/notifications_helper.py
- geonode/people/admin.py
- geonode/people/forms.py
- geonode/people/models.py
- geonode/people/search_indexes.py
- geonode/people/views.py
- geonode/security/tests.py
- geonode/security/views.py
- geonode/services/serviceprocessors/arcgis.py
- geonode/settings.py
- geonode/social/apps.py
- geonode/social/tests.py
- geonode/tests/bdd/e2e/test_login.py
- geonode/upload/tests/integration.py
- scripts/misc/create_full_geonode_db.py
- scripts/spcgeonode/django/initialize.py
> [Fixes #5809] Use "get_user_model" everywhere in order to allow full pluggable AUTH_USER_MODEL

- geonode/base/management/commands/backup.py
- geonode/base/management/commands/restore.py
- geonode/base/management/commands/settings.ini
- geonode/layers/models.py
- geonode/utils.py
Geonode and Geoserver backup/restore procedure update:
- change an order of models declaration in geonode/layers/models.py to ensure proper fixture loading order
- fix for disabling Django signals on Geonode's backup and restore
> [Fixes #5821] Backup/restore procedure update

- geonode/base/management/commands/backup.py
- geonode/base/management/commands/restore.py
- geonode/base/management/commands/settings.ini
- geonode/layers/models.py
- geonode/utils.py
(cherry picked from commit a15c57cf1e8a8eed02dd23ceb8582fc0857899fa)
#	geonode/base/management/commands/backup.py
#	geonode/base/management/commands/restore.py
#	geonode/base/management/commands/settings.ini
#	geonode/layers/models.py …
> [Backport to 2.10.x][Fixes #5816] backup and restore update

- pavement.py
PR to remove the `sleep 30` call in the `start` task by polling the server within the `start_django` task until it returns a HTTP 200 response using the predefined `waitfor` function in `pavement.py`
> [Fixes #5555] Improved waiting time in start_django and start

- geonode/people/templates/people/profile_detail.html
> [Fixes #5858] Add direct link do "Upload new Document" to Profile page

- .travis.yml
- setup.py
> [Fixes #5875] GeoNode requirement Python >= 3.6

- geonode/base/management/commands/helpers.py
(cherry picked from commit ca23620648db871ae712b49965668510385d35b4)
> [Backport to 2.10.x][Fixes #5866] Restore errors

- geonode/base/management/commands/backup.py
- geonode/base/management/commands/helpers.py
Create MD5 hash file for backup archive
> [Fixes #5896] Create MD5 hash file for backup zip

- geonode/base/management/commands/restore.py
If the MD5 file, with same name as the backup *.zip package, is placed in the same directory, the restore command should check the integrity of the zip archive comparing the MD5 hashes.
> [Fixes #5899] Check backup archive MD5 on restore

- geonode/invitations/views.py
- geonode/messaging/__init__.py
- geonode/messaging/notifications.py
- geonode/people/adapters.py
- geonode/people/models.py
- geonode/templates/user_messages/email/email_new_message_message.txt
- geonode/templates/user_messages/email/email_new_message_subject.txt
- geonode/tests/test_message_notifications.py
Fix #5914 
https://github.com/GeoNode/geonode/issues/5914
add email notification after message is created in thread or new thread is created
refactor sending email code in adapters
create new email templates
**Submitting the PR does not require you to check all items, but by the time it gets merged, …
> [Fixes 5914] message notification 

- geonode/people/views.py
- geonode/settings.py
- geonode/templates/account/signup.html
- geonode/urls.py
This simply introduces new env variable to hide display local registration form 
https://github.com/GeoNode/geonode/issues/5910
Documentation update:
https://github.com/GeoNode/documentation/pull/19
**Submitting the PR does not require you to check all items, but by the time it gets merged, they …
> [Fixes #5910] Hide local registration form

- geonode/api/api.py
- geonode/api/authorization.py
- geonode/base/fixtures/group_test_data.json
- geonode/groups/views.py
- geonode/tests/test_rest_api.py
FIX #5931
Refactor group and group profile filtering in resource api. applay general filtering rules 
fix bugs in group view
adjust test fixture
> [Fixes #5931] Add filtering to usergroups

- geonode/api/api.py
- geonode/groups/tests.py
- geonode/templates/search/_search_user_content.html
- Fixes #5933 Filtering logic error on GroupCategoryResource
> [Fixes #5933] Filtering logic error on GroupCategoryResource

- geonode/security/tests.py
- geonode/security/utils.py
- Fixes #5940 5940  GeoLimits must be stored as native CRS for Raster-type layers
> [Fixes #5940] GeoLimits must be stored as native CRS for Raster-type layers

- geonode/groups/templates/groups/_group_profile_list_item.html
- geonode/groups/templates/groups/group_list.html
- geonode/templates/search/_group_snippet.html
FIX #5942
Hit GroupProfile instead of Group in Group View. Refactor its code to reach froup profile attributes directly. Minor fixes in broken HTML structure.
In my opinion, it is  a good moment to remove GroupResorce completely, it is anyway just a proxy to GroupProfile  
**Submitting the PR does …
> [Fixes #5942] Sorting is not working on group view

- geonode/br/management/commands/backup.py
- geonode/br/management/commands/restore.py
1. B/R project-template support - dumping and restoring only apps located in LOCAL_ROOT directory, and skipping these located in site-packages of the interpreter
2. gs-backup-restore-core and gs-backup-restore-rest patches support (JSON request headers in B/R)
3. in restore with docker: backup archive should be extracted to the temporary directory accessible by Geoserver /geoserver_data/data (a shared volume between Geonode and Geoserver images)
The following are required only for core and …
> [Fixes #5944] B/R general fixes

- geonode/security/tests.py
- geonode/security/utils.py
- pyproject.toml
> [Issue #5835] GNIP-74 Improvements: toggle GWC cache instead of removing it

- geonode/layers/templates/upload/layer_upload_time.html
- geonode/static/geonode/js/upload/time.js
FIX #5960 
Align radio buttons
Add them unique id, fix js script to use those ids.
Those ids are required to mark column by clicking on the label (now always first column is picked) …
> [Fixes #5960] align ad add id for radiobuttons

- geonode/br/management/commands/backup.py
- geonode/br/management/commands/utils/utils.py
1. FIX FOR: datastore database is not restored due to faulty string concatenation
2. FIX FOR: Geoserver's backup should not fail silently, and should not skip failing resources
> [Fixes #5963] B/R fixes 2

- geonode/br/management/commands/backup.py
Reversion of the loop from #5974
> [Fixes #5981] B/R revert looped GS backup

- geonode/monitoring/management/commands/collect_metrics.py
- geonode/monitoring/tasks.py
- geonode/monitoring/tests/integration.py
- geonode/monitoring/utils.py
- geonode/settings.py
- geonode/tasks/tasks.py
- Fixes #5983 : [Monitoring] Collect metrics jobs pile up and cause exhaustion of memory
- Documentation commit [here](https://github.com/GeoNode/documentation/commit/610e12759a41c7b7364305a0fdf82158f609cf19)
> [Fixes #5983] [Monitoring] Collect metrics jobs pile up and cause exhaustion of memory

- requirements.txt
- Bump django-geonode-mapstore-client to 2.0.4
>  - Bump django-mapstore-adapter to 2.0.3

- geonode/br/management/commands/backup.py
- geonode/br/management/commands/restore.py
- geonode/br/management/commands/settings_docker_sample.ini
- geonode/br/management/commands/settings_sample.ini
- geonode/br/management/commands/utils/utils.py
- geonode/utils.py
- Fixes #6034 : [Backup/Restore Mgmt Commands] Implement option to exclude geoserver raster and vector data from backup and restore
> [Fixes #6034][Backup/Restore Mgmt Commands] Implement option to exclude geoserver raster and vector data from backup and restore

- geonode/layers/models.py
- geonode/layers/templates/layers/layer_detail.html
- Fixes #6068 : download filter dropdown shows wrong attributenames 
- Fixes #6069 : download filter values are not properly filled with unique values
> [Fixes #6068] download filter dropdown shows wrong attributenames / [Fixes #6069] download filter values are not properly filled with unique values

- geonode/upload/utils.py
- Fixes #6080 : Error Upload KML extension
> [Fixes #6080] Error Upload KML extension

- geonode/static/geonode/js/search/autocomplete.js
[FIX #6091]
Since search is broader than autocomplete. empty result dropdown can be a lie. here is its removal 
> [FIX #6091] remove empty results dropdown 

- geonode/groups/forms.py
- Fixes #6093 : Trying to add more than one member to a Group, results adding only the last one
> [Fixes #6093] Trying to add more than one member to a Group, results adding only the last one

- geonode/static/geonode/js/search/search.js
- geonode/templates/base.html
- geonode/templates/search/_pagination.html
[FIX #6095] 
Page will be scrolled to top on load event or when new portion of resources is fetched from the API (resource list views, pagination buttons )
> [FIX #6095] Scroll page after load/load new resources

- geonode/api/resourcebase_api.py
- geonode/base/populate_test_data.py
- geonode/catalogue/backends/generic.py
- geonode/layers/models.py
- geonode/maps/models.py
- geonode/maps/utils.py
- geonode/monitoring/models.py
- geonode/monitoring/utils.py
- geonode/monitoring/views.py
- geonode/proxy/templatetags/proxy_lib_tags.py
- geonode/proxy/tests.py
- geonode/proxy/views.py
- geonode/qgis_server/helpers.py
- geonode/services/serviceprocessors/arcgis.py
- geonode/utils.py
> [Minor] Format syntax

- geonode/layers/forms.py
- geonode/layers/utils.py
- geonode/qgis_server/views.py
- geonode/upload/files.py
- geonode/upload/tests/__init__.py
- geonode/upload/tests/integration.py
- geonode/upload/upload.py
- geonode/upload/upload_validators.py
- geonode/upload/utils.py
- geonode/utils.py
(cherry picked from commit bf01302180c7997db5ddf7b200f1966963dae681)
> [Hardening] Allowing huge zip files everywhere

- geonode/__init__.py
> Backports to 3.x

- geonode/settings.py
- scripts/docker/env/development/django.env
- scripts/docker/env/production/django.env
This new settings variable allows us to configure how a fallback image with gravatar is handled. The standard setting keeps the current behavior. In case a user does not have an uploaded profile image the default is loaded from gravatar.com
However, if one changes the new env. var to
`AVATAR_PROVIDERS='avatar.providers.PrimaryAvatarProvider','avatar.providers.DefaultAvatarProvider','avatar.providers.GravatarAvatarProvider'`
The fallback image defined in `AVATAR_DEFAULT_URL=/geonode/img/avatar.png` will be used. 
- update geonode-project
- update docs
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you …
> Fixes #6153 Configure gravatar fallback image

- requirements.txt
>  - Bump six to 1.15.0

- requirements.txt
>  - Bump django-mapstore-adapter to version 2.0.4.2

- dev_config.yml
- docker-compose-geoserver-server.yml
- docker-compose.async.yml
- docker-compose.yml
- geonode/utils.py
- scripts/spcgeonode/geoserver/Dockerfile
>  - Bump GeoServer to version 2.17.1

- geonode/br/management/commands/utils/utils.py
- geonode/layers/views.py
- geonode/upload/models.py
> Assorted warnings fixes

- geonode/services/serviceprocessors/wms.py
> [Fixes #6305] Error in wms.py module

- geonode/base/templates/base/iso_categories.html
- geonode/base/templatetags/base_tags.py
- geonode/base/tests.py
- geonode/static/geonode/css/base.css
- geonode/static/geonode/less/base.less
- geonode/templates/index.html
In home page show only ISO categories currently assigned to some dataset
> [Fixes #6332] In home page show only ISO categories currently assigned to some dataset

- dev_config.yml
- docker-compose-geoserver-server.yml
- docker-compose.async.yml
- docker-compose.yml
- geonode/security/tests.py
- scripts/docker/env/development/geoserver.env
- scripts/docker/env/production/geoserver.env
- scripts/spcgeonode/geoserver/Dockerfile
>  - Bump GeoServer to version 2.17.2

- requirements.txt
> Deps djangorestframework 3.8.2

- geonode/base/forms.py
- geonode/decorators.py
- geonode/documents/tests.py
- geonode/documents/views.py
- geonode/layers/tests.py
- geonode/layers/views.py
- geonode/maps/tests.py
- geonode/maps/views.py
Allow only admins to edit/create keywords
> [Fixes #6360] Allow only admins to edit/create keywords

- geonode/base/templates/base/menu.html
- geonode/static/geonode/css/base.css
- geonode/static/geonode/less/base.less
- geonode/templates/base.html
- geonode/templates/index.html
Fixes distorted navbar when multiple nav bar items are added by the admin
> [Fixes #6412] Nav Toolbar Issue

- geonode/tests/test_utils.py
- geonode/utils.py
Fixes #6394 
PR to amend `geonode.utils.fixup_shp_columnnames(...)` to properly support previously dysfunctional character sets that used to cause a segmentation fault or exception depending on the GDAL version being used. Also fixes some logical expressions that caused `has_ch` to always evaluate to `True`. I have also written a new test to verify an affected shapefile that uses `windows-1258` encoding within its column names is correctly modified in-place.
Note that this PR will fail under certain versions of GDAL due to the issues explained in the description of #6394. This PR targets GDAL 2.4, which the current Docker installation method uses, however the Travis CI runner is currently running version 1.11, which is expected to fail.
> Reviewing is a process done by project …
> [Fixes #6394] Rename shp columnnames with inLayer.AlterFieldDefn

- geonode/geoserver/helpers.py
It looks following is happening.
open() decodes the bytes in the file to Unicode text (default encoding)
etree() reads the starting `<?xml version="1.0" encoding="UTF-8"?>` and likes to interpret the string but can't  as it's already decoded to a Unicode string.
My fix opens the file in binary which successfully interprets the demo sld from the tickets
**Submitting the PR …
> [Fixes: #6509] Broken diacritics in Geoserver style

- geonode/upload/upload.py
> Fixes: #6509 specialchars in sld for zip files

- .travis.yml
- geonode/geoserver/signals.py
- geonode/geoserver/tests/integration.py
- geonode/geoserver/tests/test_helpers.py
- geonode/layers/models.py
- geonode/layers/tests.py
- geonode/layers/utils.py
- geonode/layers/views.py
- geonode/tests/integration.py
- geonode/upload/upload.py
- scripts/spcgeonode/docker-compose.yml
- setup.cfg
* [Fixes #6447] Layer is not replaced
* - Executing the transaction inside the atomic block
* - Make sure db constraints are met
* - Add missing return keyword
* - Fix travis tests …
> [Backport to 3.x][Fixes #6447] Layer is not replaced (#6566)

- geonode/templates/base.html
- geonode/templates/search/search_scripts.html
makes these things working again
- layer list
- upload
> [Fixes: #6181] DEBUG_STATIC=True breaks functionality

- geonode/invitations/views.py
> [Fixes #6658] Inviting a user fails

- geonode/base/models.py
- geonode/base/tests.py
- geonode/catalogue/templates/catalogue/full_metadata.xml
> [Fixes #6665] Improve WYSIWYG metadata editor to store formatted and plain texts

- requirements.txt
> [Fixes: #6687] Update lxml

- geonode/geoserver/helpers.py
> [Fixes #6717] Infinite GetMap requests on Thumbnail creation

- geonode/api/resourcebase_api.py
- geonode/base/forms.py
- geonode/client/hooksets.py
- geonode/documents/views.py
- geonode/geoserver/tasks.py
- geonode/layers/tasks.py
- geonode/layers/utils.py
- geonode/layers/views.py
- geonode/maps/views.py
- geonode/messaging/consumer.py
- geonode/monitoring/management/commands/render_metrics.py
- geonode/monitoring/management/commands/updategeoip.py
- geonode/monitoring/middleware.py
- geonode/proxy/views.py
- geonode/qgis_server/views.py
- geonode/security/models.py
- geonode/security/utils.py
- geonode/settings.py
- geonode/upload/tests/__init__.py
- geonode/upload/tests/integration.py
- geonode/upload/upload.py
- geonode/upload/views.py
- geonode/utils.py
- scripts/misc/create_full_geonode_db.py
> [Fixes #6715] Improve Upload (Importer) speed and code quality

- Dockerfile
> [Fixes #6758] Bump base Image for Django Docker

- geonode/documents/exif/utils.py
- geonode/documents/models.py
- geonode/documents/views.py
This PR will fix the EXIF contrib app to work with the current master and PostGIS backend. It will read the EXIF informations and store those alongside the metadata. It will read the GPS locations and save those as BBOX for the document. This results in a working search by extent for EXIF documents. However, if the images will be linked to other resources and layers, the computed extent of those will be used.
The following are required only for core and extension modules (they are welcomed, but …
> [Fixes #6774] EXIF data will not get read

- geonode/geoapps/api/serializers.py
Thanks to the existing amazing code base and after applying this PR the developer will be easily allowed to:
1. Inherit from GeoAppSerializer with no need to copy the whole code again
2. Override the `create` & `update` methods easily
3. Add extra checks if needed
Also, this benefits to have a centralized Class to add all common method to
For Example, 
After applying this PR to the `GeoStorySerializer` GeoStories App, the `class GeoStorySerializer` could be as follows
`@mapstore2_adapter/geoapps/geostories/api/serializers.py`
```python
class GeoStorySerializer(GeoAppSerializer):
class Meta:
model = GeoStory
name = 'geostory'
fields = GeoAppSerializer.Meta.fields + ('app_type', )
```
Instead of the [current file](https://github.com/GeoNode/django-mapstore-adapter/blob/master/mapstore2_adapt …
> [Fixes #6779] Improve GeoApps REST serializer

- geonode/security/views.py
The pinax notifications will be used and sent. I also fixed a failing import in `send_email_consumer()` even though I do not think that method is called anymore.
> [FIXES #6773] Request Download button will fail to sent notification

- geonode/templates/developer.html
Remove the link as the Open Data endpoint does not exist anymore
> [Fixes ##6772] Remove Open Data Link

- .clabot
Updated the .clabot file to allow access for Catalyst Academy 2021 students.
> Updated .clabot for Catalyst Academy students

- geonode/documents/templates/layouts/doc_panels.html
- geonode/geoapps/templates/layouts/app_panels.html
- geonode/layers/templates/layouts/panels.html
- geonode/maps/templates/layouts/map_panels.html
> [Fixes #6872] Ghost message on Metadata Wizard page

- .clabot
This reverts commit 9dac9fc4ea7ae9319b26fa3c232ce44ab28d5c29.
Removes Catalyst Academy 2021 students from the `.clabot` file.
> Revert "Updated .clabot for Catalyst Academy students (#6831)"

- geonode/settings.py
> [Fixes #6886] Swap static files finders

- .circleci/config.yml
- geonode/upload/tests/integration.py
- test_upload.sh
@afabiani this is more for testing or getting insights. If you think it's not getting us somewhere we can close
> [Fixes #6880] Circle CI upload tests fail irregulary

- geonode/catalogue/templates/geonode_metadata_full.html
- geonode/templates/500.html
- geonode/templates/base.html
Closes #6942 
PR to defer/preload certain assets to improve page loading times. While this helps the loading times significantly, there is the side effect that some assets will move position on-screen during the loading period (quantified by the cumulative layout shift in the screenshots below)
**Submitting the PR does not require you to check all items, but by the time it …
> [Issue #6942] Defer and preload assets to improve page loading times

- geonode/base/fields.py
- geonode/base/fixtures/test_thesaurus.json
- geonode/base/forms.py
- geonode/base/templatetags/thesaurus.py
- geonode/base/tests.py
- geonode/base/views.py
- geonode/catalogue/templates/catalogue/full_metadata.xml
- geonode/templates/search/_t_keywords_filter.html
Based on the last comment for Thesauri [GNIP](https://github.com/GeoNode/geonode/issues/6925#issuecomment-784192708), this PR is meant to change the behaviour of the thesauri in order to show the localized label based on the language selected by the user if available, otherwise will use the default one
**Submitting the PR does not require you to check all items, but by the …
> [Fixes #6925] Thesauri improvements

- geonode/base/models.py
- geonode/base/tests.py
- geonode/layers/api/tests.py
> [Fixes #6994] raw fields do not encode special chars correctly

- geonode/base/models.py
- geonode/base/thumb_utils.py
- geonode/geoserver/helpers.py
- geonode/geoserver/tasks.py
- geonode/layers/forms.py
- geonode/layers/utils.py
- geonode/layers/views.py
- geonode/proxy/views.py
- geonode/security/models.py
- geonode/security/utils.py
- geonode/security/views.py
- geonode/upload/upload.py
- geonode/upload/utils.py
- geonode/upload/views.py
- geonode/utils.py
> [Backport to 3.x] Assorted minor performance issues

- geonode/templates/metadata_form_js.html
With this PR i want to continue the work of adding new block tag for the issue #6995 
> [Fixes #6995] Extending Geonode Template

- dev_config.yml
- docker-compose-geoserver-server.yml
- docker-compose-test.yml
- docker-compose.yml
- scripts/spcgeonode/geoserver/Dockerfile
> Bump GeoServer to version 2.18.2

- geonode/geoserver/helpers.py
- geonode/geoserver/tasks.py
- geonode/security/tests.py
- geonode/tests/integration.py
> [Fixes #7051] GeoServer will create three styles instead of one

- .clabot
Clabot json was not valid (a comma was missing)
> clabot not working

- Dockerfile
- docker-compose-test.yml
- docker-compose.yml
- scripts/spcgeonode/docker-compose.yml
> [Fixes #7062] Bump to postgresql-client-13

- geonode/security/middleware.py
- geonode/security/tests.py
(cherry picked from commit 296021ee1404383756ab20ddb272db191250ec11)
> [Backport to 3.2.x][Fixes #7075] LOCKDOWN mode with custom login view (#7077)

- geonode/security/middleware.py
- geonode/security/tests.py
(cherry picked from commit 296021ee1404383756ab20ddb272db191250ec11)
> [Backport to 3.1.x][Fixes #7075] LOCKDOWN mode with custom login view (#7077)

- geonode/thumbs/thumbnails.py
ref.: issue #7114
Handle user uploaded thumbnails, with extensions different from the default one (`.png`)
> [Fixes #7114] Thumbnail upload issue

- geonode/thumbs/thumbnails.py
(cherry picked from commit 39d5836fd4b1d7a1198f78aaa9257edf6a36ec04)
> [Backport to 3.2.x][Fixes #7114] Thumbnail upload issue (#7115)

- geonode/thumbs/thumbnails.py
(cherry picked from commit 39d5836fd4b1d7a1198f78aaa9257edf6a36ec04)
> [Backport to 3.1.x][Fixes #7114] Thumbnail upload issue (#7115)

- geonode/static/geonode/js/search/search.js
References issue #7129
Resets list of contents when region filter is cleared
> [Fixes #7129] Clearing the region filter the list of contents is not reset

- geonode/static/geonode/js/search/search.js
Co-authored-by: Toni <toni.schoenbuchner@csgis.de>
(cherry picked from commit e40a53df60033846003903f948e232bc1e3ceadb)
> [Backport 3.1.x] fix region search function (#7131)

- geonode/base/templatetags/base_tags.py
- geonode/base/tests.py
- geonode/documents/templates/documents/document_thumb_upload.html
- geonode/documents/templates/documents/document_upload.html
- geonode/documents/templates/layouts/doc_panels.html
- geonode/geoapps/templates/layouts/app_panels.html
- geonode/geoserver/createlayer/templates/createlayer/layer_create.html
- geonode/geoserver/helpers.py
- geonode/geoserver/tests/test_server.py
- geonode/layers/templates/layers/layer_metadata_upload.html
- geonode/layers/templates/layers/layer_replace.html
- geonode/layers/templates/layouts/panels.html
- geonode/layers/templates/upload/layer_upload.html
- geonode/maps/templates/layouts/map_panels.html
- geonode/security/utils.py
- geonode/themes/tests.py
- geonode/upload/upload.py
> [Fixes #7135][Advanced Workflow] Non admin user cannot change permission

- geonode/__init__.py
- geonode/base/templatetags/base_tags.py
- geonode/base/tests.py
- geonode/documents/templates/documents/document_thumb_upload.html
- geonode/documents/templates/documents/document_upload.html
- geonode/documents/templates/layouts/doc_panels.html
- geonode/geoapps/templates/layouts/app_panels.html
- geonode/geoserver/createlayer/templates/createlayer/layer_create.html
- geonode/geoserver/helpers.py
- geonode/geoserver/tests/test_server.py
- geonode/layers/templates/layers/layer_metadata_upload.html
- geonode/layers/templates/layers/layer_replace.html
- geonode/layers/templates/layouts/panels.html
- geonode/layers/templates/upload/layer_upload.html
- geonode/maps/templates/layouts/map_panels.html
- geonode/security/utils.py
- geonode/themes/tests.py
- geonode/upload/upload.py
(cherry picked from commit 12896c0042ba18c5e77df0bf8985b7cabcc08bf1)
> [Backport to 3.2.x][Fixes #7135][Advanced Workflow] Non admin user cannot change permission

- geonode/__init__.py
- geonode/base/templatetags/base_tags.py
- geonode/base/tests.py
- geonode/documents/templates/documents/document_thumb_upload.html
- geonode/documents/templates/documents/document_upload.html
- geonode/documents/templates/layouts/doc_panels.html
- geonode/geoserver/createlayer/templates/createlayer/layer_create.html
- geonode/geoserver/helpers.py
- geonode/geoserver/tests/test_server.py
- geonode/layers/templates/layers/layer_metadata_upload.html
- geonode/layers/templates/layers/layer_replace.html
- geonode/layers/templates/layouts/panels.html
- geonode/layers/templates/upload/layer_upload.html
- geonode/maps/templates/layouts/map_panels.html
- geonode/security/utils.py
- geonode/themes/tests.py
- geonode/upload/upload.py
(cherry picked from commit 12896c0042ba18c5e77df0bf8985b7cabcc08bf1)
#	geonode/geoapps/templates/layouts/app_panels.html
#	geonode/security/utils.py
> [Backport to 3.1.x][Fixes #7135][Advanced Workflow] Non admin user cannot change permission

- geonode/br/management/commands/utils/utils.py
With this PR i want to:
- wrap table name in double-quotes to let postgres manage the table in uppercase/lowercase/camelcase without drop "missing table" error
> [Fixes #7164] restore does not delete table in uppercase/camelcase

- geonode/br/management/commands/utils/utils.py
With this PR i want to:
- wrap table name in double-quotes to let postgres manage the table in uppercase/lowercase/camelcase without drop "missing table" error
> [Backport 3.2.x ][Fixes #7164] restore does not delete table in uppercase/camelcase

- geonode/br/management/commands/restore.py
> [Backport 3.2.x][Fixes #7164] change BK_BEST_EFFORT to true

- geonode/base/tests.py
- geonode/br/management/commands/restore.py
> [Backport 3.1.x][Fixes #7164] BK_BEST_EFFORT_ always true

- geonode/catalogue/backends/pycsw_plugin.py
As per #7160:
- Move all `Layer.*` filtering to `ResourceBase.*` filtering.
No test added, waiting for github to complete existing testing.
> [Fixes #7160] Review CSW filtering in pycsw_plugin

- geonode/catalogue/backends/pycsw_plugin.py
(cherry picked from commit 72f0ef156486599cf0fe08cb86937b1d8bbe2fe5)
> [Backport to 3.2.x][Fixes #7160] Review CSW filtering in pycsw_plugin (#7162)

- geonode/catalogue/backends/pycsw_plugin.py
(cherry picked from commit 72f0ef156486599cf0fe08cb86937b1d8bbe2fe5)
#	geonode/catalogue/backends/pycsw_plugin.py
> [Backport to 3.1.x][Fixes #7160] Review CSW filtering in pycsw_plugin (#7162)

- geonode/layers/models.py
- geonode/services/admin.py
- geonode/services/serviceprocessors/arcgis.py
- geonode/services/tasks.py
- geonode/services/tests.py
> [Backport to 3.2.x][Fixes #7183] Remote services do not associate correctly the GeoNode Layer to HarvestJob

- geonode/layers/models.py
- geonode/services/admin.py
- geonode/services/serviceprocessors/arcgis.py
- geonode/services/tasks.py
- geonode/services/tests.py
> [Backport to 3.1.x][Fixes #7183] Remote services do not associate correctly the GeoNode Layer to HarvestJob

- geonode/geoserver/views.py
> [Fixes #7197] Missing parenthesis in feature_edit_check

- geonode/security/models.py
(cherry picked from commit 8454e6321d9f002bbf8f686afc69f26cccc2d71b)
> [Backport to 3.2.x] add resource base permissions (#7202)

- geonode/security/models.py
(cherry picked from commit 8454e6321d9f002bbf8f686afc69f26cccc2d71b)
> [Backport to 3.1.x] add resource base permissions (#7202)

- geonode/base/populate_test_data.py
- geonode/layers/templates/layers/layer_append.html
- geonode/layers/templates/layers/layer_detail.html
- geonode/layers/tests.py
- geonode/layers/urls.py
- geonode/layers/utils.py
- geonode/layers/views.py
* [Fixes #7194] Add new append_layer html
* [Fixes #7194] Test helper utility for create single layer
* [Fixes #7194] Add append data to existing edit layer html
* [Fixes #7194] Flake8 formatting
* [Fixes #7194] New layer_append url map
* [Fixes #7194]Validation helper function for replace and appen layer
* [Fixes #7194] Add view for layer_append feature
* [Fixes #7194] Test coverage for new validation function
(cherry picked from commit b404e0d03ff6e4b372d2adc4fbf9f72b98e4a75c)
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if …
> [Backport to 3.2.x][Fixes #7194] Append data to an existing layer  (#7195)

- geonode/documents/views.py
- geonode/maps/views.py
> [Fixes #7237 ] Remove slack contrib support

- geonode/documents/forms.py
- geonode/documents/templates/documents/document_metadata_advanced.html
- geonode/documents/views.py
- geonode/layers/templates/layers/layer_metadata_advanced.html
- geonode/layers/views.py
- geonode/maps/forms.py
- geonode/maps/templates/maps/map_metadata_advanced.html
- geonode/maps/views.py
- geonode/templates/metadata_base.html
- geonode/templates/metadata_form_js.html
* [Fixes #7224] Harmonize/improve metadata editing pages
* [Fixes #7224] Harmonize/improve metadata editing pages
* [Fixes #7224] Harmonize/improve metadata editing pages, typos removed
* [Fixes #7224] Question mark missing
(cherry picked from commit 6a742ddc7429c0e2b6f7d460561cbb43e29a511d)
The following are required only for core and extension modules …
> [Backport to 3.2.x][Fixes #7224] Harmonize/improve metadata editing pages (#7240)

- geonode/context_processors.py
- geonode/documents/templates/documents/document_metadata_advanced.html
- geonode/documents/templates/layouts/doc_panels.html
- geonode/layers/templates/layers/layer_metadata_advanced.html
- geonode/layers/templates/layouts/panels.html
- geonode/maps/templates/layouts/map_panels.html
- geonode/maps/templates/maps/map_metadata_advanced.html
- geonode/templates/metadata_form_js.html
* [Resolves #6995] Increase UI block coverage in geonode
* [Resolves #6995] ADVANCED_EDIT_EXCLUDE_FIELD available also in maps and documents
(cherry picked from commit 76f62f23f4d849f0e2bf7c0fa207b4965e8da02b)
**Submitting the PR does …
> [Backport to 3.2.x][Resolves #6995] Increase UI block coverage in geonode (#7243)

- geonode/geoserver/views.py
- geonode/layers/views.py
- geonode/maps/models.py
- geonode/maps/templates/maps/map_detail.html
- geonode/maps/tests.py
- geonode/maps/views.py
- geonode/static/geonode/css/base.css
- geonode/static/geonode/less/base.less
* add ui view
* add legend as property
(cherry picked from commit c4ff3b7e4850a35fd2929e78d4e5964d3744cd7a)
**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied …
> [Backport to 3.2.x][Fixes #7254] Map Legend (#7255)

- geonode/api/api.py
- geonode/api/tests.py
- geonode/people/templates/people/profile_detail.html
- geonode/people/tests.py
- geonode/security/tests.py
- geonode/security/utils.py
- geonode/templates/search/_general_filters.html
Protects user's information by returning limited attributes on their profile to anonymous and non-admin users.
> [Fixes  #7269] Reduce information returned to users to only what is strictly required and accessible

- geonode/api/api.py
- geonode/base/fixtures/test_xml.xml
- geonode/geoserver/tasks.py
- geonode/layers/metadata.py
- geonode/layers/tests.py
- geonode/layers/utils.py
- geonode/upload/models.py
- geonode/upload/tests/test_utils.py
- geonode/upload/upload.py
- geonode/upload/utils.py
- geonode/urls.py
* test
* rollback
* [Fixes #7279] Keyword Handler for metadata upload, remove keyword from geoserver step and add tests
* [Fixes #7279] Add test for set_metadata_function cd /opt/geonode ; /usr/bin/env /home/mattia/.virtualenvs/local-geonode/bin/python /home/mattia/.vscode-server/extensions/ms-python.python-2021.3.680753044/pythonFiles/lib/python/debugpy/launcher 41039 -- /opt/geonode/manage.py test geonode.layers.tests.TestSetMetadata -v 2 --settings=geonode.local_settings --keepdb
* [Fixes #7279] Test coverage for set_metadata with ISO xml dummy
* [Fixes #7279] Add keyword handler in upload
* [Fixes #7279] Flake8 indentation
* [Fixes #7279] Fix KeywordHandler descripiton
* [Fixes #7279] Add tests for convert_keyword
* - Pep8 formatting
- Make sure set_metadata returns a non-null …
> [Backport to 3.2.x][Fixes #7279] Keyword parsing improvements (#7286)

- geonode/geoserver/tasks.py
- geonode/static/geonode/js/upload/LayerInfo.js
- geonode/upload/upload.py
- geonode/upload/utils.py
- geonode/upload/views.py
* test
* rollback
* [Fixes #7288] Layer information handling moved to final step instead of geoserver_finalize_upload
* [Fixes #7288] rollback metadata file
* [Fixes #7288] flake8 indentation
* [Fixes #7288] Remove xml reading
* [Fixes #7288] Fix flake8 warnings
* - Double check "gs_resource" is not None
* - Avoid unneeded attribute value assignments
* - Updaye GeoServer resource anyaway
* - Add more checks on Keywors "dict" and upload error messages
Co-authored-by: afabiani <alessio.fabiani@gmail.com>
(cherry picked from commit 9730434bdb803c1081aa60074e0d1625622000eb)
> Reviewing is a process done by project maintainers, mostly on a volunteer …
> [Backport to 3.2.x][Fixes #7288] Layer saving cleanup (#7293)

- geonode/templates/_permissions_form.html
(cherry picked from commit fa53409dcdb890e452555427c4eb2dd2f9e8cc4f)
> [Backport to 3.2.x][Fixes #7303] Missing user search bar in geolimits

- geonode/templates/_permissions_form.html
(cherry picked from commit fa53409dcdb890e452555427c4eb2dd2f9e8cc4f)
> [Backport to 3.1.x][Fixes #7303] Missing user search bar in geolimits

- geonode/layers/views.py
- geonode/maps/views.py
References: #7311
Uses an empty string on setting default style in capability config for layers.
> [Fixes  #7311] Missing cache in layers loaded on geonode

- geonode/layers/views.py
- geonode/maps/views.py
(cherry picked from commit 619c9cd9ac074ea8ddd254bb9afa48e2b1237955)
> [Backport to 3.2.x][Fixes #7311] Missing cache in layers loaded on geonode

- geonode/layers/views.py
- geonode/maps/views.py
(cherry picked from commit 619c9cd9ac074ea8ddd254bb9afa48e2b1237955)
> [Backport to 3.1.x][Fixes #7311] Missing cache in layers loaded on geonode
