.travis.yml
pavement.py
setup.py

This PR improves the developer experience by exposing a single pavement task that runs all of the tests.  Now developers (and travis) can run all of the tests with `paver run_tests`.

Use a single paver task to execute all of the tests.

---

geonode/geoserver/helpers.py

When saving internal style objects, GeoNode uses the `sld_name` property from **gsconfig** which inspects the SLD and returns text from the `<Name>` element within the `<UserStyle>` element (https://github.com/boundlessgeo/gsconfig/blob/36a6190aa96181d585811ad483aa147e5efd6903/src/geoserver/style.py#L53).  The problem with this is that the name element could be different the actual name of the style in Geoserver which causes problems when GeoNode use a style's name to lookup the style in Geoserver in other places in the code.

Use an SLD's name instead of text from a name element when saving styles.

---

setup.py

@ingenieroariel  - This replaces `Django >=1.6.1, <=1.6.5` with `Django==1.6.10`.  Both @simod and I seem to remember that there was a reason why we had to version it that way but not the specific reason why.  Do you remember why?

Bump Django to 1.6.10.

---

docs/reference/developers/settings.txt
geonode/context_processors.py
geonode/documents/views.py
geonode/layers/views.py
geonode/maps/views.py
geonode/settings.py
geonode/templates/social_links.html
geonode/utils.py

The social links are no longer hard coded, but added as a list to the settings.py file.  Admins can now easily remove or add their social networks of choice.  This will be useful for managing customization of multiple deployments.
Minor Changes
- prepended a mailto email link.
- context_processors.py defaults SOCIAL_BUTTONS to False if var is not found in settings.py.  Most settings.py files come with SOCIAL_BUTTONS included.
- included https check when sharing url
More importantly, this will open up a simple way to leverage "Web Intents" / APIs to integrate GeoNode services into other systems, such as discovery platforms, url shorteners, etc.  Are there other web intents that should be added to the default settings.py file?

Social Links Enhancements

---

geonode/groups/templates/groups/activity.html
geonode/groups/views.py
geonode/social/templates/social/activity_list.html
geonode/social/views.py

**Activity Filters (All, Layers, Maps, Comments)**
This PR adds tabs to the global activity feed and group activity feeds.  This enhancement allows users to filter activity for only relevant information.  A common use case is an open data geonode.  If users are looking for new spatial data, they should be able to filter the feed to just see new layers (not see comments, new maps, etc.).

Activity Filters (All, Layers, Maps, Comments)

---

geonode/documents/views.py
geonode/layers/views.py
geonode/maps/views.py

Do not include admins in view counts.  Related downstream issue: https://github.com/ebola-geonode/ebola_geonode/issues/18

Do not include admins in view counts

---

geonode/utils.py

Avoided Internal Server Error on layer_detail, map_detail and document_detail  if there are ASCII characters in resource titles.

Fixed issue with non ASCII characters

---

geonode/maps/models.py

Currently the README contained in a map download has the author hardcoded to "The GeoNode Team". With this fix the "point of contact" field is used instead. Also the license, if present, is added.

Fix the README contained in the zip file created by a map download

---

geonode/views.py

This PR permit to search user with insensitive case.
(test on Manage Group Members page for a group)
At the same time I exclude AnonymousUser on the list of result.

research user-group insensitive and exclude AnonymousUser

---

docs/reference/developers/settings.txt
geonode/settings.py
geonode/utils.py

Building on https://github.com/GeoNode/geonode/pull/1918, this PR adds initial support for using "web intents" to register geospatial services with CKAN.  This PR adds support for the optional `abstract` querystring parameter to SOCIAL_ORIGINS.  Commented out by default, this PR adds a block to the settings.py file for managing CKAN "social links", to enable publishing.  To enable, remove the comment from the following line in the settings.py: `SOCIAL_ORIGINS.extend(CKAN_ORIGINS)`.  The commented out example in the settings.py file points to Humanitarian Data Exchange (https://data.hdx.rwlabs.org/).
Additional querystring parameters would need to be supported on the CKAN side to build out the workflow.

Web Intents / CKAN / Initial Support

---

pavement.py

Adds a --geoserver option to the setup_geoserver paver function.  You can pass a custom url, including `file:///.../.../geoserver.war```.  For instance:
```
paver setup --geoserver file:///home/vagrant/build/geoserver/geoserver.war
```
This will help when developing on wifi networks with low bandwidth since you wont' have to download the binary every time.

Paver Support for Local Geoserver Binary

---

geonode/documents/templates/documents/document_detail.html
geonode/documents/views.py

Only show metadata links for documents that are listed in settings.py.  Original issue identified in https://github.com/GeoNode/geonode/pull/1635.  Implements work done for layers in https://github.com/GeoNode/geonode/commit/8917f3afea685560601d6ec15babfe8d8f372ec2 for documents.

Fix for document metadata links

---

pavement.py

Adds a --jetty option to the setup_geoserver paver function.  You can pass a custom url, including `file:///.../.../jetty-runner-8.1.8.v20121106.jar```.  For instance:
```
paver setup --geoserver file:///home/vagrant/build/geoserver/jetty-runner-8.1.8.v20121106.jar
```
This will help when developing on wifi networks with low bandwidth since you wont' have to download the binary every time.

Paver Support for Local Jetty Runner

---

geonode/settings.py
geonode/utils.py

Following on #1918 and #1930, this PR adds support for building dates and caveats into the CKAN intent url.  Caveats is a list, in markdown format, of: maintenance_frequency, license, and data_quality_statement.
CKAN links are still disabled by default in settings.py

Web Intents / CKAN / Date and Caveats (Social Links 3)

---

docs/tutorials/admin/install/quick_install.txt
geonode/settings.py
pavement.py

This checks if the JAVA_HOME variable is set before complaining to add the --java_path flag to paver start. 
Also, running paver start the second time without doing a paver stop first would throw a "permission denied" to downloaded/null.txt.  Permission was denied because it was being used by the currently running Geoserver.  A better message is thrown now.
Both outlined in #1970

Paver and settings improvements for Windows users

---

geonode/local_settings.py.sample

Because probably you'll need to change ```SITEURL``` but then you'll need to set ```CATALOGUE``` after it.
See https://github.com/GeoNode/geonode/issues/2016

Add SITEURL and CATALOGUE to local_settings.py.sample

---

geonode/templates/index.html

1. fixing links in homepage :
* Create maps was pointing on explore maps
* Share data (when unregistred) was pointing on users list
* Explore layers was replaced by add layers when registred
2. Logic was reviewed for layers and maps : links on top always pointing to lists and button below depend on authentication and leading to creating or viewing the objects.
3. The users parts has become independent from registred or not and will always point to users page.

changing links in homepage for registred and unregistred users

---

geonode/layers/templates/layers/layer_style_manage.html

In ref to #2049 
This PR consist to have a required value on the select input.
Using HTML5 propertie 
When you click on update button, a message pop up on the screen. (this message use the default language on your browser)

add required value for style management

---

geonode/api/api.py
geonode/api/resourcebase_api.py
geonode/api/urls.py
geonode/layers/search_indexes.py
geonode/static/geonode/js/search/search.js
geonode/templates/search/_region_filter.html
geonode/templates/search/_search_content.html
geonode/templates/search/search_scripts.html

For issue #1826, this PR creates a region filter to be displayed right above the extent filter.  The filter is collapsed by default.  The filter uses an autocomplete field against the full list of regions.
@simod, any suggestions/issues?
**Need to Fix**
**Known Issues**
**Future Enhancements**

HOLD: Region Filter

---

geonode/layers/templates/layers/layer_detail.html
geonode/layers/views.py
geonode/settings.py

In layer details page displaying the attributes label and description in place of WPS indicators when OGC WPS_ENABLED is set to False.
By default, WPS_ENABLED is now set to False. Refs #1412

Using label and description in layer attributes when WPS_ENABLED is set to False

---

geonode/templates/base.html

On the same way than "extra_tab" block into the nav bar.
Can we adding a extra-block into user menu to permit more custimation of geonode project?

adding extra_user_menu into user menu

---

geonode/static/geonode/js/search/search.js

Load the categories, regions and keywords from API only if the relative filter is available in page.
It can happen, in a customization, that I want to have just the keywords, or just the categories etc and without this PR is not be possible.

Separate categories, regions and keywords filters

---

geonode/documents/templates/documents/document_detail.html

A little improvement for visualization of the document preview.
Verified on smartphone and web browser.
The main problem was that the preview was taking too much space.
50% look right for me.

improve visual of document_detail page

---

geonode/api/api.py
geonode/api/authorization.py
geonode/api/resourcebase_api.py
geonode/base/models.py
geonode/base/templatetags/base_tags.py
geonode/geoserver/helpers.py
geonode/geoserver/signals.py
geonode/geoserver/tests.py
geonode/geoserver/views.py
geonode/groups/tests.py
geonode/layers/models.py
geonode/layers/utils.py
geonode/security/models.py
geonode/security/tests.py
geonode/social/signals.py
geonode/templates/_permissions_form_js.html
geonode/tests/integration.py

This PR solves the major issues described in #2130 and #2122.
The guardian permissions are checked faster avoiding complex joins
The categories, regions and keyword counts are done in the post-process in bulk and not per object anymore
The layer_upload uses gsconfig so to not query geoserver for all the layers available
The layer_acls check is improved by ~75%
A proper test to load lot of data has to be done in a realistic way. Loading many times the same layer will hit the db to find an available name so there is still a slight slow down in layer upload like it becomes 1s slower every 300 layer loaded.

Improve geonode performances

---

geonode/maps/templates/maps/map_geoexplorer.js
geonode/static/geonode/js/extjs/GeoNode-GeoExplorer.js
geonode/static/geonode/js/extjs/Geonode-CatalogueApiSearch.js

Proposition to re-enable the layer searcher in the add layer tool of the map composer (issue #2022 ).
This code use the geonode api (/api/layers) and a copy of the GeonodeCatalogSource adapted to match the geonode api

Re-enable layer searcher in the add layer tool 

---

geonode/security/models.py

This should prevent KeyError exceptions on layer info pages for any pre-existing layers that may have additional user permissions ('add_layer', 'delete_layer', etc) not in the list.
https://github.com/GeoNode/geonode/issues/2142

Filter out any user permissions that are not in the PERMISSIONS_TO_FETCH list

---

geonode/api/resourcebase_api.py
geonode/documents/search_indexes.py
geonode/groups/search_indexes.py
geonode/layers/search_indexes.py
geonode/maps/search_indexes.py
geonode/people/search_indexes.py

Currently, the results returned from the search API when HAYSTACK_SEARCH = True are very different from the standard API results: some item fields are missing and others have different names.  This patch will make the result format more similar (though not identical).

Make haystack search results more similar to standard API search results

---

geonode/static/geonode/js/upload/FileTypes.js
geonode/upload/files.py
geonode/upload/views.py

This PR provides GeoJSON support when using the importer backend.  
**Notes**: 
* GeoJSON uploads will not work for users who use the rest uploader backend.
* Relies on 2.6+ fix https://github.com/geoserver/geoserver/commit/a7efe793d3b1025eceb41c899f381a5b16df5b9b.

Support GeoJSON uploads through the importer backend.

---

geonode/catalogue/backends/generic.py

When you set GeoNetwork as the CSW backend and Spanish language, it crashes with error:
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xf3 in position ##: ordinal not in range(128)`
I found that the problem were the accents included in the metadata content.

fix encoding problem when using Spanish lang (accents)

---

geonode/api/resourcebase_api.py

From haystack documentation: "If you want to match a phrase, you should use either the __exact filter type or the Exact input type"

Fix Haystack search issue with regions containing spaces.

---

geonode/base/templates/base/resourcebase_info_panel.html

This fixes the shift in category and owner values when keywords are empty (Resource details).

Fixed checking for keywords

---

geonode/base/templates/base/resourcebase_info_panel.html
geonode/context_processors.py
geonode/settings.py

Adds `SRID_DETAIL` flag for specifying if you want to show the SRID on a layer/map detail page above/below the fold.  Current default of not showing is maintained.

Added SRID Flag

---

geonode/base/models.py
geonode/documents/enumerations.py
geonode/documents/models.py
geonode/settings.py

Fixes #2175.  For CSW, adds link for documents to point to the download url.
Generates ISO XML like:
```
<gmd:onLine>
<gmd:CI_OnlineResource>
<gmd:linkage>
<gmd:URL>http://localhost:8000/documents/1/download</gmd:URL>
</gmd:linkage>
<gmd:protocol>
<gco:CharacterString>WWW:DOWNLOAD-1.0-http--download</gco:CharacterString>
</gmd:protocol>
<gmd:name>
<gco:CharacterString>.jpg</gco:CharacterString>
</gmd:name>
<gmd:description>
<gco:CharacterString>Test.jpg (Hosted Document Format)</gco:CharacterString>
</gmd:description>
</gmd:CI_OnlineResource>
</gmd:onLine>
```

Fixes #2175

---

geonode/layers/management/commands/importlayers.py
geonode/layers/utils.py

This PR adds a `regions` option to the importlayers manage.py command.  Could be very useful for importing a lot of foundation data for an individual country (for example OSM data).  Additionally, it adds support for tar files (.tar and .tar.gz) to the importlayers command (this does not add support to the GUI).
In the future, a "license" option for importlayers would be useful too.  However, we should deconflict our license list with CKAN's and other sources fist.
**Other Minor changes**
- Categories will match case insensitive on identifier and gn_description now.
- Keywords get trimmed

Import Layers / Regions and Tarfile Support

---

geonode/base/templates/base/resourcebase_info_panel.html

This PR implements basic schema.org functionality for resourcebase objects for better search engine optimization.
Schema.org microdata is used by the major search engines to index pages.  You can validate schema.org microdata with https://developers.google.com/structured-data/testing-tool/.
See: http://schema.org/docs/gs.html.

Initial Schema.org Implementation

---

geonode/contrib/favorite/models.py
geonode/contrib/favorite/readme.txt
geonode/contrib/favorite/templates/favorite/_favorite.html
geonode/contrib/favorite/templates/favorite/_favorite_js.html
geonode/contrib/favorite/templates/favorite/favorite_list.html
geonode/contrib/favorite/tests.py
geonode/contrib/favorite/urls.py
geonode/contrib/favorite/utils.py
geonode/contrib/favorite/views.py

Uncomment 'geonode.contrib.favorite' entry in settings.py to enable.
Once enabled, UI allows authenticated user to favorite Document, Layer and Map.

port existing MapStory Favorites feature to GeoNode as optional module.

---

docs/reference/developers/settings.txt
geonode/context_processors.py
geonode/contrib/exif/templates/exif/_exif_document_detail.html
geonode/contrib/exif/utils.py
geonode/documents/templates/documents/document_detail.html
geonode/documents/views.py
geonode/settings.py
geonode/templates/_actions.html

Duplicate of PR #2205 but squashed commits.
This PR adds an Exif contrib app.  This app is disabled by default.  If enabled by the `EXIF_ENABLED` settings flag, this app parses Exif tags from JPEGs uploaded as documents and automatically generates metadata, including date, keywords, and a brief abstract.  It uses `from PIL import Image, ExifTags`, so doesn't require any changes to dependencies.

EXIF Support

---

geonode/layers/models.py

uploadsession can be empty under certain circomstancies, for example when there is a layer cascade delete when removing an user

Fix for #2222

---

docs/reference/developers/settings.txt
geonode/contrib/slack/enumerations.py
geonode/contrib/slack/utils.py
geonode/documents/views.py
geonode/layers/views.py
geonode/maps/views.py
geonode/settings.py

References #2214.  This PR add initial support for slack integration.  The contrib app uses the JSON templates in `contrib/slack/enumerations.py` to build messages when a resourcebase object event happens, such as a metadata edit or new document.  It then POSTs the JSON payload to each url found in `SLACK_WEBHOOK_URLS`.
To enable, set `SLACK_ENABLED` to `True` and add the correct webhook endpoint to `SLACK_WEBHOOK_URLS`.
This is just initial support.  Additional features on the wishlist would be: using celery tasks, better event coverage, message routing to different channels on context, etc.

Initial Slack integration via contrib app

---

docs/reference/developers/settings.txt
geonode/context_processors.py
geonode/contrib/nlp/utils.py
geonode/documents/views.py
geonode/settings.py

This PR add a `nlp` contrib app.  This app is disabled by default.  If enabled by the `NLP_ENABLED` settings flag, the app will use [MITIE](https://github.com/mit-nlp/MITIE) and natural language processing (NLP) techniques to infer additional metadata from the raw contents of new text documents.  This contrib app will help fill key metadata gaps.
Specifically, the app will identify locations mentioned within the document and crosscheck them against regions (https://github.com/GeoNode/geonode/blob/master/geonode/base/models.py#L117) to autofill the regions metadata field.  Keywords are generated for identified organizations but only if they match "existing" keywords.
In the future this app can be enhanced in a few ways.  Additional structured metadata could be inferred for layers by …

Intitial NLP Support

---

geonode/contrib/exif/templates/exif/_exif_document_detail.html
geonode/documents/templates/documents/document_detail.html
geonode/settings.py

Fix to [exif contrib app](https://github.com/GeoNode/geonode/tree/master/geonode/contrib/exif) so that it passes tests when not included in `settings.INSTALLED_APPS`.  Switched to using `with` for including contrib templates in core templates.
Hold for Travis-CI test.

Fix to Exif Contrib App

---

geonode/contrib/nlp/utils.py
geonode/layers/utils.py

Continuation of #2230 to extend NLP to shapefile metadata.  When a shapefile is uploaded, the keywords (and regions) from the metadata xml (if it is included) are extended with keywords and region inferred by the [nlp contrib app](https://github.com/GeoNode/geonode/tree/master/geonode/contrib/nlp).  The NLP contrib app parses the title, abstract, and purpose looking for regions and keywords.
Unfortunately the nlp contrib app still misses many regions.  Until a region refractor (#2232) that incorporates a "geographic thesaurus" with multiple names we'll have a hard time matching the text "Syria" in the abstract to "Syrian Arab Republic", etc.

Added NLP hook for layer upload

---

geonode/catalogue/templates/catalogue/opensearch_description.xml
geonode/catalogue/urls.py
geonode/catalogue/views.py
geonode/templates/base.html
geonode/tests/smoke.py

cc @pjdufour 
This PR provides [OpenSearch](http://www.opensearch.org/Home) support to GeoNode in the following areas:
- all webpages have an [autodiscovery](http://www.opensearch.org/Specifications/OpenSearch/1.1#Autodiscovery_in_HTML.2FXHTML) link in `<head>`.
- the discovery document has a link to the basic HTML search as well as a pycsw powered Atom output search.  The reason for two different endpoints in the document is because pycsw does not provide HTML output, which is an OpenSearch autodiscovery requirement for web browser based search addons

add OpenSearch autodiscovery support

---

geonode/layers/metadata.py
geonode/layers/utils.py
geonode/upload/upload.py

This PR references #2237.  On layer upload, regions are extracted from attached ISO XML.  If GeoNode can't resolve the place keyword to a Region object, then it adds the region name as a keyword/tag.
@tomkralidis

Extract regions from ISO metadata

---

docs/tutorials/admin/install/custom_install.txt

The datastore name was referred as "geonode_data" or "geonode-imports". Use only "geonode_data" for coherency.

[doc] Only one datastore name in custom_install

---

geonode/static/geonode/js/extjs/Geonode-CatalogueApiSearch.js

this patch performs a more useful search on "title" field. The issue does not occur in developing mode due to a counter-intuitive behavior of the django SQLite backend [1].
[1] https://docs.djangoproject.com/en/1.8/ref/databases/#sqlite-string-matching

Case insensitive search on GeoExplorer Find Layers

---

geonode/layers/templates/upload/layer_upload.html
geonode/layers/views.py
geonode/static/geonode/js/upload/cookie.js
geonode/static/geonode/js/upload/upload.js

I'm not sure how/where upload.js gets included, but have here added cookie.js alongside upload.js.

Require user to select category before uploading

---

geonode/base/models.py
geonode/catalogue/models.py
geonode/layers/forms.py
geonode/layers/management/commands/importlayers.py
geonode/layers/metadata.py
geonode/layers/templates/layers/layer_metadata.html
geonode/layers/templates/upload/layer_upload.html
geonode/layers/utils.py
geonode/layers/views.py
geonode/static/geonode/js/upload/LayerInfo.js
geonode/templates/metadata_form_js.html
geonode/upload/forms.py

Implements #2250 
- layer upload: when a metadata XML file is provided, present checkbox to enable preservation of metadata
- layer metadata editing: when metadata is to be preserved, switch the UI form to readonly and hide all submit buttons.  In addition, `POST` requests will in the same situation (i.e. bypassing the UI) will throw 400 with a JSON exception
- `importlayers` adds a `-m` /  `--metadata_uploaded_preserve` boolean flag for backend workflows
This PR introduces a new field `metadata_uploaded_preserve` (boolean, `default=False`) in `geonode.base.models.ResourceBase`.  Migration is required (but not provided here).

(Hold for 2.5.x) add support for preserving XML metadata with upload (#2250)

---

geonode/layers/views.py
geonode/maps/models.py
geonode/maps/views.py
geonode/settings.py
geonode/tests/integration.py
geonode/utils.py

Added DEFAULT_MAP_CRS as a variable in settings.py and modified hard coded value for EPSG:900913.
Note: If this is set to EPSG:4326 the basemap must be EPSG:4326
Add the following to local_settings.py to test with EPSG:4326 basemap
DEFAULT_MAP_CRS = "EPSG:4326"
MAP_BASELAYERS = [{
"source": {"ptype": "gxp_olsource"},
"type": "OpenLayers.Layer",
"args": ["No background"],
"visibility": False,
"fixed": True,
"group":"background"
}, {
"source": {"ptype": "gxp_olsource"},
"type": "OpenLayers.Layer.WMS",
"args": ["World map", "http://vmap0.tiles.osgeo.org/wms/vmap0", {"layers": 'basic'}],
"visibility": True,
"fixed": True,
"group": "background"
}

added projection option for EPSG:4326 - settings.DEFAULT_MAP_PROJECTION

---

geonode/geoserver/signals.py
geonode/layers/models.py

Currently if you try to delete a layer in GeoNode but its missing in GeoServer, GeoNode will error out and prevent the deletion.  This PR helps GeoNode avoid those errors, so it'll delete the layers even if GeoNode and GeoServer fall our of sync for some reason, which can easily happen when adding some layers automatically via scripting.

More resilient layer delete

---

docs/reference/developers/settings.txt
geonode/api/api.py
geonode/settings.py

Includes a API_INCLUDE_REGIONS_COUNT setting to enable region facets count. It also add region code to the api filtering fields

API_INCLUDE_REGIONS_COUNT setting to enable region facets

---

geonode/base/enumerations.py

German was missing as possible language for metadata information. As mentioned by 
Jeffrey Johnson <ortelius@gmail.com>
I have added it to the list and created this pull request.

added german as language

---

geonode/contrib/slack/utils.py
geonode/layers/utils.py

Slack enhancement, related to #2229.
GeoNode will now send a notification via slack when a new layer has been uploaded via importlayers or the user interface.

Message posted to Slack after layer upload

---

geonode/base/forms.py
geonode/templates/metadata_form_js.html

DateTimeFields for the metadata were not accepting datetime instances in the PM range, messing with the listing of layers when sorted by latest. This PR provides a fix for this issue.

DateTimeFields not accepting PM datetimes

---

geonode/geoserver/ows.py
geonode/geoserver/signals.py
geonode/settings.py
geonode/tests/integration.py

WCS are currently broken in GeoNode and in addition on raster load we do four different GetCapabilities requests that are not used anywhere. This PR remove the usage of OWSLib to generate the WCS links, so also the GetCaps are avoided,  width and height are not necessary anymore thanks to the use of the WCS version 2.0.1.
The Gtopo30 is currently broken in GeoServer, there's an open bug already.

use WCS version 2.0.1, no need to do getCapabilities

---

geonode/layers/metadata.py

Changes proposed on #2388, allowing the upload of metadata with keywords of types other than 'place' or 'theme', in conformity with the ISO 19115 [codelist](http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_KeywordTypeCode).

Keywords not restricted by type

---

geonode/templates/base.html

Changed to Django template tag. It was just hard string. Now You can change help URL in urls.py, like I needed to.

Modal user menu Help link fix.

---

geonode/maps/views.py

To resolve issue https://github.com/GeoNode/geonode/issues/2432.
_(Issue: If a map contains a layer with a bounding box, the map's center value is forced to Web Mercator, regardless of the DEFAULT_MAP_CRS value in settings.py.)_
Rewritten so that the map's center point is returned in coordinates if DEFAULT_MAP_CRS is EPSG:4326; otherwise, it defaults to Web Mercator.

Improve WGS84 support

---

geonode/documents/templates/documents/document_detail.html
geonode/documents/templates/documents/document_metadata_detail.html
geonode/documents/urls.py
geonode/documents/views.py
geonode/layers/templates/layers/layer_detail.html
geonode/layers/templates/layers/layer_metadata_detail.html
geonode/layers/urls.py
geonode/layers/views.py
geonode/maps/templates/maps/map_detail.html
geonode/maps/templates/maps/map_metadata_detail.html
geonode/maps/urls.py
geonode/maps/views.py
geonode/templates/metadata_detail.html

I would like to contribute to the project by providing a solution that tested here in my organization.
We concluded that for the processing and visualization of metadata we should get rid of the dependence of use of Geonetwork. For this thought to implement a specific page for metadata visualization. The idea was to provide more this feature within the GeoNode so that users could enjoy a complete interface to interact with the metadata (editing and reading).
The implementation covers the inclusion of a specific button for access to a page that displays metadata of a layer, or map, or document.
While the display is functioning in most cases, the metadata display page still has some bugs related to the layout, which may appear depending on the registered data, but I think this kind of …

Metadata read button

---

geonode/base/forms.py
geonode/geoserver/helpers.py
geonode/layers/models.py
geonode/layers/templates/layers/layer_detail.html
geonode/settings.py
geonode/templates/base.html
geonode/templates/search/_pagination.html
geonode/templates/search/_search_content.html

- Adds `pt-br` (Portuguese Brazil) to the language list
- Mark strings for translation in code and templates

Fix some translation issues

---

geonode/documents/models.py

Set max_length=255 for doc_file and doc_url in document model as per #2285

Set max_length=255 for doc_file and doc_url in document model

---

dev_config.yml
pavement.py
setup.py

Added pyyaml to dependencies and moved urls from inside the pavement.py python code to a `dev_config.yml` file.  This should improve maintainability and simplify the configuration of development workflow for GeoNode in disconnected or slow internet environments (cafe, train, code sprint, etc.).

moved urls from inside pavement code into yaml file

---

geonode/local_settings.py.sample

As it is currently written it is too easy to confuse with the 'NAME' of the postgis DB.

Clarify origin of datastore identifier.

---

geonode/maps/views.py

*Related: https://github.com/GeoNode/geonode/issues/2430*
Django 1.7+ dropped simplejson in favor of vanilla json -- this is mostly fine, except in some edge cases. One such case is `decimal.Decimal` types: standard library json doesn't handle serializing these by default.
DjangoJSONEncoder covers this, and using it where needed fixes the problem. The encoder+decimal handling [exists in Django 1.6](https://github.com/django/django/blob/stable/1.6.x/django/core/serializers/json.py#L101-102) so users on an old version should still be fine.

Use DjangoJSONEncoder when we need to handle Decimal types

---

geonode/base/migrations/0002_topiccategory_fa_class.py

On some platforms, a relative reference to a file in `geonode/base/fixtures` throws an IOError:
```
class Migration(migrations.Migration):
File "/vagrant/.venv/src/geonode/geonode/base/migrations/0002_topiccategory_fa_class.py", line 45, in Migration
with open('geonode/base/fixtures/initial_data.json') as data_file:
IOError
[Errno 2] No such file or directory: u'geonode/base/fixtures/initial_data.json'
```
Using the absolute path fixes this.

use absolute path to data file to avoid IOError

---

geonode/services/migrations/0001_initial.py
geonode/services/models.py

Ref: https://github.com/GeoNode/geonode/issues/2501
Django recommends a `OneToOneField` over `ForeignKey(unique=True)`; in Django 1.8 this generates a warning at runtime.
In practice, the behavior should be equivalent with this change: the only difference would be how relationship reversal is handled, but I did not find any existing references to `WebServiceHarvestLayersJob` from the `Service` side of the relationship, so this shouldn't affect GeoNode's current behavior.
See also: https://docs.djangoproject.com/en/1.8/ref/models/fields/#django.db.models.OneToOneField

Satisfy Django with OneToOneField instead of FK where unique=True

---

geonode/base/migrations/0001_initial.py
geonode/base/models.py

Ref: https://github.com/GeoNode/geonode/issues/2501
Including `null=True` does nothing for a ManyToManyField; Django's system checker throws a warning on this one. Removing the null arg but leaving `blank=True` keeps the expected behavior.
See also: https://docs.djangoproject.com/en/1.8/ref/models/fields/#manytomany-arguments

'null' has no effect on a ManyToManyField; removed 

---

pavement.py

*Note: I'm raising this PR partly for discussion; feel free to close if preferred.*
I noticed that Travis CI is erroring (non-fatally; tests & linting do still run) during the initial migration step, e.g., https://travis-ci.org/GeoNode/geonode/builds/137479227#L2473:
```
...
django.db.utils.OperationalError: no such table: django_site
```
It looks like this exception started being thrown after [this commit](https://github.com/GeoNode/geonode/commit/a39176fa4f469f00e53a065533d205b2211f7f1d) happened - related Travis build [here](https://travis-ci.org/GeoNode/geonode/builds/126400625#L2301) is the first instance of this particular error.
Testing `paver sync` locally reproduces the error Travis is getting; reverting that commit resolves it. However I'm hesitant to revert without clarity on …

Fix Travis CI/paver sync error during migration

---

geonode/contrib/api_basemaps/__init__.py
geonode/contrib/api_basemaps/bing.py
geonode/contrib/api_basemaps/mapbox.py
geonode/settings.py

Added mapbox api basemaps functionality if MAPBOX_ACCESS_TOKEN is set.
fix for #2478 
- created an api_basemaps app under geonode.contrib
- moved bing basemap to api_basemaps
- set default value for both to None and check for os.environ for both

added mapbox api basemaps functionality

---

geonode/layers/templates/layers/layer_geoext_map.html
geonode/maps/templates/maps/map_include.html

Hi, 
This first very simple pull request is also a way to check if it is the proper way to do it through GitHub (did we fork the good base from Geonode ? Etc.). Then, we will send you our functionnalities that we developed on our website (aware.cirad.fr - development version), as Agnès Tendero told you a few days ago. As a reminder these functionalities are :  
1. Concatenating the metadata Regions in Title search fields
2. Display the full list of resources of each catalogue for every user (logged in or not)
3. List of layers/maps/documents sorted by permission : first the authorized ones, then the restricted ones.
4. Export metadata to text and HTML format
5. Restrictions for unauthenticated users : hide 'Add layer', 'Create new map', 'Add documents' options
6. Search by text (title) …

 set 600px instead of 400 for geoext frame for layers and maps templates

---

geonode/contrib/api_basemaps/__init__.py
geonode/contrib/api_basemaps/cartodb.py
geonode/contrib/api_basemaps/osm.py
geonode/contrib/api_basemaps/stamen.py
geonode/contrib/api_basemaps/thunderforest.py
geonode/settings.py

- removed mapquest basemaps (will add when setup api key is identified)
- added cartodb basemaps
- added stamen basemaps
- added thunderforest basemaps
- added alternate osm basemaps
Each on is configurable with = True, by default they are set to False
migrated basemap variable checks to geonode.contrib.api_basemap to clear up settings.py

added additonal api basemaps functionality

---

geonode/base/models.py
geonode/layers/utils.py

Refactor thumbnail files to be stored in the location configured for media storage so that whether uploaded or auto-generated, the locations are consistent when the application is configured for remote storage.

Update to how thumbnails are saved

---

geonode/geoserver/signals.py

This PR adds the TIME param to allow thumbnails generated for time enabled layers to include all features. Without this change, the thumbnail would only include features from the first time instance which could be blank
.

Add TIME param to thumbnail request

---

docs/tutorials/users/edit_style/index.txt

After reading issue https://github.com/GeoNode/geonode/issues/2448
I was thinking could be useful add this line in the users docs.
Added advice on importing external .sld styles that will be displayed as "none" if there's no Title.

updated index.txt

---

geonode/catalogue/templates/geonode_metadata_full.html
geonode/catalogue/urls.py
geonode/catalogue/views.py
geonode/documents/templates/documents/document_detail.html
geonode/layers/templates/layers/layer_detail.html

Hi, these additions allow the user to download full metadata in .txt and .html formats. 
I'm sorry to post this PR a second time (#2530), but there was a problem on the other one, so I thought it was better to do a new one. 
I noticed there will be a new "Metadata Detail" section in the future version of GeoNode, so I don't know if my PR will be that useful ! But anyway, here it is. 
Thanks

Enable .txt and .html formats exports for metadata

---

geonode/base/autocomplete_light_registry.py
geonode/base/templatetags/base_tags.py
geonode/documents/autocomplete_light_registry.py
geonode/layers/autocomplete_light_registry.py
geonode/maps/autocomplete_light_registry.py
geonode/templates/autocomplete_response.html
geonode/templates/search/search_scripts.html

These additions enable to search according the catalogue where the user is. 
If the user is in the "Layers" section (for example) and starts typing something in the left text-search bar, only layer-type resources will be shown in the list in the autocomplete box. 
In the actual version of Geonode, document-type or map-type resources can be shown while the user is in the Layer section, but when he clicks on the resource name in the box, nothing will appear...
However, with these additions, the principal search box in the header navbar will keep searching in all catalogues and will keep displaying all results from all types anyway. These modifications mainly have effects the left panel search filters.

Enable search according to catalogue

---

geonode/layers/templates/layers/layer_style_manage.html

Currently, the JavaScript in the `layer_style_manage.html` template populates the layer style dropdown with the name of the style rather than the title, despite the titles being displayed in the "Available styles" list. This pull request populates the dropdown with the title.

Fix Layer Style Titles In Dropdown

---

geonode/social/views.py

As of Django 1.8, 'name' has been removed as a real field on the ContentType model. Using 'model' instead gives the same/desired results.
*error prior to fix:*
```
Internal Server Error: /social/recent-activity
File "/vagrant/.venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/vagrant/.venv/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
return self.dispatch(request, *args, **kwargs)
File "/vagrant/.venv/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
return handler(request, *args, **kwargs)
File "/vagrant/.venv/lib/python2.7/site-packages/django/views/generic/list.py", line 174, …
```

'name' no longer a ContentType field in Django 1.8+

---

geonode/upload/utils.py

Some database settings may not explicitly define the schema, so default to using public.

Default to public schema if not defined

---

geonode/settings.py
geonode/social/__init__.py
geonode/social/apps.py

The current pinned version of actstream no longer works "old-style", with models set in `ACTSTREAM_SETTINGS['MODELS']`... models now need registered in actstream prior to their use as action objects. In Django 1.8+, this requires use of AppConfig.
See also: http://django-activity-stream.readthedocs.io/en/latest/configuration.html

register models for actstream 0.5+ / Django 1.8+

---

geonode/geoserver/helpers.py
geonode/layers/utils.py

Currently, replacing a layer throws `'NoneType' object has no attribute 'layerfile_set'` half-way through, and fails to complete the replacement: it successfully deletes the original layer, but doesn't finish importing the new layer, so the result is error + no layer at all.
The str/int port fix is incidental to the main issue above but resolves a TypeError occurring during the same replace-layer process.

Fix "replace layer" errors

---

geonode/static/geonode/js/upload/LayerInfo.js
geonode/upload/views.py

This PR synchronizes the async requests for multi-file imports by using the upload id as the unique identifier allowing the server to return the correct status to the client when polling for updates.

Fix client/server handling for multi-file asyc upload/import

---

geonode/geoserver/helpers.py

It appears that GeoWebCache aggressively caches tiles produced using old SLD data, so that when a style is updated the tiles generated with the old style can be retained. This patch is intended to help GeoNode's GeoWebCache invalidate the tiles for the layer in question.

Invalidate geowebcache after style update

---

docs/reference/developers/settings.txt
docs/tutorials/admin/index.txt
docs/tutorials/admin/s3_config/index.txt

Currently having an issue with the added documentation section in the table of contents. It's not appearing correctly when viewing the siblings, although it appears in the ToC fine at the root level.

Added documentation for configuring an AWS S3 Bucket with GeoNode

---

geonode/layers/migrations/0002_initial_step2.py

Reference: https://github.com/GeoNode/geonode/issues/2579
Just a revert commit, but I'm raising it as a good practice / papertrail patch to pull in if desired.

Revert " - remove layer_is FK constraints from layer_styles migrations"

---

geonode/people/templates/people/_profile_opengraph.html

Certain URLs, e.g.
`http://192.168.99.110:8000/people/profile/admin/?limit=100&offset=0`
Contain malformed meta links, e.g.
`<meta name="og:image" content="http://example.comhttp://www.gravatar.com/avatar/9a46584a89af11e4130ca7d6808e81a7/?s=200">`
The cause is straightforward in the template itself - see the diff. I'm guessing we probably don't want https://{{SITE_DOMAIN}} prepended to a gravatar URL.

fix broken og:image link in meta tag in head

---

geonode/base/admin.py

This is a proposed fix for #2566. 
To recap, when accessing admin URLs pertaining to certain models (e.g. /admin/maps/map/2/), template rendering raises "TypeError: 'NoneType' object is not callable" (I'll spare readers the full traceback because I'm certain you can easily replicate it against any version of Geonode going back to the great Django 1.8 upgrade commit). So these admin views for these models do not load.
To diagnose, this relates to `class ResourceBaseAdminForm` in `base/admin.py`, where `TaggitField` is instantiated with an instance of `TaggitWidget`. Before this patch, no value is specified for the first arg `autocomplete`; therefore, during the template render, that `None` value gets called. 
The first step of the fix is suggested by a commented-out line where …

fix exception during renders of admin forms using autocomplete_light

---

Makefile
docker-compose.yml

Smoke tests and unit tests now work with `make test` using docker.

make test works in docker

---

geonode/groups/templates/groups/group_list.html
geonode/people/templates/people/profile_list.html
geonode/static/geonode/js/search/search.js
geonode/templates/search/_group_search_content.html
geonode/templates/search/_group_snippet.html
geonode/templates/search/_search_user_content.html
geonode/templates/search/_sort_filters.html

_Feel free to squash prior to merging; left as-is for info only_
Ref: https://github.com/GeoNode/geonode/issues/2555
Adds a context-dependent search (filter box) to the `/people` and `/groups` pages. This search works similarly to those on the other resource pages (map, layer, documents). In the case of `/people` search, searches as executed on the `username` property (as people profiles do not have a `title`).
_Re-styled group page showing all groups_
_search results using context-specific group search: autocomplete results are shown in drop-down from search box_
_Same; for /people_
_Same; for /people -- text may be entered to search first name, last name, or username values: autocomplete shows the username of matching profile(s)_

Add context-specific search for people, groups

---

dev_config.yml
geonode/base/migrations/0004_auto_20160824_0245.py
geonode/people/migrations/0003_auto_20160824_0245.py
geonode/services/migrations/0003_auto_20160824_0245.py
geonode/settings.py
pavement.py

This PR fixes a set of bugs preventing launch of a simple development machine using paver.  With this fix, we can launch Ubuntu 16.04 LTS development machines for vanilla/community GeoNode!  I use https://github.com/pjdufour/geonode-devops for provisioning the development machine.
**Settings**
- Fixed sqlite database path issue (reverted back to previous use of `PROJECT_ROOT`)
- Reverted `DEBUG` and `TEMPLATE_DEBUG` back to `True` by default.
**Migrations**
- Added additional migrate commands to paver (in correct order).
- Added migrations for `services`, `base`, and `people` apps.
I identified the missing migrations using `python manage.py makemigrations --dry-run  --noinput`, which should probably be added to docs somewhere.  Output was:
```
Migrations for 'services': …
```

Development Fixes (pavement, settings, and migrations)

---

docs/tutorials/devel/devel_env/index.txt
docs/tutorials/devel/devel_env/index_bk.txt

This fixes some typos in the "Install GeoNode for Development" section of the "Developers Workshop".

Fix typos in "Install GeoNode for Development"

---

geonode/geoserver/signals.py

The repoURL was using the GeoServer DataStore connection_parameters
value to contstruct the GeoGig repository URL, which looks like:
`http://<server>/geoserver/geogig/geoserver://<repo name>`
The statistics and logs URL for GeoGig needs to use a repo URL like
this:
`http://<server>/geoserver/geogig/repos/<repo name>`

Fix GeoGig stats/logs URL for Layer info page.

---

geonode/maps/views.py

An exception is produced if you add a remote layer (via the Remote Services feature) to a map, then try to download the map by going to:
Download Map -> Download Data Layers -> Start downloading this map
This PR fixes this by removing Remote Services layers from the list of layers to download.

Exclude remote services layers from map download feature.

---

geonode/upload/upload.py

When uploading a Raster layer, the GeoServer Importer would sometimes fail with a NullPointerExcption trying to deference the target DataStore on the Task. In debugging the issue, I found that in these cases, the Import Task execution request would *reattach* to the GeoServer Catalog and effectively overwrite the DataStore on the Task to null.
The code for this case was always sending the Import Task execution twice [ `import_session.commit(async)` ], once on line 391 and then again just before returning the target datastore, while other cases would only send the request at the very end. Preventing the second request for Raster uploads seems to eliminate the race condition in GeoServer Importer.
Also, I removed the repeated block of code at 393, it will never get hit since it's the same …

Fix race condition during Raster upload/import

---

geonode/layers/views.py
geonode/local_settings.py.qgis.sample

If we are using the QGIS Server backend, the path to the log was not defined.

fix QGIS path log when using qgis server backend

---

geonode/geoserver/views.py
geonode/layers/templates/layers/layer_style_manage.html

Need to use Style objects instead of strings to update the style correctly.
`{{ style.0 }}` is used for the value in the UI because the `cat.get_style()` lookup uses the `sld_title` field (in .0), not the `name` field.

Bugfix for updating style through UI

---

geonode/layers/templates/layers/layer_detail.html
geonode/maps/templates/maps/map_detail.html

Prevents the modal from spawning with the previous comment if you click "Add comment" again before refreshing the page.

Clear comment modal after adding comment

---

geonode/social/urls.py
geonode/social/views.py

Prior to these applied changes, the "My Activity" link would sometimes incorrectly display the user's actions. They would lack the link to the object sometimes, and sometimes not display at all.
The User activity feed prior to this change:

Fixing missing and broken links to actions on the user's activity page

---

geonode/upload/upload.py

One approach to the problem described in
https://github.com/GeoNode/geonode/issues/2646
This patch uses the Django field definition to get the length, so this can be controlled from that one place and won't get out of sync.

truncate upload names over length to allow upload

---

geonode/api/api.py
geonode/api/resourcebase_api.py
geonode/layers/utils.py
geonode/services/views.py
geonode/upload/views.py

This subtle misunderstanding of Python tends to cause confusing bugs.
Suppose you have a definition statement like 'def function(keys=[]): ...' 
This def statement is evaluated once, at import time, to create a function object. It is at this time that '[]' is evaluated, and it is that ONE list object which is retained as the default value for 'keys'. In other words, Python doesn't store the expression and re-evaluate it every time the default is needed, it evaluates it once at import time and the resulting value is passed for every call where that arg is not given.
To explain this with code, the effect is something like this:
default_keys = []
def function(keys=default_keys):
...
When function() is called with a value for keys, no problem will be seen. Even when it is called with no value …

remove mutable default values for kwargs

---

geonode/groups/views.py

The wrong filter was being applied for this view, causing it to give an error.

Fixed bug breaking Group Activity view

---

MANIFEST.in

previous adjustments to the setup.py and MANIFEST.ini were not allowing certain filetypes to be packaged, loading.gif was the most noticeable.

Package up all necessary files

---

docker-compose.yml

Please! Fix it Celery service on docker-compose:
Correct way:
```
celery:
image: geonode/django
links:
- rabbitmq
- postgres
- elasticsearch
command: celery worker --app=geonode.celery_app:app -B -l INFO
```
Instead of:
```
celery:
image: geonode/django
links:
- rabbitmq
- postgres
- elasticsearch
command: celery worker --app=geonode.celeryapp:app -B -l INFO
```

Fixing syntax error: celery_app

---

geonode/geoserver/management/commands/updatelayers.py

This PR exposes the permissions arg so that custom permissions can be applied to layers during the creation/registration process.
Example Usage:
```
python manage.py updatelayers --skip-geonode-registered -i -p "{'users': {'AnonymousUser': ['change_layer_data', 'download_resourcebase', 'view_resourcebase']},'groups': {'registered': ['change_layer_data', 'download_resourcebase', 'view_resourcebase']}}"
```

Enable update layers management command to accept the permissions dict

---

docs/tutorials/install_and_admin/geonode_install/setup_configure_httpd.txt

This fixes "[Errno 13] Permission denied: '/home/geonode/geonode/geonode/uploaded/layers/" encountered by user when trying to upload layer files.

Insert missing sudo to chmod commands

---

setup.py

- removed import on INSTALLED_SCHEMES since its usage was removed on this commit  (aff43c0).
- limiting the version of celery to less then the 4.0 release, due to django-celery not having a release in over a year which would include the updates in master to support the new version of celery.  If you currently install Geonode it will install celery 4.0, but when attempting to use any django commands an ImportError occurs due to no module named timeutils.

Fix for GeoNode install of celery (django-celery version installed doesnt support celery 4.0)

---

geonode/templates/user_messages/_message_snippet.html
geonode/templates/user_messages/inbox.html

This is an update to the inbox messages to use AJAX. Now when a user deletes a message, it sends an AJAX request. Therefore, they will remain in their active tab (`Inbox` or `All`), where before you would always be returned to the default active tab, `Inbox`.

Process inbox messages using AJAX

---

geonode/contrib/geosites/models.py
geonode/geoserver/helpers.py
geonode/geoserver/signals.py
geonode/services/views.py
geonode/tests/integration.py
geonode/tests/utils.py
geonode/utils.py

Split this function into two with one containing geoserver-agnostic logic, and the other home to the geoserver-specific logic.  This is support for django-osgeo-importer changes which will allow imports that don't require a geoserver instance.

Split geoserver.helpers.set_attributes()

---

requirements.txt
setup.py

When using `pip install -r requirements.txt` I was finding that my Celery worker was not booting properly.
```
...
File "/env/lib/python2.7/site-packages/django/core/management/base.py", line 534, in check
self.stderr.write(msg, lambda x: x)
TypeError: function takes exactly 1 argument (2 given)
```
This is an incompatibility between Celery 3.1.17 and Django 1.8. https://github.com/celery/celery/issues/2536
Fix: upgrade to Celery 3.1.18, which supports Django 1.8. http://docs.celeryproject.org/en/latest/history/changelog-3.1.html#version-3-1-18
I verified that 3.1.18, 3.1.19, 3.1.25 and some other versions boot fine without this exception.
If I had to guess about why we only just noticed this, I would guess that most users installing GeoNode since the upgrade to Django 1.8 did not use the …

require celery version to be at least 3.1.18

---

geonode/settings.py

-  The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_DIRS, TEMPLATE_CONTEXT_PROCESSORS, TEMPLATE_DEBUG. https://docs.djangoproject.com/en/1.8/topics/templates/#support-for-template-engines
- historic pep8 fixes

The standalone TEMPLATE_* settings were deprecated in Django 1.8

---

geonode/api/resourcebase_api.py

Update the object_list limit to use the value assigned to CLIENT_RESULTS_LIMIT in settings rather than a hard coded value.

Update the object_list limit 

---

geonode/base/admin.py
geonode/base/autocomplete_light_registry.py
geonode/base/models.py
geonode/base/translation.py
geonode/catalogue/backends/pycsw_local.py
geonode/contrib/dynamic/models.py
geonode/contrib/dynamic/postgis.py
geonode/contrib/geosites/api.py
geonode/documents/admin.py
geonode/documents/autocomplete_light_registry.py
geonode/documents/translation.py
geonode/geoserver/helpers.py
geonode/groups/admin.py
geonode/groups/autocomplete_light_registry.py
geonode/groups/models.py
geonode/layers/admin.py
geonode/layers/autocomplete_light_registry.py
geonode/layers/translation.py
geonode/maps/admin.py
geonode/maps/autocomplete_light_registry.py
geonode/maps/models.py
geonode/maps/translation.py
geonode/people/admin.py
geonode/people/autocomplete_light_registry.py
geonode/people/models.py
geonode/services/admin.py
geonode/upload/admin.py
geonode/upload/views.py

This boring patch fixes all the flake8 errors obtained by running `python -m flake8 geonode` with the following versions:
`3.2.1 (pyflakes: 1.3.0, mccabe: 0.5.2, pycodestyle: 2.2.0) CPython 2.7.12 on Linux`
I'm aware the existing flake8 config is ignoring some classes of errors, this fixes them anyway

Fix flake8 warnings 

---

geonode/upload/tests/integration.py
geonode/upload/upload.py

This is a small change to fix a minor big with the uploader.
The problem exists when we try to upload a zipped shapefile that includes an xml sidecar file. When we ended up in the final_step of the upload process, the xml file would be attempted to be read. However, the code was operating correctly only in the case of the xml being uploaded alongside other individual shapefiles. If they are packaged together in a .zip, it would fail to open the xml file since it hasn't been extracted in this context.
This update will xml files packaged in a zip to be correctly read and handled by the uploader.

Correctly handle xml sidecar files within a zip

---

docs/tutorials/advanced/adv_data_mgmt/osm.txt

Documentation on osm-extract, a script that allows to download data from OpenStreetMap for a country of interest, perform ETL procedures in order to classify data into layers and publish it in a PostgreSQL+PostGIS database.

Add instructions on how to use osm-extract

---

requirements.txt

Installing today GeoNode from master on a Ubuntu virtualenv, I have detected two dependencies missing, which caused the following errors
oauthlib missing was causing an error when using paver:
$ paver sync
File "manage.py", line 29, in <module>
execute_from_command_line(sys.argv)
File "/home/vagrant/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
utility.execute()
File "/home/vagrant/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
django.setup()
File "/home/vagrant/env/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
apps.populate(settings.INSTALLED_APPS)
File …

Adding django-braces and oauthlib in requirements

---

geonode/api/resourcebase_api.py
geonode/layers/models.py

This adds a geogig_link URL to the search results and avoids using the full TastyPie hydration cycle that https://github.com/GeoNode/geonode/pull/2789 caused.
The following changes were made:
1. The model for `Layer` now has `geogig_enabled` and `geogig_link` properties. 
2. Object formatting was moved out of `create_response` and into a new class method, `format_objects`.
3. The `VALUES` object was moved out of `create_response` and is now a class member.
4. The `LayerResource` class has a new `format_objects` method which converts the models to dictionaries, then adds in the `geogig_link` property to the dictionary.
These changes work with https://github.com/boundlessgeo/MapLoom/pull/45
Thanks again.

Adding a geogig_link URL to /api/layers

---

geonode/geoserver/signals.py

With https://github.com/GeoNode/django-osgeo-importer/pull/83 providing means for serving geopackage tiles via mapproxy and geoserver doesn't handle them well, these checks skip geoserver processing for tile layers from geopackage files altogether.

Short-circuit Layer.save() geoserver signal processing for gpkg tile layers.

---

geonode/settings.py

Best practice to "name" the template engine to avoid conflicts in downstream projects when multiple template engined may be used.
See https://docs.djangoproject.com/en/1.10/_modules/django/template/utils/

named template engine

---

docs/tutorials/advanced/adv_data_mgmt/osm.txt

Provide some more details on osm-extract in the tutorial section, a script that allows to publish OSM data as vector layers in GeoNode.

Enrich osm-extract docs, in the tutorials section

---

geonode/static/geonode/js/upload/LayerInfo.js
geonode/static/geonode/js/upload/upload.js

Currently if you upload new data, you can tick "Import to Geogig" and continue your upload without specifying a name for the GeoGig repo. This is not desired and will cause the upload to hang.
For now I have modified the javascript to detect an empty Geogig repo name if the "Import to Geogig" checkbox is ticked, and deliver an error message if the "Upload Files" button is clicked before specifying a name.
Another potential solution is to disable the Upload Files button if: The Geogig repo name is empty AND "Import to Geogig" is ticked. This can be done in conjunction with the current fix. Does this sound appropriate to do? If it is, I'll give it a shot to add that to this commit, or to another commit for the future if we want to get this merged in quickly in the interim.

Do not allow upload with empty geogig repo name

---

geonode/maps/views.py
geonode/people/views.py
geonode/utils.py

Solves an issue where two access tokens are added to OGC requests, which causes the request(s) to fail and for the Geoserver OAuth endpoint to be unusable in the browser's existing session.

Duplicate Access tokens on OGC request

---

geonode/static/geonode/js/upload/upload.js

Fixing a bug accidentally introduced in [PR#2809](https://github.com/GeoNode/geonode/pull/2809)
Variable names were not defined, causing javascript errors upon upload. This fix will apply the changes to the geogig bug fix correctly.

Fix bug with missing variable definitions on checkGeogig

---

geonode/maps/views.py
geonode/utils.py

Solves an issue where the access token was sent to most services/endpoints, which in some cases causes the request to fail.
Also solves a case where expired access tokens where being used.

Send access token only to OGC_SERVER

---

geonode/people/models.py

This will allow you to login to GeoNode using any case in the log in form.
Ergo, if I want to log in to user TravisB, this change allows me to login with any of the following: travisb, travisB, TRAVISB, etc.

Make usernames case insensitive for authentication

---

geonode/geoserver/helpers.py
geonode/geoserver/management/commands/updatelayers.py

Added an option in gs_slurp to execute signals (false by default).
Fixes #2838

Execute signals when running updatelayers

---

docs/tutorials/admin/admin_mgmt_commands/index.txt
geonode/maps/management/commands/fix_baselayers.py
geonode/maps/tests.py
geonode/maps/utils.py

fix_baselayer is a command to fix the base layers for one or more maps.
Base layers are synced by the command with the ones included in the MAP_BASELAYERS setting.
Tests and documentation provided.
Usage:
python manage.py fix_baselayers
python manage.py fix_baselayers map_id

Adding the fix_baselayers command

---

geonode/maps/templates/maps/map_detail.html
geonode/maps/templates/maps/map_edit.html
geonode/maps/urls.py
geonode/maps/views.py
requirements.txt

It adds a route to maps for editing maps. 
The new client has two modi, view and compose. Right now the edit path would show the view instead of the compose. 
The current client will not be affected since it is a copy of the current view.

Add new routes/views for simple edit

---

geonode/people/templates/people/_profile_list_item.html

This change solves an issue where sorting looks incorrect in the UI due to formatting errors.
Steps to reproduce visual bug:
1. Create more than 4 users.
2. Give each user an Organization Name, varying their length to emphasize the problem.
3. Navigate to the People search page.
4. Select the filter dropdown, and pick any of them which will cause the tiles to become reorganized.
You should see the profile cards look out of order due to being of varying sizes.
Additionally, another small bug existed where the tiles were supposed to display "No Organization Info" if the organization field had no data. This was also corrected.

Format people cards to be universal height so sorting works properly

---

geonode/settings.py

Since BROKER_URL is set in https://github.com/GeoNode/geonode/blob/master/scripts/docker/env/production/django.env#L2 we can get the value from the env file.
This should fix the celery container from constantly restarting because of invalid BROKER_URL.

fix: get rabbitmq broker url from docker env file

---

geonode/settings.py

they break installations, better use meta tags in html instead

don’t use version in leaflet libraries settings

---

docs/tutorials/install_and_admin/geonode_install/setup_configure_httpd.txt

"The uploaded/layers directory doesn't have to be served by apache, it only needs write permissions"
- @simod on #2896
https://github.com/GeoNode/geonode/issues/2896#issuecomment-278587461

Removed uploaded/layers from Apache config

---

geonode/maps/templates/maps/map_leaflet.html
geonode/settings.py

Fix to issue #2728 I opened past November.
When "LAYER_PREVIEW_LIBRARY" was set to "leaflet", the map detail was not rendering in the correct way. There where a number of problems with the previous implementation:
1. Base layers where not correctly created. I solved by using the base layers provided [here](https://github.com/GeoNode/geonode/blob/master/geonode/layers/templates/layers/layer_leaflet_map.html#L13);
2. the coordinates of the map center (`{{ resource.center_x }}`,` {{ resource.center_y }}`) where in google mercator, now they're converted in WSG84 by using [proj4js](http://proj4js.org/) library;
3. in the loop over the user's layers, the wrong Leaflet function was used to instantiate a WMS tile layer object given the URL to the WMS;
4. add a LayerControl object correctly …

Fix issue with Leaflet library

---

geonode/templates/geonode/geo_header.html
geonode/templates/geonode/geo_header_debug.html

Google deprecated the Google Earth service by the end of 2015.
As the functionallity is broken, the button must be removed.
Solves https://github.com/GeoNode/geonode/issues/2921

Remove the 3D viewer tool from maps

---

geonode/utils.py

When accessing GeoExplorer info popup the about section shows a 404
Needed to change default behavior to adopt geonode's location
Solves https://github.com/GeoNode/geonode/issues/2892

Change Geoexplorer aboutUrl

---

docs/tutorials/install_and_admin/quick_install.txt

The current instructions do not result in a working system. Additional steps were set out in http://osgeo-org.1560.x6.nabble.com/syncdb-on-a-new-install-doesn-t-work-relation-people-profile-does-not-exist-tp5272419p5278374.html.

Add extra information for Ubuntu install

---

geonode/upload/files.py

OS X adds a "__MACOSX" directory when creating a zipped file. We allow for uploading of zip files in importer, but it will trip up in the `_contains_bad_names` function, because it recognizes this directory as an xml unsafe name. If we skip this, it'll give an index out of bounds error later, presumably because there's extra copies of the files (I'm not actually 100% sure why).
The goal of this commit is to just clean the directory, so I added a function which just strips anything in a "__MACOSX" directory.

Handle OS X zipped files in upload

---

geonode/base/models.py

Along with GeoServer commit https://github.com/geoserver/geoserver/commit/94ea2c0047f6367ce02a2462bde053565f7999fb
**WARNING:** You need to update GeoServer too, at least the OAuth2 Plugin
http://ares.boundlessgeo.com/geoserver/2.9.x/community-latest/geoserver-2.9-SNAPSHOT-sec-oauth2-geonode-plugin.zip

[ISSUE #2914] - User is still authenticated in geoserver after logging out from geonode

---

geonode/static/geonode/js/upload/LayerInfo.js

This was modified previously in [PR#2956](https://github.com/GeoNode/geonode/pull/2956) in order to fix XML unsafe names being uploaded (ie spaces and parentheses), but I made an error in removing the JavaScript which would capture the file extension, causing the geogig import to turn up empty. Reverted those lines back to correctly grab the file extension again.

Fixed incorrect DOM name to create geogig store

---

geonode/base/templates/base/_resourcebase_snippet.html
geonode/documents/templates/documents/document_list.html
geonode/documents/urls.py
geonode/layers/templates/layers/layer_list.html
geonode/layers/urls.py
geonode/maps/urls.py
geonode/static/geonode/js/search/cart.js
geonode/static/geonode/js/search/search.js
geonode/static/geonode/js/templates/cart.html
geonode/templates/index.html
geonode/templates/search/_search_content.html

A bunch of small search ui improvements, including many from #2762 
- resourcebase snippet uses col-lg-*, which should render better on phones
- facet_type variable passed to template and to angular for use
- checkboxes for selecting layers instead of cart icon
- a tooltip for hovering over the checkboxes

search ui improvements

---

geonode/base/templates/base/_resourcebase_snippet.html
geonode/context_processors.py
geonode/documents/templates/documents/document_detail.html
geonode/layers/templates/layers/layer_detail.html
geonode/maps/templates/maps/map_detail.html
geonode/settings.py
geonode/templates/_actions.html

Created 3 settings to easily toggle detail page tabs on/off.  Particularly useful for downstream projects that are not currently using the commenting or ratings.  All default to `True`.
- DISPLAY_SOCIAL (FKA SOCIAL_BUTTONS)
- DISPLAY_COMMENTS
- DISPLAY_RATINGS
Other minor fixes to detail pages, too.

tab display settings

---

setup.py

Recent versions of Tastypie have a `ignore_bad_filters` that is not supported on the underlying queryset object.

Peg django-tastypie to 0.13.1

---

geonode/api/resourcebase_api.py

If a request fails to provide an `offset` value, e.g., `int(None)` throws an exception

Provide default value if request doesn't include offset to avoid TypeError

---

geonode/settings.py

The ALLOWED_HOSTS setting needs to be a list but
there is no way to make it so just by using os.getenv
Added logic to check if the environment variable exits
and if so, split on comma. colon, or semicolon excluding
leading or trailing spaces

parse separated allowed hosts

---

geonode/api/resourcebase_api.py

The method was breaking layer api (no more owner and category) and possibly slowing down them. Suggestion is to put geogig_link as layer attribute if needed in master

remove loop from layer api (remove geogig_link) and use faster owner api

---

geonode/context_processors.py
geonode/templates/base.html

Hide Geoserver menu when not needed
Add settings.INSTALLED_APPS accessible as global variable in HTML.
Disable geoserver link in admin menu if geoserver is not present.

Hide Geoserver menu when not needed

---

geonode/templates/search/_sort_filters.html

Adjusts the icons display for search filters so they work and display correctly for people and groups. Currently only works correctly for maps/layers, and disappears when selecting a different filter on the people or group search.

Fix to correctly show icons on people and group filters

---

geonode/layers/views.py

The link in the DB may not have the character `?` in its URL.
So for these links, the link was like this:
`geonode.org&access_token=foo` which is wrong.

fix build querystring with links

---

geonode/layers/templates/layers/layer_leaflet_map.html

When we are using leaflet as layer preview library, if the map has both tile_url and ows_url, it will be both rendered in the map. This might be a bug.
Move this particular code:
```
L.tileLayer.betterWms('{{ resource.ows_url|safe }}', {
layers: '{{ resource.typename }}',
transparent: true,
format: 'image/png'
}).addTo(map);
```
To the bottom of the if else clause (because maybe someone forgot to put another case).
This will make sure `resource.ptype == "gxp_wmscsource"` will be evaluated first.

Fix duplicate tiling in Leaflet Preview

---

geonode/__init__.py
requirements.txt
setup.py

See https://github.com/GeoNode/geonode/pull/3111 for more conversation related to this.
What is our preferred way of releasing updates to a current "stable" release? this OAuth2 issue is currently a blocker for e.g., anyone pinning GeoNode 2.6 out of PyPI as a project dependency, etc.
Pulling in @afabiani's fix & releasing a 2.6.1 package is one way to handle this, but if there is another preferred solution let's talk about it & get this resolved. :)

Bugfix to 2.6 release

---

geonode/layers/forms.py
geonode/layers/models.py
geonode/layers/tests.py
geonode/static/geonode/js/upload/FileTypes.js
geonode/upload/files.py
geonode/upload/views.py

Make GeoNode supports asc file uploader.
At first I just want to make the support available with QGIS Server backend, but it seems it will work also on geoserver. This PR is only addressing the GeoServer backend one. The QGIS Server backend will be added in the another PR (since we move qgis_server to geonode).
cc @gubuntu @lucernae

ASCII support

---

geonode/base/admin.py
geonode/layers/templates/layers/layer_detail.html
geonode/layers/views.py

- Issues
- set thumbnail button not working with geonode-client 
- solution: 
- geonode-client use [boundless sdk](https://github.com/boundlessgeo/sdk) which contains a component to create thumbnail or create image for current view as blob so I created a function to post this image data (blob) to our endpoint [here](https://github.com/GeoNode/geonode-client/pull/173). 
-  but our end point generate thumbnail server-side so we need to skip this step if `preview=='react'`(a flag in the request to identify sender). 
this PR skip generating image (server-side) and save blob data as thumbnail image

set thumbnail function  for geonode-client

---

requirements.txt
setup.py

During my upgrade from GeoNode 2.4 to GeoNode 2.6, I noticed that the system after the command: 
sudo -u geonode python manage.py collectstatic
raises the following error:
File "manage.py", line 29, in <module>
execute_from_command_line(sys.argv)
File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
utility.execute()
File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 328, in execute
django.setup()
File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
apps.populate(settings.INSTALLED_APPS)
File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 115, in populate
app_config.ready()
File …

 Geonode 2.6 : Adding django-jsonfield-compat package to setup.py and requirements.txt 

---

setup.py

Shapely 1.6.0 is not compatible with geonode
we need to restrict Shapely version to 1.5.17 or less
please review this [issue](https://github.com/cartologic/cartoview/issues/57)

Fix Shapely Version

---

setup.py

Running any Django command with the latest version of Six, and with Geonode's dependencies (the version of ```django-autocomplete-light``` that gets pulled in, to be precise) will fail with something similar to this:
```
File "manage.py", line 11, in <module>
execute_from_command_line(sys.argv)
File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
utility.execute()
File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
django.setup()
File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
apps.populate(settings.INSTALLED_APPS)
File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in …
```

Version constrain six, see https://github.com/benjaminp/six/issues/210

---

.gitignore

Running docker-compose generates the celery files at the project root
celerybeat-schedule.bak
celerybeat-schedule.dat
celerybeat-schedule.dir
Add line in .gitignore to ignore from repo
celerybeat-schedule.*

gitignore celery helper files

---

geonode/base/models.py

This error happened when in the Keywords selectbox a tag appear more than once. This should not happen, usually, but it may happen if there some error on the metadata xml.
A fix on GeoNode has been pushed in order to overcome such kind of exceptional cases.

 - Avoid Multiple Tags Exception

---

geonode/upload/utils.py

A change in either the GeoServer API or `gs_catalog` has caused `None` to be returned when failing to lookup a `store`. Previously it was throwing a `FailedRequestError`. This forces an exception to be thrown if None is returned.

GeoServer stores weren’t being created automatically

---

geonode/layers/templates/layers/layer_geoext_map.html
geonode/maps/templates/maps/map_geoexplorer.js
geonode/maps/templates/maps/map_include.html
geonode/maps/utils.py
geonode/maps/views.py
geonode/utils.py
requirements.txt

This is actually the outcome on GeoExt GIS client
and the maps

 - Improve GeoExt base GIS viewer; adding 'wrapDateline' option and update OL2 version

---

geonode/geoserver/tests.py
geonode/geoserver/views.py

Without this small check, the method returns "404: not found" to anonymous users or unauthorized ones.

 - Intercept and handle correctly resource not found exception

---

geonode/layers/metadata.py

Parse all dateformats (not only the first one) and return empty string if none matches.

Fix dateformat sniffing.

---

.gitignore
geonode/base/models.py
geonode/base/populate_test_data.py
geonode/context_processors.py
geonode/geoserver/helpers.py
geonode/geoserver/signals.py
geonode/layers/forms.py
geonode/layers/models.py
geonode/layers/populate_layers_data.py
geonode/layers/tests.py
geonode/layers/utils.py
geonode/layers/views.py
geonode/maps/models.py
geonode/maps/tests.py
geonode/maps/urls.py
geonode/maps/views.py
geonode/qgis_server/__init__.py
geonode/security/models.py
geonode/security/tests.py
geonode/services/views.py
geonode/settings.py
geonode/tests/csw.py
geonode/tests/integration.py
geonode/tests/smoke.py
geonode/upload/forms.py
geonode/urls.py

This commit contains changes to accomodate QGIS Server as alternative backend.
It also contains various improvements on main geonode codes.
Changes:
- Various code branches to determine which backend is currently being used
- Add decorator annotation to methods specific for GeoServer
- Improve documentation and codes on several methods that will be used by QGIS Server backend later

QGIS Server Related PR: GeoNode code improvements.

---

geonode/templates/search/_group_snippet.html

This PR adds group logos to the groups page.
It is related to issue #3394 
The current behaviour:
Proposed modification:

[WIP] Adds group logos to the groups list in the frontend

---

requirements.txt

Removing a duplicate in requirements which is causing an error on pip install

Removing a duplicate in requirements which is causing an error on pip install

---

geonode/api/resourcebase_api.py

Handles empty titles and missing thumbnails in resource api
It has been done with an hack, as apparently CommonModelApi cannot be dehydrated

Handles empty titles and missing thumbnails in resource api

---

geonode/groups/tests.py

This PR is related to issue #3394 and the recently closed PR #3395. It adds a couple of unit tests that verify that the backend API provides a `GroupProfile`'s logo when responding to list view requests

Added tests to assert presence of logo urls in list view of groups

---

geonode/static/geonode/js/search/search.js

This PR use 'OpenStreetMap Mapnik' as default source for baselayer which allow http and https connection. This will remove browser warning about mixed content when using HTTPS to connect to geonode.
Same PR as https://github.com/GeoNode/geonode/pull/3409 but target master branch

Switch to https

---

Makefile
README
scripts/docker/env/development/django.env
scripts/docker/env/production/django.env

In the current setup using docker, the allowed hosts aren't read properly since they're in a list in the ENV file.  This removes the list syntax, since django already puts the data we send to it from the ENV file into a list for ALLOWED_HOSTS and adds geonode to the ALLOWED_HOSTS list since we're supposed to access the build at geonode/ in our browsers based on the README by modifying our local hosts file.

Fix docker builds

---

geonode/context_processors.py
geonode/geoserver/templates/geoserver/layer.xml
geonode/geoserver/views.py
geonode/layers/templates/layers/layer_detail.html
geonode/maps/templates/maps/map_detail.html
geonode/people/templates/people/profile_detail.html
geonode/settings.py
geonode/tests/integration.py
geonode/tests/smoke.py
geonode/urls.py

This PR implements enhanced WMS GetCapabilities endpoints.
It will be possible to retrieve a GetCapabilities document for a single layer, for all of the layers of a given map, user and category.
Example:
GetCapabilities for all layers in a map:
http://localhost:8000/capabilities/map/3/
GetCapabilities for all layers of a given user:
http://localhost:8000/capabilities/user/admin/
GetCapabilities for all layers in a category:
http://localhost:8000/capabilities/map/biota/
GetCapabilities for a given layer:
http://localhost:8000/layers/geonode:mylayer
In the UI this link are displayed in the layer, map and profile details page when DISPLAY_WMS_LINKS is True (which is by default).
Code is migrated from old WorldMap version and it is courtesy of @mbertrand

Implement enhanced WMS capabilities

---

docs/tutorials/admin/admin_mgmt_commands/index.txt
geonode/geoserver/management/commands/find_geoserver_broken_layers.py

A command which will list layers which have a missing resource in GeoServer
sample usage:
```
$ ./manage.py find_geoserver_broken_layers --owner admin
Checking layer 1/4: geonode:flares_noaa owned by admin
Checking layer 2/4: geonode:tm_world_borders_0_3 owned by admin
Layer geonode:tm_world_borders_0_3 is broken!
Checking layer 3/4: geonode:camer_hyd_basins_vm0_2007 owned by admin
Checking layer 4/4: geonode:ukr_nhr_hotspots owned by admin
***** Layers with errors: 1 in a total of 4 *****
geonode:ukr_nhr_hotspots by admin
```

Add the find_geoserver_broken_layers command

---

geonode/api/api.py
geonode/api/resourcebase_api.py
geonode/base/templates/base/_resourcebase_snippet.html
geonode/templates/search/_general_filters.html

As detailed in the title, allow search and index pages to show the Owners Full Names if available, like shown here below

[Minor Improvement] - Print Owners Full Name instead of username when available

---

docker-compose.yml

The rationale is to allow developers to build django image with the tag `latest` from master for new features

Rename django image tag from latest to geonode

---

docs/tutorials/admin/geoserver_geonode_security/index.txt
docs/tutorials/install_and_admin/geonode_install/index.txt

Updated docs on GeoServer Advanced Security section;
GeoFence plugin from 2.12.x version and above, gets the default role service from the properties file and no more from the GeoServer default settings.

[Docs Updates] - GeoServer Advanced Security: update GeoServer/GeoFence Default Role Service section

---

geonode/base/migrations/24_to_26.py

Remove fields that were added in two separate migrations causing errors when you stand up geonode. This PR needs to go into master as well as 2.7.x so I will be creating two PRs for it. You can see the other instance of these same migrations that I kept at https://github.com/GeoNode/geonode/blob/master/geonode/base/migrations/26_to_27.py.

Remove Double Migrations [2.7.x]

---

geonode/base/migrations/24_to_26.py

Remove fields that were added in two separate migrations causing errors when you stand up geonode.  This PR needs to go into master as well as 2.7.x so I will be creating two PRs for it.  You can see the other instance of these same migrations that I kept at https://github.com/GeoNode/geonode/blob/master/geonode/base/migrations/26_to_27.py.

Remove Double Migrations [Master]

---

geonode/contrib/api_basemaps/bing.py

error message : 
```
settings.MAP_BASELAYERS.append(settings.BASEMAP)
AttributeError: 'module' object has no attribute 'BASEMAP'
```

fix for AttributeError: 'module' object has no attribute 'BASEMAP'

---

geonode/base/models.py
geonode/geoserver/helpers.py
geonode/geoserver/signals.py
geonode/settings.py

This allows different implementations of thumbnail generators. This PR configures Geonode to use the old/current implementation - so there should be no changes.
I did, however, make a minor change in ResourceBase#save_thumbnail(). The old implementation (theoretically) allowed multiple thumbnails (just call #save_thumbnail() with different filenames), however, only one is really supported. For example, see ResourceBase#thumbnail_url, ResourceBase#get_thumbnail_url(), and the rest of Geonode just using ResourceBase#thumbnail_url. This makes it more explicit.
There is also a minor change in the layer#post_save() handler. I put a guard on the call to generate a thumbnail. This is because an alternate implementation could be to schedule a celery task to create the thumbnail in the future. …

Add ability to control thumbnail generation implementation

---

geonode/maps/templates/maps/map_detail.html

Fixes #3641 by adding an `<article>` wrapper around the info content.
Equivalent to same section in layer_detail.html: https://github.com/GeoNode/geonode/blob/a80e8e40c851f2df954e1db1bbccb08b60a3686a/geonode/layers/templates/layers/layer_detail.html#L62

Fixes #3641 - tabbed content on map detail page broken

---

geonode/security/utils.py

Layers created in GeoServer and then imported into GeoNode may not necessarily reside in the default workspace. This change ensures that we use the workspace of the layer (if present otherwise the default workspace) when writing rules to geofence.
Fixes #3672

Retrieve correct workspace for layer when managing geofence rules

---

geonode/geoserver/helpers.py

(Re-rolled this PR against master, as requested in https://github.com/GeoNode/geonode/pull/3716. A backport to whichever branches will contribute to the 2.8.x releases would be much appreciated.)
When uploading new layers to GeoServer, the  ```_create_db_featurestore``` function in geoserver/helpers.py looks for a datastore with a name that matches the database name of the configured datastore-connection.
Other similar functions, such as ```create_geoserver_db_featurestore``` in upload/utils.py (https://github.com/GeoNode/geonode/blob/2.8.0/geonode/upload/utils.py#L636) and ```get_or_create_datastore``` in contrib/createlayer/utils.py (https://github.com/GeoNode/geonode/blob/2.8.0/geonode/contrib/createlayer/utils.py#L144) use ```ogc_server_settings.DATASTORE``` as the datastore name. 
If …

Use the correct datastore name in _create_db_featurestore

---

.dockerignore
.travis.yml
geonode/local_settings.py.qgis.sample
geonode/settings.py

Previously, there are some errors detected in the sample settings file. This could lead to decreased coverage and unittests on QGIS Server side.
This PR contains the following changes:
- Disable QGIS Server Backend by default. User needs to enable it manually
- Update local_settings.py.qgis.sample
- Include static folder in .dockerignore

Fix QGIS Server settings sample

---

requirements.txt

Somewhere on the way, SQLAlchemy got into requirements.txt, from 
https://github.com/GeoNode/geonode/commit/17772e55c0eee6f361c4c373b7305b5a1df6a5a4#diff-b4ef698db8ca845e5845c4618278f29aR151
It looks it's not used anywhere. This PR cleans the situation.

removed unused sqlalchemy

---

geonode/settings.py

We don't need to distinct between docker env and regular env here. `ALLOWED_HOSTS` can be provided in any of supported form.

support for different notations of allowed_hosts env var

---

docs/tutorials/install_and_admin/vm_running_vagrant.txt

Hi, 
I´ve updated the vagrant tutorial for ubuntu_16.04 and added information regarding 
- private network setup, 
- memory
- shared folder between host and client. 
Personally I think it´s easier to show a example Vagrantfile instead of using vagrant init (which creates a bloated Vagrantfile). In case you want to stay with vagrant init I can change this part again.
Cheers,
Toni

Updated vagrant tutorial for Ubuntu 16.04

---

geonode/static/geonode/js/utils/thumbnail.js

partial backport (only thumbnail.js) from
https://github.com/GeoNode/geonode/commit/c5d7ea5bcd803186fec165fdc8e67989698736cf
698736cf#diff-7bfea77702d6821693ca6297dcec75b5
Fixes https://github.com/GeoNode/geonode/issues/3692

[backport 2.6.x] backport thumbnail fix

---

geonode/upload/upload_validators.py

Uploading a shapefile results in _IndexError: list index out of range_ for `shape_component = shp_files[0]` in the `def validate_shapefile_components(possible_filenames):`
Fixed this by adding the .shp file to the file_paths passed along (also tested for a zipped shapefile, this was already working correctly).

Add .shp file to file_paths for validate_shapefile_components

---

docs/tutorials/install_and_admin/geonode_install/install_geonode_application.txt
docs/tutorials/install_and_admin/geonode_install/install_geoserver_application.txt

This PR is based  #3754 
- apt install: libgdal-dev has been set twice 
- the documentation title says install **geonode 2.8** but as master is used one will currently end with 2.9 which can be missleading. I would suggest to  consistently stay with 2.8 (stable)
- I´ve extended the pip part comments for  installation of pygdal as this might be a hard step for not advanced users. as the user already opens requirements.txt I think it´s easiest to set the correct pygdal version in this step as well. As alternative I´m using [this](https://gist.github.com/t-book/ccc2f8d6e2c3b735e76c9b779152ee39) with vagrant but think it´s better to keep things simple and understandable for users in docs.
- the documentation is saying tomcat7 restart. which should be tomcat8 restart
that´s it.
cheers,
toni

#3754: corrected geonode Version. Fixed tomcat reference

---

setup.py

django-autocomplete-light 2.3.4 and lxml 3.8 throw exceptions (see below).
django-autocomplete-light 2.3.4
```
File "initialize.py", line 11, in <module>
django.setup()
File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
apps.populate(settings.INSTALLED_APPS)
File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
app_config = AppConfig.create(entry)
File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
module = import_module(entry)
File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
__import__(name)
File "/usr/local/lib/python2.7/site-packages/autocomplete_light/__init__.py", line 7, in <module>
from .shortcuts import *  # …
```

pin some incompatible python dependencies

---

geonode/contrib/monitoring/migrations/0022_service_last_check_default.py
geonode/contrib/monitoring/models.py

This will populate `last_check` fields in autoconfiguration. Otherwise, collector will not collect data.

populate service.last_check in monitoring in autoconfigure

---

geonode/contrib/monitoring/utils.py

This will enable monitoring collector to record requests from audit log API in GS in dockerized env. GN was expecting urls to request logs starting with url stated in `monitoring.models.Service.base_url`, but GS was returning public urls, which would fail the check.

do not check url from gs in monitoring

---

geonode/base/models.py

It seems connection was make through PUBLIC_LOCATION, while it's an internal call.
For some reason, this made the request very slow (>120s !!) on some dockerized setups.
I'm not sure this actually works to log in the user to geoserver though...

fix slow login/logout on certain circumstances

---

requirements.txt

This adds `geoip2` package so `django.contrib.gis.geoip2` module in django 1.11+ will work

use geoip2 for monitoring

---

geonode/messaging/consumer.py

This will catch errors in `geonode.geoserver.signal` handlers, so message can be acknowledged, and won't be repeated indefinitely in consumer.

catch geoserver error in messaging, to avoid looped delivery

---

requirements_tests.txt

We have Twisted test facilities introduced in test runner https://github.com/GeoNode/geonode/blob/master/geonode/tests/suite/runner.py#L9-L10
Dependency was introduced in https://github.com/GeoNode/geonode/commit/c0b298f69883d94875a4cc20dc34a447a9f879b5#diff-b4ef698db8ca845e5845c4618278f29aR160
but removed later in https://github.com/GeoNode/geonode/commit/3817491d9850fd6f8a0b207ac088afc93298663d#diff-b4ef698db8ca845e5845c4618278f29aL159
This reintroduces Twisted in requirements, but to avoid messing with main requirements, it's in tests-specific file.

test-specific requirements: twisted

---

scripts/docker/env/development/django.env
scripts/docker/env/production/django.env
tasks.py

… API by forcing to APV version 1.24
For more context please see:
https://github.com/geosolutions-it/geonode-generic/issues/28
and
https://github.com/geosolutions-it/geonode-generic/pull/29

Fix issues where docker client may be incompatible with docker server

---

tasks.py

Running docker-compose would fail.  It looks like it was just missing the import of the ast module.  I made that fix locally and everything worked correctly.  
Relevant output of the error message prior to the change is given below.  
NameError: global name 'ast' is not defined
File "/usr/local/bin/invoke", line 11, in <module>
sys.exit(program.run())
File "/usr/local/lib/python2.7/site-packages/invoke/program.py", line 293, in run
self.execute()
File "/usr/local/lib/python2.7/site-packages/invoke/program.py", line 414, in execute
executor.execute(*self.tasks)
File "/usr/local/lib/python2.7/site-packages/invoke/executor.py", line 129, in execute
result = call.task(*args, **call.kwargs)
File "/usr/local/lib/python2.7/site-packages/invoke/tasks.py", line …

add missing ast import

---

docs/organizational/contribute/README
docs/tutorials/install_and_admin/quick_install.txt
geonode/layers/templates/layers/layer_style_manage.html

The list of style name grows fast and it´s hard to find what one is looking for when managing styles. This PR suggests a search input to filter available style names by input.  Here is what you can expect: https://vimeo.com/279245798 
**Some thoughts.**
- The used library for the multiselect (http://loudev.com/) suggests to use a third party library to add search capabilites "Note: This feature is not built-in but depends on an other plugin. I personally use the excellent quicksearch library, but you can use whatever library you like." 
I´ve decided to not add another dependency but add functionalities with some lines of jquery. As it´s specific to the page the code has been added to the template file (and not to assets.js)
- Icon: Unfortunately the selector of the top search is nested …

added search input for styles to manage page

---

geonode/documents/templates/documents/document_detail.html

This commit restrict the use of "Edit document Button". Following permissions are tested:
- change_resourcebase_metadata OR
- change_resourcebase OR
- delete_resourcebase
It should solve issue: https://github.com/GeoNode/geonode/issues/3040

Restrict use of Edit Document Button

---

geonode/layers/utils.py
geonode/tests/integration.py

the original code failed in identifying srid for non 4326 vector layers.
this PR addresses the problem by calling `identify_epsg` function before `srs.srid` and adds some use cases.
the PR is used for the following use cases:
- layers with epsg:4326
- no problem at all.
- layers with epsg non 4326
- this is where the original code fails to identify the correct epsg code from the shapefile. this PR basically is to resolve this issue.
- layers without epsg, but has a valid projection definition
- none of the original code and this PR will work. 
we just check if the boundary is within the 4326. 
if so, then we assume it is a 4326.  
otherwise, we ask a user to upload a layer with an authoritative SRID

fix a srid bug when uploading vector layers

---

geonode/static/geonode/js/templates/cart.html

The left sided cart items (/layers + /maps) jump on hover. 
Adding a clearfix  causes the outer element to establish a new block formatting context for its floats, so it's able to expand to contain them and it´s items stop jumping on hover.

prevent change of height on cart item hover

---

geonode/layers/templates/layers/layer_detail.html

This is a very minor thing. Mostly a minor improvement to the layer_details template.
See #3942 for more details on this issue/improvement.

[Closes #3942] Make 'Edit data' link aware of the storeType

---

geonode/views.py

mimetype has been deprecated in Django 1.7, mimetype was replaced by content_type.

fix ident_json view

---

geonode/contrib/worldmap/wm_extra/views.py
geonode/settings.py

When using worldmap client we need geoserver layers to use gxp_gnsource vs gxp_wmscsource

[worldmap client] use gxp_gnsource in geoserver base map

---

dev_config.yml

The latest GeoServer 2.13 build has problems with uploading of shape files. In agreement with Alessio we restored an older working build. This can remain for 2.8 branch until the problem is fixed. See #4210 for more.

Restored older GeoServer Version #4120

---

scripts/spcgeonode/README.md

`exit 0` fails becaouse `exit` is not a command available (it is a valid shell builtin command). `true` instead can be found at `/usr/bin/true`.
```
$ man true | head -n4
TRUE(1)                                            User Commands                                           TRUE(1)
NAME
true - do nothing, successfully
```

Replace exit with a valid command

---

docker-compose.yml

changed the docker-compose.yml to use geonode/postgis:10
See my PR#1 https://github.com/GeoNode/postgis-docker/pull/1

Update PostgreSQL to v10.x

---

scripts/spcgeonode/django/docker-entrypoint.sh
scripts/spcgeonode/docker-compose.yml

Fix and complete https://github.com/GeoNode/geonode/pull/4208.
I am not sure of the logic behind it, but this is the smallest patch that makes possible again to upload layers in GeoNode.

Use geoserver instead of gs (partial revert)

---

docker-compose.yml
scripts/spcgeonode/docker-compose.yml

[RabbitMQ Dockerfile](https://github.com/docker-library/rabbitmq/blob/master/Dockerfile-alpine.template) contains a `VOLUME` command, thus creating a volume even if `docker-compose.yml` do not use it apparently. It is better to be aware of the existence of that volume to avoid further problems and permission issues with third party software (volumes created by containers have different permissions from the ones defined by the compose file in Portainer).

Add rabbitmq volume

---

scripts/spcgeonode/geoserver/docker-entrypoint.sh

Fix #4206 
It has been suggested that `gs` should be used instead, but regression tests in https://github.com/GeoNode/geonode-selenium show that it would not work at the moment.

Add suffix geoserver to BASEURL

---

scripts/spcgeonode/django/initialize.py
scripts/spcgeonode/geoserver/docker-entrypoint.sh

Instead of having multiple containers failing repeatedly as a normal procedure, this patch allows a clean start for geoserver and geonode, thus reducing resource usage and avoiding raising alarms in monitoring systems.

Wait for GeoServer and PostgreSQL instead of failing

---

scripts/spcgeonode/.env
scripts/spcgeonode/docker-compose.yml
scripts/spcgeonode/geoserver/docker-entrypoint.sh
scripts/spcgeonode/pgdumper/Dockerfile
scripts/spcgeonode/pgdumper/crontab
scripts/spcgeonode/pgdumper/docker-entrypoint.sh

This patch allows to setup a PostgreSQL password for SPC Geonode.
Password is not set by default (the variable is empty, thus avoiding breaking backwards compatibility), but if sets makes safer to expose Postgres port over the internal network (useful if a centralized backup system is in use).
@olivierdalang Do you know how to fix the pgdumper cron script to use an environmental variable for the password?

Setup Postgres password for SPC Geonode

---

scripts/spcgeonode/geoserver/docker-entrypoint.sh

> @frafra no matter if the certificate is valid or not, you need to add it to the java truststore in order to make GeoServer recognize it and avoid throwing that exception.
> 
> See if this [link ](https://docs.geoserver.org/stable/en/user/community/oauth2/index.html#ssl-trusted-certificates) might be helpful somehow.
https://github.com/GeoNode/geonode/issues/4232#issuecomment-465524029

Import SSL Certificate for GeoServer

---

.travis.yml
geonode/messaging/consumer.py
geonode/proxy/tests.py
geonode/proxy/views.py
pavement.py

I tested the modifications alone, but not the merged `.travis-ci.yml` file because I have issue with Travis CI (it says that my geonode repository is legacy, they do not support migration to the new system at the moment, so it seems that I cannot use it nor disable it).
This pull request fixes #4234.

Test with geonode-selenium

---

geonode/settings.py
requirements.txt

Removes unnecessary dependencies from the requirements.txt and settings.py files.  This PR is connected to issue https://github.com/GeoNode/geonode/issues/4255.  I verified that the tests pass locally.  They're also working on Travis CI now as well.
All of these dependencies were checked against the Python codebase to make sure they weren't being used, and the tests seem to agree.  I also did some manual smoke testing to make sure nothing was broken.  If the Travis CI tests show anything different, or if anyone sees a dependency they think we still need I'll take a look and add them back if necessary.

Removes Old Python Dependencies

---

scripts/spcgeonode/docker-compose.yml

This patch fixes this kind of errors, which result in a HTTP 502:
```
invalid request block size: 6871 (max 4096)...skip
invalid request block size: 6817 (max 4096)...skip
invalid request block size: 6824 (max 4096)...skip
invalid request block size: 6798 (max 4096)...skip
```

8 KB buffer for spc uwsgi

---

uwsgi.ini

Same as https://github.com/GeoNode/geonode/pull/4344 but for non-spc setups.

8 KB buffer for uwsgi

---

requirements_docs.txt

As #4348 describes read the docs is failing because of Shapely. I think it could be fixed by installing libgeos-dev before building. Anyways I do not see a way how to force read_the_docs to do so.
Hence I would comment Shapely and pycsw (shapely is a requirement) in requirements_docs.txt. (_I do not see a reason why those would be needed for sphinx._)
Closes: #4348

#4348 fix failing read_the_docs

---

geonode/layers/utils.py

I think there is a little bug in create_gs_thumbnail_geonode.
```
if local_bboxes:
for _bbox in local_bboxes:
if bbox is None:
bbox = _bbox
else:
if bbox[0] > _bbox[0]:
bbox[0] = _bbox[0]
[...]
``` 
Let´s say we save a map with several layers and bbox is None for the first.
_bbox will be assigned. In this case bbox is now a tuple looking something like
`['14.4841477044', '14.484949669', '40.750922921', '40.7518136301', 'EPSG:4326']
`
Now the next layer has a bbox and tries to update it which will fail with Error 500 as tuples are immutable
`TypeError at /maps/new/data 'tuple' object does not support item assignment`
My fix just converts the tuple to a list making it mutable if needed.
Closes: #4358

#4358 fix thumbnail creation with different bbox

---

geonode/services/templates/services/service_list.html

Missing quotes makes service page fail. This PR corrects it:
`<th>{% trans Type" %}</th>`
https://github.com/GeoNode/geonode/blob/master/geonode/services/templates/services/service_list.html#L17
Closes: #4374

Fixes: #4374, added missing quote to trans

---

geonode/people/templates/people/profile_detail.html
geonode/templates/base.html
geonode/templates/index.html

The current index page has minor issues regarding translations:
1. the base class which is used in body tag is used for styling. It shouldn't be translated otherwise the css selector will fail:
https://github.com/GeoNode/geonode/blob/master/geonode/templates/index.html#L8
2. the search box placeholder should be translated
https://github.com/GeoNode/geonode/blob/master/geonode/templates/index.html#L43
https://github.com/GeoNode/geonode/blob/master/geonode/templates/base.html#L294

Fixes: #4443 issues translations on index

---

geonode/base/models.py

Replace custom logic for generating media URLs in ResourceBase.save_thumbnail with call to Django File Storage's `.url` method, to support media file storages hosted remotely.
Fixes https://github.com/GeoNode/geonode/issues/4456

Use Django file storage API to construct media URL

---

.travis.yml

In order to fix the Selenium tests for the regular Docker setup, we are going to switch to a different GeoTIFF file. In order not to break the CI system, I will just add this new file first, before updating geonode-selenium.

Add new GeoTIFF for Travis CI (Fixes #4497)

---

setup.py

https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires
This would also allow Dependabot to figure out the Python version we are targeting and avoid proposing Python 3 only upgrades.

Use python_requires

---

docs/install/project/index.rst
docs/start/index.rst
docs/start/quick/index.rst

Dear @afabiani 
I've merged the two existing ansible docs into one and removed some parts (but referenced the ansible docs where needed). 
Further added a section about galaxy role geonode.geonode and an example playbook. As the ansible role targets geonode project, the docs make most sense under /install/project to me. In kind, you prefer them elsewhere no problem.
It would be nice too especially review the role and playbook part ( I use the official stack very rarely ).
For your convenience find here the PR-build:
http://csgis.de/2load/html/start/quick/index.html#install-via-ansible
http://csgis.de/2load/html/install/project/index.html#install-with-ansible

added ansible to docs

---

requirements.txt
scripts/spcgeonode/django/Dockerfile

This PR fixes: https://github.com/GeoNode/geonode/issues/4593
Short Version:
Following the manual a user will install pygdal. As pygdal set's the required Version for numpy loose like `numpy>=1.0.0` we will end with `numpy==1.17.*` which has no support for python 2.7. 
By pinning the version in requirements to `1.16.*` the installation will succeed. (Of course only if requirements are installed before pygdal which the docs already suggest)

Fix pygdal break with recent version of numpy

---

scripts/spcgeonode/letsencrypt/Dockerfile

For more information watch here : https://github.com/plesk/letsencrypt-plesk/issues/117
Before, error was like this : 
```
pkg_resources.ContextualVersionConflict: (cryptography 1.8.1 (/usr/lib/python2.7/site-packages), Requirement.parse('cryptography>=2.1.4'), set(['PyOpenSSL']))
```

Solve letsencrypt ssl error

---

scripts/spcgeonode/docker-compose.override.yml

solves #4603
The dev tags are no longer maintained and the whole spc images should be ported to geonode main docker hub in the future.

spc: switched to latest tags for override.yml

---

geonode/geoserver/createlayer/utils.py
geonode/geoserver/helpers.py
geonode/geoserver/management/commands/find_geoserver_broken_layers.py
geonode/geoserver/signals.py
geonode/geoserver/upload.py
geonode/local_settings.py.geoserver.sample
geonode/security/tests.py
geonode/services/serviceprocessors/wms.py
geonode/settings.py
geonode/tests/integration.py
geonode/upload/utils.py
geonode/utils.py
package/support/geonode.local_settings
requirements.txt

[Fixes #4639] Switch library "gsconfig" to "geoserver-restoconfig"

---

geonode/static/geonode/js/search/cart.js
geonode/static/geonode/js/status/main.js
geonode/static/geonode/js/upload/csv.js
geonode/static/geonode/js/upload/main.js
geonode/static/geonode/js/upload/srs.js
geonode/static/geonode/js/upload/time.js
geonode/static/geonode/js/utils/batch_ops.js
geonode/templates/base.html

Replaces manual generation of URLs for static assets in various templates
with using Django's `{% static %}` tag to retrieve the base URL for static
assets.
Fixes https://github.com/GeoNode/geonode/issues/3738

[Draft] Make templates use static url set by Django

---

geonode/tests/integration.py
requirements.txt

[Backports to 2.10.x] Update django-tastypie requirement from <=0.14.0 to <0.15.0

---

geonode/documents/tasks.py
geonode/geoserver/tasks.py
geonode/layers/tasks.py
geonode/maps/tasks.py
geonode/qgis_server/tasks/update.py
geonode/services/tasks.py
geonode/settings.py
geonode/tasks/tasks.py

```
Commits ["5d36229a00983d4a3cdc0907b959218993efc389","64c9ff49813cf36902426089aef978721c707da1"] could not be cherry-picked on top of 2.10.x
```
```bash
git fetch
git cherry-pick 5d36229a00983d4a3cdc0907b959218993efc389 64c9ff49813cf36902426089aef978721c707da1
git checkout -b backport-4817-to-2.10.x
git push --set-upstream origin backport-4817-to-2.10.x
cd ../..
```
Then, create a pull request where the `base` branch is `2.10.x` and the `compare`/`head` branch is `backport-4817-to-2.10.x`.

[Backport 4817 to 2.10.x] Removing a layer is broken - Celery error

---

geonode/layers/templates/layers/layer_detail.html
geonode/upload/tests/integration.py
geonode/upload/upload.py
geonode/upload/views.py

[Fixes #4831] GeoNode Importer mode not really asynchronous

---

requirements.txt

[Backport to 2.10.x] Backport requirements.txt to 2.10.x

---

scripts/spcgeonode/django/initialize.py
scripts/spcgeonode/docker-compose.yml
scripts/spcgeonode/nginx/spcgeonode.conf

Commits ["b97e0a10b99d18961a6afccc9e85fa7869bffb55","75c5f20146468822c032109cbe97812c8ea0f4e9","b2404d678bd7210327ec78a3970f968bb6afe84b","004f2c57973dfeaf0f0c6165647920748c95306c","c3b0e85a8bcc4ecfb162f4805fc474a5c3dfd66d","5bcbe01386a8fb1b1a4bdf46aebac59fccaa7862","1c95b48057d7e64085d0d0406f1f24d4242f4f24","b1e4db7245d3c29fa9fc4d744fa4d45066c66b9a","1989f7acac587129ba1a0e3af7682d11deca27c5","f5578602835a093e4813e7374fa8771556143395","0375aa46f8451bc388437562368391bbf2b981dd"] could not be cherry-picked on top of 2.10.x
git fetch
git cherry-pick b97e0a10b99d18961a6afccc9e85fa7869bffb55 75c5f20146468822c032109cbe97812c8ea0f4e9 …

[Backport 4573 to 2.10.x] Spcgeonode with mapstore2 and postgis

---

requirements.txt

- Install `pip install django-mapstore-adapter==1.0.6` instructions [Here](https://pypi.org/project/django-mapstore-adapter/1.0.6/)
- GeoNode MapStore client v1.4.0
- Based on [MapStore2 - v2019.02.00](https://github.com/geosolutions-it/MapStore2/releases/tag/v2019.02.00)
[GeoNode MapStore Adapter](https://github.com/GeoNode/django-mapstore-adapter/issues?q=is%3Aissue+is%3Aclosed+milestone%3A1.0.6) the list of issues solved.
[GeoNode MapStore Adapter](https://github.com/GeoNode/django-mapstore-adapter/pulls?q=is%3Apr+is%3Aclosed+milestone%3A1.0.6) the list of PR closed.
[MapStore2](https://github.com/geosolutions-it/MapStore2/issues?q=is%3Aissue+milestone%3A2019.02.00+is%3Aclosed) the list of MapStore2 issues solved.
---
<li> 2019-09-05: afabiani <a …

Bump django-mapstore-adapter from 1.0.5 to 1.0.6

---

requirements.txt

Bumps [django-mapstore-adapter ](https://github.com/GeoNode/django-mapstore-adapter) from1.0.6 to 1.0.7.
<details>
<summary>Commits</summary>
- 2019-09-09: afabiani <a href="https://github.com/GeoNode/django-mapstore-adapter/commit/cf3d57f661d0865cc06c6529d0cdc0267dc2b16e" target="blank"> [Fixes #6] geonode plugin center error: get_zoom() expects a GEOS Geometry with an SRID of 4326</a>
- See full diff in [compare view](https://github.com/GeoNode/django-mapstore-adapter/compare/v1.0.6...v1.0.7)
</details>
<br />

Bump django-mapstore-adapter from 1.0.6 to 1.0.7

---

requirements.txt

Bumps [gn-gsimporter](https://github.com/GeoNode/gsimporter) from1.0.10 to 1.0.12.
<details>
<summary>Commits</summary>
- [`ea90668b432f678e01eb3cc205eae9f1679db034`](https://github.com/GeoNode/gsimporter/commit/ea90668b432f678e01eb3cc205eae9f1679db034) - bump to version 1.0.12
- [`00d010d3444f97b190bb45386e4aa45997f0fe76`](https://github.com/GeoNode/gsimporter/commit/00d010d3444f97b190bb45386e4aa45997f0fe76) - [Fixes Regression] - Skip SSL Cert verification causes error with HTTP scheme
- See full diff in [compare view](https://github.com/GeoNode/gsimporter/compare/1.0.10...1.0.12)
</details>
<br />

Bump gn-gsimporter from 1.0.10 to 1.0.12

---

docs/intermediate/monitoring/api/index.rst
docs/intermediate/monitoring/user_analytics/index.rst
geonode/monitoring/admin.py
geonode/monitoring/collector.py
geonode/monitoring/tests/integration.py
geonode/monitoring/utils.py
geonode/monitoring/views.py

Commits ["b5763fe17b7ed2312d29405fea69c6a5cd7c0da2","b5b488b770ef5960459b48fe26be20b078a6c9d5","14482ee224fc111ed060a9af723055480a25e06c","df9c85892851ee24b0d469e020696c7174d43e82"] could not be cherry-picked on top of 2.10.x
git fetch
git cherry-pick b5763fe17b7ed2312d29405fea69c6a5cd7c0da2 b5b488b770ef5960459b48fe26be20b078a6c9d5 14482ee224fc111ed060a9af723055480a25e06c df9c85892851ee24b0d469e020696c7174d43e82
git checkout -b backport-4864-to-2.10.x
git push --set-upstream origin backport-4864-to-2.10.x
cd ../..
Then, create a pull request where the base branch is 2.10.x and the compare/head branch is …

[Backport 4864 to 2.10.x] [Fixes #4861] improved monitoring api filtering (#4864)

---

geonode/geoserver/helpers.py
geonode/tests/integration.py

Commits ["5dc3ef0a6478ead4ba5ce7ed0e6eb8f920514cfa","94574f42c0ccdc9a5334fc98419bb85a1166f14d"] could not be cherry-picked on top of 2.10.x
git fetch
git cherry-pick 5dc3ef0a6478ead4ba5ce7ed0e6eb8f920514cfa 94574f42c0ccdc9a5334fc98419bb85a1166f14d
git checkout -b backport-4868-to-2.10.x
git push --set-upstream origin backport-4868-to-2.10.x
cd ../..
Then, create a pull request where the base branch is 2.10.x and the compare/head branch is backport-4868-to-2.10.x.

[Backport 4868 to 2.10.x] [Fixes #4827] Line layer uploaded to GeoNode is rendered as point layer (#4868)

---

geonode/layers/templates/layers/layer_detail.html

Fixes: #4920
Code on page footer is missing script tag
- [] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)

[Fixes: #4920] Footer Display Code on Detail Layer pages

---

geonode/groups/forms.py
geonode/groups/templates/groups/group_members.html
geonode/groups/views.py

Commits ["28755ed905bd8c0dd446e878ad8b887e0c90247a"] could not be cherry-picked on top of 2.10.x
git fetch
git cherry-pick 28755ed905bd8c0dd446e878ad8b887e0c90247a
git checkout -b backport-4925-to-2.10.x
git push --set-upstream origin backport-4925-to-2.10.x
cd ../..
Then, create a pull request where the base branch is 2.10.x and the compare/head branch is backport-4925-to-2.10.x.

[Backport to 2.10.x][Fixes #4924] Add member to Group is broken

---

requirements.txt

Bump django-geonode-mapstore-client to 1.4.2

Bump django-mapstore-adapter to 1.0.8

---

docs/install/core/index.rst

Apache Tomcat 8.5 is updated to v8.5.46

Use Tomcat 8.5.46

---

geonode/static/geonode/js/search/cart.js

[Fixes #4954] only needed attributes added to cookie, when adding layer to cart

---

geonode/layers/templates/layers/layer_detail.html

I have chosen `if layer_type != "raster"` over `if layer_type == "vector"` as I do not know if there are other types (next to vector) to consider.
[Fixes: #4930]
[Closes: #4930]

[Fixes: #4930] Remove Edit Data button for RASTER layer

---

docs/basic/settings/index.rst
docs/basic/theme/index.rst
geonode/api/api.py
geonode/base/fixtures/profiles_test_data.json
geonode/groups/apps.py
geonode/groups/conf/__init__.py
geonode/groups/conf/settings.py
geonode/groups/models.py
geonode/groups/tests.py
geonode/locale/ar/LC_MESSAGES/django.po
geonode/locale/de/LC_MESSAGES/django.po
geonode/locale/el/LC_MESSAGES/django.po
geonode/locale/en/LC_MESSAGES/django.po
geonode/locale/fr/LC_MESSAGES/django.po
geonode/locale/it/LC_MESSAGES/django.po
geonode/people/models.py
geonode/templates/index.html
geonode/tests/bdd/conftest.py

* Fixes #1784
* Fixes #2161
* Fixes #2164
* Fixes #5052
This PR adds the following improvements to GeoNode Groups:
1. Hide "private" groups to "non-members"
The groups with access of type "private" won't be listed/visible to non-members at all.
2. A "superuser" can always "manage" a Group, despite it is a member or not
It won't be possible to exclude a "superuser" from a Group anymore.
3. "Registered Members" Group concept
By default, GeoNode will create a group called "Registered Members" allowing a resource owner to provide access to all members.
At login, GeoNode will check for active membership to this default group.
This group won't be accessible nor visible to anonymous users.

[Fixes #1784][Fixes #2161][Fixes #2164][Fixes #5052]

---

geonode/layers/templates/layers/layer_detail.html

- Fixes #4942 : Download layer filter not sending CQL filter anymore

[Fixes #4942] Download layer filter not sending CQL filter anymore

---

geonode/templates/invitations/forms/_invite.html

**Expected Behavior**
Sending an invitation shows just one message
**Actual Behavior**
Sending an invitation shows two messages, the second one misleading

[Fixes #4659] Double message on Submit invite users

---

docs/install/core/index.rst

Commits ["17cc5c767a4df811539e47395db0bbfd4e6fde03","0bb703c93dc2f4b8ef289b31e75c00b7736d48f1"] could not be cherry-picked on top of 2.10.x
git fetch
git cherry-pick 17cc5c767a4df811539e47395db0bbfd4e6fde03 0bb703c93dc2f4b8ef289b31e75c00b7736d48f1
git checkout -b backport-5074-to-2.10.x
git push --set-upstream origin backport-5074-to-2.10.x
cd ../..
Then, create a pull request where the base branch is 2.10.x and the compare/head branch is backport-5074-to-2.10.x.

Backport  5074 to 2.10.x

---

geonode/settings.py
pavement.py

Fixes #5096 : Disabling geonode.monitoring causes model exceptions on views

[Fixes #5096] Disabling geonode.monitoring causes model exceptions on views

---

geonode/templates/index.html

[Fixes #5089] Update index.html

---

geonode/catalogue/models.py
geonode/geoserver/helpers.py

- Fixes #4827 : Line layer uploaded to GeoNode is rendered as point layer

[Fixes #4827] Line layer uploaded to GeoNode is rendered as point layer

---

geonode/api/resourcebase_api.py

[Fixes #5121] ResourceBase API returns an error if a curated thumbnail img file is not existing anymore

[Fixes #5121] ResourceBase API returns an error if a curated thumbnail img file is not existing anymore

---

geonode/base/models.py
geonode/layers/tests.py
geonode/services/templates/services/service_detail.html

[Fixes #5137]
[Fixes #5138] 
Encode Hierarchical tags and external service

[Fixes #5137][Fixes #5138] Encode Hierarchical tags and external service

---

geonode/base/widgets.py

This will stop the error:   
```
File "/Users/ts/github/csgis.geonode/geonode/base/widgets.py", line 33, in __init__
autocomplete_light.MultipleChoiceWidget(
AttributeError: 'module' object has no attribute 'MultipleChoiceWidget'
```
From what I see `classautocomplete_light.MultipleChoiceWidget` is now
```
classautocomplete_light.widgets.MultipleChoiceWidget(autocomplete=None, widget_js_attributes=None, autocomplete_js_attributes=None, extra_context=None, registry=None, widget_template=None, widget_attrs=None, *args, **kwargs)
```
@afabiani @capooti this should fix the described issue however I would suggest that we continue here: https://github.com/GeoNode/geonode/issues/5158
The following are required only for core and extension modules (they are welcomed, but not required, for contrib …

[Fixes #5105] Error when using THESAURI

---

geonode/geoserver/tests/__init__.py
geonode/geoserver/tests/test_helpers.py
geonode/geoserver/tests/test_server.py
geonode/geoserver/upload.py
geonode/layers/utils.py
geonode/layers/views.py
geonode/static/geonode/js/upload/LayerInfo.js
geonode/tests/integration.py
geonode/upload/utils.py

The backport to 2.10.1 failed:
Commits ["a305f3218d57bbc15cea7a5cba531b401b74b5bf","f088a57855573b99e79289eb1e6eee119b3a7bc3"] could not be cherry-picked on top of 2.10.1
git fetch
git worktree add .worktrees/backport 2.10.1
git cherry-pick a305f3218d57bbc15cea7a5cba531b401b74b5bf f088a57855573b99e79289eb1e6eee119b3a7bc3
git checkout -b backport-5164-to-2.10.1
git push --set-upstream origin backport-5164-to-2.10.1
cd ../..
Then, create a pull request where the base branch is 2.10.1 and the compare/head branch is backport-5164-to-2.10.1.

Backport 5164 to 2.10.1

---

geonode/geoserver/tests/__init__.py
geonode/geoserver/tests/test_helpers.py
geonode/geoserver/tests/test_server.py
geonode/geoserver/upload.py
geonode/layers/utils.py
geonode/layers/views.py
geonode/static/geonode/js/upload/LayerInfo.js
geonode/tests/integration.py
geonode/upload/utils.py

The backport to 2.10.x failed:
Commits ["a305f3218d57bbc15cea7a5cba531b401b74b5bf","f088a57855573b99e79289eb1e6eee119b3a7bc3"] could not be cherry-picked on top of 2.10.x
git fetch
git cherry-pick a305f3218d57bbc15cea7a5cba531b401b74b5bf f088a57855573b99e79289eb1e6eee119b3a7bc3
git checkout -b backport-5164-to-2.10.x
git push --set-upstream origin backport-5164-to-2.10.x
cd ../..
Then, create a pull request where the base branch is 2.10.x and the compare/head branch is backport-5164-to-2.10.x.

Backport 5164 to 2.10.x

---

requirements.txt

- Fixes #5209 : MapStore client critical slow-down with latest Chrome updates

[Fixes #5209] MapStore client critical slow-down with latest Chrome updates

---

requirements.txt

Commits ["763c5ef085f5010f714711ddececb64fdfa6810e"] could not be cherry-picked on top of 2.10.1
git fetch
git worktree add .worktrees/backport 2.10.1
git cherry-pick 763c5ef085f5010f714711ddececb64fdfa6810e
git checkout -b backport-5211-to-2.10.1
git push --set-upstream origin backport-5211-to-2.10.1
cd ../..
Then, create a pull request where the base branch is 2.10.1 and the compare/head branch is backport-5211-to-2.10.1.

Backport 5211 to 2.10.1

---

geonode/monitoring/collector.py
geonode/monitoring/tests/integration.py

This PR fixes #5214 .
It avoids "None" elements in the countries list returned by the following endpoint:
`GET /monitoring/api/metric_data/request.country/`

[Fixes #5214] Fix regression on monitoring countries endpoint

---

geonode/base/models.py
geonode/base/tests.py

added __unicode__ functions for menu and menu items
**To reviewer: Should the __str__ functions be deleted, or shall they stay?**

[Fixes #5197] Admin Panel add Menu Item does not work for UTF-8 Characters

---

codecov.yml
geonode/layers/tests.py
geonode/layers/views.py
geonode/proxy/tests.py
geonode/version.py
pavement.py
requirements.txt

- Fixes #5223 : Layer details broken if no store identified

[Fixes #5223] Layer details broken if no store identified

---

codecov.yml
geonode/layers/tests.py
geonode/layers/views.py
geonode/proxy/tests.py
geonode/version.py
pavement.py
requirements.txt

The backport to 2.10.1 failed:
Commits ["0e37af02269101729cc3e409bd4977e79bc1c1a1"] could not be cherry-picked on top of 2.10.1
git fetch
git worktree add .worktrees/backport 2.10.1
git cherry-pick 0e37af02269101729cc3e409bd4977e79bc1c1a1
git checkout -b backport-5224-to-2.10.1
git push --set-upstream origin backport-5224-to-2.10.1
cd ../..
Then, create a pull request where the base branch is 2.10.1 and the compare/head branch is backport-5224-to-2.10.1.

[Backport to 2.10.1][Fixes #5223] Layer details broken if no store identified

---

codecov.yml
geonode/layers/tests.py
geonode/layers/views.py
geonode/proxy/tests.py
geonode/version.py
pavement.py
requirements.txt

The backport to 2.10.x failed:
Commits ["0e37af02269101729cc3e409bd4977e79bc1c1a1"] could not be cherry-picked on top of 2.10.x
git fetch
git cherry-pick 0e37af02269101729cc3e409bd4977e79bc1c1a1
git checkout -b backport-5224-to-2.10.x
git push --set-upstream origin backport-5224-to-2.10.x
cd ../..
Then, create a pull request where the base branch is 2.10.x and the compare/head branch is backport-5224-to-2.10.x.

[Backport 2.10.x][Fixes #5223] Layer details broken if no store identified

---

requirements.txt

Commits ["17357ae00727a48c150786e35a4909602e1d89fe"] could not be cherry-picked on top of 2.10.x
git fetch
git cherry-pick 17357ae00727a48c150786e35a4909602e1d89fe
git checkout -b backport-5266-to-2.10.x
git push --set-upstream origin backport-5266-to-2.10.x
cd ../..
Then, create a pull request where the base branch is 2.10.x and the compare/head branch is backport-5266-to-2.10.x.

[Backport 2.10.x] Update django-modeltranslation requirement

---

geonode/upload/upload.py
geonode/upload/views.py
requirements.txt

- Fixes #4635 : Encoding issues when uploading layers using a shapefile

[Fixes #4635] Encoding issues when uploading layers using a shapefile

---

geonode/geoserver/upload.py

- Fixes #5272 : Line layer uploaded to GeoNode is rendered as point layer

[Fixes #5272] Line layer uploaded to GeoNode is rendered as point layer

---

scripts/spcgeonode/letsencrypt/Dockerfile
scripts/spcgeonode/letsencrypt/docker-entrypoint.sh

ACME1 protocol has reached eol. 
We need to use ACME2 server to issue new certs.
therefore we need to update alpine image to use certbot with min version 0.22 and explicitly name the server (--server in entrypoint)
This should be done with geonode-project as well.
---

Fixes #5260 Failed to get the LE certificates with SPC

---

geonode/maps/qgis_server_views.py
geonode/qgis_server/helpers.py
geonode/qgis_server/signals.py
geonode/qgis_server/tasks/update.py
geonode/qgis_server/tests/test_helpers.py
geonode/qgis_server/views.py
requirements.txt

PR to bump Celery to 4.3.0 as outlined under https://github.com/GeoNode/geonode/issues/4276
Had to fix a number of Celery tasks that were previously expecting a `layers.Layer` or `maps.Map` instance, as instances cannot be serialised into json.
This PR supersedes #4628  …

[Issue #4276] Bump Celery to 4.3.0

---

geonode/templates/index.html

- Fixes #5325 : Improve Featured Datasets thumbs layout on main page

[Fixes #5325] Improve Featured Datasets thumbs layout on main page

---

geonode/api/api.py
geonode/api/resourcebase_api.py
geonode/api/tests.py

PR to update `api` app to be Python 2.7/3 cross-compatible as part of https://github.com/GeoNode/geonode/issues/4276.

[Issue #4276] Upgrade api for Python 2.7/3 compatibility

---

docs/basic/settings/index.rst
geonode/groups/tests.py
geonode/people/signals.py

- Fixes  #5335 : Auto assignment of users to "registered-members" group is not working under certain conditions

[Fixes  #5335] Auto assignment of users to "registered-members" group is not working under certain conditions

---

geonode/utils.py

- Issue #4276 : Upgrade geonode.utils for Python 2.7/3 compatibility

[Issue #4276] Upgrade geonode.utils for Python 2.7/3 compatibility

---

geonode/upload/files.py
geonode/upload/forms.py
geonode/upload/models.py
geonode/upload/tests/__init__.py
geonode/upload/tests/integration.py
geonode/upload/tests/test_settings.py
geonode/upload/upload.py
geonode/upload/utils.py
geonode/upload/views.py

PR to update `upload` app to be Python 2.7/3 cross-compatible as part of #4276.

[Issue #4276] Upgrade upload for Python 2.7/3 compatibility

---

geonode/favorite/models.py
geonode/favorite/utils.py
geonode/favorite/views.py

PR to update `favorite` app to be Python 2.7/3 cross-compatible as part of #4276.

[Issue #4276] Upgrade favorite for Python 2.7/3 compatibility

---

geonode/groups/templatetags/groups_tags.py
geonode/groups/tests.py

PR to update `groups` app to be Python 2.7/3 cross-compatible as part of #4276.

[Issue #4276] Upgrade groups for Python 2.7/3 compatibility

---

geonode/maps/autocomplete_light_registry.py
geonode/maps/management/commands/remove_broken_layers.py
geonode/maps/qgis_server_views.py
geonode/maps/tests.py
geonode/maps/utils.py
geonode/maps/views.py

PR to update `maps` app to be Python 2.7/3 cross-compatible as part of #4276.

[Issue #4276] Upgrade maps for Python 2.7/3 compatibility

---

geonode/messaging/consumer.py
geonode/messaging/producer.py

PR to update `messaging` app to be Python 2.7/3 cross-compatible as part of #4276.

[Issue #4276] Upgrade messaging for Python 2.7/3 compatibility

---

geonode/monitoring/__init__.py
geonode/monitoring/aggregation.py
geonode/monitoring/collector.py
geonode/monitoring/management/commands/collect_metrics.py
geonode/monitoring/management/commands/render_metrics.py
geonode/monitoring/middleware.py
geonode/monitoring/models.py
geonode/monitoring/probes.py
geonode/monitoring/tests/integration.py
geonode/monitoring/utils.py

PR to update `monitoring` app to be Python 2.7/3 cross-compatible as part of #4276.

[Issue #4276] Upgrade monitoring for Python 2.7/3 compatibility

---

geonode/layers/autocomplete_light_registry.py
geonode/layers/management/commands/importlayers.py
geonode/layers/models.py
geonode/layers/tests.py
geonode/layers/utils.py
geonode/layers/views.py

PR to update `layers` app to be Python 2.7/3 cross-compatible as part of #4276.

[Issue #4276] Upgrade layers for Python 2.7/3 compatibility

---

docs/basic/settings/index.rst
geonode/local_settings.py.geoserver.sample
geonode/settings.py

- Fixes #5366 : Sentinel Cloudless Background should use JPEG format rather than PNG

[Fixes #5366] Sentinel Cloudless Background should use JPEG format rather than PNG

---

geonode/geoserver/createlayer/utils.py
geonode/geoserver/helpers.py
geonode/geoserver/management/commands/find_geoserver_broken_layers.py
geonode/geoserver/management/commands/sync_geonode_layers.py
geonode/geoserver/management/commands/updatelayers.py
geonode/geoserver/ows.py
geonode/geoserver/views.py

PR to update `geoserver` app to be Python 2.7/3 cross-compatible as part of #4276.

[Issue #4276] Upgrade geoserver for Python 2.7/3 compatibility

---

geonode/qgis_server/gis_tools.py
geonode/qgis_server/helpers.py
geonode/qgis_server/management/commands/import_qgis_styles.py
geonode/qgis_server/tests/test_helpers.py
geonode/qgis_server/tests/test_management.py
geonode/qgis_server/tests/test_views.py
geonode/qgis_server/tests/test_xml_utilities.py
geonode/qgis_server/views.py
geonode/qgis_server/xml_utilities.py

PR to update `qgis_server` app to be Python 2.7/3 cross-compatible as part of #4276.

[Issue #4276] Upgrade qgis_server for Python 2.7/3 compatibility

---

geonode/services/management/commands/importservice.py
geonode/services/models.py
geonode/services/serviceprocessors/base.py
geonode/services/serviceprocessors/handler.py
geonode/services/serviceprocessors/wms.py
geonode/services/test_selenium.py
geonode/services/tests.py
geonode/services/views.py

PR to update `services` app to be Python 2.7/3 cross-compatible as part of #4276.

[Issue #4276] Upgrade services for Python 2.7/3 compatibility

---

geonode/decorators.py
geonode/middleware.py
geonode/settings.py
geonode/utils.py

PR to update the `geonode/` directory to be Python 2.7/3 cross-compatible as part of #4276.

[Issue #4276] Upgrade geonode for Python 2.7/3 compatibility

---

geonode/proxy/templatetags/proxy_lib_tags.py
geonode/proxy/tests.py
geonode/proxy/views.py

PR to update `proxy` app to be Python 2.7/3 cross-compatible as part of #4276.

[Issue #4276] Upgrade proxy for Python 2.7/3 compatibility

---

geonode/security/middleware.py
geonode/security/tests.py
geonode/security/utils.py
geonode/security/views.py

PR to update `security` app to be Python 2.7/3 cross-compatible as part of #4276.

[Issue #4276] Upgrade security for Python 2.7/3 compatibility

---

geonode/base/models.py
geonode/catalogue/views.py
geonode/documents/admin.py

- Fixes #5392 : [Performance] Put meaningful generic thumbs if thumbnail generation fails some some reason

[Fixes #5392][Performance] Put meaningful generic thumbs if thumbnail generation fails some some reason

---

.travis.yml
docs/install/core/index.rst
docs/install/project/index.rst
geonode/geoserver/helpers.py
geonode/geoserver/views.py
geonode/maps/models.py
geonode/maps/tests.py
geonode/utils.py
scripts/spcgeonode/django/Dockerfile

- Fixes #5429 : Layer feature info templates are not used inside maps

[Fixes #5429] Layer feature info templates are not used inside maps

---

docs/install/core/index.rst
geonode/layers/templates/layers/layer_detail.html
geonode/maps/templates/maps/map_detail.html

The backport to `2.10.x` failed:
```
The process 'git' failed with exit code 128
```
```bash
git fetch
git worktree add .worktrees/backport-2.10.x 2.10.x
cd .worktrees/backport-2.10.x
git switch --create backport-5474-to-2.10.x
git cherry-pick eac2b2cd0e07472f3ec58e05d9c7fff638986101
git push --set-upstream origin backport-5474-to-2.10.x
cd ../..
git worktree remove .worktrees/backport-2.10.x
```
Then, create a pull request where the `base` branch is `2.10.x` and the `compare`/`head` branch is `backport-5474-to-2.10.x`.

Backport 5474 to 2.10.x

---

geonode/layers/templates/layers/layer_detail.html

[Fixes #5416] LIKE filter on layer download tab doesn't let setting a pattern value
The backport to `2.10.x` failed:
```
The process 'git' failed with exit code 128
```
```bash
git fetch
git worktree add .worktrees/backport-2.10.x 2.10.x
cd .worktrees/backport-2.10.x
git switch --create backport-5417-to-2.10.x
git cherry-pick 46fdb0661ff74322da39932b904816d800cc7518
git push --set-upstream origin backport-5417-to-2.10.x
cd ../..
git worktree remove .worktrees/backport-2.10.x
```
Then, create a pull request where the `base` branch is `2.10.x` and the `compare`/`head` branch is `backport-5417-to-2.10.x`.

[Backport to 2.10.x][Fixes #5416] LIKE filter on layer download tab doesn't let setting a pattern value

---

geonode/layers/tests.py
geonode/layers/utils.py
geonode/layers/views.py

- [Fixes #5486] "resolve_object" get confused when present a remote layer with alternate similar to the local one

[Fixes #5486] "resolve_object" get confused when present a remote layer with alternate similar to the local one

---

geonode/geoserver/tests/test_helpers.py
geonode/geoserver/views.py

The backport to 2.10.x failed:
The process 'git' failed with exit code 128
git fetch
git worktree add .worktrees/backport-2.10.x 2.10.x
cd .worktrees/backport-2.10.x
git switch --create backport-5498-to-2.10.x
git cherry-pick 1d4b03759c9990993c2fd0a0a6ac2d81f0474422
git push --set-upstream origin backport-5498-to-2.10.x
cd ../..
git worktree remove .worktrees/backport-2.10.x
Then, create a pull request where the base branch is 2.10.x and the compare/head branch is backport-5498-to-2.10.x.

[Backport 2.10.x][Fixes #5497] W*S on QGis not authenticating

---

docs/install/core/index.rst

Following the instructions for the first time install a warning stating `mixed content` appeared.
Finally found out it was related to Gravatar because an environment variable was missing in the setup.
This PR adds it to the documentation so nobody will see the same error.

Fix mixed content when logged in

---

pavement.py

PR to stop geoserver using `psutil` instead of `os.kill` and sleeping as termination typically takes <30 seconds.

[Issue #5555] Improve speed of terminating geoserver

---

geonode/geoserver/helpers.py
geonode/layers/utils.py

Fix #5577. 
The `lxml.fromstring()` function is unable to parse XML documents with an encoding defined within the actual document and raises a 
` ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration`
The correct way to parse those XML documents is to load them as a bytes objects, which this PR implements. 
The following are required only for …

[Fixes #5577] Vector layer does NOT have geometry or any attributes

---

geonode/documents/renderers.py
geonode/geoserver/helpers.py
geonode/layers/views.py
geonode/security/tests.py

- [Fixes #5520] Change assertTrue to assertEqual to verify response content type value.

[Fixes #5520] Change assertTrue to assertEqual to verify response content type value.

---

geonode/geoserver/helpers.py
geonode/layers/management/commands/set_layers_permissions.py
geonode/layers/tests.py
geonode/layers/utils.py
geonode/security/models.py

- [Fixes #5599] set_layers_permissions duplicate assignment

[Fixes #5599] set_layers_permissions duplicate assignment

---

geonode/groups/models.py
geonode/groups/templates/groups/_group_list_item.html
geonode/groups/templates/groups/_group_profile_list_item.html
geonode/groups/templates/groups/group_detail.html
geonode/groups/templatetags/groups_tags.py
geonode/people/templates/people/profile_detail.html
geonode/templates/search/_group_snippet.html
requirements.txt

[Fixes #5593] Users Avatar and Groups Logo appear as broken img

[Fixes #5593] Users Avatar and Groups Logo appear as broken img

---

scripts/spcgeonode/django/initialize.py

This PR should avoid problems to users upgrading SPCGeoNode to newer GeoNode versions.
- [] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
flake8 fails, but not on the part of …

[Fixes #5646] Set skip_authorization for older setups

---

AUTHORS
geonode/groups/models.py
geonode/groups/views.py

THe change in this Pull Request makes sure that the membership is properly synchronized between GroupProfile and django.contrib.auth-groups. The logic of automatically adding a user to the django auth group, when he was added to a groupprofile was moved from the GroupProfile.join() to GroupMember.save(). The removal has been moved from groups.views.group_member_remove() to GroupMember.delete().
Now, it doesn't matter anymore if a user has been added to a groupprofile through the frontend or the django admin panel.
For …

[FIXES #5639] Group membership is ignored for layer permissions

---

geonode/base/models.py
geonode/layers/utils.py
geonode/security/utils.py
geonode/services/serviceprocessors/arcgis.py
geonode/services/serviceprocessors/wms.py

- Fixes #5682 : Thumbnails broken for RemoteServices using a invalid WMS GetCapabilities request

[Fixes #5682] Thumbnails broken for RemoteServices using a invalid WMS GetCapabilities request

---

.travis.yml
pyproject.toml
requirements.txt
setup.py

Fixes #5735
- pyproject.toml refers to setup.py
- add pip as dependency
- support for pip 20 is added in setup.py
- installing geonode from another directory is now possible
- Travis early fail + print commands (set -ex)
- Travis do not use system wide packages
- minor fix for black
This should allow GeoNode tu use pyproject.toml without having to switch to Poetry, which it would be nice but it would be better to do it later.
The following are required only for core and extension modules (they …

Fix CI and improve pyproject.toml/setup.py

---

pavement.py
scripts/backup-restore/backup.py
scripts/backup-restore/gn20_to_24.py
scripts/backup-restore/gn24_to_24.py
scripts/backup-restore/helpers.py
scripts/backup-restore/migrate_layers.py
scripts/backup-restore/restore.py
scripts/cloud/demo_site.py
scripts/cloud/ec2.py
scripts/cloud/fabfile.py
scripts/misc/create_full_geonode_db.py
scripts/spcgeonode/django/initialize.py

Fixing remaining files which had flake8 complaints.

flake8 updates

---

geonode/catalogue/templates/catalogue/full_metadata.xml

Adds DOI to ISO XML support for #5796 

add DOI support to ISO metadata (#5796)

---

geonode/templates/index.html

Excess width (240px) caused page to scroll horizontally and obscure the nav menu icon on mobile devices. Set to 100%.
Tested on Geonode 2.10.3 with chrome DevTools ("Samsung S5" setting).

Fixes issue #5839: Featured thumbnails on home too wide

---

manage.sh
scripts/docker/env/development/geoserver.env
scripts/docker/env/production/geoserver.env
tasks.py
uwsgi.ini

- Fixes #5868 : GeoNode core docker not setting correctly HTTP protocol and port

[Fixes #5868] GeoNode core docker not setting correctly HTTP protocol and port

---

geonode/base/management/commands/helpers.py

Restore error fix - restore procedure was not creating tables in Geoserver on PostGIS store.

[Fixes #5866] Restore errors

---

geonode/base/management/commands/delete_resources.py
geonode/base/tests.py

Management command removing certain resources (layers, maps, documents), based on django's Q() expressions.

[Fixes #5893] delete_resources management command

---

geonode/br/management/commands/restore.py
geonode/br/tasks.py

Add optional email notification for superusers about restore procedure outcome

[Fixes #5922] Send notification about restore procedure

---

geonode/br/management/commands/restore.py

Fix for notification sending on successful backup restoration

[Fixes #5929] Restore notification email is not sent on success

---

geonode/br/management/commands/backup.py
geonode/br/management/commands/restore.py
geonode/br/tests/__init__.py
geonode/br/tests/test_backup.py
geonode/br/tests/test_restore.py

By default backup and restore commands should set Gn into Read Only mode during the operations, and restore to previous state after that (if it was already in r/o mode it should remain as it was)
A new optional parameter should permit to switch this functionality off. …

[Fixes #5936] Backup/Restore with Read-Only mode

---

geonode/api/resourcebase_api.py
geonode/settings.py
geonode/static/geonode/js/search/search.js
geonode/templates/base.html
geonode/templates/index.html
geonode/templates/search/_text_filter.html
geonode/tests/test_search.py

FIX #5912
It extends resourcebase api to perform OR queries on given lookups. By default tastypie is combinig queries with **and** operator, **or** has to be requested by sending **f_method** parameter. 
On frontend side purpose and abstract lookups are added
New configuration is described here:
https://github.com/GeoNode/documentation/pull/20
#5912
The following are required only for core and extension modules (they are …

[Fixes #5912] Extend resource search api with abstract and purpose fields

---

geonode/version.py

This Pr fixes #5882
**Geonode populates the current version:**
https://github.com/GeoNode/geonode/blob/master/geonode/urls.py#L84
**and formats it to two or three decimals**
3.0 || 3.0.1 || ...
**Mapstore reads this enpoint to check the current version (in our case this is of no use!)**
https://github.com/geosolutions-it/MapStore2/blob/22bbfe82be2db71cd622d27bed457ccd41bb1332/web/client/actions/version.js#L42
**Mapstore will read the version as number in case it looks like f.e. `3`or `3.1` (which is the case when the patch number is zero). Further fail when using `indexOf` which is a string or array method.**
https://github.com/geosolutions-it/MapStore2/blob/22bbfe82be2db71cd622d27bed457ccd41bb1332/web/client/selectors/version.js#L10
---
**My fix removes the line which skips the patch …

Fixes #5882 Mapstore fails with version 3.0.0

---

docker-compose.yml
geonode/br/management/commands/restore.py

Restore: extracting backup archive in the directory accessible by `Geoserver` docker image.

[Fixes #5965] B/R: restoration in Docker

---

geonode/br/management/__init__.py
geonode/br/management/commands/__init__.py
geonode/br/management/commands/backup.py
geonode/br/management/commands/restore.py
geonode/br/management/commands/settings.ini
geonode/br/migrations/__init__.py

- Fixes #5975 : Geoserver backup sometime fails when running in Docker

[Fixes #5975] Geoserver backup sometime fails when running in Docker

---

geonode/base/management/commands/migrate_baseurl.py
geonode/base/models.py
geonode/documents/forms.py
geonode/documents/models.py
geonode/documents/templates/documents/document_detail.html
geonode/documents/tests.py
geonode/documents/views.py
geonode/geoserver/helpers.py
geonode/geoserver/signals.py
geonode/geoserver/tests/integration.py
geonode/groups/models.py
geonode/layers/forms.py
geonode/layers/tests.py
geonode/layers/utils.py
geonode/layers/views.py
geonode/maps/models.py
geonode/maps/templates/maps/map_detail.html
geonode/maps/tests.py
geonode/maps/views.py
geonode/messaging/producer.py
geonode/monitoring/tests/integration.py
geonode/proxy/views.py
geonode/security/models.py
geonode/security/utils.py
geonode/security/views.py
geonode/settings.py
geonode/social/signals.py
geonode/utils.py

- Fixes #5993 : Unexpected behavior of resource created under different RESOURCE_PUBLISHING setting

[Fixes #5993] Unexpected behavior of resource created under different RESOURCE_PUBLISHING setting

---

geonode/notifications_helper.py
geonode/social/signals.py
geonode/templates/pinax/notifications/email_body.txt

FIX #6001
Restrict recipients of comment notification just to resource owner and aministrator

[FIX #6001] Limit comment notifications

---

geonode/base/templatetags/user_messages.py
geonode/groups/templates/groups/group_members.html
geonode/messaging/views.py
geonode/templates/user_messages/_message_snippet.html
geonode/templates/user_messages/inbox.html

FIX [#6037 ]
Bug was caused by nested forms
Messages table is no longer part of rad/unread form . Now it contains hidden input for each tread in inbox, that input is processed on backed side 
Minor improvement in text bolding for unread messages  …

[6037] Fix double click to remove message

---

geonode/geoserver/createlayer/utils.py
geonode/geoserver/createlayer/views.py

[Fixes #6025][Fixes #6040] Error on click 'Create Layer'

---

scripts/spcgeonode/docker-compose.yml
scripts/spcgeonode/nginx/docker-entrypoint.sh
scripts/spcgeonode/nginx/nginx.conf.envsubst
scripts/spcgeonode/nginx/nginx.https.available.conf.envsubst

[Fixes #6048][SPCGeoNode] HTTPS_PORT not considered by envsubst

---

geonode/maps/tests.py
geonode/utils.py

[Fixes #6027] Use osm source as default source type for geoext

---

geonode/br/management/commands/backup.py
geonode/br/management/commands/restore.py
geonode/br/management/commands/utils/utils.py
geonode/br/tests/test_restore.py

- Fixes #6052 : [Backup/Restore] Improve the restore of folders on the base of backup filter settings

[Fixes #6052][Backup/Restore] Improve the restore of folders on the base of backup filter settings

---

geonode/geoserver/ows.py
geonode/geoserver/tests/test_server.py

- Fixes #6088 : WCS download links are wrong for WCS 2.0.1

[Fixes #6088] WCS download links are wrong for WCS 2.0.1

---

geonode/base/models.py
geonode/base/views.py
geonode/documents/tests.py
geonode/documents/views.py
geonode/geoserver/helpers.py
geonode/geoserver/views.py
geonode/layers/tests.py
geonode/layers/utils.py
geonode/layers/views.py
geonode/maps/models.py
geonode/maps/views.py
geonode/services/serviceprocessors/arcgis.py
geonode/services/serviceprocessors/wms.py
geonode/social/signals.py
geonode/tests/integration.py
geonode/upload/upload.py

- Fixes #6099 : Move triggering of notifications out of notification_sender signals for ResourceBase

[Fixes #6099] Move triggering of notifications out of notification_sender signals for ResourceBase

---

geonode/tests/test_utils.py
geonode/utils.py

During Backup and Restore filters are used to include/exclude certain content from the backup. When the geonode upload directory/other directories (e.g the static root, templates dir, etc) that have to be backed up contain content (files) that are at their root. The content is backed up irrespective of date-time filters by configured by "data_dt_filter".
**Submitting the PR …

[Fixes #6193] Geonode's "data_dt_filter" backup filter does not apply when a directory to be backed up contains files at it's root.

---

requirements.txt

Closes: 6201
Geoserver-rest-config .2 introduces a bug with many styles.

Fixes: 6201 Large amount of requests ending in a 502

---

geonode/singleton.py

FIX #6223  Just in case update kwargs of SingletonModel save to prevent new insertion to the db 

FIX [6223] Prevent integrity errors on singleton model 

---

geonode/layers/templates/layers/layer_detail.html
geonode/layers/tests.py
geonode/layers/views.py

Limite "maps using this layer" to maps the user has permission to see

[Fixes #6261] Limit "maps using this layer" to maps the user has permission to see

---

geonode/base/models.py
geonode/base/tests.py

Upload a Thumbnail broken when CACHE BUSTING is enabled

[Fixes #5721] Upload a Thumbnail broken when CACHE BUSTING is enabled

---

geonode/base/models.py
geonode/documents/tests.py

PR to perform thumbnail deletions using the Django file storage API.
Previously, `os.remove` was used to delete files from Django storage, which did not function correctly for remote storage as this is not implemented. This fix uses Django's `storage.delete` method instead which will work if the chosen storage plug-in implements it.
**Submitting the PR does not require you to …

[Issue #6414] Delete thumbnails using Django file storage API 

---

geonode/base/models.py
geonode/base/thumb_utils.py
geonode/base/utils.py
geonode/documents/renderers.py
geonode/documents/tasks.py
geonode/documents/tests.py
geonode/documents/utils.py
geonode/layers/utils.py
geonode/qgis_server/tests/test_helpers.py
geonode/qgis_server/tests/test_views.py
geonode/settings.py

Fixes #6414 
PR to replace file system operations performed using Python's `os`, `shutil` etc. library functions with the more generic [Django file storage API](https://docs.djangoproject.com/en/2.2/ref/files/storage/) function calls with the goal of supporting Django storage plugins such as [django-storage-swift](https://github.com/dennisv/django-storage-swift).
**Submitting …

[Issue #6414] File system operations do not adhere to Django file storage API

---

geonode/layers/templates/layers/layer_detail.html

[Fixes #6511] Missing features in filter in layer download view
In case of dealing with labeled attribute in the filter section of download, view dropdown is not displayed. This is caused by using improper key for data response

[Fixes #6511] Missing features in filter in layer download view

---

geonode/documents/views.py
geonode/groups/tests.py
geonode/groups/views.py
geonode/layers/views.py
geonode/maps/views.py
geonode/people/adapters.py
geonode/tests/test_rest_api.py
geonode/views.py

[Fixes #5801] Check User permissions for private group

---

geonode/layers/templates/layers/layer_list.html
geonode/layers/templates/layers/layer_list_default.html

The Style tag is rendered outside the html DOM
```
toni@base:~/$ curl  https://master.demo.geonode.org/layers/?limit=5 | head -n40 > /tmp/test; cat /tmp/test; rm /tmp/test
```
```
<style>
#paneltbar {
margin-top: 90px !important;
}
</style>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
```
**This PR will fix it. However. I could not find an Element with ID #paneltbar. there is a chance that this is obsolete at all**
The …

[Fixes: #6640] Style Tag outside of html

---

scripts/spcgeonode/.env
scripts/spcgeonode/docker-compose.yml
scripts/spcgeonode/geoserver/Dockerfile
scripts/spcgeonode/geoserver/docker-entrypoint.sh

Fixes and issue with SPC GeoServer running out of Memory because it was using default JVM startup options 
```
org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.client.OAuth2RestTemplate]: Factory method 'geoServerOauth2RestTemplate' threw exception; nested exception is java.lang.OutOfMemoryError: Java heap space
````

Fix startup JVM options for SPC Docker GeoServer

---

scripts/spcgeonode/django/Dockerfile

This PR modifies the spcgeonode `Dockerfile` for django to add `git` as an additional system dependency. This shall fix #6728

[Fixes #6728] SPCGeoNode Dockerfile build error - missing git

---

geonode/layers/templates/layers/layer_detail.html

This PR will stop showing image download formats for vector files and instead give auth users the possibility to request download permissions.

[Fixes #6742] request download permission not shown

---

geonode/notifications_helper.py

Sorry to spam with so many notifications related PRs. I just discover little regressions on my way to use the moderation workflow. Should have tested everything first and maybe merged some of the changes.
So, this will allow approved and published notification to get sent with pinax. Before this code changes the owner will get marked as an excluded user in the list. …

[FIXES #6782] Approval notifications will not get send

---

geonode/layers/templates/layers/layer_style_upload.html
geonode/layers/tests.py

[Fixes #6866] What is the effect of assigning permissions to styles?

---

geonode/geoserver/tasks.py
geonode/geoserver/tests/test_server.py
geonode/layers/utils.py

This is also related to https://github.com/GeoNode/django-mapstore-adapter/commit/bd0250b6588b843f33a1da8aafd3b0504bb14f0b

[Fixes #6895] Correcly catching thumbnail async task errors

---

geonode/base/templates/base/_resourcebase_snippet.html
geonode/templates/search/_search_content.html

[Fixes #6914] Remove "add to basket" tool for documents and maps

---

geonode/documents/views.py

This PR will use the slugified document title to create the filename for downloads.

[Fixes #6910] meaningful filename for document download

---

geonode/settings.py
geonode/tests/smoke.py

GEOSERVER_LOCATION requires to end with trailing slash other wise it will raise an error which can't be explained.
```
gsimporter.api.NotFound
ERROR 2021-02-01 15:54:28,314 upload 1 139829203416832 Error creating import session
File "/usr/local/lib/python3.8/site-packages/geonode/upload/upload.py", line 305, in save_step
next_id = _get_next_id()
File "/usr/local/lib/python3.8/site-packages/geonode/upload/upload.py", line 228, in _get_next_id
importer_sessions = gs_uploader.get_sessions()
File "/usr/local/lib/python3.8/site-packages/gsimporter/client.py", line 47, in get_sessions
return self._call(self.client.get_imports)
File "/usr/local/lib/python3.8/site-packages/gsimporter/client.py", line 34, in _call
robj = fun(*args)
File …
```

[Fixes #6916] gsimporter.api.NotFound caused by missing trailing slash at the end of GEOSERVER_LOCATION

---

.circleci/config.yml
geonode/geoserver/helpers.py
geonode/messaging/notifications.py
geonode/notifications_helper.py
geonode/tests/test_message_notifications.py
geonode/tests/test_search.py
geonode/tests/test_utils.py
geonode/tests/utils.py

[Fixes #6957] Duplicated registered attributes in GeoNode - and Update sttributes can't fix it

---

geonode/base/api/serializers.py
geonode/base/api/tests.py
geonode/base/models.py
geonode/documents/api/tests.py
geonode/geoapps/api/tests.py
geonode/geoapps/models.py
geonode/layers/api/tests.py
geonode/layers/models.py
geonode/maps/api/tests.py
geonode/maps/models.py

[Fixes #6955][REST API v2] Expose 'embed urls' of the concrete resources

---

geonode/catalogue/backends/pycsw_local.py
geonode/tests/csw.py

[Fixes #6960] Remove the "published" filter from CSW catalogue

---

geonode/base/admin.py
geonode/base/models.py
geonode/layers/admin.py

Add admin pages for Thesaurus, ThesaurusKeyword and related localized tables.

[Issue #6925] Thesaurus admin pages

---

geonode/base/models.py
geonode/base/thumb_utils.py
geonode/geoserver/tasks.py
geonode/layers/forms.py
geonode/layers/utils.py
geonode/proxy/views.py
geonode/upload/utils.py
geonode/upload/views.py
geonode/utils.py

This PR includes a small series of minor improvements and fixes as described here below:
- Make `is_monochromatic_image` able to fetch local thumbs instead of querying URL anytime: this is a performance improvement; if the method recognizes that the thumbnail url is pointing to a local file, it will fetch it from the local storage instead of getting the stream from the URL. This also resolves a potential issue with NATted instances.
- Create "tempdirs" under "settings.STATIC_ROOT" in order to make sure containers share the same folder: when running docker containers in `ASYNC` mode, if the `/tmp` folder is not shared between `django` and `celery` containers, the latter won't be able to retrieve the uploaded auxiliary files. By creating the `/tmp` folder under the `STATIC_FOLDER` fixes the …

Assorted minor performance issues

---

geonode/context_processors.py
geonode/layers/templates/layouts/panels.html
geonode/templates/metadata_form_js.html

In order to fix issue #7033 regarding the mandatory fields in the editor, I want to introduce new settings named `` which will set on UI the fields mandatory based on the settings list. 
By default, all fields will stay optional.
NOTE: as most of the geonode fields, the mandatory is just from UI perspective
PR for documentation is available here => https://github.com/GeoNode/documentation/pull/84
The following are required only for core and extension modules (they are welcomed, but not required, …

[Fixes: #7033] Mandatory fields in editor

---

geonode/layers/templates/layers/layer_metadata_advanced.html
geonode/locale/it/LC_MESSAGES/django.po
geonode/templates/metadata_base.html
geonode/templates/metadata_form_js.html

In order to fix bug #7034 I added a little check on form-submit where:
1. finds for all mandatory fields via `Django-form` (which are the ones with `required=True`)
2. if there is at least 1 element required which is not filled will show a `modal `with the information of the errors, plus a `console.error`
NOTE: this fix is implemented in both `Wizard` and `Advanced Edit` …

[Backport to 3.2.x][Fixes: #7034] Metadata UI freezes on empty mandatory fields

---

geonode/templates/metadata_form_js.html

Small bugifix related to #7033 the class names were incorrect
- [x The issue connected to the PR must have Labels and Milestone assigned

[Fixes #7033] fix header tab classes

---

geonode/api/api.py
geonode/api/tests.py
geonode/templates/search/_t_keywords_filter.html

With this PR I want to:
- Fix facets for Thesauri in order to return the translated keywords label (if exists) otherwise return the alt_label of the keyword. (At the moment if the translation does not exist, the keyword is not shown)
- Add tests coverage for resource `thesaurus/keywords`
- Remove the label `Thesaurus:` from the facet to make it lighter than before …

[Fixes: #6925] Thesauri improvements

---

geonode/geoserver/helpers.py
geonode/geoserver/tasks.py
geonode/security/tests.py
geonode/tests/integration.py

(cherry picked from commit 4c86d15b0e1180513fc29fcd9297948eb623fef7)

[Backport to 3.2.x][Fixes #7051] GeoServer will create three styles instead of one

---

geonode/security/middleware.py
geonode/security/tests.py

Enable to set `LOCKDOWN_GEONODE` with a custom login view. `LoginRequiredMiddleware` did not include `LOGIN_URL` in whitelisted URLs, causing infinite redirection loop, in case where `LOGIN_URL` didn't point at `account_login` view. Additionally, made sure, that following `LOGIN_URL` formats are supported by `LoginRequiredMiddleware`:
- `/path/to/login`
- `path/to/login`
- `<full site URL>/path/to/login` …

[Fixes #7075] LOCKDOWN mode with custom login view

---

geonode/layers/templates/layers/layer_metadata_advanced.html

References: ISSUE #6995
With this PR i want to continue the work related to the addition of the `block` tags in geonode template.
In this PR i add the blocks to `layer_metadata_advanced.html`

[Fixes #6995] Extending Geonode Template

---

geonode/base/models.py
geonode/base/tests.py
geonode/catalogue/templates/geonode_metadata_full.html

[Backport to 3.1.x  #7105] Remove HTML tags from metadata detail

[Backport to 3.1.x #7105] Remove HTML tags from metadata detail

---

geonode/catalogue/views.py

The GetCapabilities operation should return the proper URLs for the various operation, so we need a way to alter the pyCSW configuration to provide the redefined URL.
We're adding a parameter `config_updater=None` providing the function that alters the configuration in order to provide the redefined URL.
**Submitting the PR does not require you to check all items, but by the …

[Fixes #7118] CSW prefiltering URLs

---

geonode/catalogue/views.py

The GetCapabilities operation should return the proper URLs for the various operation, so we need a way to alter the pyCSW configuration to provide the redefined URL.
We're adding a parameter config_updater=None providing the function that alters the configuration in order to provide the redefined URL.
**Submitting the PR does not require you to check all items, but by the …

[Backport to 3.2.x][Fixes #7118] CSW prefiltering URLs

---

geonode/base/fixtures/test_thesaurus.json
geonode/base/forms.py
geonode/base/tests.py
geonode/context_processors.py
geonode/locale/it/LC_MESSAGES/django.po
geonode/templates/metadata_base.html
geonode/templates/metadata_form_js.html

In order to fix the issue #7101 :
- now the `$('#preview_tab').on('show.bs.tab')` event, will block the user with a warning modal by warning him that  some required field is missing by using `preventDefault();`
A field is considered required if match with this code;
```javascript
$( ':input[required]').each( function () {
if ( this.value.trim() == '' ) {
errors.push(this.id)
}
});
```
- Change the behavior of the Thesaurus item from `required` in Django-form to `required` from a UI point of view (like the other fields as commented [here](https://github.com/GeoNode/geonode/issues/7095#issuecomment-802010017)) 
-  Re-add `.vscode` to gitignore
- Add `REQ_THESAURI` to context processor in order to dynamically assign required classes in UI for the thesaurus
- Fix thesaurus tests with the new …

[Backport #7101] Error in preview

---

geonode/br/management/commands/utils/utils.py

With this PR i want to:
- wrap table name in double-quotes to let postgres manage the table in uppercase/lowercase/camelcase without drop "missing table" error

[Backport 3.1.x][Fixes #7164] restore does not delete table in uppercase/camelcase

---

geonode/br/management/commands/restore.py
geonode/br/management/commands/utils/utils.py

[Fixes #7164] BK_BEST_EFFORT always true

---

geonode/base/admin.py
geonode/base/forms.py
geonode/base/templates/admin/thesauri/change_list.html
geonode/base/templates/admin/thesauri/upload_form.html

In order to change the way to upload the thesaurus, with this PR i want to:
- Change `ThesaurusAdmin` in order to add a custom URL with the `upload` feature
- Custom template for upload (extended from `admin/base.html`)
- `import_rdf` function in `ThesaurusAdmin` which call the management command `upload_thesaurus` to perform the upload via web
PR Documentantion -> https://github.com/GeoNode/documentation/pull/88
The following are required only for core and extension modules (they are welcomed, …

[Backport Fixes #7150] Thesaurus from web

---

geonode/geoserver/tests/test_server.py
geonode/geoserver/views.py
geonode/security/models.py
geonode/security/tests.py

References #7109
Adds a check for the read-only mode to edit-features

[Fixes #7109] Disable edit permissions globally when read-only mode is active

---

geonode/base/populate_test_data.py
geonode/layers/templates/layers/layer_append.html
geonode/layers/templates/layers/layer_detail.html
geonode/layers/tests.py
geonode/layers/urls.py
geonode/layers/utils.py
geonode/layers/views.py

In order to resolve #7194 with this pr I want to:
- Creating new HTML for `layer_append` and his `view`
- New helper utility for the tests named `create_single_layer `for create only a single layer instead of the 10 created by `GeoNodeBaseTestSupport`
- New validation function for `layer_append `& `layer_replace` named `validate_input_source` which will check for the compatibility between the layer in upload and the information in the catalog. (with tests)
This will check the attributes of the uploaded file and the GS catalog:
```python
new_schema_fields = [field.name for field in lyr.schema]
gs_layer = gs_catalog.get_layer(layer.name)
if not gs_layer:
raise Exception(
_("The selected Layer does not exists in the catalog."))
gs_layer = gs_layer.resource.attributes
schema_is_compliant = …
```

[Fixes #7194] Append data to an existing layer 

---

geonode/thumbs/tests/test_unit.py
geonode/thumbs/thumbnails.py
geonode/thumbs/utils.py

Refers: ISSUE #7292
Implemented solution
- for generating a default thumbnail (thumbnail generated in `EPSG:3857`; BBOX retrieved from `layer.bbox` of an instance), cropping the BBOX to the `EPSG:3857`'s area of use was introduced to ensure correct CRS transformations
- for the default thumbnail's CRS (`EPSG:3857`), the flow for BBOXes provided in `EPSG:3857` was preserved
- for the default thumbnail's CRS (`EPSG:3857`), for BBOXes provided in CRSs different from `EPSG:3857` an additional check was introduced, forcing the crop of the overflowing coordinates to `EPSG:3857`'s area of use
- for forced thumbnail's CRS (different from `EPSG:3857`; by default used in layers from external services), and additional check was introduced, turning off thumbnail's ratio preservation, in case of …

[Fixes #7292] Thumbnail failure when data bbox extends beyond the are a of use of EPSG:3857

---

geonode/client/templates/ol/layers/layer_ol2_map.html
geonode/client/templates/ol/maps/map_ol2.html

References: #7312
The widget still uses the deprecated 900913, which most part of external services don't support anymore. This PR replaces it with EPSG:3857

[Fixes #7312] Replace EPSG:900913 with EPSG:3857 inside metadata wizard's thumbnail widget

---

geonode/thumbs/thumbnails.py

(cherry picked from commit d263fa4fdbedb7a5d20488addfe90da6ca54c81c)

[Backport to 3.2.x][Fixes #7336] Thumbnail generation fails for remote services (#7345)

---

geonode/services/serviceprocessors/arcgis.py

References: #7369
Unsupported thumbnail creation removal for ESRI layers (fix for code clarity).

[Fixes #7369] Thumbnail error for arcgis layers

---

geonode/base/migrations/0045_auto_20200507_0445.py

Fixes #7342 Migration breaks layers

---

geonode/maps/models.py

cherry-picked from https://github.com/GeoNode/geonode/commit/190e5f0939c3e89eca1d2dcd16f79cd867fba3a9

[Backport to 3.2.x][Fixes #7367] Error when Map Legend tries to read the name of the default style for a layer

---

Dockerfile

* GDAL upgrade to issue wtih postgres 12 and higher https://github.com/OSGeo/gdal/issues/1692
* add bullseye to source list to get GDAL 3.2.1 instead of compiling it.
(cherry picked from commit 5f45545ea6c9e498b155d14281d6be1de7fb85c4)
**Submitting the PR does not require you to check all items, but …

[Backport to 3.2.x][Fixes #7362] GDAL upgrade to issue wtih postgres 12 and higher  (#7363)

---

geonode/api/api.py

References: #7393
Fixes json count for geoapps owners.

[Fixes  #7393] Geoapp filters return values from the first geostory only

---

geonode/geoserver/helpers.py
geonode/geoserver/views.py

[Fixes #7390] Fix parsing of style title from UserStyle.Title element

---

geonode/base/management/commands/dump_thesaurus.py

Add a command to export a thesaurus.
```
$ python manage.py dump_thesaurus --help
usage: manage.py dump_thesaurus [-h] [--name NAME] [-l] [--version]
[-v {0,1,2,3}] [--settings SETTINGS]
[--pythonpath PYTHONPATH] [--traceback]
[--no-color] [--force-color]
Dump a thesaurus in RDF format
optional arguments:
-h, --help            show this help message and exit
--name NAME           Dump the thesaurus with the given name
-l, --list            List available thesauri
[...other standard options...]
```
```
$ python manage.py dump_thesaurus --list
LISTING THESAURI
id: 2 sort:  0 DISABLED name=ConditionsApplyingToAccessAndUse title="Conditions Applying To Access and Use" URI:http://inspire.ec.europa.eu/metadata-codelist/ConditionsApplyingToAccessAndUse
id: 1 sort:  0 DISABLED …
```

[Resolves #7375][Backport 3.2.x] Export thesauri

---

geonode/base/api/tests.py
geonode/base/api/views.py
geonode/services/serviceprocessors/arcgis.py
geonode/services/serviceprocessors/wms.py
geonode/services/tests.py

References: #7442
- Creates remote services with resource_type and metadata_only=True
- Removes service from resource_types api
vice should not be returned in list of services

[Fixes #7442] Missing information for remote layers

---

.circleci/config.yml
geonode/base/populate_test_data.py
geonode/catalogue/backends/pycsw_plugin.py
geonode/catalogue/backends/tests.py

References: #7441
With this PR i want to:
- Add test helper utility in order to create a single `Map` or `Document`
- Set new `pycsw_filters` in `GeoNodeRepository` with default value as `{'resource_type__in': ['layer']}`
- Tests in order to validate the method …

[Resolves #7441] Handle configuration for CSW pre-filtering

---

geonode/api/tests.py
geonode/base/fixtures/test_thesaurus.json
geonode/base/models.py
geonode/base/tests.py

References: #7429
- Add function `generate_thesaurus_reference` as `post_save` in order to generate the `about`  based on the specification provided into the issue #7429 
- Add new items in the test thesaurus json
- Test coverage for the new function …

[Fixes #7429] Null references in thesauri items

---

geonode/security/models.py

[Fixes  #7494] "set permissions" operations should be done inside an atomic transaction

---

geonode/services/migrations/0042_update_metadata_only.py

(cherry picked from commit 4811e71e09572409e77baca71b1fb89a9ea7832d)

[Backport 3.2.x][Fixes #7536] Migration to update existing services with metadata_only=True

---

geonode/geoapps/api/tests.py
geonode/geoserver/tasks.py
geonode/layers/tests.py
geonode/security/utils.py
geonode/tests/utils.py
geonode/upload/tests/integration.py

[Fixes #7557] Permissions set during the upload are lost

---

geonode/geoapps/api/tests.py
geonode/geoserver/tasks.py
geonode/layers/tests.py
geonode/security/utils.py
geonode/tests/utils.py
geonode/upload/tests/integration.py

* update layer with perms set on upload
* - Add unit tests
* fix lgtm
* - fix failing tests
* remove unused function
(cherry picked from commit 6ee01f8f889bdb29e0dbe0d6f9f0f6a28ff4981c) …

[Backport to 3.2.x][Fixes #7557] Permissions set during the upload are lost (#7563)

---

geonode/templates/base.html

This PR fix the problem with the source of `boostrap-rtl-min.css` which is actually RawGit and RawGit has reached the end of its useful life according to corresponding website (https://rawgit.com/)
The PR replace the RawGit source by source available at `https://cdnjs.com/libraries/bootstrap-rtl/3.3.4` and which is `https://cdnjs.cloudflare.com/ajax/libs/bootstrap-rtl/3.3.4/css/bootstrap-rtl.min.css`
This CSS is only needed for LTR languages like arabic.
The following are required only for core …

[Fixes #7562] Change bootstrap-rtl css source to cloudflare

---

geonode/geoserver/tasks.py
geonode/tests/integration.py

[Fixes #7525] Remove Geoserver keywords at layer creation time

---

geonode/geoserver/tasks.py
geonode/tests/integration.py

(cherry picked from commit f484ba365e3fbc6bb11d826dbe363f106b6cb90b)

[Backport to 3.2.x] [Fixes #7525] Remove Geoserver keywords at layer creation time

---

geonode/services/serviceprocessors/wms.py
geonode/services/tests.py
geonode/utils.py

[Fixes #7603] RemoteServices legend urls do not contain 'sld_service' param

---

geonode/utils.py

This PR fixes a slow upload behaviour in case a geonode instance has a lot of raster datastores (several thousands) in geoserver. For a user this results in a bad experience as the upload bar is stuck at 80%. My fix favours first a search with all attributes and if nothing is found a general search without the store.
Further Background:
#7618 
https://lists.osgeo.org/pipermail/geonode-devel/2021-May/003254.html
The following are required only for core and extension modules (they are welcomed, but …

[Fixes: GeoNode#7618] Very slow upload on large instance

---

geonode/documents/templates/layouts/doc_panels.html
geonode/geoapps/templates/layouts/app_panels.html

References: #7638
The thumbnail widget inside the metadata wizard is broken.
Showing by default the `thumbnail_url` if the `curated thumbnail` is not available

[Fixes #7638] thumbnail widget inside the metadata wizard is broken

---

geonode/base/api/serializers.py
geonode/base/api/views.py
geonode/favorite/models.py
geonode/favorite/tests.py

References: #7644
From the `api/v2/resources/{id}/favorite` endpoint, the `content_type` of the resource is set as `resourcebase` in the favorite table, while from the Layer/Document/app table, is correctly assigned -> `['document', 'geostory', 'map', 'layer']`
So this means that the `FavoriteFilter` when is called, filter for the `resource_type` available in the queryset (for reducing the weight of the query)
With this PR I want to assign the correct subtype of the resource even if a `resourcebase` is sent to the favorite creation
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with …

[Fixes #7644] Api - filter favorite in /resources endpoint doesn't return all favorites item

---

geonode/base/views.py

Add filters for searched value.
- If is a keyword label we use ORM in order to filter the results required
- if not (this means that the lable does not exists for the selected language), just check if the letters are contained in the keyword label
- In case of both are not true, the keyword will be excluded from the results
**Submitting the PR does not require you to check …

[Fixes #7676] Search by thesauri items fails

---

geonode/base/templates/base/_resourcebase_snippet.html

References: #7679
Truncate abstract at 300 chars

[Fixes #7679] Abstract not truncated in resource list

---

geonode/thumbs/thumbnails.py
geonode/thumbs/utils.py

[Fixes #7675] Problem creating thumbnail

---

geonode/documents/api/tests.py
geonode/documents/models.py

[Fixes #7741] Expose document link as embed_url inside API v2 response

---

geonode/documents/api/tests.py
geonode/documents/models.py

(cherry picked from commit dcaaed932b37131b0ce37a15b8641111d9f21106)

[Backport to 3.2.x] [Fixes #7741] Expose document link as embed_url inside API v2 response

---

geonode/base/api/tests.py
geonode/base/views.py
geonode/documents/api/tests.py
geonode/geoapps/api/tests.py
geonode/layers/api/tests.py
geonode/maps/api/tests.py
geonode/people/forms.py

References: #7795
Remove defined urls in tests file, importing geonode.urls.
Waiting for circleCI feedback

[Fixes #7795] URL tests use own URLs 

---

geonode/settings.py

Fix parsing of  `DEFAULT_MAP_CENTER_X` and `DEFAULT_MAP_CENTER_Y` in setting.py.
See #7809.

[Fixes #7809][3.2.x] DEFAULT_MAP_CENTER_X/Y not properly parsed

---

.circleci/config.yml
CHANGELOG.md
geonode/base/models.py
geonode/groups/tests.py
geonode/layers/api/views.py
geonode/layers/tests.py
geonode/settings.py
geonode/utils.py
geonode/views.py

[Fixes #7735] Editing layer metadata in admin interface throws an error

---

geonode/base/api/tests.py
geonode/base/api/views.py
geonode/base/migrations/0060_resourcebase_state.py
geonode/layers/api/tests.py
geonode/layers/api/views.py
geonode/layers/templates/datasets/dataset_detail.html
geonode/layers/templates/layouts/panels.html
geonode/maps/templates/layouts/map_panels.html
geonode/maps/templates/maps/map_detail.html
geonode/maps/urls.py
geonode/maps/views.py
geonode/thumbs/tests/test_integration.py

- moved `set_thumbnail_from_bbox` to resourcebase instead of `dataset`
- tests moved from `DatasetApi` to `ResourceBaseApi`
References: #7860

[Fixes #7860]  Replace layer_thumbnail method for maps 

---

geonode/base/api/serializers.py

Fix API error when FAVORITE app is disabled.
Refers to #7882

[Fixes #7882][32x] Error in handling favorite

---

geonode/context_processors.py
geonode/layers/api/views.py
geonode/layers/tests.py
geonode/settings.py
geonode/utils.py
requirements.txt
setup.cfg

Please refer to https://github.com/GeoNode/geonode-mapstore-client/pull/384 
**Notes: requirements & setup.cfg must be updated once the PR on the client is merged** …

[Backport 3.3.x][Fixes #7764] Implement GeoApp for Dashboards

---

celery_dev.sh
geonode/base/models.py
requirements.txt

References: #7896
- update celery_dev.sh with the new developements
- update requirements.txt with libraries required to run async flow
- Fix bug related to the thumbnail. Now if the actual filename returned by the storage manager is different from the one in the original upload path, it will be replaced with the new filename
**Submitting the PR does not require you to check …

[Fixes #7896] Thumbnail creation fix and celery update

---

geonode/layers/tests.py
geonode/thumbs/tests/test_unit.py
geonode/thumbs/thumbnails.py

[Fixes #7835][Backport 3.3.x] The first time a map is saved thumbnail is created using the default style instead of the selected one

---

geonode/layers/tests.py
geonode/thumbs/tests/test_unit.py
geonode/thumbs/thumbnails.py

[Fixes #7835][Backport 3.2.x] The first time a map is saved thumbnail is created using the default style instead of the selected one

---

geonode/base/api/tests.py
geonode/base/api/views.py

[Fixes #7972] Query filters are not working on some api v2 endpoints

---

geonode/base/models.py

References: #7974
The `settings.MEDIA_ROOT` is not defined with a non-docker installation, so the system will create it something like: `/opt/path/uploaded` while when running with docker, the `settings.MEDIA_ROOT` is defined like this:  `/opt/path/uploaded/`
By default the save_thumbnail, add a slash to create the correct path for the thumbnail with this line:
https://github.com/GeoNode/geonode/blob/212f81cb8bdaa22b8588957f1a27f8b3af1a3e8e/geonode/base/models.py#L1670
so when it's time to check if we need to remove the temporary image, it checks the path:
https://github.com/GeoNode/geonode/blob/212f81cb8bdaa22b8588957f1a27f8b3af1a3e8e/geonode/base/models.py#L1677-L1679
so with Docker, we will have:
```python
tmp_location='/opt/uploaded//thumbs/img.jpg …
```

[Fixes #7974] Thumbnails not created when uploading a new dataset

---

geonode/upload/utils.py

[Fixes #8069] Upload step without _ASYNC_UPLOAD set throws an error if the request is None

---

.env

The ALLOWED_HOSTS variable in .env file is not imported from docker-compose. There is an error in how the variable is written there, double quotes should be removed. Needs to be: ALLOWED_HOSTS=['django', '\*'] instead of ALLOWED_HOSTS="['django', '\*']".
This PR fixes a syntax error in the ALLLOWED_HOSTS variable, needed to launch correctly GeoNode with docker in v 3.2.X in a local machine.
The following are required only for core and extension modules (they are welcomed, but not required, for …

Fixed #8072 error in docker-compose local start due to bad env variable ALLOWED_HOSTS in .env

---

.env

The ALLOWED_HOSTS variable is not imported from from docker-compose. There is an error in how the variable is written there, double quotes should be removed. Needs to be: ALLOWED_HOSTS=['django', '*'] instead of ALLOWED_HOSTS="['django', '*']".
(cherry picked from commit ae35b9ec74f6108e86fe256cc749f4f72ab05d47)
The following are required only for core and extension modules (they are welcomed, but not required, for …

[Backport to 3.3.x] Fixed #8072 (#8073)

---

.env

The ALLOWED_HOSTS variable is not imported from from docker-compose. There is an error in how the variable is written there, double quotes should be removed. Needs to be: ALLOWED_HOSTS=['django', '*'] instead of ALLOWED_HOSTS="['django', '*']".
(cherry picked from commit ae35b9ec74f6108e86fe256cc749f4f72ab05d47)
The following are required only for core and extension modules (they are welcomed, but not required, for …

[Backport to 3.2.x] Fixed #8072 (#8073)

---

geonode/base/populate_test_data.py
geonode/documents/models.py
geonode/documents/tests.py
geonode/documents/utils.py
geonode/documents/views.py

[Fixes #8101] Fixes to documents embed

---

geonode/layers/models.py
geonode/security/models.py
geonode/security/tests.py
geonode/security/utils.py

References: #8112
* `GeofenceAdapter` and  `GeofenceLayerRulesUnitOfWork` were created:
* When inside the `GeofenceLayerRulesUnitOfWork` the geofence transactions were stacked to be executed at the end (`__exit__`).
*  `GeofenceLayerRulesUnitOfWork` were used as a context manager.
* In case of failure:
* `geofence_adapter.rollback()` restore the previous state, if needed. 
* Django Testing
```
./manage.py test geonode.security.tests.PermissionsTest.test_set_layer_permissions_unit_of_work --keepdb
./manage.py test geonode.security.tests.PermissionsTest.test_layer_set_default_permissions_unit_of_work --keepdb
./manage.py test geonode.security.tests.PermissionsTest.test_layer_permissions_geofence_rollback --keepd
```
* Manual Testing:
* Run the application.
* Add a layer.
* Change its …

[3.3.x][Fixes #8112] Dump and restore Geofence rules in case of requests or transaction failures

---

geonode/social/apps.py
geonode/social/signals.py
geonode/social/templates/social/activity_list.html
geonode/social/templatetags/social_tags.py
geonode/social/tests.py
geonode/social/views.py
geonode/static/geonode/css/base.css
geonode/static/geonode/less/base.less

[Backport 3.3.x][Fixes #8057] GeoStory: missing tab in recent activities

---

geonode/geoserver/tests/test_helpers.py
geonode/geoserver/tests/test_server.py
geonode/geoserver/urls.py
geonode/geoserver/views.py

[Fixes #8318] Wrong match for Geoserver path

---

geonode/proxy/tests.py
geonode/utils.py

[Fixes #8327] The final file extension is incorrect when exporting data from the attribute table

---

geonode/geoserver/tests/test_helpers.py
geonode/geoserver/tests/test_server.py
geonode/geoserver/urls.py
geonode/geoserver/views.py

(cherry picked from commit f283a12922f18384bba46d1c8ba446c2c99271b0)

[Backport to 3.3.x][Fixes #8318] Wrong match for Geoserver path (#8344)

---

geonode/security/models.py
geonode/security/tests.py

[Fixes #8341] Duplicate permission on layers

---

geonode/base/models.py
geonode/documents/views.py
geonode/geoserver/createlayer/utils.py
geonode/groups/models.py
geonode/layers/utils.py
geonode/security/models.py
geonode/security/tests.py

References: #8362
This PR fixes few problema on the Advanced Workflow missing in the the previous one related to the same issue.
In particular the group managers had different set of permissions when uploading a new layer and when promoting a new member. …

[3.3.x][Fixes #8362] Permissions to brand new group managers  (#8367)

---

geonode/layers/api/serializers.py
geonode/layers/api/tests.py

[Fixes #8427] add ptype field to datasets list API

---

geonode/thumbs/thumbnails.py

[Fixes #8446] Error whem saving a new map

---

geonode/thumbs/thumbnails.py
geonode/thumbs/utils.py

[Fixes #8446] Fix thumbnail creation for new empty maps

---

geonode/base/api/serializers.py
geonode/geoapps/api/serializers.py
geonode/geoapps/api/tests.py
geonode/resource/utils.py

[Fixes #8474] Regression on geoapp API POST and PUT requests

---

geonode/base/models.py
geonode/geoapps/api/tests.py
geonode/geoapps/tests.py

[3.3.x][Fixes #8429]GeoApps have empty uuid

---

geonode/base/models.py
geonode/geoapps/api/tests.py
geonode/geoapps/tests.py

* [Fixes #8429]GeoApps have empty uuid
* save uuid on resource
(cherry picked from commit 702837981e79c975fcca5dcd594bfb3ea3501971)

[Bckport to 3.2.x][Fixes #8429]GeoApps have empty uuid (#8473)

---

scripts/docker/letsencrypt/Dockerfile
scripts/docker/letsencrypt/docker-entrypoint.sh

Proposed for fixing GeoNode#8376
- Change to the entrypoint script and directory structures so that the provisioned cert and challenges can be accessed by nginx container as well
- Since `spcgeonode` was deprecated, the directory references are changed to `geonode-certificates` according to the `docker-compose.yml` in the root directory
- Certbot now has official docker image. Meanwhile certbot from apk package was stuck in version 0.xx . To avoid CLI and ACME API mismatch in the previous containers, we use the latest pinned version of certbot as base image.
Since letsencrypt testing involves provisioning a real DNS address and real server. I don't know how to include testing for this, but I tested it manually on a server for some project.
> Reviewing is a process done by project …

[Fixes #8376] Fix letsencrypt certificate handling

---

geonode/proxy/tests.py
geonode/proxy/views.py
requirements.txt
setup.cfg

references: #8458
* A temp folder is created.
* Some layer files are copied to this folder.
* Some other files are created inside this folder.
* And there are also, some files that are get from http requests and stored in this folder.
* Them, for each file in this folder, the file is added to a zip file and...
* This zip file is returned.
* No need to create the temp folder.
* Instead of copying the files, it's path is stored in a list, to be added to the streaming zip later.
* Other files, are stored in this list, they are stored by it's path or http streams or file name.
* When we have a list of all files to be zipped, we add them to the zip stream file.
* This zip stream is returned in a StreamingHttpResponse.
* django-sendfile2 needs a zip file to be stored somewhere in the file …

[3.3.x][Fixes #8458] Direct download timeout with big files

---

geonode/tests/utils.py
geonode/upload/api/tests.py
geonode/upload/upload_validators.py

[Fixes #8551] raster uploads require sending the same file twice

---

geonode/templates/_permissions_form.html

This PR moved all the geolimits map code inside a function and it initializes it only when the geolimits tab is clicked. This PR adds also the tiled true param to the WMS request and it increases the tile size to 512
**Submitting the PR does not require you to check all items, but by the time it gets …

[Fixes #8508] Improve GeoLimits layer tiles loading

---

geonode/maps/api/tests.py
geonode/maps/api/views.py

[Fixes #8637] Thumbnail not generated on creating a map

---

geonode/geoserver/helpers.py
geonode/layers/views.py

This PL is to fix https://github.com/GeoNode/geonode/issues/8611
- setting version of the style before uploading (geoserver-restconfig)
- re-generate thumbnail
- [ x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
**Submitting the …

[Fixes #8611] Setting style version for upload, re-generate thumbnail 

---

geonode/geoserver/helpers.py
geonode/geoserver/management/commands/importlayers.py
geonode/upload/api/tests.py
geonode/upload/api/views.py
geonode/upload/utils.py

references: #8647 
* Upload by api changed.
* Instead of running always these 3 steps: `save`, `check`, `final`
* It calls the next step given by the `redirect_to` field in response.
* It stops when:
* it performs the final step
* in case of errors or
* when we count more than the max amount of steps. (defined by the [list of steps](https://github.com/GeoNode/geonode/blob/master/geonode/upload/utils.py#L200-L223) - currently, a max of 7 steps)
* It uses the url query params to be used in the next calls, instead of ignoring it.
* Try to upload different files at:  http://master.demo.geonode.org/catalogue/#/upload/dataset
* Files that requires manual steps: SRS step, time step, csv...
* Files that do not requires manual steps: shp, prj files etc...
* We should not close the page while the …

[Fixes #8647] Fix upload API

---

geonode/settings.py

reduce tinymce tools

---

geonode/documents/forms.py
geonode/documents/tests.py
geonode/geoserver/createlayer/templates/createlayer/dataset_create.html
geonode/geoserver/createlayer/tests.py
geonode/geoserver/createlayer/utils.py
geonode/geoserver/createlayer/views.py
geonode/layers/forms.py
geonode/security/permissions.py
geonode/upload/forms.py

[Fixes #8740] Adopt default permissions for new resources

---

geonode/base/api/tests.py
geonode/resource/manager.py

[Fixes #8772] Previous owner is assigned to the cloned resource, instead of the user that performed the clone operation

---

geonode/geoserver/createlayer/utils.py

ref https://github.com/GeoNode/geonode/issues/8780

[Fixes #8780] Thumbnail is not created when createing a new dataset

---

geonode/layers/utils.py

When creating a new `UploadSession` via `get_or_create`, the database has a constraint that a user must be specified. Thus, geonode generates an error when trying to create one with only the layer details specified.
The `default` dictionary on `get_or_create` allows the addition of variables for creation with modifying the search query for existing `UploadSession` objects. …

Correctly assign a user when creating a new upload session.

---

geonode/base/api/serializers.py

[Fixes #8808] Order execution requests by last_updated

---

geonode/geoserver/tests/test_server.py
geonode/geoserver/views.py

[Fixes #8858] Support "workspaced" requests on GeoServer proxy view

---

geonode/layers/tests.py
geonode/layers/views.py

relates to #8873 
Base permission changed on direct download link
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate it if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

[Fixes #8873] Permissions not checked on the direct download button of a resource

---

geonode/layers/tests.py
geonode/layers/views.py

backport https://github.com/GeoNode/geonode/pull/8882

[Backport][Fixes #8873] Permissions not checked on the direct download button of a resource

---

geonode/base/models.py
geonode/upload/utils.py

ref #8913 
This PR I want to introduce:
- Add transaction atomic bloc to keyword manager to avoid duplication error due to the concurrency

[Backport][Fixes #8913] Duplicate keyword error raised on massive upload

---

geonode/settings.py

Include two new variables that allows configuration of projections definitions and patch rules for plugin configuration

[Backport 3.3.x][Fixes #8934] Allow configuration of projection and patch rules via settings.py for geonode-mapstore-client 

---

geonode/settings.py

Include two new variables that allows configuration of projections definitions and patch rules for plugin configuration

[Fixes #8934] Allow configuration of projection and patch rules via settings.py for geonode-mapstore-client

---

geonode/base/api/permissions.py
geonode/base/api/tests.py
geonode/base/api/views.py
geonode/documents/api/views.py
geonode/geoapps/api/tests.py
geonode/geoapps/api/views.py
geonode/layers/api/views.py
geonode/maps/api/views.py
geonode/resource/api/urls.py
geonode/upload/api/tests.py
geonode/upload/api/views.py

[Fixes #8908] Review API v2 allowed methods

---

geonode/base/populate_test_data.py
geonode/base/tests.py
geonode/base/utils.py
geonode/documents/views.py
geonode/layers/views.py
geonode/maps/views.py
geonode/security/models.py
geonode/security/tests.py
geonode/security/utils.py
test_dev.sh

References #8937 
This PR introduces the following changes:
- Fixes permissions returned in `get_workflow_perms` when advanced workflow is enabled
- Removes setting of owner permissions in views
- Checks advanced workflow status when setting owner permissons
- Adds test-cases for permissions when advanced workflow is enabled …

[Backport 3.3.x][Fixes #8937] User with perms can edit approved and published resources when Advanced workflow is enabled

---

geonode/security/tests.py
geonode/security/utils.py

[Fixes #8937] User with perms can edit approved and published resources when Advanced workflow is enabled

---

geonode/geoserver/tests/test_server.py
geonode/geoserver/views.py

[Fixes #9042] Disable caching header in GeoNode proxy for the REST API

---

geonode/upload/models.py
geonode/upload/upload.py

[Fixes #9092] The Upload Workflow never updates the Resource files

---

geonode/base/api/tests.py
geonode/base/api/views.py
geonode/base/models.py

[Fixes #9101] Keywords filter only returns the root nodes of the tree

---

geonode/settings.py

[Fixes #9148] switch from wikimedia to osm for thumbnail basemap

---

geonode/base/models.py
geonode/upload/models.py
geonode/upload/tasks.py
geonode/upload/upload.py

[Backport to 3.3.x][Fixes #9186] Upload marks as PROCESSED a resource not ready yet

---

setup.cfg

[Fixes #9200] Make 4.x track client 4.x

---

geonode/version.py

[Fixes #9202] PEP-440 compliant version

---

geonode/base/auth.py
geonode/security/middleware.py
geonode/security/tests.py
geonode/settings.py

This solution has several security implications. It will be kept on hold until a better approach will be found.

Revert "[Fixes #9212] Login with basic auth or token headers or apikey GET parameter"

---

geonode/base/api/serializers.py
geonode/security/tests.py
geonode/security/utils.py

[Fixes #9210] Owner is still able to edit data and style after a resource has been approved and A/W is active

---

requirements.txt
setup.cfg

Updates django-markdownify to version 0.9.1  which solves #9263 

bump django-markdownify to 0.9.1 fixes #9263

---

geonode/services/tasks.py

[Fixes #9268] Refresh the harvest_job object

---

.clabot
geonode/storage/manager.py

[Fixes #9196] Fix storage manager copy function

---

geonode/security/utils.py

A/W: owner should not have any modification permission on published resource
ref #9332 

[Fixes #9332] A/W: owner should not have any modification permission on published resource

---

geonode/geoserver/tests/test_server.py
geonode/security/tests.py
geonode/upload/api/tests.py
geonode/upload/tests/test_utils.py
geonode/upload/tests/utils.py
geonode/upload/upload.py

[Fixes #9330] Upload randomly causing "java.lang.NullPointerException" during Import

---

geonode/upload/upload.py

[Backport 3.3.x] [Fixes #9330] Upload randomly causing "java.lang.NullPointerException" during Import

---

geonode/security/tests.py

[Backport 3.3.x][Fixes #9332][Test Cases] A/W: owner should not have any modification permission on published resource

---

geonode/base/api/tests.py
geonode/catalogue/models.py

[Fixes #9370] "catalogue_post_save" fails on retrieving the self resource

---

geonode/base/api/tests.py
geonode/catalogue/models.py
geonode/thumbs/thumbnails.py
geonode/version.py

[Backport 3.3.x][Fixes #9370] "catalogue_post_save" fails on retrieving the self resource

---

geonode/maps/api/exception.py
geonode/maps/api/tests.py
geonode/maps/api/views.py

[Fixes #9386] Adopt DRF exceptions inside maps APIv2

---

geonode/geoapps/api/exceptions.py
geonode/geoapps/api/serializers.py
geonode/geoapps/api/tests.py

[Fixes #9413] Adopt DRF exceptions inside geoapps APIv2 4.0.x API v2

---

geonode/services/serviceprocessors/wms.py
requirements.txt
setup.cfg

[Fixes #9426][Remote Services] Errors on creating WMS Cascade stores and layers

---

geonode/utils.py

[Fixes #9500] OWS Url wrong for INDEXED Remote Services

---

geonode/geoserver/security.py

[Fixes #9531] Provide priority to _update_geofence_rule method

---

geonode/base/models.py

[Fixes #9529] psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "base_hierarchicalkeyword_path_key"

---

geonode/br/management/commands/restore.py
geonode/settings.py
geonode/tests/test_utils.py
geonode/utils.py

[Fixes  #9591] Expose supported upload file formats as configurations

---

geonode/geoserver/helpers.py
geonode/thumbs/tests/test_unit.py
geonode/thumbs/utils.py

[Fixes #9637] Performance scalability issues with Thumbnail generation

---

geonode/geoserver/helpers.py
geonode/thumbs/tests/test_unit.py
geonode/thumbs/utils.py

[Backport to 3.3.x][Fixes #9637] Performance scalability issues with Thumbnail generation

---

docker-compose.yml

[Backport to 3.3.x][Fixes #9662][Docker] Wrong healthcheck on Django container

---

geonode/geoserver/helpers.py

[Fixes #9669] Updatelayers unexpectedly fails if layer is 'None'

---

geonode/proxy/views.py

[Fixes #9673] Proxy must use OGC_REQUEST_TIMEOUT instead of an hardcoded one

---

.circleci/config.yml
geonode/people/tests.py

[Fix #9689] Fix people tests

---

geonode/resource/api/exceptions.py
geonode/resource/api/tests.py
geonode/resource/api/views.py

ref #9756
- [x ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)

[Fixes #9756] ExecutionRequest endpoint should allow the delete

---

geonode/base/api/tests.py

Add test on extra metadata

---

docker-compose-test.yml
docker-compose.yml

Fixing the db healthcheck in all compositions

[Fixes #9839] db healthcheck fails with 'FATAL: role "root" does not exist'

---

setup.cfg

[Dependencies] align setup.cfg to requirements.txt

---

geonode/resource/models.py

[Fixes #9878] drf_spectacular error breaks redoc and swagger-ui schemas

---

docker-compose.yml

[Fixes #9917] Current django health check in docker-compose.yml useless.

---

geonode/layers/templates/layouts/panels.html
geonode/layers/views.py
geonode/templates/metadata_form_js.html

[#Fixes #9945] Do not show the time configuration for raster datasets

---

geonode/base/api/permissions.py
geonode/base/api/tests.py
geonode/base/api/views.py
geonode/people/utils.py

[#Fixes #9944] Unable to clone a resource

---

geonode/geoserver/helpers.py
geonode/geoserver/tasks.py

References: #10024
Solves the problem of bad styles assigned to layer.
- Main fix is by setting proper lock ids in celery tasks.
- Added lot of debug logging, also useful for post-mortem investigations
- Split some nested commands and improved robustness

[Fixes #10024] Wrong default style when creating layer

---

geonode/base/api/tests.py
geonode/base/models.py
geonode/documents/tasks.py
geonode/documents/tests.py
geonode/thumbs/tests/test_integration.py
geonode/thumbs/tests/test_unit.py

[Fixes #10091] improve thumbnails quality

---

geonode/base/models.py
geonode/documents/management/commands/sync_geonode_documents.py
geonode/documents/tasks.py

[Fixes #10138] Render pdf thumbnails from top margin

---

geonode/geoserver/manager.py
geonode/geoserver/signals.py

[4.0.x][Fixes #10208] Add a custom hook at the end of the permissions assign

---

geonode/base/views.py
geonode/layers/tests.py
geonode/layers/utils.py

[Fixes #10287] The "set_layer_permissions" management command does not behave correctly with "AnonyousUser"

---

scripts/docker/nginx/docker-entrypoint.sh
scripts/docker/nginx/nginx.conf.envsubst
scripts/docker/nginx/nginx.https.available.conf.envsubst

Containers should always listen on some fixed ports. Only remapped externally exposed ports should change.
This PR removes all references to `HTTP_PORT` and `HTTPS_PORT` inside `scripts/docker/nginx` and fixes issue #9041.
Such change should be propagated to geonode-project. I tested it successfully on geonode-project, so I believe it should work here too, since it is a rather small change and both compose files are the same with respect to how ports are remapped and exposed.
Users could still experience this issue after applying the patch, if they do not delete the `nginx-confd` volume. I would actually suggest keeping that volume disabled by default, so that the configuration is created each time, by looking at the environment variables.
> Reviewing is a process done by project …

[Fixes #9041] Docker NGINX listen on ports 80/443

---

geonode/api/resourcebase_api.py

[Fixes #10420] Add resource_type to legacy API response

---

geonode/catalogue/tests.py
geonode/catalogue/urls.py
geonode/catalogue/views.py

References: #10374
A new UI route (`/catalogue/:uuid`) has been defined that takes a UUID as a parameter. In the backend, a corresponding database query is triggered which, based on the available metadata of the layer, allows the user to be redirected to the actual URL. …

[Fixes #10374] UUID resolver endpoint

---

geonode/geoserver/helpers.py
geonode/geoserver/tests/test_helpers.py
geonode/geoserver/views.py

[Fixes #10462] GeoNode is vulnerable to an XML External Entity (XXE) injection

---

geonode/geoserver/helpers.py
geonode/geoserver/tests/test_helpers.py
geonode/geoserver/views.py
geonode/utils.py
requirements.txt
setup.cfg

[Fixes #10464] Fix code scanning alert - Uncontrolled data used in path expression

---

.devcontainer/.env
.env
.env_dev
.env_local
.env_test

[Fixes #10509] Configure UTF-8 encoding for shapefiles in Geoserver by default

---

.clabot

PR for adding 52°North staff to the CLA bot config

[CLA] add 52North staff to .clabot

---

geonode/catalogue/templates/catalogue/full_metadata.xml

This is a small fix for the ISO 19139 metadata template. Two validation problems are solved. Metadata served via pycsw should be valid after integrating the adjustments.

Fix ISO 19139 metadata validity

---

geonode/layers/tests.py
geonode/layers/utils.py

[Fixes #10525] set/unset batch permissions on groups raise an error

---

geonode/base/api/tests.py
geonode/br/management/commands/restore.py
geonode/geoserver/geofence.py
geonode/geoserver/helpers.py
geonode/geoserver/security.py
geonode/layers/tests.py
geonode/security/tests.py
geonode/utils.py

The creation of the Rules in GeoFence should be as quick as possibile.
In order to improve the performance of rule creation, we can leverage on the use of GeoFence batch.
See whole rationale on  #10537.

[Fixes #10537] Improve rules creation using GeoFence batch

---

.github/PULL_REQUEST_TEMPLATE.md

Add black geonode to the requested QA xchecks

---

geonode/settings.py

[Fixes #10615] Implement fallback language for PyCSW to avoid warnings

---

geonode/geoserver/tests/test_helpers.py

[Fixes #10887] Fix test request

---

geonode/documents/templates/layouts/doc_panels.html

[Fixes #10925] Fix default value for crop widget thumbnail prefetch

---

geonode/base/api/serializers.py
geonode/base/api/tests.py
geonode/base/api/views.py

ref #10936 
The API is filterable:
- If the filter is related to the resource which we are asking the linked_resource we can use the dynamic filter example:
With the below URL, the filter will refer to the information of the resource PK and not to the linked resource. This is due to the behavior of the dynamic filter that geonode uses. We cannot change this
```python
URL: /api/v2/{PK}/linked_resources?filter{resource_type}=map
```
With the below URL, the filter will refer to the linked resource. The filter accepts the default django queryset filtering
```python
URL: /api/v2/{PK}/linked_resources?resource_type=map
URL: /api/v2/{PK}/linked_resources?title__icontains=title
URL: /api/v2/{PK}/linked_resources?resource_type=map
```
> Reviewing is a process done by project maintainers, mostly on …

[Fixes #10936] Implement a generic API endpoint for linked resources

---

geonode/geoserver/helpers.py
geonode/layers/forms.py
geonode/layers/templates/layouts/panels.html
geonode/layers/tests.py
geonode/layers/views.py

[Fixes #19061] Time serie date field not recognized

---

geonode/base/templatetags/thesaurus.py

[Fixes #10976] Fix thesaurus labels translations

---

geonode/security/models.py
geonode/security/tests.py

[Fixes #11034] Drop AnonymousUser from perm spec

---

geonode/geoserver/security.py

[Fixes #11030] Create Geofence * rule for anonymous group inside the sync command

---

geonode/api/tests.py
geonode/base/api/filters.py
geonode/base/api/views.py
geonode/base/models.py

#11061
Adds a new Filter that handles `filter{tkeywords}` and removes such queryparam from the request, so that DREST won't process the same params again.
A new `force_and param` has been added in order to provide a further on-demand behaviour. 
It will be documented and used in the forecoming 4.2 version.
**Submitting the PR does not require you to check all items, but by …

[Fixes #11061] Filtering by tkeywords

---

requirements.txt
setup.cfg

[Fixes #11072] Revert django-autocomplete-light upgrade

---

geonode/facets/providers/region.py
geonode/facets/tests.py
geonode/settings.py

Implements flat faceting for Regions as described in #11095

[Fixes #11095] Regions: flat faceting

---

geonode/base/fixtures/regions.json
geonode/resource/utils.py

Fix region intersection test

---

geonode/base/api/filters.py
geonode/facets/tests.py
geonode/facets/views.py

See  #11102
Adjust the count of resources for facets according to filters already applied.
Filters are applied to `facets` and to `facets/<facet_name>` results by adding one or more `filter{FIELD_EXPR}=VALUE` query params.

[Fixes #11102] Faceting: prefiltering

---

geonode/facets/models.py
geonode/facets/providers/keyword.py
geonode/facets/tests.py
geonode/settings.py

Implements #11101
Creates a new FacetProvider `KeywordFacetProvider`

[Fixes #11101] Faceting: keywords

---

geonode/facets/models.py
geonode/facets/providers/baseinfo.py
geonode/facets/providers/category.py
geonode/facets/providers/keyword.py
geonode/facets/providers/region.py
geonode/facets/providers/thesaurus.py
geonode/facets/providers/users.py
geonode/facets/tests.py
geonode/facets/views.py
geonode/settings.py

2 commits for 2 issues:
- #11226 : Rename facet entry key to filter.
First step (see related issue)
The commit msg does not include the "fixes" because issue should not be closed right now.
- #11233: Faceting: improvement: facet configuration

Faceting : #11226 key to filter - step 1 + #11233 configuration

---

geonode/documents/api/tests.py
geonode/documents/api/views.py
geonode/documents/tests.py
geonode/documents/views.py

[Fixes #11249] Mark remote documents with sourcetype REMOTE

---

geonode/facets/tests.py
geonode/facets/views.py

[Fixes #11273] Faceting: /facets loses some filters along the way

---

geonode/geoserver/helpers.py
geonode/geoserver/tests/test_helpers.py

Change URL in `get_dataset_capabilities_url`
#11265

[Fixes #11265] Change the WMS URL to a more generic OWS URL

---

geonode/geoserver/helpers.py
geonode/geoserver/tests/test_helpers.py
geonode/layers/api/serializers.py
geonode/layers/models.py

[Fixes #11312] Expose dataset ows url

---

geonode/settings.py

[Fixes #11394] Enable IFC format

---

geonode/base/api/serializers.py
geonode/base/api/tests.py
geonode/documents/models.py
geonode/documents/tests.py
geonode/geoserver/tests/test_server.py
geonode/layers/api/tests.py
geonode/layers/download_handler.py
geonode/layers/models.py
geonode/layers/tests.py
geonode/layers/utils.py
geonode/layers/views.py
geonode/proxy/tests.py
geonode/security/permissions.py
geonode/security/tests.py
geonode/settings.py
geonode/tests/smoke.py
geonode/utils.py

[Fixes #11421] Improvements for DownloadHandler

---

geonode/base/api/views.py
geonode/documents/api/views.py
geonode/layers/api/views.py
geonode/maps/api/views.py

adding args, kwargs in the API

Add args and kwargs in resources API

---

geonode/people/forms.py

[Fixes #11381] Remove `ProfileCreationForm.clean_username()`

---

geonode/api/api.py

[Fixes #11497] Dehydrate `organization` field

---

geonode/harvesting/harvesters/base.py
geonode/harvesting/harvesters/geonodeharvester.py
geonode/harvesting/tests/test_integrations.py
geonode/resource/utils.py

[Fixes #11533] Remote resources created by harvesters do not have remote subtype

---

geonode/upload/api/tests.py

Test fix CircleCi test

---

.pre-commit-config.yaml

This commit bumps the version of the black pre-commit hook in geonode due to the issue described in issue #11566
closes #11566 

issue#11566_pre-commit_hook_black_isnt_working_on_Ubuntu_22_04_3

---

.circleci/config.yml

[Fixes #11603] Improve codecov integration

---

geonode/facets/providers/thesaurus.py
geonode/facets/tests.py

[Fixes #11643] Thesaurus topics should only return its own keys

---

geonode/facets/providers/category.py
geonode/facets/providers/keyword.py
geonode/facets/providers/region.py
geonode/facets/providers/thesaurus.py
geonode/facets/tests.py

The query has been completely rewritten.

[Fixes #11652] Facets: wrong count on multiple tkeywords filtering

---

geonode/geoserver/geofence.py
geonode/geoserver/manager.py
geonode/geoserver/security.py

- Fixes #11447 (Bad role name in creating GeoFence rules)
- Fixes  #11668 (Bad ordering of GeoFence rules) 

[Fixes #11447, #11668] Various fixes in GeoFence permissions

---

.env.sample
geonode/base/tests.py
geonode/context_processors.py
geonode/singleton.py

Add environment variable to Force the "READ_ONLY" mode.
- If `TRUE`, set the application in `read_only` even if is not set in the configuration. 
- If `FALSE`, set the application will not be in `read_only` even if is set in the configuration
-  …

Control read only mode with environmental variable #11710

---

.env.sample

[Fixes #11806] Don't quote JAVA_OPTS

---

setup.cfg

Since 4.2.0.dev0 is not considered >= 4.2.0

Fix minimum version for the client

---

docker-compose-dev.yml
docker-compose-test.yml
docker-compose.yml
geonode/base/api/tests.py
geonode/harvesting/harvesters/geonodeharvester.py

Upgrade Geoserver with fix for oauth2

---

geonode/settings.py

This PR is intended to fix the bug about the MAP_CENTER here https://github.com/GeoNode/geonode/issues/11889 
Note: **Careful when redefine the center of the new map, you need to consider the default CRS as well, the coordinate should have the same projection.**
- [ x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [ x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be …

[Fixes #11889 ] MAP_CENTER is not passed to mapstore

---

geonode/catalogue/templates/catalogue/full_metadata.xml

Fixes [issue#11883](https://github.com/GeoNode/geonode/issues/11883), the extent values should now only include decimal separator whichever language is selected. …

[Fixes #11883] the extent values should now only include decimal separator

---

geonode/base/templatetags/sanitize_html.py
geonode/base/tests.py
geonode/templates/metadata_detail.html
requirements.txt
setup.cfg

Add a new template tag for legacy pages to sanitize html with nh3

[Fixes #11862] Sanitize HTML data

---

geonode/base/api/mixins.py
geonode/base/api/views.py
geonode/documents/api/tests.py
geonode/documents/api/views.py
geonode/geoapps/api/tests.py
geonode/geoapps/api/views.py
geonode/layers/api/tests.py
geonode/layers/api/views.py
geonode/maps/api/tests.py
geonode/maps/api/views.py

hide resources from search and catalogue listing

---

geonode/base/api/urls.py
geonode/base/api/views.py
geonode/people/urls.py
geonode/people/views.py

[Fixes #11992] Transfer users API under people app

---

geonode/br/management/commands/backup.py
geonode/br/management/commands/restore.py

According to #11977, removed the backup and restoring of
- templates
- static dirs
- static root
Also taking care of 
- #12002 
- #12003 

[Fixes #11977][Backport 4.1.x] B/R should only deal with data

---

.circleci/config.yml

CircleCI was failing because 20.10.12 is [deprecated](https://discuss.circleci.com/t/remote-docker-image-deprecations-and-eol-for-2024/50176)

Upgrade Remote Docker version for CircleCI

---

geonode/br/management/commands/backup.py
geonode/br/management/commands/restore.py

According to #11977, removed the backup and restoring of
- templates
- static dirs
- static root
Also taking care of 
- #12002 
- #12003 

[Fixes #11977] B/R should only deal with data

---

.circleci/config.yml
geonode/base/api/permissions.py
geonode/base/api/serializers.py
geonode/base/api/tests.py
geonode/people/tests.py
geonode/people/views.py

[Fixes #11995 Implement POST and PATCH methods for the User API

---

geonode/base/api/tests.py
geonode/people/tests.py
geonode/people/utils.py
geonode/people/views.py
geonode/settings.py

[Fixes #11995] Implement the DELETE method for the User API

---

geonode/resource/manager.py
geonode/resource/tests.py

[Fixes #12063] Cannot clone map/geoapp with linked resources

---

geonode/geoserver/context_processors.py
geonode/layers/templates/datasets/dataset_metadata_upload.html
geonode/layers/templates/datasets/dataset_style_upload.html
geonode/settings.py
geonode/static/geonode/js/upload/LayerInfo.js

[Fixes #12049] Adapt the SLD and XML upload forms to the new progress API

---

geonode/geoserver/context_processors.py
geonode/layers/templates/datasets/dataset_metadata_upload.html
geonode/layers/templates/datasets/dataset_style_upload.html
geonode/settings.py
geonode/static/geonode/js/upload/LayerInfo.js

[Backport #12050] [Fixes #12049] Adapt the SLD and XML upload forms to the new progress API

---

requirements.txt
setup.cfg

From lxml 5.2.1 changelog:
>LP#2059910: The minimum CPU architecture for the Linux x86 binary wheels was set back to “core2”, but with SSE 4.2 enabled
This fix solves core dump caused by lxml on some KVM virtualized machines

lxml 5.2.1 fixes ABI compatibility

---

.devcontainer/.env
.env.sample
.env_dev
.env_local
.env_test
geonode/settings.py
requirements.txt
setup.cfg

[Fixes #12106] Switch to PyLibMCCache

---

geonode/base/api/serializers.py
geonode/people/api/serializers.py
geonode/resource/api/serializer.py

As an improvement of #12110, uses the new link serialization for a couple more Serializers, removing the related deprecation messages in the log.
Improved Serializers are:
- `ExecutionRequestSerializer`: using new `AutoLinkField`
- `UserSerializer`: `AutoLinkField` was already there, but the class still inherited from `BaseDynamicModelSerializer`. Fixed.
Also fixed the selection of the target view_name. …

[#12110] Clean up some deprecation messages

---

geonode/settings.py

[Fixes #12232] Increase the default value of CLIENT_RESULTS_LIMIT

---

geonode/harvesting/harvesters/arcgis.py

[Fixes #12235] Retrieve the ows_url for ArcGIS resources from the harvester url

---

geonode/resource/manager.py
geonode/security/models.py
geonode/security/tests.py
geonode/security/utils.py

[Fixes #12237] Extend tests for permissions assignment

---

geonode/proxy/apps.py
geonode/proxy/tests.py
geonode/proxy/utils.py
geonode/proxy/views.py
geonode/services/models.py
geonode/settings.py
geonode/utils.py

[Fixes #12253] Improvements to the proxy view

---

geonode/geoapps/api/serializers.py
geonode/geoapps/api/tests.py
geonode/geoapps/api/views.py

[Fixes #12261] Current user is assigned as owner on geoapp update

---

geonode/assets/local.py

[Fixes #12341] Assets: link generation

---

geonode/thumbs/tests/test_unit.py
geonode/thumbs/thumbnails.py

[Fixes #12384] Uploaded thumbnail for 3dtiles resource is not saved

---

geonode/base/management/command_utils.py
geonode/catalogue/management/commands/regenerate_xml.py
geonode/catalogue/models.py

[Fixes #12369] Create a command to regenerate the XML metadata

---

geonode/base/api/serializers.py
geonode/storage/data_retriever.py

ref #12436 
The `get_real_instance()` method should be called to use the proper model instance method instead of the base one to get the linked resources

[Fixes #12436] Linked resources are not present in maps api payload

---

geonode/layers/metadata.py

[Fixes #12445] Possible missing fields when parsing temporalExtent

---

.github/workflows/flake8.yml
pyproject.toml

[Fixes #12458] black fails on python3.10 constructs

---

geonode/base/api/serializers.py
geonode/base/api/tests.py
geonode/base/models.py
geonode/maps/api/tests.py
geonode/people/models.py
geonode/security/utils.py

[Fixes #12594] Error when saving a new map

---

.env_dev
geonode/assets/handlers.py
geonode/assets/local.py
geonode/assets/models.py
geonode/assets/tests.py
geonode/assets/utils.py
geonode/br/management/commands/backup.py
geonode/br/management/commands/restore.py
geonode/br/management/commands/settings_docker_sample.ini
geonode/br/management/commands/settings_sample.ini
geonode/br/management/commands/utils/utils.py
geonode/documents/models.py

- Add assets folder to the backup
- Add Asset foolder to restore
- During the restore the asset path is replaced with the new ASSETS_ROOT if needed
- Now the asset works with a custom Manager named `AssetPolymorphicManager` which is required to correctly handle the dump during the backup procedure. There is an [hack in the polymorphic model](https://github.com/jazzband/django-polymorphic/blob/cfd49b26d580d99b00dcd43a02409ce439a2c78f/polymorphic/base.py#L161-L175), but works only if the dump is called via CLI
- align test and code to the new changes
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you …

[Fixes #12627] Include assets inside B/R

---

geonode/people/models.py

This is a quick proposal to ensure a user gets all permissions assigned, including custom permissions which are unknown to GeoNode but potentially created and needed by contrib apps.
See #12639 and https://github.com/GeoNode/geonode/discussions/12635 for more details …

[Fixes #12639] Adds all assigned group permissions to user

---

.env_dev
geonode/upload/handlers/common/raster.py
geonode/upload/handlers/common/remote.py
geonode/upload/handlers/common/vector.py
geonode/upload/handlers/shapefile/handler.py
geonode/upload/handlers/tiles3d/handler.py
geonode/upload/handlers/tiles3d/tests.py
requirements.txt

ref https://github.com/GeoNode/geonode/issues/12674
for 44x -> https://github.com/GeoNode/geonode-importer/pull/277

[Fixes #12674] store spatial file is always false during cloning

---

.clabot
geonode/documents/api/views.py
geonode/documents/views.py

Aims to resolve https://github.com/GeoNode/geonode/issues/12616
It seems like the problem was that permissions were assigned to None both when handling UI and API document upload. On UI it didn't cause a problem because in UI upload there is also a call setting permissions to defaults again. Here I am removing the unnecceary assigment of permissions to None in UI code and setting permissiosn to defaults in API code.

[Fixes #12616] Document upload permissions fix

---

geonode/assets/local.py
geonode/proxy/views.py
requirements.txt
setup.cfg

Upgrade of the library `zipstream-ng` is required since they add the functionality we need as described in the changelog:
https://github.com/pR0Ps/zipstream-ng/blob/v1.8.0/CHANGELOG.md

[Fixes #12728] 3dtiles download does not keep the folder structure

---

geonode/upload/handlers/tiles3d/handler.py
geonode/upload/handlers/tiles3d/tests.py
geonode/upload/tests/end2end/test_end2end.py

[Fixes #12763] 3D tiles geometricError mandatory field should be on tileset level

---

geonode/people/forms/__init__.py
geonode/people/forms/recaptcha.py
geonode/people/templates/people/account_login.html
geonode/people/views.py
geonode/settings.py
geonode/urls.py

[Fixes #12815] Add Recaptcha support for GeoNode Sign-In Form

---

geonode/people/forms/__init__.py
geonode/people/forms/recaptcha.py
geonode/people/templates/people/account_login.html
geonode/people/views.py
geonode/settings.py
geonode/urls.py

Fixes this Issue: [Add Recaptcha Form on GeoNode Login](https://github.com/GeoNode/geonode/issues/12815)
Originally put on 4.4.x branch, and now submitted to maste branch

[Fixes #12815]  Add custom login view/template to support recaptcha on Login Form (#12825)

---

geonode/people/templates/people/avatar/add.html
geonode/people/templates/people/avatar/change.html
geonode/people/templates/people/avatar/confirm_delete.html
geonode/settings.py

This PR is to correct a little template breaker into GeoNode. In the Profile Editor, Change Avatar, when we click on change button, it renders a simple HTML page. This page is a django-avatar default template. With some little modifications, these pages now are with geonode template and some additional links, like "go back to profile editor", "delete avatar"...
This proposal were submitted on this further request: 
The following are required only for core and extension modules (they are welcomed, …

[Fixes #12841] Add avatar templates, changing default from django-avatar to geonode-base

---

geonode/layers/api/serializers.py
geonode/layers/api/views.py
geonode/upload/handlers/common/vector.py

This branch includes fixes in terms of the fields management through through the GET method of the endpoint: /api/v2/datasets/<pk>/timeseries . Also the …

[Fixes 12766] New fixes regarding the Timeseries API

---

geonode/base/api/serializers.py
geonode/base/api/tests.py
geonode/layers/download_handler.py

Revert "[Fixes #12880] Asset download doesn't work with 3D Tiles"

---

geonode/base/forms.py
geonode/documents/admin.py
geonode/geoapps/admin.py
geonode/layers/admin.py
geonode/maps/admin.py

ref #12921 
The new metadata editor require an id while calling the autocomplete endpoint, so we cannot switch to it.
It means that we can mantain the tkeywords in the admin interface, but without autocomplete (like we have for regions and other metadata): …

[Fixes #12921] Fix Layers admin interface raise error

---

geonode/metadata/manager.py
geonode/metadata/signals.py
geonode/metadata/tests/tests.py

[Fixes #12988] Metadata editor: fix jsonschema caching mechanism

---

geonode/upload/handlers/shapefile/handler.py
geonode/upload/handlers/shapefile/tests.py

Use `SHAPE_ENCODING` parameter to inform the ogr2ogr command of the encoding for the Shapefile so it can transform accordingly.

[Fixes #12981] Fix encoding for Shapefile uploads

---

geonode/metadata/api/views.py
geonode/metadata/i18n.py
geonode/metadata/tests/tests.py

- different HTTP return code according to the error
- possibility to localize the return message

[Fixes #12998] Metadata editor: improve return info when updating data

---

docker-compose-test.yml
docker-compose.yml
geonode/layers/api/serializers.py

This PR was created according to this issue: #13046 

[Fixes #13046] Fixing the layer's serializer which dynamically creates the featureino (For GeoNode 4.4.x)

---

geonode/tests/suite/base.py
geonode/tests/suite/runner.py
requirements.txt
requirements_tests.txt
setup.cfg

This PR was created according to this issue: #13057 The Twisted library is used by `TwistedParallelTestSuiteRunner` class but this runner is not used by the testing suite. Thus, it can be completely removed.

[Fixies #13057] Removing Twisted library from the dependencies and the related code

---

celery.sh
scripts/docker/base/ubuntu/Dockerfile

[Fixes #13087] Remove flower - this comes from old monitoring solution

---

geonode/base/api/tests.py
geonode/base/api/views.py

This PR is created according to this issue #13030 . The endpoint will delete the thumbnail image from disk and the corresponding database fields: thumbnail_field and thumbnail_path

[FIXIES #13030] Endpoint to delete a resource's thumbnail

---

geonode/base/api/views.py
geonode/people/api/views.py
geonode/people/tests.py

Ref https://github.com/GeoNode/geonode/issues/12996

[Fixes #12996] Allow changing ownership of a single resource

---

geonode/base/api/tests.py
geonode/base/api/views.py

This PR fixes this issue: #13100 

[Fixes #13100] Fixing permissions bug of the delete_thumbnail endpoint

---

scripts/docker/base/ubuntu/Dockerfile

This PR was created and fixes this issue: #13102 
The version `0.38.1` of `wheel` is defined explicitly on [Dockerfile](https://github.com/GeoNode/geonode/blob/master/scripts/docker/base/ubuntu/Dockerfile) of the base image because otherwise Docker installs by default the version of `0.37.1`
**Submitting the PR does not require you to check all items, but by the time it gets …

[Fixes #13102] Define a specific version of the Wheel package

---

geonode/metadata/api/views.py
geonode/metadata/handlers/abstract.py
geonode/metadata/handlers/base.py
geonode/metadata/handlers/contact.py
geonode/metadata/handlers/sparse.py
geonode/metadata/i18n.py
geonode/metadata/manager.py
geonode/metadata/signals.py
geonode/metadata/tests/test_handlers.py
geonode/metadata/tests/tests.py

See https://github.com/GeoNode/geonode/issues/13043
We may probably want to add a fixtures containg messages.
Best option would be to import the i18n thesaururs as RDF file and not as json fixture. TBD.

[Fixes #13043] Metadata editor: allow customization of error messages

---

.clabot
entrypoint.sh

Issue: https://github.com/GeoNode/geonode/issues/13162 
When the static root is set to a non default location, entrypoint.sh would crash as the hardcoded file location is not present.
Background:
Celery and Geonode sometimes throw SuspiciousFileExceptions by Django Path checks:
`ERROR/ForkPoolWorker-172] Detected path traversal attempt in '/mnt/volumes/statics/uploaded/thumbs/dataset-c3e2c0df-78bb-47c9-b449-b0e23c25726a-thumb-671e619d-97a9-47a9-b50d-81b5baf45ca5.jpg'
File "/usr/src/geonode/geonode/base/models.py", line 1570, in save_thumbnail
storage_manager.save(storage_manager.path(upload_path), img)
File "/usr/src/geonode/geonode/storage/manager.py", line 161, in save
File "/usr/src/geonode/geonode/base/models.py", line 1570, in save_thumbnail …

[Fixes #13162] Fixes hardcoded geonode init lock in entrypoint.sh

---

geonode/groups/tests.py

A broken test makes fail all the build from master.
The reason is due to the merge of the new client update. The test is just counting how many times a word is present in the response page. 
Not a strong test, so is better to remove that assert …

Fix test suite

---

geonode/storage/data_retriever.py
geonode/storage/manager.py
geonode/upload/tests/end2end/test_end2end.py

Addresses #13172 by ensuring that the file upload process respects the `FILE_UPLOAD_PERMISSIONS` setting when it's set to `None`.
Previously, the upload process unconditionally applied `os.chmod()` to uploaded files and directories, leading to a TypeError when `FILE_UPLOAD_PERMISSIONS` was `None`. This behavior caused issues in environments like Azure Files, where file permissions are managed externally and cannot be modified by the application.
The following are required only for core and …

[Fixes #13172] Respect `FILE_UPLOAD_PERMISSIONS=None` in layer uploads to avoid chmod errors

---

geonode/api/tests.py

This PR migrates from `unittest.assertEquals` to `unittest.assertEqual` which is deprecated from Python2.7:
```python
DeprecationWarning: Please use assertEqual instead.
```
Fixes #13180

[Fixes #13180] Resolve warnings of testing library

---

geonode/base/api/views.py

This PR was created according to this issue: #13159 

[Fixes #13159] Removing change ownership support from the `/permissions` endpoint

---

geonode/geoserver/management/commands/importlayers.py

A refactor of the `importlayers` script for the 4.4.x branch so it supports all data formats supported by the upload API. It makes use of the same `BaseHandler` classes used by the importer to check whether a file is valid for upload and whether all of the required files are present (it also checks for optional files).
It also adds the `--overwrite-existing-layers` and `--skip-existing-layers` flags. Although the `--skip-existing-layers` flag doesn't appear to be supported in the upload API yet.
By using the same `BaseHandler` classes as the importer the aim is help keep the `importlayers` command in sync with the importer. For example, if additional file extensions are added to handlers, or a completely new handler is introduced, the `importlayers` command should start supporting it …

[Fixes #13049 backport for 4.4.x] Update importlayers command to handle all data formats supported by the upload API (for 4.4.x)

---

geonode/metadata/handlers/sparse.py
geonode/metadata/tests/test_handlers.py

[Fixes #13275] SparseField: automatically generate thesauri autocomplete URL

---

.clabot
.env_dev
.env_local
.env_test
geonode/base/api/serializers.py
geonode/base/api/tests.py
geonode/groups/models.py
geonode/people/models.py
geonode/people/signals.py
geonode/resource/manager.py
geonode/security/registry.py
geonode/security/tests.py
geonode/settings.py

Fixes #13311
This PR optimizes the performance of the Resource API as described in the issue [GeoNode/geonode#13311](https://github.com/GeoNode/geonode/issues/13311). As mentioned in the issue, a test case has been written to validate the improvements. 
Fig: This figures shows initial curl request results without implementing cache on resource endpoint.
Fig: This figures shows curl request results  implementing cache on resource endpoint.
A local Python test script was also executed to evaluate cache performance and scalability. The results are shown below:
Fig: Performance test results demonstrating cache scalability.
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so …

[Fixes #13311]: Implement caching for User Permission retrieval for Resource Base Endpoints Reducing number of queries in Database.

---

geonode/assets/serializers.py
geonode/assets/utils.py
geonode/base/api/serializers.py
geonode/base/tests.py

[Fixes #13514] Extended the asset link serializer to inform the client whether an asset can be deleted or not
