geonode/base/api/permissions.py
geonode/base/api/tests.py
geonode/base/api/views.py

(cherry picked from commit 52ead579a04c97011056451063ccd7a9e669bf49)

[Backport to 3.2.x][Fixes #7325] Limit resource/{pk}/get_perms | set_perms to resource owner and admins

---

geonode/base/api/serializers.py
geonode/base/api/tests.py
geonode/base/models.py
geonode/geoapps/api/tests.py
geonode/people/models.py
geonode/security/models.py

(cherry picked from commit 2995fab606134d1cee8b6ed8333c70e81b7323cf)

[Backport to 3.2.x][Fixes #7327] Return permissions for the authenticated user inside the resource and user response

---

geonode/base/migrations/0045_auto_20200507_0445.py

(cherry picked from commit e55410228676df6d284b1df35fc08be9a2934055)

[Backport to 3.2.x] Fixes #7342 Migration breaks layers (#7357)

---

geonode/maps/models.py

Fixes get_legend_url on default layer style

[Fixes #7367] Error when Map Legend tries to read the name of the default style for a layer

---

geonode/base/templates/base/_resourcebase_snippet.html
geonode/client/templates/leaflet/maps/map_list.html
geonode/documents/templates/documents/document_list.html
geonode/geoapps/templates/apps/app_list_default.html
geonode/layers/templates/layers/layer_detail.html
geonode/layers/templates/layers/layer_list_default.html
geonode/maps/templates/maps/map_detail.html
geonode/maps/templates/maps/map_list_default.html
geonode/people/templates/people/profile_detail.html
geonode/services/templates/services/service_list.html
geonode/templates/500.html
geonode/templates/search/_search_content.html

Hide the create and Upload resources buttons for anonymous users

[Fixes #7380] Create resources buttons are enabled for Anonymous users

---

geonode/base/templates/base/_resourcebase_snippet.html
geonode/documents/templates/documents/document_list.html
geonode/geoapps/templates/apps/app_list_default.html
geonode/layers/templates/layers/layer_detail.html
geonode/layers/templates/layers/layer_list_default.html
geonode/maps/templates/maps/map_detail.html
geonode/maps/templates/maps/map_list_default.html
geonode/people/templates/people/profile_detail.html
geonode/services/templates/services/service_list.html
geonode/templates/500.html
geonode/templates/search/_search_content.html

[port master][Fixes #7380] Create resources buttons are enabled for Anonymous users

---

Dockerfile

[Issue description](https://github.com/OSGeo/gdal/issues/1692)

[Fixes #7362] GDAL upgrade to issue wtih postgres 12 and higher 

---

geonode/layers/utils.py
geonode/upload/utils.py

- Conversion `minus `in `underscore `for match the `schema_complaint `during layer `append/replace`
- Fix `KeywordHandler `to accept also `HierarchicalKeyword`

[Backport Resolves #7392] Fix upload/replace/append layer

---

geonode/maps/models.py

References: #7391
Consider a layer's default_style_name if the layer has a default style set.

[Fixes #7391] MapLegend shows wrong legend instead od the selected (default) style

---

geonode/templates/metadata_detail.html

References: #6995
Add block tag in `metadata_detail.html`

[Fixes #6995] Extend block template in metadata_detail

---

geonode/templates/metadata_form_js.html

References #7398
Fixes truncated tooltips on layer meta-data-form

[Fixes #7398] Truncated tooltips in advanced edit

---

geonode/templates/metadata_form_js.html

References #7398
Fixes truncated tooltips on layer meta-data-form

[Backport 3.2.x] [Fixes #7398] Truncated tooltips in advanced edit

---

geonode/maps/models.py

Enables Map Legend display style title if available else uses the name

[Fixes #7409] Map legend must use style title if available

---

geonode/maps/models.py

(cherry picked from commit edf64701d2c244ab8caa2079b90117fa944d2218)

[Backport to 3.2.x][Fixes #7409] Map legend must use style title if available

---

geonode/proxy/views.py

In the `gs` proxy, added encoding of data before sending it to Geoserver.

[Fixes #7267] Legend graphics will not render UTF-8 characters (eg. äöü)

---

geonode/base/models.py
geonode/base/templatetags/thesaurus.py
geonode/documents/views.py
geonode/layers/views.py
geonode/maps/views.py
geonode/settings.py

Fix flake8 format for master branch

---

geonode/geoapps/views.py

[Fixes #7456] Update of a GeoApp metadata returns a JSON message instead of redirecting to the GeoApp page

---

geonode/geoapps/views.py

(cherry picked from commit bba5432ebe4b1f4242b96726b610e5ad601ab140)

[Backport to 3.2.x][Fixes  #7456]Update of a GeoApp metadata returns a JSON message instead of redirecting to the GeoApp page

---

.env
Dockerfile
celery-cmd
docker-compose-test.yml
docker-compose.yml

[Fixes #7428] Port Celery optimizations from geonode-project

---

geonode/base/api/tests.py
geonode/base/api/views.py
geonode/services/serviceprocessors/arcgis.py
geonode/services/serviceprocessors/wms.py
geonode/services/tests.py

* modify remote service
* remove service from resource types
(cherry picked from commit fa210d4c25f288276ca79126156528595885093c)

[Backport to 3.2.x][Fixes #7442] Missing information for remote layers (#7443)

---

geonode/documents/views.py
geonode/geoapps/views.py
geonode/layers/views.py
geonode/maps/tests.py
geonode/maps/views.py

[Fixes #7444] Refactor how resource permissions are set inside the mapstore client context

---

geonode/documents/views.py
geonode/geoapps/views.py
geonode/layers/views.py
geonode/maps/tests.py
geonode/maps/views.py

(cherry picked from commit d6aea70ce7f721e9e5cc37d315416518bc4625d4)

[Backport to 3.2.x][Fixes #7444] Refactor how resource permissions are set inside the mapstore client context

---

requirements.txt
setup.cfg

Bump Django from 2.2.16 to 2.2.20

---

geonode/base/management/commands/set_all_layers_metadata.py
setup.cfg

References: #7435
Include UUID handling in `set_all_layer_metadata`.
With This approach, if `LAYER_UUID_HANDLER` esists will:
- Update the layer `uuid` based on the `LAYER_UUID_HANDLER` logic ([here ](https://docs.geonode.org/en/master/basic/settings/index.html#uuid-handler)is the doc just for reminder)
- Refresh the layer object from the DB
- Continue the normal flow …

[Fixes #7435] Include UUID handling in set_all_layer_metadata

---

geonode/api/api.py
geonode/templates/search/_sort_filters.html

References: #7477
Add sorting dropdown in Group Categories

[Fixes #7477] Sorting dropdown is blank for Group Categories

---

geonode/base/api/serializers.py
geonode/base/utils.py

[Fixes #7467] API returns some URLs as relative, others as absolute

---

geonode/base/api/serializers.py
geonode/base/utils.py

[Backport 3.2.x][Fixes #7467] API returns some URLs as relative, others as absolute

---

geonode/base/api/serializers.py
geonode/base/api/tests.py
geonode/context_processors.py
geonode/layers/tests.py
geonode/people/templates/people/profile_edit.html
geonode/settings.py
requirements.txt
setup.cfg

References: #7480
Documentation: https://github.com/GeoNode/documentation/pull/98

[Fixes #7480] Allow to exclude fields from the "Profile Edit" page

---

geonode/base/api/permissions.py
geonode/base/api/serializers.py
geonode/base/api/tests.py
geonode/base/api/urls.py
geonode/base/api/views.py
geonode/base/utils.py

[Fixes #7482]  Implement API v2 endpoints to complete the support for filtering

---

geonode/base/templates/base/_resourcebase_info_panel.html
geonode/templates/metadata_detail.html

References: #7490
Adding `|safe` tag to show the `&` in `_resourcebase_info_panel.html` and `metadata_detail.html`

[Fixes #7490] Keyword with "&" not correclty handled in resource preview

---

geonode/settings.py
geonode/urls.py
requirements.txt
setup.cfg

Bump geonode-oauth-toolkit to version 2.2.0

---

geonode/layers/api/serializers.py

[Fixes #7510] SLD body returned by GeoNode API is malformed

---

geonode/base/api/tests.py
geonode/base/api/views.py

[Fixes #7507] Owners API V2 Returns users with no resources

---

geonode/settings.py
geonode/urls.py
requirements.txt
setup.cfg

* Bump geonode-oauth-toolkit to version 2.2.0
* [Fixes:#7488] Prevent /o endpoints
* - Enable OIDC Views
(cherry picked from commit b19a9c0e9cf4ed19a13940b4abaf0ec5e6f8038a)
#	requirements.txt
#	setup.cfg
**Submitting the PR does not require you to check all items, but by the time it gets merged, …

[Backport to 3.2.x] Bump geonode-oauth-toolkit to version 2.2.0 (#7509)

---

geonode/layers/api/serializers.py

[Fixes #7526] Layer SLD URLs refer to the internal GeoServer address instead of the public one

---

geonode/layers/api/serializers.py

(cherry picked from commit f3745ceb79ee2973ed41d4f11a84d49ba1eba95a)

[Backport 3.2.x][Fixes #7526] Layer SLD URLs refer to the internal GeoServer address instead of the public one

---

.clabot
geonode/base/api/serializers.py
geonode/base/api/tests.py
geonode/base/api/views.py
geonode/documents/api/serializers.py
geonode/geoapps/api/serializers.py
geonode/layers/api/serializers.py
geonode/maps/api/serializers.py
geonode/upload/api/serializers.py

[Backport to 3.2.x][Fixes #7529] GeoNode V2 API layers, maps and resources responses do not include URLs for each resource

---

geonode/templates/base.html

(cherry picked from commit a6e522db364d1e1ba62737ca0064f46132bdcf08)

[Backport to 3.2.x] Change bootstrap-rtl css source to cloudflare (#7553)

---

geonode/base/utils.py
geonode/geoserver/helpers.py
geonode/utils.py

[Fixes #7580]: Missing sld_version parameter inside legend requests

---

geonode/base/utils.py
geonode/geoserver/helpers.py
geonode/utils.py

(cherry picked from commit a84f7b2bee447fe66527c165585e4afe3f0a335c)

[Backport to 3.2.x][Fixes #7580]: Missing sld_version parameter inside legend requests

---

geonode/base/api/serializers.py
geonode/base/api/tests.py
geonode/base/api/views.py

(cherry picked from commit 92de42c8cec9a486da2575d3940c8508a77bf9df)

[Backport to 3.2.x][Fixes #7571]: API v2 favorites

---

geonode/layers/templates/layers/layer_detail.html
geonode/layers/templatetags/layer_tags.py

[Fixes #7587]: Legend repeated twice in preview if style names are similar

---

geonode/services/templates/services/service_list.html

References: #7600
Replace "Register a new Service" with "Add Remote Service"

[Fixes #7600] Replace "Register a new Service" with "Add Remote Service"

---

geonode/settings.py

References #7623
This improves client and Geoserver performances on average.

[Fixes #7623] Set CSW default tile size 512px

---

geonode/utils.py

(cherry picked from commit 9497b81e344714cea3306185e3031218f266b51e)

[Backport to 3.2.x][Fixes: GeoNode#7618] Very slow upload on large instance (#7620)

---

geonode/geoapps/forms.py
geonode/geoapps/templates/apps/app_metadata.html
geonode/geoapps/templates/apps/app_metadata_advanced.html
geonode/geoapps/templates/layouts/app_panels.html
geonode/geoapps/views.py

References #7619
- fix thesauri in geostory
- align geostory with the other templates format

[Resolves #7619] Align geostory and fix issue with the thesauri

---

geonode/base/api/filters.py
geonode/base/api/tests.py
geonode/base/api/views.py

* Add favorite filter in Resource api/v2 enpoint
* Add filter for user also in favorite query
* [Fixes #7628] Pr fixes
(cherry picked from commit 97873bd72a9cade41239cd8f9a433de50c798a1d) …

[Backport to 3.2.x][Fixes #7628] Add favorite filter in Resource api/v2 enpoint (#7627)

---

requirements.txt

Revert "Bump sqlalchemy from 1.4.15 to 1.4.18"

---

requirements.txt

Revert "[Backport 3.2.x] Bump sqlalchemy from 1.4.15 to 1.4.18"

---

requirements.txt

Revert "Revert "Bump sqlalchemy from 1.4.15 to 1.4.18""

---

requirements.txt

Revert "Revert "[Backport 3.2.x] Bump sqlalchemy from 1.4.15 to 1.4.18""

---

geonode/thumbs/utils.py

In the WMS request, If the token is available, is now sent as `Berarer`

[Fixes #7696] Wrong authorization for WMS service

---

geonode/geoapps/views.py

relates to https://github.com/GeoNode/geonode/issues/7704

[Fixes #7704] Geostories raise an error on save

---

geonode/geoserver/management/commands/set_default_gridsets.py

[Fixes #7699] Automation to fix gridsets configurations for existing layers

---

geonode/client/templates/ol/maps/map_ol2.html
geonode/client/templates/ol/maps/map_ol3.html

[Fixes #7700] Wrong number formatting caused by i18n breaks metadata wizard widget

---

geonode/base/templates/base/_resourcebase_snippet.html
geonode/documents/templates/documents/document_list.html
geonode/geoapps/templates/apps/app_list_default.html
geonode/layers/templates/layers/layer_detail.html
geonode/layers/templates/layers/layer_list_default.html
geonode/maps/templates/maps/map_detail.html
geonode/maps/templates/maps/map_list_default.html
geonode/people/templates/people/profile_detail.html
geonode/services/templates/services/service_list.html
geonode/templates/500.html
geonode/templates/base.html

[Fixes  #7728] Enforce add_resourcebase permission control everywhere

---

geonode/base/views.py
geonode/people/forms.py

Fix reverse urls for get_url_for_app_model and get_url_for_model methods

[Backport][Fixes #7740] patch fix reverse urls

---

geonode/layers/api/serializers.py
geonode/layers/api/tests.py
geonode/layers/api/views.py

References #7789
- [ x Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.
- [] This PR passes all existing unit tests (test results will be reported …

[Fixes #7789]: Defer attributes_set property inside the API v2 datasets list endpoint

---

geonode/base/api/serializers.py
geonode/geoserver/helpers.py
geonode/geoserver/tests/test_helpers.py
geonode/upload/upload.py

Remove the translation of the subtype into storeType. Update function name that retrieves that information
MapstoreAdapter pr https://github.com/GeoNode/geonode-mapstore-client/pull/314

[Fixes #7794] Keep serializer consistent with the new ResourceBase.sutype

---

geonode/base/templates/base/_resourcebase_snippet.html
geonode/documents/templates/documents/document_list.html
geonode/geoapps/templates/apps/app_list_default.html
geonode/layers/templates/layers/layer_detail.html
geonode/layers/templates/layers/layer_list_default.html
geonode/maps/templates/maps/map_detail.html
geonode/maps/templates/maps/map_list_default.html
geonode/people/templates/people/profile_detail.html
geonode/services/templates/services/service_list.html
geonode/templates/500.html
geonode/templates/base.html

[Fixes #7757] Remove read only check inside templates

---

geonode/templates/base.html

References: #7803
This improvement add some extra blocks in the base.html template to allow to add new classes to the html and body tags

[Fixes #7803] Allow extensibility of classes of html and body tag inside the base.html temeplate

---

geonode/static/geonode/js/upload/upload.js

References: #7887
In a nutshell, the `getUploadItems` will fetch values from the API with the status `PROCESSED`.
The resource manager will re-set this status in various steps, so this scenario is possible:
- Start uploading the dataset
- finishing upload, but the thumbnail is missing, the status is set as `COMPLETED`
- Fetch upload status -> empty `JSON` means that there are uploads in progress
- Starting thumb creation -> status set as `PROCESSED`
- Fetching upload status -> the same upload `ID` is in processing, for the code is a new one
- Creation of a new row in the result table
The fix will remove the object from the process array if they are present in the upload one to emphasise that the prosses is not finished yet
> Reviewing is a process done by project maintainers, mostly on a …

[Fixes #7887] Duplicate row in upload UI with async flow active

---

celery-cmd
celery.sh
celery_dev.sh
pavement.py
requirements.txt
scripts/spcgeonode/docker-compose.override.yml
scripts/spcgeonode/docker-compose.yml
setup.cfg

[Backport to 3.2.x][Fixes #7895] File upload fails with 400 Bad Request

---

geonode/thumbs/thumbnails.py

[Fixes #7739] An empty map cannot be saved

---

geonode/thumbs/thumbnails.py

(cherry picked from commit 246d7b6bc47324b04f04276a1cd5cdb1bbdbe56f)
#	geonode/thumbs/thumbnails.py

[Backport to 3.3.x][Fixes #7739] An empty map cannot be saved (#7806)

---

geonode/thumbs/thumbnails.py

(cherry picked from commit 246d7b6bc47324b04f04276a1cd5cdb1bbdbe56f)
#	geonode/thumbs/thumbnails.py
(cherry picked from commit d3e38b49a7c80bb60fd57590a589f848a89abca8) …

[Backport to 3.2.x][Fixes #7739] An empty map cannot be saved (#7806)

---

geonode/base/api/views.py

Rename reference to MapstoreClient
related client pr: https://github.com/GeoNode/geonode-mapstore-client/pull/401

[Fixes #7921] Rename reference to MapstoreClient

---

geonode/resource/manager.py
geonode/resource/tests.py

[Fixes  #7923] Implement Test Cases for the Resource Manager

---

geonode/geoserver/manager.py
geonode/geoserver/security.py
geonode/security/tests.py

[Fixes #7931] Trying to set GeoLimits does not disable GWC cache

---

geonode/base/templates/base/batch_permissions.html
geonode/security/utils.py

[Backport 3.2.x][Fixes #7959] Unable to set permission using django admin 

---

geonode/base/templates/base/batch_permissions.html

[Fixes #7959] Unable to set permission using django admin

---

geonode/layers/templates/layers/layer_detail.html
geonode/layers/templates/layers/layer_list_default.html
geonode/security/tests.py
geonode/security/views.py
geonode/static/geonode/js/search/cart.js
geonode/templates/_bulk_permissions_form.html
geonode/templates/_permissions.html
geonode/templates/_update_permissions_modal.html
geonode/templates/search/_search_content.html

[3.2.x][Fixes #7999] Set bulk permissions from resources list pages

---

geonode/harvesting/harvesters/geonode.py
geonode/layers/api/serializers.py
geonode/layers/api/tests.py

[Fixes #8018] FeatureInfoTemplate from REST API v2 not properly working

---

geonode/maps/templates/maps/map_detail.html

[Fixes #8008] Remove WMS GetCapabilities link from map detail page

---

geonode/security/models.py
geonode/security/permissions.py
geonode/security/tests.py

[Fixes #8025] Get user permission on ResourceBase model always returns the full set of perms despite the 'subtype'

---

geonode/client/hooksets.py

[3.3.x][Fixes #8005] Create an abstract GeoNode hook for the layer export

---

.env
entrypoint.sh

Moved invokeadmin inside the first tasks block, that is executed only the first time or when the FORCE_REINIT env is set.
This PR fixes the [issue](https://github.com/GeoNode/geonode-project/issues/211)
**Submitting the PR does not require you to check all items, but by the time it gets merged, they …

Change location of invokeadmin task.

---

geonode/layers/templates/layers/layer_detail.html
geonode/layers/templates/layers/layer_list_default.html
geonode/security/tests.py
geonode/security/views.py
geonode/static/geonode/js/search/cart.js
geonode/templates/_bulk_permissions_form.html
geonode/templates/_update_permissions_modal.html
geonode/templates/search/_search_content.html

[Backport3.3.x][Fixes #7999] Set bulk permissions from resources list pages

---

geonode/templates/base.html

[Fixes #7927] Docker 3.3.x GeoNode core theme is not changing

---

geonode/people/templates/people/profile_detail.html
geonode/templates/500.html

[3.3.x][Fixes #8051] Wrong URL inside Admin profile -> GeoServer Tab.

---

geonode/people/templates/people/profile_detail.html
geonode/templates/500.html

 [Fixes #8051] Wrong URL inside Admin profile -> GeoServer Tab.

---

geonode/people/templates/people/profile_detail.html
geonode/templates/500.html

[Backport 3.2.x] [Fixes #8051] Wrong URL inside Admin profile -> GeoServer Tab.

---

README.md

- [v ] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [v ] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.
The following are required only for core and extension modules (they are welcomed, but …

Small fix installation doc URL

---

geonode/services/tasks.py

[Fixes #8099] fix service url for remote service handler

---

geonode/geoserver/manager.py
geonode/geoserver/security.py
geonode/resource/manager.py

Revert "[master][Fixes #8112] Dump and restore Geofence rules in case of requests or …"

---

docker-compose.yml

[3.3.x] 3.3.x updated to geoserver 2.19.x

---

geonode/settings.py
requirements.txt
setup.cfg

References: #8156
Added `django-user-requests` to the requirements.txt and settings.py.
* To manually test and use the library: [usage](https://github.com/selwin/django-user_agents#usage)
* Here is a quick snippet that can be added inside any template:
```html
<hr/>
<p>{{request.user_agent}}</p>
<p>Is mobile: {{request.user_agent.is_mobile}}</p>
<hr/>
```
* Result on PC:
* Result on Smartphone:
The following are required only for core and extension modules (they are welcomed, but not required, …

[Fixes #8156] Implement mobile detection

---

geonode/settings.py
requirements.txt
setup.cfg

References: #8156
Added `django-user-requests` to the requirements.txt and settings.py.
* To manually test and use the library: [usage](https://github.com/selwin/django-user_agents#usage)
* Here is a quick snippet that can be added inside any template:
```html
<hr/>
<p>{{request.user_agent}}</p>
<p>Is mobile: {{request.user_agent.is_mobile}}</p>
<hr/>
```
* Result on PC:
* Result on Smartphone:
The following are required only for core and extension modules (they are welcomed, but not required, …

[3.3.x][Fixes #8156] Implement mobile detection

---

geonode/base/templates/base/_resourcebase_snippet.html
geonode/documents/templates/documents/document_detail.html
geonode/geoapps/templates/apps/app_detail.html
geonode/layers/templates/layers/layer_detail.html
geonode/maps/templates/maps/map_detail.html
geonode/templates/_actions.html
geonode/templates/base.html
geonode/templates/index.html
geonode/templates/search/_pagination.html
geonode/templates/search/_search_content.html
geonode/templates/search/_text_filter.html

Disable some GeoNode features when viewed from mobile only for 3.3.x
refers to #8161 

[Fixes #8161] Disable some GeoNode features when viewed from mobile

---

geonode/people/templates/people/_profile_filters.html
geonode/people/templates/people/profile_detail.html
geonode/static/geonode/js/search/search.js

[3.3.x][Fixes #8058] GeoStory: missing actions in user profile page

---

geonode/people/templates/people/_profile_filters.html
geonode/people/templates/people/profile_detail.html
geonode/static/geonode/js/search/search.js

References  #8058
> Reviewing is a process done by project maintainers, mostly …

[Backport 3.2.x][Fixes #8058] GeoStory: missing actions in user profile page

---

geonode/favorite/tests.py
geonode/favorite/urls.py
geonode/favorite/views.py
geonode/geoapps/templates/apps/app_detail.html
geonode/geoapps/views.py

[3.3.x][Fixes #8059]GeoStory: missing "favorite" handling

---

geonode/base/templates/base/_resourcebase_snippet.html
geonode/client/templates/leaflet/maps/map_list.html
geonode/documents/templates/documents/document_list.html
geonode/geoapps/templates/apps/app_list_default.html
geonode/layers/templates/layers/layer_detail.html
geonode/layers/templates/layers/layer_list_default.html
geonode/maps/templates/maps/map_list_default.html
geonode/people/templates/people/profile_detail.html
geonode/static/geonode/css/base.css
geonode/static/geonode/less/base.less
geonode/static/geonode/less/mobile.less
geonode/static/package.json
geonode/templates/_actions.html
geonode/templates/account/signup.html
geonode/templates/base.html
geonode/templates/index.html
geonode/templates/search/_search_content.html

[3.3.x][Fixes #8180] CSS improvements for mobile 3.3.x only

---

geonode/favorite/tests.py
geonode/people/fixtures/mock_processor.py
geonode/people/templates/people/_profile_filters.html
geonode/people/templates/people/profile_detail.html
geonode/people/tests.py
geonode/social/apps.py
geonode/social/signals.py
geonode/social/templates/social/activity_list.html
geonode/social/templatetags/social_tags.py
geonode/social/tests.py
geonode/social/views.py
geonode/static/geonode/css/base.css
geonode/static/geonode/less/base.less
geonode/utils.py

[3.3.x][Fixes #8294] Remove dependencies and references to MapStore adapter apps inside PRs

---

geonode/documents/templates/documents/document_upload.html

[3.3.x][Fixes #8179] Bad behaviour in upload page when no file is selected

---

geonode/base/models.py
geonode/geoserver/helpers.py
geonode/resource/manager.py
geonode/security/permissions.py
geonode/security/tests.py

[Fixes #8320] Edit compact permission for registered users don't return download_permisison for documents

---

geonode/geoserver/tests/test_helpers.py
geonode/geoserver/tests/test_server.py
geonode/geoserver/urls.py
geonode/geoserver/views.py

(cherry picked from commit f283a12922f18384bba46d1c8ba446c2c99271b0)
(cherry picked from commit 6dfe68587ae284686cfdd535b95249cc2dea9d9b)

[Backport to 3.2.x][Fixes #8318] Wrong match for Geoserver path (#8344)

---

geonode/geoapps/templates/apps/app_detail.html
geonode/settings.py

[Fixes #8326] fixes category for geoapps ratings

---

geonode/settings.py

* fixes category for geoapps ratings
* fix typo
(cherry picked from commit 066df2e1f25e84efe63be379d9e62b3d4568f239)
#	geonode/geoapps/templates/apps/app_detail.html …

[Port to master][Fixes #8326] fixes category for geoapps ratings (#8339)

---

geonode/security/models.py
geonode/security/tests.py

(cherry picked from commit 23c04e61ccc287e2453826661fd90534bbd752f9)

[Port to master][Fixes #8341] Duplicate permission on layers

---

geonode/geoapps/tests.py
geonode/geoapps/views.py

[3.2.x][Fixes #8325] Geoapp thumbnails uploaded from the MapStore client disappear after saving the metadata from the wizard

---

geonode/geoapps/tests.py
geonode/geoapps/views.py

[3.3.x][Fixes #8325] Geoapp thumbnails uploaded from the MapStore client disappear after saving the metadata from the wizard

---

geonode/base/api/serializers.py
geonode/base/api/tests.py
geonode/security/permissions.py
geonode/security/tests.py

[References #8361] Backend: Report if a user is admin or superstaff in permissions response

---

geonode/documents/templates/documents/document_detail.html

This PR replace the current width of video document preview from 500px to 100% in this way the video will fit the container also on mobile devices

[3.3.x][Fixes #8322] The video preview is not displayed correctly on mobile

---

geonode/maps/views.py

[Fixes #8379] Make add_layers use map_edit view

---

geonode/context_processors.py
geonode/people/templates/people/profile_detail.html

[Fixes #8420] Hide Connected social accounts link from profile if no social provider + app is configured

---

geonode/context_processors.py
geonode/people/templates/people/profile_detail.html

[Backport 3.2.x][Fixes #8420] Hide Connected social accounts link from profile if no social provider + app is configured

---

geonode/documents/templates/documents/document_detail.html

[Fixes #8454] Rating average available only in English

---

geonode/documents/templates/documents/document_detail.html

(cherry picked from commit 3418d0917f1b5c131f40087a97e689daed713e6c)

[Backport to 3.2.x][Fixes #8454] Rating average available only in English (#8455)

---

geonode/geoserver/ows.py
geonode/geoserver/tests/test_server.py
geonode/utils.py

[Backport to 3.3.x][Fixes #8461] WCS getCoverage links have wrong params

---

geonode/geoserver/ows.py
geonode/geoserver/tests/test_server.py
geonode/utils.py

(cherry picked from commit 3cd6a923fcb2709e3ae0ef0a2c632f1aef00810c)

[Backport to 3.2.x][Fixes #8461] WCS getCoverage links have wrong params

---

geonode/groups/templates/groups/category_list.html
geonode/groups/templates/groups/group_list.html

[Fixes #8459] Create a New Group button should be hidden to non-super users

---

geonode/api/resourcebase_api.py
geonode/context_processors.py
geonode/people/templates/people/_profile_filters.html
geonode/people/templates/people/profile_detail.html
geonode/static/geonode/js/search/search.js
geonode/utils.py

[Fixes #8058] GeoStory: missing actions in user profile page

---

geonode/proxy/tests.py
geonode/proxy/views.py
requirements.txt
setup.cfg

[3.2.x][Fixes #8458] Direct download timeout with big files

---

geonode/api/resourcebase_api.py
geonode/client/templates/ol/maps/map_ol3.html
geonode/geoserver/views.py
geonode/layers/api/tests.py
geonode/layers/api/views.py
geonode/layers/models.py
geonode/layers/templates/datasets/dataset_granule_remove.html
geonode/maps/api/serializers.py
geonode/maps/api/tests.py
geonode/maps/api/views.py
geonode/maps/models.py
geonode/maps/templates/maps/wmc.xml
geonode/resource/manager.py
geonode/thumbs/tests/test_integration.py
geonode/thumbs/tests/test_unit.py
geonode/thumbs/thumbnails.py

[Fixes #8504] Implement maps / dataset relationships endpoints

---

geonode/base/api/serializers.py

[Fixes #8534] Include links inside resources API v2 response

---

geonode/base/api/serializers.py
geonode/base/api/tests.py

[Backport 3.2.x][Fixes #8534] Include links inside resources API v2 response

---

geonode/base/api/serializers.py
geonode/base/api/tests.py

[Backport 3.3.x][Fixes #8534] Include links inside resources API v2 response

---

geonode/templates/account/email/email_confirmation_message.txt
geonode/templates/account/email/email_confirmation_subject.txt
geonode/templates/account/email/invite_user.txt
geonode/templates/account/email/invite_user_subject.txt
geonode/templates/account/email/password_reset_key.txt
geonode/templates/invitations/email/email_invite_message.html
geonode/templates/invitations/email/email_invite_message.txt
geonode/templates/invitations/email/email_invite_subject.txt

[Fixes #8425] Space in sitename not escaped in invitation mail body

---

geonode/geoserver/manager.py
geonode/geoserver/security.py
geonode/resource/manager.py
geonode/resource/tests.py

[Fixes #8565] Dataset Clone does not seem to be setting the GeoFence …   …rules correctly

---

geonode/resource/manager.py

[Fixes #8579] Dataset Clone should put private permissions by default

---

geonode/base/api/tests.py
geonode/base/api/views.py

[Fixes #8629] set_thumbnail response should include the URL to the updated thumbnail

---

geonode/geoserver/signals.py
geonode/geoserver/tasks.py
geonode/geoserver/tests/test_tasks.py

[Fixes #8650] Set style editor support metadata for dataset default style at creation time

---

.devcontainer/.env
geonode/settings.py
requirements.txt
setup.cfg

[Fixes #8646][Upload Improvements] Get rid of STATIC MIDDLEWHARES AWS and CACHE_BUSTING in favor of WhiteNoise

---

geonode/settings.py

[Fixes  #8665] Include new languages variables and file extensions for the client

---

geonode/documents/templates/documents/document_embed.html
geonode/documents/views.py

This PR remove the default preview in favor of the one provided by the client and ensure all document type are rendered in the template removing the direct download.
related to https://github.com/GeoNode/geonode-mapstore-client/pull/738
**Submitting the PR does not require you to check all items, but …

[Fixes #8663] Remove automatic download from document embed template

---

geonode/documents/templates/documents/document_metadata_advanced.html

[Fixes #8681] TemplateSyntaxError on document Advanced Metadata form

---

geonode/geoserver/tests/test_tasks.py
geonode/proxy/tests.py

[WIP] Fix failing test

---

geonode/services/forms.py
geonode/services/serviceprocessors/handler.py
geonode/services/tasks.py
geonode/services/tests.py
geonode/services/utils.py
geonode/services/views.py

- Service type are now pluggable like we did in past with [metadata_storer](https://docs.geonode.org/en/master/basic/settings/index.html?#metadata-storers) and [metadata_parser](https://docs.geonode.org/en/master/basic/settings/index.html?#metadata-parsers) through `SERVICES_TYPE_MODULES` variable
- The list of services available is now available through `get_available_service_type` function (will return default + custom from external libs)
- Fix choices from form to use `get_available_service_type` function
- tests coverage
Refs [#8422](https://github.com/GeoNode/geonode/issues/8422)
Doc: https://github.com/GeoNode/documentation/pull/204
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if …

[Fixes #8422] Added pluggable service types

---

geonode/base/api/tests.py
geonode/base/api/views.py
geonode/security/tests.py

[Fixes #8691] Geonode 3.3.x build is broken

---

geonode/settings.py

[Fixes #8693] Add variable for translations path for geonode-mapstore-client

---

geonode/geoserver/helpers.py
geonode/layers/utils.py

[3.3.x][Fixes #8641] Replace Layer (stable 3.2.x)

---

geonode/geoserver/helpers.py
geonode/layers/utils.py

[Backport 3.2.x] [Fixes #8641] Replace Layer (stable 3.2.x)

---

geonode/api/resourcebase_api.py
geonode/base/templatetags/base_tags.py
geonode/documents/forms.py
geonode/templates/search/_type_filters.html

References: #8499
Add GeoApp subtype on facet filters

[Backport to 3.3.x][Fixes #8499] Added GeoApp types missing to search filter

---

geonode/api/resourcebase_api.py
geonode/base/templatetags/base_tags.py
geonode/documents/forms.py
geonode/templates/search/_type_filters.html

[Backport to 3.2.x][Fixes #8499] Added GeoApp types missing to search filter 

---

geonode/documents/forms.py
geonode/documents/templates/documents/document_replace.html
geonode/documents/tests.py
geonode/documents/urls.py
geonode/documents/views.py

[Fixes #8698] Document replace page is not availalable anymore

---

geonode/client/templates/ol/maps/map_ol2.html
geonode/maps/views.py

[Fixes #8679] Unable to update map thumbnail on metadata form

---

geonode/documents/views.py

[Fixes #8723] Return plain text error response when document upload is run with no__redirect

---

geonode/upload/admin.py
geonode/upload/api/serializers.py
geonode/upload/api/tests.py
geonode/upload/api/views.py
geonode/upload/forms.py
geonode/upload/migrations/0035_update_uploadsizelimit_objects.py
geonode/upload/models.py
geonode/upload/tests/integration.py

[Fixes #8720] Change total_upload_size_sum slug to dataset_upload_size

---

geonode/resource/manager.py

[Fixes #8721] Missing resource type for some uploaded datasets

---

geonode/upload/tests/test_utils.py
geonode/upload/utils.py

Add function to get upload size

---

geonode/geoapps/templates/apps/app_detail.html
geonode/layers/templates/layers/layer_detail.html
geonode/maps/templates/maps/map_detail.html

[Backport 3.3.x][Fixes #8454] Rating average available only in English

---

geonode/geoapps/templates/apps/app_detail.html
geonode/layers/templates/layers/layer_detail.html
geonode/maps/templates/maps/map_detail.html

[3.2.x][Fixes #8454] Rating average available only in English

---

geonode/base/api/serializers.py
geonode/base/api/tests.py
geonode/base/api/views.py

References #8700 
- [ x There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users) …

[Fixes #8700]  Add the option to include the executions status of a resource inside the resources API response

---

geonode/base/api/serializers.py
geonode/base/api/tests.py
geonode/base/api/views.py
geonode/base/models.py

 [Fixes #8793] Add is_copyable property to the resource

---

geonode/upload/forms.py

fix typo in file_fields

---

geonode/geoserver/tests/test_server.py
geonode/geoserver/views.py

[Backport to 3.3.x][Fixes #8858] Support "workspaced" requests on GeoServer proxy view

---

geonode/geoserver/tests/test_server.py
geonode/geoserver/views.py

(cherry picked from commit 85e45c6d249c2407a1c8b87f8b58ac9d38fa2f36)

[Backport to 3.2.x][Fixes #8858] Support "workspaced" requests on GeoServer proxy view

---

geonode/geoserver/tests/integration.py

[Fixes #8849] Add tests for the automatic permissions set when a new resource is created

---

geonode/layers/tests.py
geonode/layers/views.py

refers to [#8873 ](https://github.com/GeoNode/geonode/issues/8873#issuecomment-1058261934) endpoint open to anonymous user

[Fixes #8873] Permissions not checked on the direct download button of a resource

---

geonode/base/management/commands/migrate_baseurl.py

[Fixes #8910] "migrate_baseurl" Management Command does not replace  the "source-address" on all the "blobs"

---

geonode/upload/tests/test_utils.py
geonode/upload/utils.py

Add function to get max upload parallelism limit for a given slug

---

geonode/upload/views.py

ref https://github.com/GeoNode/geonode/issues/8939

[Fixes #8939] Fix store_spatial_files in upload form

---

geonode/base/api/exceptions.py
geonode/layers/api/exceptions.py
geonode/layers/api/serializers.py
geonode/layers/api/tests.py
geonode/layers/api/views.py
geonode/layers/models.py
geonode/layers/utils.py

Issue 8946

---

geonode/documents/views.py

[Fixes #8950] DocumentUploadView exception return HTML instead of JSON

---

geonode/base/api/permissions.py
geonode/base/api/tests.py
geonode/base/api/views.py
geonode/documents/api/views.py
geonode/geoapps/api/tests.py
geonode/geoapps/api/views.py
geonode/layers/api/views.py
geonode/maps/api/views.py
geonode/resource/api/urls.py
geonode/upload/api/tests.py
geonode/upload/api/views.py

* - define http_method_names on API v2 views
* - add tests for groups and users
* - update tests
* - update tests
* - improve groups permissions on API
* fix lgtm
* - allow only get and post on UploadParallelismLimitViewSet
* - remove duplicate http_method_names
- add more tests
Co-authored-by: mattiagiupponi <51856725+mattiagiupponi@users.noreply.github.com>
(cherry picked from commit a83936f757d9c4f38d651170ec986810422018bd)
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so …

[Backport 8911 to 4.x][Fixes #8908] Review API v2 allowed methods (#8911)

---

geonode/services/tasks.py

[Fixes #8987]Add missing option for list remote resources

---

geonode/base/models.py

[Fixes #8984] Error adding remote services

---

geonode/base/api/tests.py
geonode/base/api/views.py

* -[Fixes #9044] Lots of keywords disconnected from resources
* - update tests
(cherry picked from commit 8eabf0f5373696712a3b2f3b30a38ee6b4501a3a)

[Backport to 4.x][Fixes #9044] Lots of keywords disconnected from resources (#9045)

---

geonode/upload/api/tests.py
geonode/upload/tasks.py

[Fixes #9056] Layer upload via API stuck in status waiting

---

.circleci/config.yml
geonode/br/tasks.py
geonode/documents/tasks.py
geonode/geoserver/helpers.py
geonode/geoserver/tasks.py
geonode/layers/tasks.py
geonode/monitoring/tasks.py
geonode/tasks/tasks.py
geonode/upload/tasks.py
pavement.py

[Fixes #9064] Improve Upload Workflow resources state management

---

.circleci/config.yml
geonode/br/tasks.py
geonode/documents/tasks.py
geonode/geoserver/helpers.py
geonode/geoserver/tasks.py
geonode/layers/tasks.py
geonode/monitoring/tasks.py
geonode/tasks/tasks.py
geonode/upload/tasks.py
pavement.py

Backport 9066 to 4.x

---

geonode/upload/views.py

 - Regression: data_retriever tempo folder issue

---

geonode/geoserver/upload.py
geonode/upload/models.py
geonode/upload/tasks.py
geonode/upload/upload.py
geonode/upload/views.py

Better and consistent management of the upload/importer sessions states.

[3.3.x] Upload Workflow Stabilization and correct state management

---

geonode/base/api/tests.py
geonode/resource/manager.py
geonode/security/permissions.py
geonode/security/tests.py

[Fixes #9106] Implement API for compact permissions

---

geonode/base/models.py
geonode/geoserver/manager.py
geonode/upload/models.py
geonode/upload/tasks.py
geonode/upload/upload.py
geonode/upload/views.py

[Fixes #9136] Async Upload deletes Importer folders cusing GeoServer to trigger the import again

---

dev_config.yml
docker-compose-geoserver-server.yml
docker-compose-test.yml
docker-compose.yml

bump to GeoServer 2.19.6

---

geonode/geoapps/tests.py
geonode/geoapps/views.py

[Fixes #9108] Unable to add category to geostories and dashboards

---

setup.cfg

[Dependencies] Align requirements to setup.cfg

---

geonode/security/utils.py

[Fixes #9163] Advanced Workflow: Demotion/Promotion/removal of managers in owner's group is not working; it works for the resource group

---

geonode/resource/manager.py
geonode/upload/models.py
geonode/upload/tasks.py
geonode/upload/views.py

[Fixes #9166] Upload Workflow: The upload api keeps calling the "final" step causing inconsistent states

---

geonode/static/geonode/js/upload/LayerInfo.js

[Fixes #9154] Remove buttons action after style and metadata upload

---

geonode/layers/views.py

[Fixes #9184] Let final step work in async mode for layer replace

---

geonode/base/models.py
geonode/upload/models.py
geonode/upload/tasks.py
geonode/upload/upload.py

[Fixes #9186] Upload marks as PROCESSED a resource not ready yet

---

requirements.txt
setup.cfg

Bump django-geonode-mapstore-client to version 4.0.0

[Dependencies] Bump django-geonode-mapstore-client to version 4.0.0

---

geonode/base/api/tests.py
geonode/geoapps/tests.py
geonode/geoserver/manager.py
geonode/layers/tests.py
geonode/resource/manager.py
geonode/resource/tests.py
geonode/resource/utils.py
geonode/tests/csw.py

[Fixes #9188] Unable to clone/copy geoapps

---

requirements.txt
setup.cfg

[Dependencies] Bump django-geonode-mapstore-client to version 4.x

---

CHANGELOG.md
geonode/__init__.py

Bump to version 4.0.0rc0

---

requirements.txt

[Fixes #9200] Reference client 4.0.1 inside branch 4.x

---

requirements.txt
setup.cfg

[Fixes #9208] Fix mapstore client version in setup.cfg and requirements

---

geonode/base/auth.py
geonode/security/middleware.py
geonode/security/tests.py
geonode/settings.py

[Fixes #9212] Login with basic auth or token headers or apikey GET parameter

---

geonode/base/management/commands/migrate_baseurl.py

[Fixes #9205] Include Dataset.ows_url inside migrate_url

---

setup.cfg

[Dependencies] Align setup.cfg to requirements

---

geonode/upload/upload.py

[Fixes #9250] Upload: task.set_charset(charset) may cause blocking error in case the GeoServer catalog has not aligned yet

---

setup.cfg

[Dependencies] Align "setup.cfg" with "requirements.txt"

---

geonode/base/templatetags/base_tags.py
geonode/maps/templates/maps/map_detail.html

Owner is unable to delete a published/approved map and Request Change button is shown on map with a user having permissions to edit in A/W
Ref #9283 

Owner is unable to delete a published/approved map and Request Change button is shown on map with a user having permissions to edit in A/W

---

setup.cfg

[Dependencies] Align "setup.cfg" to "requirements.txt"

---

geonode/harvesting/admin.py
geonode/resource/manager.py
geonode/services/serviceprocessors/wms.py

[Fixes #9312] Harvesters admin page is broken

---

geonode/resource/manager.py

[Fixes #9315] Avoid the "set_permissions" method breaks the dataset in the case a perm cannot be assigned to the resource

---

geonode/security/utils.py

Revert "[Fixes #9332] A/W: owner should not have any modification permission on published resource"

---

geonode/security/tests.py

[Fixes #9332][Test Cases] A/W: owner should not have any modification permission on published resource

---

geonode/upload/admin.py

[Fixes #9314] Error on Searching uploads in Admin Site

---

geonode/upload/admin.py

[4.x][Fixes #9314] Error on Searching uploads in Admin Site

---

geonode/upload/admin.py

[3.3.x][Fixes #9314] Error on Searching uploads in Admin Site

---

.env
.env_dev
.env_local
.env_test

[Fixes #9418] change the default JAVA_OPTS to the public URL inside GeoNode .env file

---

geonode/base/api/filters.py
geonode/base/api/tests.py

[Fixes #9389] Geoapps are added to favorites but not listed on client UI

---

geonode/api/api.py
geonode/api/authorization.py
geonode/api/tests.py
geonode/base/api/tests.py
geonode/base/api/views.py
geonode/people/tests.py
geonode/people/urls.py
geonode/people/utils.py
geonode/people/views.py
geonode/tests/smoke.py
geonode/views.py

[Fixes #9381] Hide users to anonoymous users and restric visibility for authenticated users

---

requirements.txt
setup.cfg

Bump gn-gsimporter to version 2.0.4

---

requirements.txt

Bump django-geonode-mapstore-client to version 3.3.2

---

geonode/api/resourcebase_api.py

[Fixes #9471] add resource_type as filter in legacy API

---

.env

[Fixes #9475] PRINT_BASE_URL on JAVA_OPTS should be pointing to localhost:8080 on default env

---

CHANGELOG.md
geonode/__init__.py

Bump to version 3.3.2.post1

---

geonode/security/tests.py
geonode/security/utils.py

[Fixes #9498] Documents, Maps and GeoApps permissions are not persisted on GeoNode

---

geonode/br/management/commands/restore.py

[Fixes #9518] br/restore call to migrate always fails

---

geonode/br/management/commands/restore.py

[Backport 4.x][Fixes #9518] br/restore call to migrate always fails

---

geonode/br/management/commands/restore.py

[Backport 3.3.x] [Fixes #9518] br/restore call to migrate always fails

---

setup.cfg

[Dependencies] Align "setup.cfg" to "requirements.txt" (#9588)

---

geonode/tests/test_utils.py
geonode/utils.py

function rename based on this comment https://github.com/GeoNode/geonode/pull/9612/files/9ca2d7c8fe5d8c15c4546d13482f7f0a0b22045d#r914838740
The pr on master was already merged
also the client should be merged: https://github.com/GeoNode/geonode-mapstore-client/pull/1068
**Submitting the PR does not require you to check all items, but by the time it gets merged, they should …

[Fixes #9591] Expose supported upload file formats as configurations

---

geonode/settings.py
pavement.py

[Fixes #9652] Avoid Whitenoise compression if not explicitly needed

---

geonode/views.py

[Fixes #9687] fix Geoserver public location in ident_json

---

geonode/locale/it/LC_MESSAGES/django.po

Fix typo in italian translation, issue #9683

Fix #9683 typo in italian translation

---

geonode/people/password_validators.py
geonode/people/tests.py

[Fix #9685] Implement additional password validators

---

geonode/resource/migrations/0006_executionrequest_action.py

fix error in refactor

---

setup.cfg

[dependencies] align setup.cfg to requirements.txt

---

geonode/layers/views.py

[Fixes #9754] handle get_dataset_detail_context returned value

---

geonode/security/tests.py

* fix SessionControlMiddleware test
* fix assertion
* cleanup
#	geonode/security/tests.py

[Backport to 4.x][Fixes #9752] fix SessionControlMiddleware test (#9753)

---

.circleci/config.yml
.env_test
geonode/people/utils.py
geonode/resource/api/tests.py
geonode/settings.py
geonode/tests/csw.py
geonode/tests/test_headers.py
geonode/tests/test_utils.py

Fixes CSW test cases

---

geonode/layers/views.py

[Fixes #9761] simplify map embed biew

---

.clabot
README.md
geonode/layers/views.py
geonode/locale/it/LC_MESSAGES/django.po
requirements.txt

[Backport to 4.x]  - Bunch of minor improvements that must be backported to 4.x

---

geonode/layers/views.py

Co-authored-by: Alessio Fabiani <alessio.fabiani@geosolutionsgroup.com>
#	geonode/layers/views.py

[Backport to 4.x] simplify map embed biew (#9762)

---

geonode/documents/tests.py
geonode/geoserver/helpers.py
geonode/invitations/forms.py
geonode/layers/utils.py
geonode/maps/tests.py
geonode/security/tests.py
geonode/utils.py
setup.cfg

[Backport to 4.x] Dependencies alignement 4.x

---

geonode/geoserver/management/commands/importlayers.py
geonode/upload/upload.py

[Fixes #9797] "importlayers" management command ignores sidecar and zip files

---

geonode/base/api/permissions.py
geonode/base/api/views.py
geonode/security/tests.py

[Fixes #9816] Cannot add favorite

---

geonode/base/api/permissions.py

[Fixes #9838] forever loading state on index site (API returns 403)

---

geonode/base/migrations/0084_remove_comments_from_actions.py
geonode/context_processors.py
geonode/documents/__init__.py
geonode/geoapps/__init__.py
geonode/geoserver/__init__.py
geonode/geoserver/helpers.py
geonode/groups/templates/groups/activity.html
geonode/groups/views.py
geonode/layers/__init__.py
geonode/maps/__init__.py
geonode/messaging/notifications.py
geonode/notifications_helper.py
geonode/settings.py
geonode/social/signals.py
geonode/social/templates/social/activity_list.html
geonode/social/templatetags/social_tags.py
geonode/social/views.py
geonode/templates/_actions.html
geonode/templates/about.html
geonode/templates/pinax/notifications/document_comment/full.txt
geonode/templates/pinax/notifications/document_comment/short.txt
geonode/templates/pinax/notifications/layer_comment/full.txt
geonode/templates/pinax/notifications/layer_comment/short.txt
geonode/templates/pinax/notifications/map_comment/full.txt
geonode/templates/pinax/notifications/map_comment/short.txt

[Fixes #9881] AttributeError on viewing recent activities

---

geonode/resource/models.py

[Backport 4.x][Fixes #9878] drf_spectacular error breaks redoc and swagger-ui schemas

---

geonode/geoserver/helpers.py

WIP - fix broken tests

---

setup.cfg

[Dependencies] Align requirements.txt with setup.cfg

---

geonode/base/utils.py
geonode/layers/templates/layers/layer_detail.html
geonode/templates/metadata_detail.html

[3.3.x][Fixes #9921] Original Layer / Dataset not offered as Download on layer detail page

---

geonode/base/api/tests.py
geonode/people/utils.py

[Fixes #9919] User endpoint return 404 if user is not in registered members

---

setup.cfg

[dependencies] Align "setup.cfg" to the "requirements.txt" file

---

geonode/base/api/tests.py
geonode/layers/forms.py
requirements.txt
setup.cfg

Bump djangorestframework to version 3.12.0

---

geonode/base/api/permissions.py
geonode/base/api/views.py
geonode/resource/api/views.py

[#Fixes #9970] Fix users has perms

---

geonode/geoserver/helpers.py

[Fixes #9960] Unable to edit style for cloned datasets

---

.circleci/config.yml
requirements.txt
setup.cfg

[Fixes #9972] SECURITY - Outdated requirements.txt for branch 3.3.x

---

geonode/geoserver/helpers.py

[Fixes #9987] Avoid call to delete the style if is the default one

---

README.md

Revert "Deprecated branch notice"

---

requirements.txt

switched to client 4.0.x

---

geonode/geoserver/helpers.py
geonode/geoserver/tasks.py

(cherry picked from commit 40fae5b3240ddf5b033688ce1891d7e7f1cfc304)
References: #10024
Solves the problem of bad styles assigned to layer.
- Main fix is by setting proper lock ids in celery tasks.
- Added lot of debug logging, also useful for post-mortem investigations
- Split some nested commands and improved robustness

[Fixes #10024] Wrong default style when creating layer

---

setup.cfg

[Dependencies] Align setup.cfg with requirements.txt

---

geonode/documents/migrations/0036_clean_document_thumbnails.py
geonode/documents/models.py
geonode/documents/tasks.py

[Fixes #10040] Remove auto-generated thumbnail for documents

---

requirements.txt

Revert "Bump djangorestframework from 3.12.0 to 3.14.0"

---

geonode/layers/management/commands/importlayers.py

Currently, the importlayers management command, fails, because it is making a put request. And the endpoint expects a post requests. Changed that in the file importlayers.py. 
**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied …

Fix: importlayers change put to post

---

geonode/social/templates/social/activity_list.html

[Fixes #10073] Unable to view Maps tab in Recent activities

---

geonode/static/geonode/js/upload/time.js
geonode/upload/templates/upload/dataset_upload_base.html
geonode/upload/templates/upload/dataset_upload_time.html

[Fixes #10075] Improvements to the upload time step UI

---

requirements.txt
setup.cfg

(cherry picked from commit e66dd985393d7728ddce2cd1f33b737cbb2b5f6e)
#	requirements.txt

[Backport to 4.0.x][Dependencies] Align setup.cfg to requirements.txt (#10124)

---

setup.cfg

Align setup.cfg with requirements.txt

---

geonode/documents/api/serializers.py
geonode/geoapps/api/serializers.py
geonode/harvesting/config.py
geonode/layers/api/serializers.py
geonode/maps/api/serializers.py

ref #10168 
Add 'executions' field to concrete instance endpoints

[Fixes #10168] Add 'executions' field to concrete instance endpoints

---

geonode/security/tests.py
requirements.txt
setup.cfg

[Fixes #10165][3.2.x][Depencendies] Security audit and checks

---

geonode/documents/templates/documents/document_metadata_detail.html
geonode/templates/metadata_detail.html

[Fixes #10171] Dynamic rendering of document_detail view template

---

requirements.txt
setup.cfg

[Fixes #10198] uwsgi library update

---

geonode/base/admin.py
geonode/base/forms.py
geonode/base/templates/base/user_and_group_permissions.html
geonode/base/views.py
geonode/layers/management/commands/set_layers_permissions.py
geonode/layers/tests.py
geonode/layers/utils.py
geonode/people/tests.py
geonode/people/urls.py
geonode/settings.py

ref #10251 
Align the function used by the UI and the management command to elaborate the payload based on the API workflow (using PermsCompact. In this way the two flows, follows the same idea in the background relying on the PermsCompact and the resource_manager …

[Fixes #10251] Review geonode management command set_layers_permissions

---

geonode/base/api/views.py
geonode/geoapps/api/views.py
geonode/layers/api/views.py
geonode/maps/api/views.py

ref #10263 
defining just add_resourcebase permission to evalute if the user can perform a creation instead of using the EDIT permissions

[Fixes #10263] non admin user in fresh instance cannot create resources_

---

geonode/base/auth.py
geonode/security/tests.py

Fix broken test

---

geonode/base/admin.py
geonode/base/forms.py
geonode/base/templates/base/user_and_group_permissions.html
geonode/base/urls.py
geonode/base/views.py
geonode/people/tests.py

ref #10251 
This is the new behaviour

[Fixes #10251] improve feedback to the user and UI experience of batch permisisons assignment

---

geonode/base/api/tests.py
geonode/resource/manager.py

[Fixes #10302] Incorrect permissions assigned on cloning a resource

---

.clabot

[CLA] Add MalteIwanicki to clabot

---

requirements.txt

[Dependencies] Bump django-geonode-mapstore-client to version 4.0.5

---

CHANGELOG.md
geonode/__init__.py

Bump GeoNode to version 4.0.2 final

---

geonode/__init__.py
requirements.txt

After Release Update: Bump GeoNode to version 4.0.2 dev

---

CHANGELOG.md
geonode/__init__.py

Bump to 4.1.x

---

CHANGELOG.md
geonode/__init__.py

(cherry picked from commit e6dd1f3e92f070d578a4a9fe29881e0f87abda3b)
#	geonode/__init__.py

Bump GeoNode to version 4.1.0 dev

---

.github/workflows/codeql.yml
requirements.txt
setup.cfg

#	.github/workflows/codeql.yml
#	requirements.txt

[Backport to 4.1.x][Dependencies] Align "setup.cfg" to "requirements.txt" (#10507)

---

geonode/base/api/tests.py
geonode/base/api/views.py

ref #10524 
Adding user/group permissions list to the `groups/{id}/resources` and `users/{id}/resources endpoint`

[Fixes #10524] Resource permissions are not returned in the users/groups endpoint

---

requirements.txt

[Dependencies] Bump black to version 22.12.0

---

pavement.py
setup.py
tasks.py

[Code Formatting] Applying black to root files

---

geonode/geoserver/helpers.py
geonode/geoserver/tests/test_server.py
geonode/utils.py

[Code Format] Minor refactoring of geofence create options

---

dev_config.yml
docker-compose-geoserver-server.yml
docker-compose-test.yml
docker-compose.yml

[4.0.x] Bump GeoServer to version 2.20.7

---

CHANGELOG.md
geonode/__init__.py
requirements.txt

Bump to release 4.0.3

---

geonode/layers/models.py

[Fixes #0705]Log missing download url as INFO

---

.env
geonode/settings.py

[Fixes #9879] LANGUAGE example is not valid and results in broken home page

---

geonode/base/migrations/0067_resourcebase_storetype.py
geonode/base/migrations/0074_drop_curated_thumbs.py
geonode/layers/migrations/0036_remove_layer_storetype.py
geonode/layers/migrations/0040_dataset_ows_url.py
geonode/upload/migrations/0033_auto_20210527_1520.py

Fixes for multiple migration errors, a commit for each issue:
- GeoNode#10752
- GeoNode#10751
- GeoNode#10753
- GeoNode#10755

Fixes for multiple migrations

---

geonode/base/migrations/0067_resourcebase_storetype.py
geonode/base/migrations/0074_drop_curated_thumbs.py
geonode/layers/migrations/0036_remove_layer_storetype.py
geonode/layers/migrations/0040_dataset_ows_url.py
geonode/upload/migrations/0033_auto_20210527_1520.py

* #10747 Migration base/0074_drop_curated_thumbs.py broken
* #10752 Migration base.0067_resourcebase_storetype broken
* #10751 Migration upload/0033_auto_20210527_1520 broken
* #10753 Migration layers.0040_dataset_ows_url broken
* #10755 Some other migrations broken …

[Cherry Pick #10749] Fixes for multiple migrations

---

geonode/messaging/notifications.py
geonode/settings.py

[Fixes #10716] Configure user notifications off by default

---

geonode/documents/models.py
geonode/documents/tests.py
geonode/layers/models.py
geonode/layers/tests.py

[Fixes #10750] Implement custom download URLs

---

geonode/documents/models.py
geonode/documents/tests.py
geonode/layers/models.py
geonode/layers/tests.py

[Backport 4.0.x] [Fixes #10750] Implement custom download URLs

---

geonode/settings.py

[Backport 4.0.x][Fixes #10615] Implement fallback language for PyCSW to avoid warnings

---

geonode/maps/admin.py

[Minor] Add autocomplete_fields to maps admin MapLayer datasets

---

setup.cfg

(cherry picked from commit e7620effb065ca8b4bf9a0e4969adfd454ed36b3)
#	setup.cfg

[Backport to 4.1.x][Dependencies] Align setup.cfg to requirements.txt (#10788)

---

geonode/people/adapters.py

[Fixes #10830] Reset password rises 502 gatweay error if any error occurs

---

requirements.txt
setup.cfg

[Backport to 4.0.x][Dependencies] Align setup.cfg to requirements.txt

---

docker-compose-test.yml
docker-compose.yml
tasks.py

ref https://github.com/GeoNode/geonode/issues/10836

[Fixes #10836] Use GS ows service for healthchecks

---

dev_config.yml
docker-compose-geoserver-server.yml
docker-compose-test.yml
docker-compose.yml

[Fixes #10907] Bump to Geoserver 2.23.0

---

requirements.txt

Revert "Bump owslib from 0.28.1 to 0.29.1"

---

geonode/base/api/tests.py
geonode/base/api/views.py

ref #10978 
Remove `page` and `page_size` from the query params used by the dataset filtering in the `linked_resources` endpoint

[Fixes #10978] Page size in linked_resources raise an issue

---

geonode/base/api/tests.py
geonode/base/api/views.py
geonode/documents/models.py
geonode/layers/models.py
geonode/maps/models.py

ref #10993 
- Calculation of the `linked_resource` is moved as property in the resource model
- add test coverage

[Fixes #10993] Add all resources in linked_resources endpoint

---

geonode/base/management/commands/load_thesaurus.py

Import the `preferredLabel` method into the module.
Also performed black reformatting

[Fixes #11032] Error loading thesaurus

---

geonode/documents/api/serializers.py
geonode/documents/api/tests.py
geonode/documents/api/views.py

[Fixes #11037] Enable the creation of docs form URLs with the API

---

geonode/facets/__init__.py
geonode/facets/apps.py
geonode/facets/models.py
geonode/facets/providers/category.py
geonode/facets/providers/thesaurus.py
geonode/facets/providers/users.py
geonode/facets/tests.py
geonode/facets/urls.py
geonode/facets/views.py
geonode/settings.py
geonode/urls.py

Includes commits for #10995 (faceting)
- Base framework: initial app, urls and basic logic for extensible faceting through registering
- Facets provider for Thesaurus keywords, owner and category
Replaces #10997 which was a WIP PR and contained too many commits. …

[Fixes #10995] Faceting

---

setup.cfg

Upgrade setup.cfg since [geonode-importer](https://github.com/GeoNode/geonode-importer) has been [published to PyPI with version 1.0.0](https://pypi.org/project/geonode-importer/).

Bump geonode-importer to the published PyPI package

---

geonode/br/management/commands/backup.py
geonode/br/management/commands/restore.py
geonode/br/management/commands/settings_docker_sample.ini
geonode/br/management/commands/settings_sample.ini
geonode/br/management/commands/utils/utils.py
geonode/br/tasks.py
geonode/br/tests/test_backup.py
geonode/br/tests/test_restore.py
geonode/geoserver/management/commands/create_tile_layers.py
geonode/settings.py

Details included in #10792
Also adds a `create_tile_layers` command to recreate on geoserver the missing gwc layers.

[Fixes #10792][4.0.x] Improve B/R procedures

---

geonode/base/api/serializers.py

[Fixes #11078] Return POC email from API

---

geonode/services/serviceprocessors/arcgis.py

[Fixes #11080] Fixes missing service handler parameter

---

dev_config.yml
docker-compose-geoserver-server.yml
docker-compose-test.yml
docker-compose.yml

[Fixes #11100] Bump to Geoserver 2.23.1

---

geonode/settings.py

Add geotiff to supported raster type

---

geonode/documents/api/serializers.py
geonode/documents/api/tests.py

ref https://github.com/GeoNode/geonode/issues/11118

Remove doc_file and file_path from document serializer

---

geonode/geoserver/management/commands/set_default_gridsets.py

[Fixes #11129] GWC REST path incorrectly renamed to datasets

---

dev_config.yml
docker-compose-geoserver-server.yml
docker-compose-test.yml
docker-compose.yml

Revert "[Fixes #11100] Bump to Geoserver 2.23.1 (#11104) (#11107)"

---

geonode/base/auth.py

[Fixes #11147] Strip port from visitor_ip_address

---

requirements.txt
setup.cfg

Track client and importer development packages

---

Dockerfile
scripts/docker/base/ubuntu/Dockerfile

[Fixes #11230] Split and tag base Docker image

---

docker-compose-dev.yml

[Fixes #11237] Docker compose uses the published image

---

geonode/facets/providers/keyword.py
geonode/facets/providers/users.py

[Fixes #11259] Faceting: fixes

---

geonode/facets/models.py
geonode/facets/providers/baseinfo.py
geonode/facets/providers/category.py
geonode/facets/providers/keyword.py
geonode/facets/providers/region.py
geonode/facets/providers/thesaurus.py
geonode/facets/providers/users.py
geonode/facets/tests.py
geonode/facets/views.py

[Fixes #11262] Faceting: improvement: include count 0 topics

---

geonode/harvesting/harvesters/arcgis.py
requirements.txt
setup.cfg

[Fixes #11080] Unable to add ArcGIS REST ImageServer as Remote Service

---

geonode/layers/api/serializers.py

[Fixes #11342] use bracket notation inside the default feature template

---

geonode/layers/api/tests.py

[Fixes #11350] Fix tests for layer featureinfo template

---

requirements.txt
setup.cfg

[Fixes #11383] Remove explicit dependency from wandb

---

geonode/documents/templates/layouts/doc_panels.html
geonode/geoapps/templates/layouts/app_panels.html
geonode/settings.py

[Fixes #11430] Improve metadata template for geoapp

---

geonode/thumbs/thumbnails.py
geonode/thumbs/utils.py

[Fixes #11491 abd #11492] Fix alpha blending and remote layers in thumbnails

---

geonode/base/api/serializers.py

[Fixes #11535] Return category description in API response

---

celery-cmd

adding hostname to celery state db

---

geonode/thumbs/background.py
geonode/thumbs/tests/__init__.py
geonode/thumbs/tests/test_backgrounds.py

[Fixes #11610] Make thumbs backgrounds tests run

---

geonode/documents/forms.py
geonode/documents/views.py

[Fixes #11716] extension for remote document is not saved

---

geonode/documents/views.py

[Fixes #11752] Render remote docs with document embed template

---

requirements.txt
setup.cfg

[Fixes #11801] Upgrade to geoserver-restconfig 2.0.10

---

.env.sample

[Fixes #11808] Fix template variable for print base url

---

.env.sample

[Backport 4.2.x] [Fixes #11808] Fix template variable for print base url

---

docker-compose.yml

[Fixes #11822] Update Docker images to final tags

---

docker-compose.yml

[Backport 4.2.x] [Fixes #11822] Update Docker tags for 4.2.x

---

docker-compose-test.yml
docker-compose.yml

[Fixes #11825] Use GeoNode 4.2.x Docker image

---

setup.py

[Fixes #11830] Add long_description_content_type for Markdown

---

docker-compose-dev.yml

Remove docker-compose-dev reference to nginx script

---

setup.cfg

setup.cfg was not aligned in this https://github.com/GeoNode/geonode/pull/11708

Update setup.cfg django-recaptcha to 4.0.0

---

.github/workflows/flake8.yml

update github action to get the current black and flake version in the repo

Align Black and Flake versions to requirements inside the github action 

---

requirements.txt
setup.cfg

Update geonode-oauth-toolkit dependency

---

geonode/br/management/commands/create_tile_layers.py

[Backport 4.1.x][Fixes #11912] GWC layers only cache default style after B/R restore

---

geonode/__init__.py
requirements.txt
setup.cfg

Fixes the GWC tiled layers configuration with B/R
https://github.com/GeoNode/geonode/pull/11942

Release 4.1.4

---

geonode/base/api/tests.py
geonode/base/api/views.py

[Fixes #11918]  Implement linked_resources API creation and deletion methods

---

geonode/base/api/tests.py
geonode/base/api/views.py

[Fixes #11944] Implement filtering for linked_resources

---

geonode/base/templatetags/sanitize_html.py
geonode/base/tests.py
geonode/templates/metadata_detail.html
requirements.txt
setup.cfg

[Fixes #11862] Sanitize HTML data

---

geonode/base/api/tests.py
geonode/people/templates/people/profile_edit.html

[Fixes #11960] NoReverseMatch at /people/edit/<username>

---

.circleci/config.yml
geonode/api/tests.py
geonode/api/views.py

[Fixes #11978] Remove Bearer token parsing from userinfo

---

geonode/layers/api/permissions.py
geonode/layers/api/tests.py
geonode/security/utils.py

[Fixes #10880] REST API always filters dirty resources

---

geonode/services/test_selenium.py
geonode/services/tests.py

[Fixes #11675] Demo WMS service used in services tests returns 404

---

geonode/br/management/commands/backup.py
geonode/br/management/commands/restore.py

[Fixes #11977][Backport 4.2.x] B/R should only deal with data

---

requirements.txt
setup.cfg

Bump geoserver restconfig

---

geonode/settings.py

Fix to login rate limits configuration

---

geonode/people/tests.py
geonode/people/views.py

[Fixes #11995] Implement endpoint to transfer resources

---

geonode/base/api/tests.py
geonode/base/api/views.py
geonode/geoserver/signals.py

- Moved some python logic into db queries
- Prefiltering set of ResourceBases before applying permissions
- Avoiding queries when a specific linktype is requested

[Fixes #12068] linked_resources API is slow

---

geonode/people/tests.py
geonode/people/views.py

[Issue 11995] Implement endpoint to unregister as a project manager

---

geonode/base/api/tests.py
geonode/base/api/views.py
geonode/geoserver/signals.py

[Fixes #12068][Backport 4.2.x] linked_resources API is slow

---

requirements.txt
setup.cfg

Upstream PR for django upgrade has been merged. We can change the requirements from GeoNode fork back to the upstream repo.
Unluckly no pypi pushing was done...
https://github.com/AltSchool/dynamic-rest/pull/354

Bump dynamic rest library to v2.2.0

---

geonode/base/api/mixins.py
geonode/base/api/serializers.py
geonode/base/api/tests.py
geonode/documents/api/serializers.py
geonode/geoapps/api/serializers.py
geonode/layers/api/serializers.py
geonode/maps/api/serializers.py

[Fixes #12079] Fix resources API

---

geonode/base/api/tests.py

[Fixes #12099] Fix API tests

---

tasks.py

[Fixes #12089] Errors in init entrypoint

---

geonode/base/api/mixins.py
geonode/base/api/serializers.py
geonode/base/api/tests.py
geonode/base/api/views.py
geonode/documents/api/serializers.py
geonode/geoapps/api/serializers.py
geonode/layers/api/serializers.py
geonode/maps/api/serializers.py

[Fixes #12077] Add linked_resources info in resources API calls

---

geonode/settings.py

[Fixes #12102] Replace azure account with microsoftgraph account

---

geonode/base/api/tests.py
geonode/base/api/views.py
geonode/documents/api/views.py
geonode/geoapps/api/views.py
geonode/layers/api/views.py
geonode/maps/api/views.py
geonode/settings.py

[Fixes #12104] API query params presets

---

geonode/base/api/tests.py

Fix tests for #12104 conflicting with #12110 changes

---

geonode/base/migrations/0074_drop_curated_thumbs.py

[Fixes #12141] Error in migration base.0074_drop_curated_thumbs

---

geonode/geoserver/geofence.py

[Fixes #12150] Make GeoFence rule removal more robust

---

geonode/base/api/tests.py
geonode/base/api/views.py
geonode/base/models.py
geonode/base/widgets.py
geonode/documents/templates/layouts/doc_panels.html
requirements.txt
setup.cfg

[Backport 4.2.x] [Fixes #12170] Unable to set advanced contact roles in metadata editor

---

requirements.txt
setup.cfg

[Fixes #12229] tinymce is not visible after the upgrade to v4

---

Dockerfile

[Fixes #12223] Fix comment in Dockerfile

---

geonode/services/tests.py
geonode/services/views.py

[Fixes #12255] Harvester is not deleted when its Service is deleted

---

geonode/assets/local.py
geonode/assets/utils.py
geonode/assets/views.py
geonode/base/api/serializers.py
geonode/maps/api/views.py
geonode/settings.py
requirements.txt

12226 directory assets 3

---

geonode/assets/local.py
geonode/base/base_urls.py
geonode/base/forms.py
geonode/base/models.py
geonode/base/templates/base/base_embed.html
geonode/base/templates/base/base_metadata.html
geonode/base/templates/base/base_metadata_advanced.html
geonode/base/templates/base/base_metadata_detail.html
geonode/base/templates/base/base_panels.html
geonode/base/views.py
geonode/client/templatetags/client_lib_tags.py
geonode/settings.py
geonode/urls.py
requirements.txt

ref https://github.com/GeoNode/geonode/issues/12366
importer pr: https://github.com/GeoNode/geonode-importer/issues/246
Adding HTML to let the metadata being edited

[Fixes #12366] Introduction of 3dtiles in GeoNode

---

geonode/assets/views.py

The permission logic is already inside the asset API, no need to add additional classes. The `UserHasPerms` was trying to find the PK of the asset as ResourceBase, so it should be removed

[Fixes #12382] Fix permsission on API for assets

---

geonode/people/forms.py
geonode/people/views.py
geonode/templates/account/signup.html

[Fixes #12361] Fix captcha field visualization in signup page

---

geonode/br/management/commands/restore.py

[Fixes #12304] Move create_tile_layers to backup.sh

---

geonode/templates/owner_rights_request.html

Add missing "m" in "Request permission"
- [] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue" …

Add missing "m" in "Request permission"

---

geonode/facets/providers/group.py
geonode/facets/tests.py

[Fixes #12413] Group filter autocomplete does not work

---

.github/workflows/flake8.yml
geonode/assets/local.py
geonode/assets/tests.py
geonode/proxy/tests.py
geonode/proxy/views.py
geonode/storage/data_retriever.py
requirements.txt
setup.cfg

[Fixes #12412] Download whole asset

---

geonode/geoserver/helpers.py
geonode/geoserver/management/commands/sync_geonode_datasets.py
geonode/layers/api/views.py

[Fixes #12441] GS layers metadata update

---

geonode/base/api/serializers.py

[Fixes  #12435] Improve resource serializer for Links - Assets

---

geonode/settings.py

importer now will define the list of handlers, geonode will expose only the custom one

[Fixes #12472] Importer autoregister

---

geonode/resource/utils.py

[Fixes #12501] Localized TKeywords are not properly parsed

---

geonode/base/views.py
geonode/documents/views.py
geonode/geoapps/views.py
geonode/layers/views.py
geonode/maps/views.py
geonode/people/models.py
geonode/security/tests.py
geonode/security/utils.py

[Fixes #8848] Implment can_feature, can_publish and can_approve methods

---

geonode/static/geonode/less/base.less

ref https://github.com/GeoNode/geonode/issues/12549

Profile icon proportions

---

geonode/catalogue/urls.py

[Fixes #12553] Remove type control from uuid url

---

geonode/catalogue/urls.py

[Fixes #12553][Backport 4.4.x] The uuid direct link doesn't work if the uuid field is not a uuid value

---

geonode/templates/account/login.html

ref https://github.com/GeoNode/geonode/issues/12567

[Fix #12567] Duplicate "forgot password" in login page

---

geonode/documents/templates/layouts/doc_panels.html
geonode/geoapps/templates/layouts/app_panels.html

[Fixes #12610] Metadata Wizard steps leaked inside the settings tab

---

geonode/maps/models.py

[Fixes #12636] Fix bbox comparison during map extent calculation

---

geonode/__init__.py

bump GeoNode to version 5.0.0

---

geonode/assets/management/commands/migrate_file_to_assets.py

even for a single file, the destination must be a list not a string

Fixes #12732: Files destination must be a list

---

setup.cfg

Importer dependencies added to setup.cfg

align setup.cfg to requirements.txt

---

geonode/base/forms.py

[Fixes #12770] Thesaurus title label is not rendered

---

geonode/settings.py

FILE_UPLOAD_HANDLERS change handlers order

---

.env_dev
geonode/upload/handlers/tiles3d/handler.py

[Fixes #12789] Improve 3dtiles filename handling

---

geonode/people/adapters.py
geonode/settings.py

[Fixes #12872] Improvements to GeoNode OpenID for Entra ID

---

geonode/base/api/serializers.py
geonode/base/api/tests.py
geonode/layers/download_handler.py

[Fixes #12880] Asset download doesn't work with 3D Tiles

---

geonode/resource/manager.py
geonode/resource/tests.py

[Fixes #12883] Error in passing params from metadata parsers to storers

---

geonode/documents/admin.py

[Fixes #12904] Include advertised in the list editable fields

---

geonode/metadata/schemas/base.json

Added mandatory constraints according to ISO19115

[Fixes #12956] Metadata editor: review mandatory flags

---

geonode/metadata/handlers/abstract.py
geonode/metadata/manager.py

[Fixes #12983] Metadata manager: add pre- and post- save hooks

---

geonode/metadata/handlers/abstract.py
geonode/metadata/handlers/base.py
geonode/metadata/handlers/sparse.py
geonode/metadata/i18n.py
geonode/metadata/settings.py

Rationale in https://github.com/GeoNode/geonode/issues/12957 and comments.

[Fixes #12957] Metadata editor: customizable title and description labels

---

geonode/documents/forms.py
geonode/documents/tests.py
geonode/documents/tests/data/test.CSV
geonode/documents/views.py
geonode/resource/utils.py

[Fixes #12951] CSV file preview fails

---

geonode/metadata/api/views.py
geonode/metadata/tests/tests.py

Fix master build

---

geonode/base/api/views.py
geonode/thumbs/thumbnails.py

This PR was created according to this issue: #13031 

[FIXIES 13031] Fixing bug related with the thumbnail's update on a map

---

geonode/documents/migrations/0037_delete_documentresourcelink.py

[Fixes #12591] Migration documents.0037_delete_documentresourcelink may fail

---

create-envfile.py

[Fixes #13055] Limit the list of punctuations used inside create-envfile.py

---

requirements.txt

This PR was created according to this issue #13065 

[Fixes #13065] Upgrade Django version to 4.2.17 on GeoNode 4.4.x

---

geonode/tests/suite/base.py
geonode/tests/suite/runner.py
requirements.txt
requirements_tests.txt
setup.cfg

[Backport 4.4.x][FIXIES #13057] Removing Twisted library from the dependencies and the related code

---

geonode/catalogue/templates/catalogue/full_metadata.xml

[Fixes #13012] Use global UUID online resource inside ISO Metadata

---

setup.cfg

This PR was created according to this issue: #13090 

[Fixes #13090] Syncing PIP upgrade with setup.cfg

---

requirements.txt
setup.cfg

This PR was created according to this issue: #13085 . The following changes were applied:
- `cryptography` was removed from the requirements.txt file since it is not a direct dependency
- `pyOpenSSL` was removed, since it is not used and it is not an indirect dependency
- `cryptography` is installed automatically to the latest version: 44.0.2, as a dependency of `paramiko` and `jwcrypto`
- `paramiko` was also upgraded to the latest version `3.5.1`, because in the version of 3.4.0, paramiko exported some warnings after the `cryptography` upgrade
The changes above was also tested on 4.4.x and can be applied.
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing …

[FIXIES #13085] Upgrade Cryptography and remove pyOpenSSL

---

geonode/security/models.py
geonode/security/permissions.py
geonode/security/tests.py

[Fixes #13011] Return edit data permissions for remote layers

---

geonode/assets/tests.py
geonode/assets/utils.py
geonode/assets/views.py

Fix download perms for assets

---

geonode/base/api/views.py

This PR was created according to this issue: #13152 

[Fixes #13152] Removing the method resource_service_ingest() from master

---

geonode/metadata/handlers/doi.py
geonode/metadata/handlers/sparse.py

- Add methods to handle sparse fields content before saving
- Minor improvement to doi handler (does not concern the issue itself really, but makes the code a bit stronger)

[Fixes #13144] Improve Sparse field handler

---

geonode/groups/tests.py
geonode/resource/manager.py
geonode/upload/celery_tasks.py

[Fixes #13184] Ensure resource is in dirty state during clone and delete

---

geonode/metadata/api/views.py

[Fixes #13190] Make the Thesaurus autocomplete referenceable by identifier

---

geonode/base/api/tests.py
geonode/base/api/views.py
geonode/base/urls.py
geonode/base/views.py
geonode/resource/manager.py
geonode/upload/celery_tasks.py

The PR was created according to this issue: #13213 

[Fixes #13213] Do not copy the featured flag value when copying a resource

---

geonode/base/admin.py
geonode/documents/admin.py
geonode/layers/admin.py
geonode/maps/admin.py

[Fixes #13254] Add sparse fields in admin

---

geonode/groups/templates/groups/group_detail.html
geonode/people/templates/people/_profile_about_item.html
geonode/static/geonode/css/base.css

This PR was created according to this issue: #13286 

[Fixes #13286] Fixing group managers list in the group page

---

geonode/harvesting/harvesters/arcgis.py
geonode/harvesting/harvesters/base.py
geonode/harvesting/harvesters/geonodeharvester.py
geonode/harvesting/harvesters/wms.py
geonode/harvesting/tests/harvesters/base.py
geonode/harvesting/tests/harvesters/geonode.py
geonode/harvesting/tests/harvesters/test_harvester.py
geonode/harvesting/tests/test_harvester_worker_geonode_legacy.py
geonode/harvesting/tests/test_integrations.py
geonode/harvesting/tests/test_tasks.py
geonode/services/serviceprocessors/wms.py

This PR was created according to this PR: #13279 

[Fixes #13279] Removing `resource copy` related code from harvesting app

---

geonode/social/templates/social/activity_list.html

This PR was created according to this issue: #13302 

[Fixes #13302] Rename Layers tab to Datasets in the recent activity page

---

geonode/harvesting/tasks.py
geonode/harvesting/tests/test_tasks.py
geonode/settings.py

This PR was created according to this issue: #13318 

[Fixes #13318] Adapt Harvester tasks expiration dynamically

---

geonode/metadata/handlers/abstract.py
geonode/metadata/handlers/base.py
geonode/metadata/handlers/contact.py
geonode/metadata/handlers/doi.py
geonode/metadata/handlers/hkeyword.py
geonode/metadata/handlers/region.py
geonode/metadata/handlers/sparse.py
geonode/metadata/handlers/thesaurus.py
geonode/metadata/i18n.py
geonode/metadata/tests/test_handlers.py
geonode/metadata/tests/test_i18n.py

See #13327: Metadata editor: improve label customization

[Fixes #13327] Metadata editor: improve label customization

---

geonode/assets/views.py
geonode/base/api/tests.py
geonode/base/api/views.py
geonode/base/auth.py
geonode/documents/api/views.py
geonode/facets/views.py
geonode/geoapps/api/views.py
geonode/harvesting/api/views.py
geonode/layers/api/tests.py
geonode/layers/api/views.py
geonode/maps/api/views.py
geonode/metadata/api/views.py
geonode/people/api/views.py
geonode/resource/api/views.py
geonode/security/middleware.py
geonode/security/tests.py
geonode/settings.py
geonode/upload/api/tests_old.py
geonode/upload/api/views.py

We also remove uselsss authentication_classes definition inside DRF views, since they are the same the predefined `DEFAULT_AUTHENTICATION_CLASSES`

[Fixes #13343] POST requests throw crsf error when ENABLE_APIKEY_LOGIN is active

---

docker-compose-test.yml
docker-compose.yml

[Fixes #13262] Memcached container not starting upon reboot

---

geonode/metadata/schemas/base.json

[Fixes #13389] Metadata editor: fix capitalization

---

.github/workflows/flake8.yml

[Fixes #11612] Run flake using python 3.12

---

geonode/groups/views.py

[Fixes #13432] Do not switch to group detail when adding or removing members

---

geonode/base/api/tests.py
geonode/base/api/views.py

This PR fixes #13368 
Changes Made:
- A view has been added on ResourceBaseViewSet for ISO metadata download.
- Test case has been added to test the view.

[Fixes #13368] Download ISO metadata directly from Resource metadata_xml

---

geonode/base/migrations/0094_fix_otherrestrictions_codetype.py

This PR updates the migration(`0094_fix_otherrestrictions_codetype.py`) introduced in [PR #13439](https://github.com/GeoNode/geonode/pull/13439), where `RestrictionCodeType` import was used [via](https://github.com/GeoNode/geonode/pull/13439/commits/6cceccde5bbd05faf1455b8c63365f275b3aad82):
```python
RestrictionCodeType = apps.get_model('base', 'RestrictionCodeType')
```
However, it was observed that the fields were not properly updated (reason not yet confirmed but suspect due to historical model). Since it should normally work but does not in this case when tested, So this PR is reverting to a direct import of `RestrictionCodeType` from base models, which was already present in the migration but not used as imported on above line .In master branch there is direct import already so dont …

[Fixes #13364] Update of Backport of Base RestrictionType Fixture Fixed (#13404)

---

requirements.txt
setup.cfg

https://github.com/GeoNode/geoserver-restconfig/milestone/2?closed=1

Upgrade to geoserver-restconfig 2.0.15

---

geonode/api/tests.py
geonode/assets/serializers.py
geonode/assets/tests.py
geonode/assets/utils.py
geonode/assets/views.py
geonode/base/api/views.py
geonode/settings.py
geonode/upload/migrations/0052_asset_upload_size.py
geonode/upload/uploadhandler.py

[Fixes #13378] Implement POST API for asset creation.

---

geonode/geoserver/helpers.py

Fixes #13462 
This PR forward ports the changes done on [4.4.x](https://github.com/GeoNode/geonode/pull/13475) to master related to ISSUE #13462.
Improvement Remaining: [Changes Remaining](https://github.com/GeoNode/geonode/issues/13462#issuecomment-3242793439) …

[Fixes #13462] Update set_attributes_from_geoserver to use authenticated calls

---

geonode/upload/handlers/base.py
geonode/upload/handlers/common/tests_vector.py
geonode/upload/handlers/common/vector.py
geonode/upload/handlers/tests.py
geonode/upload/templates/upload/vrt_template.xml
geonode/upload/utils.py

[Fixes #13520] Improved Error Robustness for special characters and whitespaces in filenames and attribute tables

---

geonode/geoserver/helpers.py
geonode/resource/manager.py
geonode/resource/utils.py
geonode/utils.py

This PR was created according to this issue: #13559 

[Fixes #13559] Avoid local GeoServer / GeoFence calls during harvesting from an external GeoServer
